### ISSUE TITLE
Proposal list: Do not filter out "failed" proposal but should filter out "rejected" ones (maybe show rejected in it's own page)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1011]
The wrong type of proposal are being filtered out of the list of proposals.

Failed ones are ones that technically failed (probably at enactment).
Rejected ones are ones that never became valid.

----

We do not need to see rejected proposal on the list page because a proposer will see this as part of #1010 

however command line user may benefit from a page where they can see all rejected ones (for debugging). https://github.com/vegaprotocol/frontend-monorepo/issues/1012

**Comment by campbellssource** [comment]
This should be done after https://github.com/vegaprotocol/frontend-monorepo/issues/1010

**Comment by AndyWhiteVega** [comment]
Testing this looks good so far: but had to log: https://github.com/vegaprotocol/frontend-monorepo/issues/1140
