### ISSUE TITLE
Page for listing rejected proposals

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1012]
Command line users may benefit from a page where they can see all rejected ones (for debugging). this could live at something like https://token.fairground.wtf/governance/rejected

desktop wallet error messages can link to this
And we should have a link at the bottom of the proposals list "See rejected proposals" that takes you here.

**Comment by AndyWhiteVega** [comment]
Logged https://github.com/vegaprotocol/frontend-monorepo/issues/1140 other than that this has passed testing
