### ISSUE TITLE
Fairground config to list each node not just the load balancer

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1023]
The networks config appears to only have one node, the load balancer.

To make testnet more like live, this should be updated so that there are a list of nodes.

![Image](https://user-images.githubusercontent.com/13255539/184316459-250b71bf-af02-4921-8f10-3299fc5bd0e8.png)

I've not checked what the config is in the network repo, it is is the load balancer only then it should also be updated.

**Comment by dexturr** [comment]
Currently no longer using the load balancer, hwoever we are still hard coding a single node. The scope of this ticket should be adjusted to ensure that the list of n06-n11 are populated as potential connection options. @notbot00 can you add details of how to do this please 🙏

**Comment by mattrussell36** [comment]
This is done
