### ISSUE TITLE
Deposits

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#103]
- [x] Approve transaction
- [x] Deposit transaction
- [x] Await deposit event
- [x] Faucet interaction (in dev mode)

**Comment by Ditmir-Vega** [comment]
Manually tested deposits on http://localhost:4200/portfolio 
as a follow up , wrote tests scenarios for deposits on this pr : https://github.com/vegaprotocol/frontend-monorepo/pull/253
