### ISSUE TITLE
Interval labels require 'INTERVAL_' prepending to them to work with latest Vega core version

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/frontend-monorepo#1031]
Presently running `master` frontend-monorepo vs `develop` Vega core/datanode throws the error `I1H is not a valid Interval`.  It looks like this is likely due to interval labels now needing `INTERVAL_` in front of them

![image](https://user-images.githubusercontent.com/702798/184411808-9b330b12-d94a-458f-9676-07a2f8db9993.png)

This will likely also require a mapping back to the non prepended version for passing into Pennant.
Additional challenge arising: We need the non `INTERVAL_` version for current fairground interaction, which is difficult to do with the current 'master only' tagless setup.

**Comment by gordsport** [comment]
Tasks

Convert everything to use updated types
Create a map for pennant
Raise issue for pennant changes
