### ISSUE TITLE
chore: consider passing in the asset id as a prop and querying for a single asset using it

### ISSUE THREAD

**Issue by asiaznik** [vegaprotocol/frontend-monorepo#1049]
suggestion (non blocking): I would consider passing in the asset id as a prop and querying for a single asset using it

```
query Asset {
  asset(assetid: ID!) {
    ...
  }
}
```

_Originally posted by @mattrussell36 in https://github.com/vegaprotocol/frontend-monorepo/pull/960#discussion_r943206567_

**Comment by mattrussell36** [comment]
Closing as querying all assets is fine for now
