### ISSUE TITLE
Allow users to be able to configure which version of the FEs to use with VegaCapsule

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#1059]
Currently it looks like the configuration for the VegaCapsule frontends config is set to get the latest version (currently v0.0.6).

This version seems to not be fully compatible with the latest core version 0.54.0 as the staking is not working as expected.

This needs discussion before implementation, however, I think we need to have a way to specify versions that match the core versions, and also to be able to use the latest 'develop' version too.

Its possible that this issue may need to be split/transferred to the vegacapsule repo.

**Comment by dexturr** [comment]
https://github.com/vegaprotocol/frontend-monorepo/actions/runs/2993448018
