### ISSUE TITLE
Parties (aka public keys) should not be shown with the preceding 0x in block explorer.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1067]
The convention on Vega is that even though public keys are hexadecimal, they do not appear with the leading 0x.

This has perhaps become a convention from the fact that the Vega API returns parties without the 0x.

however, it appears that the Tendermint API (or whatever block explorer is using) does return parties with a preceding 0x.

This ticket is to remove the `0x` from anything that is a party in Block explorer.

- [ ] find all instances of a party that does start with a 0x
- [ ] remove the `0x`

This will help users copy paste between different apps

**Comment by pennyandrews** [comment]
This has been absorbed into https://github.com/vegaprotocol/frontend-monorepo/issues/1452
