### ISSUE TITLE
Display price impact (slippage)

### ISSUE THREAD

**Issue by elmar-vega** [vegaprotocol/frontend-monorepo#1088]
- [x] Calculations for slippage: (see comment below)
- [x] It should display as a new row in select trade size
- [x] It should display the text in green if less than 1%
- [x] It should display in amber if between 1-5%
- [x] It should display in red if more than 5%
- [x] It should have a tooltip with text:
- [x] It should work in dark/light mode
- [x] It should be tested
- [x] It should be a11y friendly

**Comment by MM0819** [comment]
To calculate the estimated slippage / price impact:

**Step 1:**

Fetch the market depth for the market, which will return an order book (for example, see below):

side   price   size
ask    105     10
ask    104     10
bid     102     10
bid     101     10

**Step 2:**

To calculate the slippage for long trade, you need to iterate over the asks until all of the volume for the trade has been filled and calculate the volume-weighted average price.

For example, given the order book above, if someone were to enter a long trade of `size=20`, then the full order will be filled by buying 10 contracts at 104 and 10 contracts at 105. Therefore, the VWAP will be:

`VWAP = ((105 x 10) + (104 x 10)) / (10 + 10) = 104.5`

Similarly, if they only wanted to buy 15 contracts, then the order will be filled by buying 10 contracts at 104 and 5 contracts at 105. In that case the VWAP will be:

`VWAP = ((105 x 5) + (104 x 10)) / (5 + 10) = 104.33`

**Step 3:**

Now that we know the estimated VWAP for the trade, we can calculate the slippage as the difference between the best possible price (the best ask in the case of this long example) and the actual price obtained in the market.

Therefore, using one the examples above, the slippage would be as follows:

For `VWAP=104.5`:

`Slippage = ((104.5 - 104) / 104) x 100 = 0.48%`

For `VWAP=104.33`:

`Slippage = ((104.33 - 104) / 104) x 100 = 0.32%`

The VWAP can be displayed as the estimated price.
