### ISSUE TITLE
Market change vote tally (inc LP votes)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1109]
Market change proposals can also be voted on by liquidity providers. once the API returns this we should show it on the proposal details page (market change only). https://github.com/vegaprotocol/vega/issues/5682

The proposal details page should also show you what vote (Token or LP is set to be the decisive one).

https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-System?node-id=1820%3A72391

**Comment by ckpringle** [comment]
Merged with #1512

**Comment by pennyandrews** [comment]
Merged with https://github.com/vegaprotocol/frontend-monorepo/issues/1512
