### ISSUE TITLE
Cast LP vote

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1110]
- [ ] on market change proposals: show you equity like share (liquidity provider vote, AKA LP)
- [ ] find out from @EVODelavega if you submit two votes, one for VEGA and a different for LP?
- [ ] [Cast vote LP ](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-System?node-id=1718%3A70064) (either token or LP)

**Comment by ckpringle** [comment]
Combined with #1512

**Comment by pennyandrews** [comment]
Combined with https://github.com/vegaprotocol/frontend-monorepo/issues/1512
