### ISSUE TITLE
Link to current governance thresholds in all governance tutorials

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#1123]
In the market creation incentive there was feedback asking how people should know what the thresholds are for voting. 

Suggestion is to include in each of the governance proposal tutorials the relevant network params (participation, majority, enact, close etc). 

It looks like the work in https://github.com/vegaprotocol/documentation/pull/177 would enable this?

**Comment by JonRay15** [comment]
@ckpringle is also looking at getting a table built on the vega.xyz/governance page to display a summary of all of these, but if we have this network param component in the docs then it makes sence to expose them in the tutorials too.

**Comment by ckpringle** [comment]
This is done in docs @JonRay15 and imminent on .xyz (reflected in asana https://app.asana.com/0/1201793103707836/1202736012584715)
