### ISSUE TITLE
Mainnet stats to use hooks for switching theme

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#113]
chore (blocking): A hook now exists for this

_Originally posted by @dexturr in https://github.com/vegaprotocol/frontend-monorepo/pull/107#discussion_r831101431_

**Comment by sam-keen** [comment]
Also make things compatible with theme toggle from ui toolkit and integrate into mainnet stats

**Comment by Ditmir-Vega** [comment]
did some sanity checks around https://stats.vega.trading/ 
- check links are working 
- check the correct data is being shown on the site 
- check status and colour is updated as expected 
- links navigating correctly to https://explorer.vega.xyz/blocks/ 

All checks passed - moving ticket to done
