### ISSUE TITLE
Rejected Proposals: Unable to Open proposal

### ISSUE THREAD

**Issue by AndyWhiteVega** [vegaprotocol/frontend-monorepo#1140]
Having posted a rejected proposal.
Then accessing Rejected Proposals.
Click view to drill into proposal. = Page not found

**Comment by AndyWhiteVega** [comment]
![Image](https://user-images.githubusercontent.com/106072061/186484386-4a2fec06-4597-4d88-b8a2-f1f16d10d0f2.png)

**Comment by AndyWhiteVega** [comment]
Example proposal to demonstrate the issue below (currently all proposals in fairground suffer this issue):

`{"rationale":{"title":"An example freeform proposal1693037184","description":"I propose that everyone evaluate the following IPFS document and vote Yes if they agree. [bafybeigwwctpv37xdcwacqxvekr6e4kaemqsrv34em6glkbiceo3fcy4si](https://dweb.link/ipfs/bafybeigwwctpv37xdcwacqxvekr6e4kaemqsrv34em6glkbiceo3fcy4si)"},"terms":{"newFreeform":{},"closingTimestamp":1693037184}}`

**Comment by sam-keen** [comment]
Fixed in https://github.com/vegaprotocol/frontend-monorepo/issues/1152
