### ISSUE TITLE
Review graphql endpoint configuration for explorer and token sites for all our networks

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/frontend-monorepo#1144]
Can we review configuration, specifically GraphQL URL, for token and explorer sites for all our networks, including the Mainnet?
- [ ] https://explorer.vega.xyz/
- [ ] http://explorer.fairground.wtf/
- [ ] https://dev.explorer.vega.xyz/
- [ ] explorer for Stagnet 3
- [ ] https://token.vega.xyz/
- [ ] https://token.fairground.wtf/
- [ ] token for devnet
- [ ] token for stagnet 3

Background:
- at least the token and explorer for the Mainnet and explorer for the Fairground have the wrong configuration.

**Comment by edd** [comment]
Semi related: https://github.com/vegaprotocol/explorer/issues/3

**Comment by notbot00** [comment]
related af: https://github.com/vegaprotocol/frontend-monorepo/issues/1102
