### ISSUE TITLE
Orderbook: Toggle to show/hide prices that do not have any orders

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1151]
Some people may want the order book to behave like a depth chart where the distance from the mid is represented by one axis and the depth by another so when looking at the cumulative volume column you get a sense of where the orders are related to the mid.
Some other people will want the order book only to show orders where prices are.

This to add a control to put it in one mode or another.

For example
![Image](https://user-images.githubusercontent.com/13255539/186660419-f9e6facf-aa74-474b-87e2-db72f2ee4675.png)

As for the default: it will be hard to know what most people want without more research. If there is a performance benefit in one over the other it should be chosen. else keep the existing behaviour as default until we know better.

**Comment by TomMcL** [comment]
Expanding on my own thoughts on this, I think showing prices with no orders behind the best prices is definitely something useful to toggle on/off but isn't awful either way (blank rows here can help picture the real shape of the book). However I'm stronger on the blank rows between best prices not existing, which for anything with a non-trivial spread makes the order book unusable.

**Comment by barnabee** [comment]
Agree fully that there is no reason that I can think of to show the empty space between the best bid and best offer.

**Comment by campbellssource** [comment]
☝️ ticket to just remove the rows, and not have a toggle.
it would suggest the default once this ticket is done = don't show hidden rows
