### ISSUE TITLE
Find a better solution for string interpolation

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#1184]
Currently we interpolate strings by splitting them into pieces. This does not work well across different langauges and may lead us into a bad place if we continue to do it. We should find a better solution for interpolation variables and other DOM elements into strings.

Consider:
 * off the shelf solutions
 * if we want to just bulk out our basic library for now

_Originally posted by @dexturr in https://github.com/vegaprotocol/frontend-monorepo/pull/1126#discussion_r953628599_

**Comment by edd** [comment]
My vote goes to https://www.i18next.com/. I mean, I should wait for your research.

**Comment by dexturr** [comment]
Mine too, not that I have any bias or preformed expectation while I wrote this ticket 😈

**Comment by dexturr** [comment]
Probably use the exsiting function we have but support some form of string interpolation & react component injection to prevent smelly code from poliferating
