### ISSUE TITLE
Block explorer: Netparams, show significant figures rather than rounding 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#1194]
Some network parameters are set to be really very low numbers, and some could potentially be set to be very low numbers. While the number looks small, that value could actually be significant for whatever the parameter is used for. 

example: [market.liquidity.minimum.probabilityOfTrading.lpOrders](https://explorer.vega.xyz/network-parameters#market.liquidity.minimum.probabilityOfTrading.lpOrders) is actually "1e-8", not 0.0000

**Comment by dexturr** [comment]
For numbers >=1 we should show 3 d.p.
For numbers < 1 we should show 3 s.f.

**Comment by candida-d** [comment]
Suggested by @barnabee: A good heuristic would be something like "trim ALL zeroes at the end of the number but show at least 4 d.p.

**Comment by dexturr** [comment]
https://github.com/MikeMcl/bignumber.js/issues/235

**Comment by pennyandrews** [comment]
https://github.com/vegaprotocol/frontend-monorepo/issues/1340
