### ISSUE TITLE
DELETE? (DUPE) Network parameter anchor links rarely work

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#1195]
When following a network parameter link, it's rare to see the expected behaviour of scrolling directly to the targeted network parameter.

For example, when following the [`👀spam.protection.max.delegations: 360`](https://explorer.vega.xyz/network-parameters#spam.protection.max.delegations) link from the [Spam protection](https://docs.vega.xyz/docs/mainnet/concepts/vega-chain#spam-protection) section, we expect the page to scroll to the position of that parameter, and highlight it.

I suspect the load time of the parameter list is the issue, as the target element doesn't exist at the moment the browser looks for it.

**Comment by pennyandrews** [comment]
Might be a duplicate of this https://github.com/vegaprotocol/frontend-monorepo/issues/1732

**Comment by edd** [comment]
@pennyandrews They are the same issue. One of the two should close

**Comment by pennyandrews** [comment]
Duplicates https://github.com/vegaprotocol/frontend-monorepo/issues/1732
