### ISSUE TITLE
Remove as many env vars from netlify/fleek/etc as possible

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1196]
I suggest that we should remove env vars from build environments and use only config files that are in repository to make builds deterministic. 
We even have custom build executors for that. 
![image](https://user-images.githubusercontent.com/1754247/187445522-0da5edd9-7829-40d8-b5e6-5c7bf66eef39.png)
With this approach we can be sure that we will have same result on without any interference from env vars

_Originally posted by @bglownia in https://github.com/vegaprotocol/frontend-monorepo/pull/1191#discussion_r958463936_

# Tasks
- [ ] TBD

**Comment by pennyandrews** [comment]
We are marking as done as already sorted for most things and anything remaining will have to be sorted as part of the move away from Netlify
