### ISSUE TITLE
Explorer on mainnet shows incorrect uptime

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#1199]
![image](https://user-images.githubusercontent.com/62546419/187490592-51d55137-744b-4504-b81f-25003944ec0b.png)

Looks like we're counting from beginning of (Unix) time.

**Comment by pennyandrews** [comment]
Barney mentioned yesterday that this wasn't done and he wasn't sure why it was closed so I had a look into it ... It looks like this was perhaps resolved for the stats app but not block explorer?
