### ISSUE TITLE
TFE: Associate button inoperable after associating

### ISSUE THREAD

**Issue by AndyWhiteVega** [vegaprotocol/frontend-monorepo#1202]
Associate some vega 
This then shows the - [Select a validator to nominate] button
Attempt to associate some more vega from Eth wallet by selecting the associate button
The button does nothing and doesn't load the expected associate screen

![Image](https://user-images.githubusercontent.com/106072061/187638854-cbc5e614-e7c4-4877-8158-e3eb0a25eaeb.png)

**Comment by dexturr** [comment]
Cause is that the route has not changed, so the router does not know to refresh the page content as we are on the same route still.

**Comment by asiaznik** [comment]
Does it mean it is expected as is? Or can we force reload a page when clicking on `Associate` and `txState == Complete`?

**Comment by dexturr** [comment]
Not expected IMO but i'd defer to @campbellssource, perhaps this should be a different route if forcing it is a pain `associate/perform` but ya know something better than that.

**Comment by ckpringle** [comment]
Should be resolved by #1822
