### ISSUE TITLE
After updatemarket proposal enactment, console info stops working

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#1210]
1: Do an update market proposal
2: Vote it through

Expected outcome: 
Console Market info should display information

Outcome:
Error message in info screen. _Something went wrong: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil_

This happens as soon as the update has been enacted.

<img width="879" alt="Screenshot 2022-08-31 at 17 44 49" src="https://user-images.githubusercontent.com/100769129/187721531-3e58d616-33de-4af4-9c97-d0dcb1cddeef.png">

**Comment by candida-d** [comment]
Looks like this will be sorted by the work in https://github.com/vegaprotocol/vega/issues/6032#issuecomment-1234206262
