### ISSUE TITLE
Rewards paid out per market ($VEGA)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1228]
As a user
I want to see rewards paid out last epoch per market in the trading UI
So that I can see see where the greatest rewards have been paid out and where I might have the best chance of earning the most rewards

Acceptance Criteria 

- [ ] I can see rewards paid out in the last epoch per market (VEGA rewards)
- [ ] There is a way to see all rewards on Vega e.g. a link to https://vega.xyz/rewards

**Comment by JonRay15** [comment]
Should be covered by the rewards dashboard work
