### ISSUE TITLE
[token site] Note on missing proposals

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1239]
https://github.com/vegaprotocol/frontend-monorepo/pull/1222 formerly had a callout that it's possible that a market proposal may not exist due to checkpoints not containing old, enacted proposals. @barnabee & me voted to remove that from the console, but there should be a comment on the token site if a proposal is not found, that it might be for that reason

**Comment by ckpringle** [comment]
Is this the same as https://github.com/vegaprotocol/frontend-monorepo/issues/1076 @edd ?
