### ISSUE TITLE
[console] Scrolling a lot in the order list makes it stop working

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#1240]
https://user-images.githubusercontent.com/100769129/188242908-c3a6c839-bde7-444d-81dd-1a3a9939b832.mov

If you have a lot of orders in the orderbook and begin to scroll down it goes black after a while and then you cannot scroll up either so it is frozen, waited for minutes without difference.

Expected result:
To be able to scroll, having page or date filter,

Results:
All orders in one list which stops working.

**Comment by mattrussell36** [comment]
@bglownia Wonder if we should look into using the date range for orders? Might be easier to handle compared to infinite scroll here?

**Comment by macqbat** [comment]
can't reproduce the issue now. Seems to be possibly fixed by some other issue fixing(?)

**Comment by mattrussell36** [comment]
This is now working again
