### ISSUE TITLE
[trading] Theme selection on Firefox/OSX is not respected

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1245]
I have my system theme set to Light:
<img width="672" alt="Screenshot 2022-09-05 at 10 50 37" src="https://user-images.githubusercontent.com/6678/188425609-6dad6c68-fac8-49f1-990a-67ba804116be.png">

If I set the Firefox theme to 'dark'
<img width="694" alt="Screenshot 2022-09-05 at 11 02 35" src="https://user-images.githubusercontent.com/6678/188425635-7818044e-8910-469d-bb7d-2888450cb32b.png">

And I clear my cookies/local storage, trading still defaults to the Light theme:
<img width="2003" alt="Screenshot 2022-09-05 at 10 53 21" src="https://user-images.githubusercontent.com/6678/188425615-9ae8f6b9-67eb-475e-a7d3-7ddccdb507eb.png">

This came up in a discussion about respecting user preferences, specifically I'd like dark to be default despite my system wide preference for light themed things. This isn't about that though, it's about following the browser level preference rather than the system one.

**Comment by mattrussell36** [comment]
@edd This should be working now
