### ISSUE TITLE
Deposit: balances do not refresh on completed withdrawal

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1249]
to recreate:

- go to https://console.fairground.wtf/portfolio/withdraw (note the amount you have)
- prepare a withdraw (that does not exceed any withdrawal limit
- confirm transaction in the Vaga wallet
- confirm transaction in Eth wallet
- see the complete message
- now see the "balance available" and the use max buttons. These still use the values as they were before the now complete withdraw.

refreshing the page updates the values.

Expected:

These values are always kept up to date with the latest state without refresh

**Comment by pennyandrews** [comment]
May be resolved / related to the fix implemented for https://github.com/vegaprotocol/frontend-monorepo/issues/1649

**Comment by mattrussell36** [comment]
@campbellssource This is now fixed
