### ISSUE TITLE
No way of disconnecting from Ethereum wallet

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1271]
## Story

**As a** a user
**I want to be able to disconnect my Ethereum wallet
**So that** I can connect with a different wallet

## Additional information

Go to deposit page https://console.fairground.wtf/portfolio/deposit
connect and do a deposit.

I now want to do a deposit from another Ethereum wallet (that I connect to via wallet connect)
but it re-establishes the connection with the previous wallet and gives me no way to change wallets.
e.g. from matamask mobile to conqbase mobile app

**Comment by PeteWilliams** [comment]
Also worth noting that the 'disconnect' function should be available on the withdrawal dialog, but is missing.

**Comment by macqbat** [comment]
We can't disconnect nor change an account from the console level. It is possible only from MetaMask extension. Not sure about case when user is connected via WalletConnector, but it's sure when he uses second method, via MetaMaskConnector. It's true that MM connector exposes method `disactivate` which we use on disconnect button, but it changes only _a flag_ of connection form active to not active. This flag/state would be possible to create something like _simulation_ of session with the account. We could simulate for the user he is connected or not, but in truth he would be still the time connected to the same account and he coudn't change his account from console level.

**Comment by PeteWilliams** [comment]
If we can't disconnect from the front-end, then maybe the 'disconnect' button should just open a dialog that tells them to do it in MetaMask?

**Comment by campbellssource** [comment]
I think the key thing is the "...So that I can connect with a different wallet" in the user story.

See how uniswap allows you to hit the power button to disconnect.
Yes, when I hit connect to metamask again I am already connected, but I am able to select Coinbase wallet.

https://user-images.githubusercontent.com/13255539/205828075-a6217ec3-ab20-4d87-9e5c-503887f70084.mov
