### ISSUE TITLE
"Wallet connect" not working on TFE

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1275]
To re-produce:
- With a clear season (no local storage, and metamask locked)
- Hit connect wallet to associate 
- Select wallet connect
- Connect a mobile wallet (e.g. metamask mobile) scan the code. hit okey on app
Expected: now connected to wallet
Actual: not connected

> Could not connect eagerly Error: No accounts returned connectEagerly index.js:109

![Image](https://user-images.githubusercontent.com/13255539/188866812-7742e61b-a437-40ec-978b-34a9d38c84f1.png)

**Comment by pennyandrews** [comment]
Close by https://github.com/vegaprotocol/frontend-monorepo/issues/1699
