### ISSUE TITLE
Link to validator profiles on the forum

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1278]
As a staker
I want to easily find a more detailed description of the validators pitch
So that I can use this information to inform who I stake

Acceptance Criteria 
* There is a link to https://community.vega.xyz/c/mainnet-validator-candidates/23 as part of step 2 

**"Use this site and your Vega wallet to nominate a validator. You can read more about the validators and take part in the discussion on [the forum ↗](https://community.vega.xyz/c/mainnet-validator-candidates/23)]**"

<img width="864" alt="Screenshot 2022-09-07 at 12 44 24" src="https://user-images.githubusercontent.com/46783148/188870527-9587d47a-f198-4cbd-85ce-8a9d460b05cf.png">

**Comment by sam-keen** [comment]
@ckpringle could you provide a link to the form url you'd like added? Thanks
