### ISSUE TITLE
Console: Both buyer and seller fields are red in fills table

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#1293]
Feedback: "the long volume is shown in red. It's different from before, when it was green. Now all are shown in red, distinguished only by "+" and "-""

This looks like a bug. You can see that the person who reported this is a taker on all trades, could it be that it's highlighting 'taker' in red rather than long/short? 

<img width="1299" alt="Screenshot 2022-09-08 at 15 47 33" src="https://user-images.githubusercontent.com/62548908/189153328-fd723b7c-4182-45fb-b047-5604408e3467.png">

Original report: https://github.com/vegaprotocol/feedback/discussions/85

**Comment by mattrussell36** [comment]
@candida-d Looks like the original discussion is a bit dated, the original issue described by the user is fixed, however the screen shot of the size field always being red is not. I've used this ticket to track the latter and updated the title.
