### ISSUE TITLE
Expiry time/date

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/frontend-monorepo#1296]
When setting the expiry time / date I can only do times after 09.59 by using the up and down arrows. If I try and type 14 (for 2pm ) it defaults to 04. I also do not get a drop down and Dan does on his Browser (Firefox on Mac)

MacOS Big Sure v 11.4 / Brave [Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (arm64)](https://brave.com/latest/)

and Chrome Chrome is up to date
Version 105.0.5195.102 (Official Build) (arm64)

https://user-images.githubusercontent.com/42541523/189326902-55596985-7ea3-465d-9393-06ccafc59a87.mov

<img width="2419" alt="Screenshot 2022-09-09 at 11 51 39" src="https://user-images.githubusercontent.com/42541523/189324507-e4f3df8f-4fe9-4509-b69f-1ff097d785bf.png">

**Comment by mattrussell36** [comment]
@rebeccajsimmonds The date picker uses your native settings, so if you want 24hr you'll need to change it on your system. Additionally brave doesn't open the date picker UI just by focusing the input. You should have a clickable calendar displaying on the right of the input, which you don't. Can you try disabling your extensions?

Screenshot from brave:
![Image](https://user-images.githubusercontent.com/6803987/193434641-382dd8fa-28f6-4499-aef2-6ee9606bcbbf.jpg)
