### ISSUE TITLE
Wallet version check

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#1304]
As there are different version of the wallet, we need the frontend to ensure that the wallet that is connected to the current dApp is compatible with the network that is running.

Open question: this check should only consider the CORE wallet version, not the desktop wallet wallet version.

We can:
* Show a generic update message
* Ask for an API that allows us to specify the desktop wallet version to update to
* Do something else

- [ ] Add env var for supported wallet versions, semantic version range
- [ ] Get version from wallet
- [ ] Ensure that the wallet version returned satisfies the semantic version range

**Comment by dexturr** [comment]
Taking a second look at this, is the new wallet feature that prevents the wallet from starting on an incompaitble network enough?

**Comment by ckpringle** [comment]
Dependent on https://github.com/vegaprotocol/vegawallet-desktop/issues/324

**Comment by pennyandrews** [comment]
@mattrussell36 to chat with Dex, Botond and Valentin about this to clarify
