### ISSUE TITLE
Replace json in Party details

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1334]
## Story 

As a user
I want to see Party details presented via standard UI elements
So that I don't have to be able to read json to be able to get the information I need

![Image](https://user-images.githubusercontent.com/47143694/190440626-8f428e8a-7ae1-4468-95c5-af6bb604a25a.png)

## Acceptance Criteria

- [x] It should display the party id and key on top and make it easy to copy the id
- [x] It should display a list of assets the party owns with the balance as a list.
- [x] It should make it easy to copy the asset id
- [ ] It should be accessible and easy to navigate using a keyboard
- [x] It should work in dark/light mode
- [ ] It should be tested

**Comment by ckpringle** [comment]
<img width="1800" alt="04 XL 1280 Party Details@2x" src="https://user-images.githubusercontent.com/46783148/192500420-e3fcbcfa-2a5d-48e7-bf39-53d57a2de2e2.png">
