### ISSUE TITLE
Improve error state for invalid ID search 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1335]
## Story

As a user
When I search for an ID that is invalid
I want to see an error message that let's me know what has happened and why I'm not getting the result I'm expecting
So that I can understand what has happened and take appropriate action to find what I'm looking for

**Comment by ckpringle** [comment]
A part of 1411

**Comment by JonRay15** [comment]
I'm going to say this is old and close it.  Fairly sure this has a "not found" type message which is fine.
