### ISSUE TITLE
Verify transaction links from Console and Token Front End work successfully 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1347]
## Story

This story should already be true...

As a user
I can view the details of each of the transactions I make in console and token frontend by clicking on a 'view on explorer' link 
So that I can check the details of my transaction (and share it with others if I wish)   

- [ ] Identify all the transaction types and places we link users to 'view on explorer' in console and token front end
- [ ] Check and test links for all transaction types
- [ ] Capture new tickets to fix any that aren't working

**Comment by AndyWhiteVega** [comment]
Console - Market Long&Short Orders Placed - Working fine - Example:
https://explorer.fairground.wtf/txs/0x0133CBC68041840D50145312AE1C81A731C2437591A1E8A5FE38C84B618BD177

Console - Limit Long Order Placed - - Working fine - Example:
https://explorer.fairground.wtf/txs/0x2DB40593712AA1D4025690A07C23355E3ACAAA9D48DFA5B78870FC259B019BD7
