### ISSUE TITLE
Health + health tooltip

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1354]
**User Story**
As a liquidity provider 
I want to understand the current health of the market in more detail, the fee levels and target stake
So that I can make a decision on providing liquidity but also understand better how liquidity on Vega actually behaves 

**Acceptance Criteria**

- There is a way to see the market health based on market status, liquidity status and how close that market is to moving from one fee level to another, and how close it is to the target stake
- We've found a way to progressively show the information e.g. mouseover 
- There is a way to access "key" type information explaining how the market health is calculated  e.g. a tooltip with list of definitions or similar

![image](https://user-images.githubusercontent.com/47143694/190521824-93be05be-4701-4eb3-a3cd-02c3b89f1ad0.png)
![image](https://user-images.githubusercontent.com/47143694/190521857-ee058bd4-7110-4447-8650-156323b86991.png)

Dashboard sketch for reference https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764531971937952&cot=14

Visual styles can be used from this early version of a design https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=399%3A20530

**Tasks**

- [ ]

**Comment by ckpringle** [comment]
Should get us what we need via GraphQL (from Tom)

```
{
  marketsConnection {
    edges {
      node {
        data {
          targetStake
          suppliedStake
        }
        fees {
          factors {
            makerFee
            infrastructureFee
            liquidityFee
          }
        }
        liquidityProvisionsConnection {
          edges {
            node {
              id
              fee
              commitmentAmount
            }
          }
        }
      }
    }
  }
}
```

**Comment by malinantonsson** [comment]
Netlify preview: https://deploy-preview-1664--liquidity-provision-dashboard.netlify.app/
