### ISSUE TITLE
Decimal places in Average entry and liquidation levels.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1364]
My entry price on this market is (as per the API) `99135000000000000000` but is being displayed as:

![Image](https://user-images.githubusercontent.com/13255539/190624356-ac5ab41d-e960-4b3f-ac6d-e63bd357cdc1.png)

We recently updated this so that it was formatted with the decimal places of the price. Because generally prices should be displayed with the same DP as the quote of a market.

However, in the case of a Average entry price, your average could have more numbers after the decimal than the quote. 
For example a market with a quote with 2 DP 
- `2.1` contracts at `10.10` each is an average entry of `10.605`
- and you could have a situation where the average in recurring `0.333333333333...`

~~It appears that core always returns average entry to the same number of decimal places as the settlement asset.~~

~~So In this case the decimal place is 18 characters from the right.~~

Core now will round the number up to the same number of DP as the market Quote.

however, we calculate liquidation level on the FE. When displaying this number is should be truncated to the same number of DP as the quote. (possibly one more)

**Comment by campbellssource** [comment]
Looks like the average entry price was fixed, liquidation level is still off.

**Comment by asiaznik** [comment]
I think it look ok, the dp for both are set to the market's dp (which is 5 in my case)
![Image](https://user-images.githubusercontent.com/1980305/193092188-f858448d-a0ae-4fb4-8fa0-8a665cbf65b5.png)

**Comment by campbellssource** [comment]
I'd like us to take a few more steps to verify.
- Try and asset with more decimal places than the market quote 
- try a market with a 0dp quote (and an asset with more)
- try a market where quote has more DP than settlement asset (if possible)
- get more feedback
- consider using the quote DP to Cap the number of decimal shown.

Also, need to resolve the discussion about what the API will return. There is some talk of it changing again.
