### ISSUE TITLE
Bug: collateral table overlapping rows

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#1366]
When I click the Collateral tab in the trading view in Console, I see some weirdness:

- There is a blank row where my Vega general account should be shown
- Down in the middle of my BTC accounts, I can see the missing row is overlaying one of the BTC rows
 
![image](https://user-images.githubusercontent.com/1325606/190626313-d840ee6a-67d3-4283-8245-ca4e636e5148.png)

In the DOM, it's positioned in the right place, but it looks like AG grid positions things using CSS translateY transformations, and it just calculates this one wrong somehow. Every other row's value goes up by 34px (the row height), except this one:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1325606/190626697-20c3f579-486c-4ffd-b26b-b98319fc6ecb.png">

Things to note:

- This happens in Chrome and Safari. Locally and on console.fairground.wtf
- If I click the Asset heading twice (ie, sort Z-A then back to A-Z) it then renders fine - despite this in theory being the same thing as originally shown!
- Sometimes happens to multiple rows

**Comment by mattrussell36** [comment]
Fixed by https://github.com/vegaprotocol/frontend-monorepo/pull/1442
