### ISSUE TITLE
Handle new account properly

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#1391]
## The Chore

Handle new account in libs/accounts/src/lib/accounts-data-provider.ts
When new account appears we are notified via subscription but there is missing data which we need

```
market {
    id
    tradableInstrument {
      instrument {
        name
      }
    }
  }
  asset {
    id
    symbol
    decimals
  }
```

We got two options here 
- change this provider be derived data provider and fetch assets, markets and accounts separately 
or
- re fetch accounts data when new account will appear

**Comment by mattrussell36** [comment]
Closing as dupe of https://github.com/vegaprotocol/frontend-monorepo/issues/1491
