### ISSUE TITLE
Add headings and enable anchors to network parameters

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1447]
## Story

As a user
I want to see network parameters organised by type
So that I can find it more quickly / avoid having to guess at the naming

## Acceptance Criteria

- [ ] I can see network parameters grouped by type e.g. 

**GOVERNANCE PROPOSALS** 
**Asset**
Governance.Proposal.Asset.MaxClose 720h
Governance.Proposal.Asset.MaxEnact 720h

**Free form**
Governance.Proposal.Freeform.MaxClose 8760h0m0s
Governance.Proposal.Freeform.MinClose 72h0m0s

- [ ] Network parameter headings act as linkable anchors i.e. a third party website can link directly to a "section" of the network parameter page 

## Tasks

- [ ] Implementation
- [ ] Team review

**Comment by pennyandrews** [comment]
Have a sketch ready for this to discuss with Elmar, once happy with it it can go to Joëlle to be designed

**Comment by edd** [comment]
This is already implemented, but buggy. See: https://github.com/vegaprotocol/frontend-monorepo/issues/1732

**Comment by neildawson** [comment]
It's a wee bit different @edd, this ticket is about adding more structure to the page to improve readability and navigability, i.e. grouping parameters, giving each of those groups a section/heading, then making those new sections/headings linkable

So we'd be able to link people to the section for new asset proposals, for example

Some [exploration on the Block explorer Miro board](https://miro.com/app/board/uXjVPVRiSOM=/?moveToWidget=3458764535724186637&cot=14)

**Comment by edd** [comment]
Oops! I see it now - my fault for skipping the intro.
