### ISSUE TITLE
Spike: Updates to work with the Sepolia test network

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#1462]
On ~Oct 6th Ropsten will be stopped/decommissioned so we will be moving to Sepolia.

Devops work is being done to migrate to Sepolia under the following issue:

- https://github.com/vegaprotocol/devops-infra/issues/1523
- https://github.com/vegaprotocol/devopsscripts/issues/72
- https://github.com/vegaprotocol/devopsscripts/issues/71

This spike is to 
- [ ] coordinate with devops to understand the changes
- [ ] understand what is required for the FE apps / team / testing
- [ ] create and schedule the FE work to be done in coordination with the network changes above

**Comment by mattrussell36** [comment]
Closing as trading app pulls all addresses from core, there is no code change, any test effort should be covered by https://github.com/vegaprotocol/frontend-monorepo/issues/1418
