### ISSUE TITLE
Add details of expected fees/margin usage/close out etc to ticket

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#1486]
## Story

As a user 
I want a preview of the impact of my trade before I place it
So that I can understand the likely outcome

## Acceptance Criteria

- [ ] I can see the estimated closeout price
- [ ] I can see the margin required
- [ ] I can see the notional size
- [ ] I can see fees
- [ ] I can see estimated slippage

### Sketch
![image](https://user-images.githubusercontent.com/1325606/192319690-cd88c4ad-fc66-4e2b-ac91-0d6e6ffa792f.png)

![image](https://user-images.githubusercontent.com/1325606/192319726-4f8db06d-4f40-4b09-8e92-342e751cf368.png)

I think these would be a big benefit in Console - I've found myself wanting when using it myself. Also helps explain how fees work in Vega, that liquidation price are variable, that these are leveraged products etc, so helps from a user-education point too.

There's already a version on this in Console Lite, so I'm hoping we can use the code as a starting point, or perhaps reuse the component entirely:  
![image](https://user-images.githubusercontent.com/1325606/192318377-80e53066-bd64-4353-a49d-813f6aa8bcc1.png)

**Comment by MadalinaRaicu** [comment]
@PeteWilliams  in the console you are able to place limit orders too. It might not make sense to display est. slippage for limit orders. 

Also, in the console-lite component, you are able to change the size based on your slippage tolerance for market orders only. 
Do we want to add this behaviour in console v2 deal-ticket for market orders only? I think this will change the shape of the order. 
So, I am not able to re-use the exact same component. 

But I will try to re-use the calculation hooks as much as possible, ex. for notional size, fees, closeout, and margin.

**Comment by PeteWilliams** [comment]
@MadalinaRaicu I think you're right about slippage - it would only apply to market orders.
As for controlling your size by setting a slippage tolerance, I think that could be useful, but for this ticket let's leave it as playback-only and we can create another ticket for the control if it's deemed a priority.
