### ISSUE TITLE
Orderbook

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#151]
### Acceptance Criteria

- Show full book (using new api with delta)
- Aggregation
  - Lowest. market tick size
  - Movement amount calculated using logarithmic scale (base 2 suggested constant)
  - Default to most precision (1 market tick)
- Layout handles auction mode (price crossing)
  - Auction
    - Mid point is indicative uncrossing price
    - Show uncrossing area on cumulative volume
  - Continuous
    - Mid point is midprice
- Histograms
  - Buy/Ask scales show the largest volume at level
  - Cumulative scales are showing sum of all orders of larger side (cumulative of course!)
  - Show cumulative volume number

### Notes

Generally the order book should show the **sum of orders at a given level**. 
for example in the following example there could be two parties with sell orders at 0.021 with volumes of 6 and 4 (meaning 10 in total.

```
price |  orders at price | sum of orders at this level and to the mid price* | side  
0.031 | 30 | 60 | sell 
0.020 | 20 | 30 | sell
0.021 | 10 | 10 | sell 

mid price: 0.020

0.019 |  5 |  5 | buy
0.018 |  5 | 10 | buy
0.009 |  5 | 15 | buy
```

## Aggregation 

Typically orders can be grouped or **aggregated** into a common level. ☝️ is shown at the tick level e.g. `0.001`.
this is shown aggregated at `0.01`
```
0.03 | 30 | 60 | sell 
0.02 | 30 | 40 | sell 

mid price: 0.020

0.01 | 10 | 15 | buy
0.09 |  5 | 15 | buy
```
Order aggregation may not be done in the first pass.

## Auction mode
The order book will need to behave significantly differently when the market is in limited order book mode Vs Auction
In limited order book mode prices below the best bid will always be bids and above the best ask will always be asks, because if orders cross they will be matched.

In auction the matching does not happen until the end of the auction.

The following image shows how a single order book could be constructed that works in both modes.

<img width="1538" alt="Screenshot 2022-04-06 at 16 15 15" src="https://user-images.githubusercontent.com/13255539/162008401-1de39b39-03cb-45d8-a7a4-964cf0437916.png">

This format is more common and space efficient if continuous trading is always the case.
<img width="707" alt="Screenshot 2022-04-05 at 14 26 58" src="https://user-images.githubusercontent.com/13255539/161764295-1ad769e4-756a-447a-9057-3616c3600e02.png">

## Rows for each potential price or rows only where there are orders in the book.

In the above example there are no orders in the book between 0.03076 and 0.03073, and as a result there is no row. Should this be the case?

## Centring and scrolling
By default the order book should be centred on the mid price (or indicative uncrossing price if in auction) and when the mid changes the users should still be anchored on or near the mid. 

This would leave many prices out of view. a user may wish to see prices that are further away from the current mid. to see more prices there are a few options
- Aggregation (see above)
- scroll
- jump to sell side, buy side or mid

**Comment by campbellssource** [comment]
For info: Here is another mock up with some other nice to haves
<img width="1183" alt="Screenshot 2022-04-06 at 16 17 16" src="https://user-images.githubusercontent.com/13255539/162009141-f19bf346-2d27-48e2-8eb3-75627745afdf.png">
