### ISSUE TITLE
LP view data provider

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#1537]
This is a bug. LP table did not auto-update.

**Comment by pennyandrews** [comment]
Hey @MadalinaRaicu is this blocked by core? if so could you pop that label on it and link to the ticket in core repo that is blocking it (either one that already exists or that you have created). Thank you!!

**Comment by MadalinaRaicu** [comment]
issue is fixed in core https://github.com/vegaprotocol/vega/issues/6408 but we are waiting for the 0.58 testnet release. if the subscriptions get deployed to console and someone runs it on testnet 0.57 it will bring data nodes down.
