### ISSUE TITLE
Manually  test add/remove signer

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#1543]
We are currently blocked from testing add remove signer until an environement with validators coming and joining leaves. This ticket is to test and fix any bugs that we find.

**Comment by gordsport** [comment]
The work to implement validators joining and leaving on a network is planned in:

https://github.com/vegaprotocol/devopsscripts/issues/75

This is in the current sprint so hopefully will be picked up v soon

**Comment by candida-d** [comment]
Bug: Copy tells people to use the "public key of the signer". It should say "node ID of the signer to add".

**Comment by candida-d** [comment]
Bug: After clicking "add" you get a bundle error, even though the API output is visible. 
<img width="1437" alt="Screenshot 2022-10-21 at 14 13 52" src="https://user-images.githubusercontent.com/62548908/197509328-3092c543-7b6f-498c-a7b3-2f0a1ed7aa02.png">

**Comment by dexturr** [comment]
This has been verified on the sandbox evnvironement e2e and we are confident it is working
