### ISSUE TITLE
Console edit order size

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#1552]
## Story

**As a** trader
**I want to** be able to edit order size
**So that** I can amend an order more fully

## Acceptance Criteria

- [ ] I can edit an orders size after it has been accepted by the network

## Additional information

Editing limit orders in the console is limited to entry price, but it should also allow for editing the order size.

### Discussed in https://github.com/vegaprotocol/feedback/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **zouhairstitou** September 29, 2022</sup>
We can adjust only the entry price, can we get a position volume as well. Thanks!!!</div>

**Comment by MadalinaRaicu** [comment]
Just a note for whoever picks up this ticket that the API supports **sizeDelta**, but the user would input the new **size**. 
So delta needs to be calculated.
