### ISSUE TITLE
IPFS deploys do not work for subfolder gateways

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1613]
next.js builds static pages, and those static pages reference static assets as `/_next/...`, which works fine if the
site is served from a domain root (e.g. `console.fairground.wtf/`, `made-up-url.ipfs.io`) but breaks down on IPFS
gateways that are still configured to use subfolders (e.g. `ipfs.io/ipfs/made-up-url`). ~Luckily we can fix this by
using `assetPrefix` to turn `/_next/` in to `./_next/`, which works in both cases.~ Narrator: It doesn't. 

# Tasks
- [ ] Update configuration for trading

Blocks #597

**Comment by edd** [comment]
The fix implemented for this broke many routes in the app, so was reverted by @mattrussell36.

**Comment by mattrussell36** [comment]
Closing as this is covered by #1921
