### ISSUE TITLE
Unable to submit proposal using min/max deadline

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#1622]
## Description

Error is shown when submitting a valid proposal clicking the min/max buttons for the voting deadline

## Steps to Reproduce

1. Go to submit a freeform proposal
2. Click on max deadlines for all relevant time periods
3. Click submit
4. Error shown
5. Click on min deadline
6. Same as abobe

Error is also seen on some of the other proposal types

**Comment by sam-keen** [comment]
@jtsang586 I've not been able to reproduce this. Could you please check if it's still affecting you? Thanks
