### ISSUE TITLE
Deposit dialog for portfolio page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1640]
Make deposit experience consistent between deposit and collateral panes.

### Tasks
- [ ] Deposit button in the deposits pane on the portfolio page should open the deposits dialog
- [ ] Deposit page removed

**Comment by MadalinaRaicu** [comment]
This one was resolved in a previous PR.  https://github.com/vegaprotocol/frontend-monorepo/pull/1696/files#diff-d9f22c629cf238c8420e078d1da26665dacd69375db740bf522d6b54da742715
