### ISSUE TITLE
Orders table filtering

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1643]
Depends on #1675 

## Story

As a trader
I want to be able to sort and filter the orders table
So that I can more easily find order information

## Acceptance Criteria

- [ ] I can filter by date range
- [ ] I can filter by status
- [ ] I can filter by type.
- [ ] I can filter by TIF
- [ ] Applied filters are editable
- [ ] Default sorting and filter is applied. 
  - [ ] status filtered by active
  - [ ] primary sort by limit -> market -> liqudity provision
  - [ ] secondary sort by price high -> low

**Comment by PeteWilliams** [comment]
Added sort/filter by type to above.
