### ISSUE TITLE
Positions table sorting and filtering

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1646]
blocked by #1645, #1675 

## Story

As a trader
I want to sort and filter positions
So that I can easily analyze my positions

## Acceptance Criteria

- [ ] I can sort and filter by market
- [ ] I can sort and filter by notional value
- [ ] I can sort and filter by asset
- [ ] I can sort and filter by open volume
- [ ] I can sort and filter by market price
- [ ] I can sort and filter by entry price
- [ ] I can sort and filter by liquidation price
- [ ] I can sort and filter by leverage
- [ ] I can sort and filter by margin allocated
- [ ] I can sort and filter by realised PnL
- [ ] I can sort and filter by unrealised PnL
- [ ] I can sort by updated date
- [ ] Applied filters are editable
- [ ] Filters can be reset

**Comment by PeteWilliams** [comment]
Added sort/filter by notional value to above.
