### ISSUE TITLE
Show full asset details in market info and dialog

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1653]
## The Chore

There is missing asset data that we should show in the market info tab and the asset dialog

#### Market info
- [x] decimals
- [x] quantum
- [x] type (IE typename, Builtin or ERC20)
- [x] contractAddress (for ERC20)
- [x] lifetimeLimit with tooltip (for ERC20)
- [x] withdrawThreshold with tooltip (for ERC20)
- [x] maxFaucetAmountMint  (for Builtin)
- [x] status
- [x] infrastructureFeeAccount balance with tooltip
- [x] globalRewardPoolAccount balance with tooltip
- [x] takerFeeAccount balance with tooltip
- [x] makerFeeRewardAccount balance with tooltip
- [x] lpFeeRewardAccount balance with tooltip
- [x] marketProposerRewardAccoiunt balance with tooltip

#### Asset dialog
- [x] ID
- [x] type (IE typename, Builtin or ERC20)
- [x] status
- [x] infrastructureFeeAccount balance with tooltip
- [x] globalRewardPoolAccount balance with tooltip
- [x] takerFeeAccount balance with tooltip
- [x] makerFeeRewardAccount balance with tooltip
- [x] lpFeeRewardAccount balance with tooltip
- [x] marketProposerRewardAccoiunt balance with tooltip

**Comment by asiaznik** [comment]
PR with updated wording: https://github.com/vegaprotocol/frontend-monorepo/pull/1712
