### ISSUE TITLE
Deposit from deal ticket

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1654]
## Story

As a trade
I want to be able to deposit from the deal ticket
So that I can get to trading as quick as possible.

## Acceptance Criteria

- [ ] I am prompted to deposit from within the deal ticket
- [ ] I can deposit from within the deal ticket

**Comment by MadalinaRaicu** [comment]
I think someone already did this 
<img width="364" alt="image" src="https://user-images.githubusercontent.com/16125548/198630336-c3176734-2b18-4a49-9908-0622375fe578.png">
