### ISSUE TITLE
Validate that user has sufficient collateral before placing an order

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1660]
## Story

As a trader
I want to be warned that I don't have enough collateral for an order before submitting a transaction
So that I don't waste time creating orders that won't be placed

## Acceptance Criteria

- [ ] I cannot place an order without sufficient collateral
- [ ] I cannot place an order without sufficient collateral accounting for margin requirements
- [ ] I am shown an insufficient collateral message if the order will not be placed

**Comment by mattrussell36** [comment]
@candida-d @PeteWilliams  Any suggestion on the wording/language here

**Comment by PeteWilliams** [comment]
Would it need to be a static message or can we pull in data like the margin required and available margin values?
Note, Madelina is adding margin requirements in this ticket: https://github.com/vegaprotocol/frontend-monorepo/pull/1771

**Comment by PeteWilliams** [comment]
I'd suggest something like 'You don't have enough margin available to open this position. 1,234 DAI currently required, 567 DAI available.[Deposit tDAI]'
