### ISSUE TITLE
DELETE? BlockExp: Network Params incorrect format for network parameter

### ISSUE THREAD

**Issue by AndyWhiteVega** [vegaprotocol/frontend-monorepo#1680]
The network parameter entitled: governance.proposal.updateAsset.requiredMajority
Shows up in a currency format with 4 decimal places - whereas it should show as a percentage

![Image](https://user-images.githubusercontent.com/106072061/194500825-f75beb62-1a5a-40ff-b8a0-c796f14a0ee2.png)

**Comment by edd** [comment]
Fixed at some point in the past
