### ISSUE TITLE
Can place any order with suspended market

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#1691]
## Description

When a market is suspended, it is possible to place any order, but only certain orders should be available to be created.

Current situation as for _11/11/2022_:

- The warning is displayed basing on Trading Mode and Trigger.
- The warning is displayed only after "Place order" clicked when trying to place one of the disallowed order type.
- Placing order is blocked after that.

Questions that needs to be answered, if we want to decide if it's a valid bug or not.

- Should the warning be based on Trading Mode and/or Trigger, or Market Status?
- Should the warning be visible all the time or only after clicking "Place order" button?
- Should an user be allowed to place "invalid order", or should it be possible only for given order types?

## Steps to Reproduce

1. Go to Console app.
2. Use market with 'suspended' status (or mock it).
3. Place some Market or Limit order.

## Expected behavior

- Only limit orders should be allowed
- GFA, GFN, GTC and GTT order TIFs are allowed
- We should show a warning message but still allow the order to be submitted

## Screenshots

<img width="875" alt="image" src="https://user-images.githubusercontent.com/24473278/194846647-6b16ec5c-5160-4c92-bc33-24b4f27644b6.png">

**Comment by campbellssource** [comment]
So to be clear. you **should** be able to place some types of orders while a market is suspended. 
or to be more explicit. Console should never prevent you from placing any type of order but should tell you if it knows that that order will not work.
Perhaps there is a poorly worded AC?

**Comment by radoslaw-szpiech** [comment]
We would need some specifics then, what's the message that should be shown? What types of orders are possible to be placed?

**Comment by radoslaw-szpiech** [comment]
Updated the summary according to our conversation with @campbellssource and @mattrussell36 on Slack.

**Comment by pennyandrews** [comment]
@radoslaw-szpiech to retest and check whether this is resolved now, and close or update ticket accordingly

**Comment by mattrussell36** [comment]
Looks like the problem is due to the fact the use-order-validation hook will return only a single error at a time (whichever condition is met first). IE if there is a problem with market state, and trading mode, then only the market state error gets shown to the user as its condition will be met first.

I would suggestion some refactoring to extract the rules in the hook and pass them to the rules prop of react-hook-form's Controller component. This way we can handle multiple validation errors simultaneously

**Comment by radoslaw-szpiech** [comment]
@mattrussell36 What about blocking placing market orders & linking that with suspended market? Could you please refine if we need to implement suggested behavior?

**Comment by radoslaw-szpiech** [comment]
Summing up the current situation (I'm also updating issue description accordingly):
- The warning is displayed basing on Trading Mode and Trigger.
- The warning is displayed only after "Place order" clicked when trying to place one of the disallowed order type.
- Placing order is blocked after that.

Questions that needs to be answered, if we want to decide if it's a valid bug or not.
- Should the warning be based on Trading Mode and/or Trigger, or Market Status?
- Should the warning be visible all the time or only after clicking "Place order" button?
- Should an user be allowed to place "invalid order", or should it be possible only for given order types?

@campbellssource @mattrussell36 @pennyandrews please, refine.
