### ISSUE TITLE
New wallet connect journey cannot connect to testnet on correct CLI wallet version

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#1692]
## Description

Testnet currently requires CLI wallet 0.57.0.

With the correct wallet installed, I see the following error trying to connect:

<img width="679" alt="Screenshot 2022-10-10 at 10 47 15" src="https://user-images.githubusercontent.com/2410498/194848555-a0a99e8a-3a1d-40f5-b594-f877cf0b1be9.png">

## Steps to Reproduce

1. Download the cli wallet from the vega repo with the required tag, i.e. `git checkout v0.57.0` and install (`go install -v ./cmd/vega`)
2. Start the wallet `vega wallet service run -n fairground`
3. Attempt to connect vega wallet on local testnet token or token.fairground

## Expected behaviour

Wallet should connect

**Comment by ValentinTrinque** [comment]
Could it be because of chain ID not being broadcast correctly ?
