### ISSUE TITLE
Warning or button disabled should be present when submitting order with 0 size

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#1693]
## Description

Following situation happen when Market state is PENDING, it works fine for ACTIVE market.
When trying to place an order with 0 size, there's no information that user made a mistake. Some warning info would be useful or button disabled.

## Steps to Reproduce

1. Go to Trading app.
2. Choose some market.
3. Set Size to 0.
4. Place an order.

## Expected behavior

Warning or button disabled should be visible.

## Actual behavior

User can click the button but nothing happens.

**Comment by campbellssource** [comment]
little note from UX team. generally we are not fans of disabled buttons. it is better to give the user something to click and then use that click event to show them something is wrong

**Comment by radoslaw-szpiech** [comment]
Yeah, so it could of course work that way - user clicks the button, then UI validation is being done and displays information (in a form of pop-up, or some red warning text somewhere) that it won't work.
