### ISSUE TITLE
It is possible to create GTT limit order with expiry date in past

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#1694]
## Description

User can submit order with Expiry date and time set to past. Date picker does not allow to do it, but one can modify input field with their own date.

## Steps to Reproduce

1. Go to Console app
2. Choose limit order.
3. Choose Good 'til Time (GTT)
4. Modify the date input field to set it to past.
5. Submit order.

## Expected behavior

It should not be possible.

## Screenshots

<img width="938" alt="image" src="https://user-images.githubusercontent.com/24473278/194851936-4610a6e4-1e52-4e95-84ff-65565c12fce0.png">

**Comment by campbellssource** [comment]
from https://github.com/vegaprotocol/frontend-monorepo/issues/1691#issuecomment-1273246392
> Console should never prevent you from placing any type of order but should tell you if it knows that that order will not work.

So in this scenario I'd expect something to tell you that the date you have selected is in the past, but not prevent you from sending the order (just incase there is an odd reason the user wants to submit one in the past, or how "past" is determined is fuzzy)
