### ISSUE TITLE
Total rewards earned in each asset 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1710]
## Story

See my total rewards earned in each asset 

Requires API change - we don't have this right now!

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by sam-keen** [comment]
This is now possible with `rewardSummaries`
