### ISSUE TITLE
Scrolling down a list of orders throws a Runtime Error

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/frontend-monorepo#1717]
## Description

Scrolling down a long list of orders in the orders tab an error `TypeError: undefined is not an object (evaluating 'data.market')` is thrown.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/702798/195213372-985d8002-76c7-4632-bf4d-a89b43fd17a4.png">

This is thrown part way down the list (unsure how best to investigate further)

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/702798/195213510-1dd960aa-c974-4f17-aa0b-6cb271f5260e.png">

**Comment by edd** [comment]
Closed as a duplicate of https://github.com/vegaprotocol/frontend-monorepo/issues/1674
