### ISSUE TITLE
Don't show mainnet network on console

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1734]
## The Chore

The network switcher on console shouldn't show mainnet as an option as trading is not enabled yet.

Currently the network switcher declares some constants within the component file to create the dropdown. This const and the dropdown should be decoupled so that the networks can be passed in as props allowing different options per app.

## Tasks

- [ ] Don't render network if its not configured for the environment, currently it shows 'unavailable' text.
- [ ] Update network switcher dropdown to use a 'check' icon rather than '(current)' text so that its aligned with other dropdowns

**Comment by barnabee** [comment]
Seems ok, yeah
