### ISSUE TITLE
Add BlockExplorer link component

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#175]
EtherscanLink component currently consumes NX_ETHERSCAN_URL which is problematic if we ever want to publish the toolkit as it is environment specific at build time, so we need a better solution for easily linking to other apps.

Proposed solution:
- [ ] Add a generic Link component
- [ ] Add some method (hook/context/hoc) of easily consuming these env vars to construct links to both Etherscan and the Vega block explorer
- [ ] Replace usage of the EtherscanLink component with Link components so that it no longer uses env vars

**Comment by dexturr** [comment]
Env URLs

https://vegaprotocol.slack.com/archives/C033K0B1N2J/p1647967187524509
