### ISSUE TITLE
Reward estimate this epoch

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1750]
## Story 

As a user
I want to see my estimated rewards this epoch
So that I can understand the sort of rewards I might earn from my current behaviour

## Acceptance criteria 

- [ ] I can see estimated earnings each reward type that I am currently participating in 
- [ ] I can see what the estimate is based on for each i.e. based on the # of maker fees paid, liquidity fees paid, etc.

## Notes:
Likely deprioritised as the reward pools are not fixed during an epoch, only at epoch end, and could be misleading.

**Comment by JonRay15** [comment]
Literally impossible 

Closing
