### ISSUE TITLE
Trade futures

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1763]
## Chore 

As a team we want to make it clear to console users which product type each market represents so that they know the types of products they can trade AND so that we have a way to show other product types as and when we are ready to. 

## Tasks

- [ ] Add column to market selection (popup, market list page, market list drop down) for "Product type"
- [ ] Add to deal ticket (just above the place order button) - you are buying [n] [Product type*] contract[(s)]

*For right now this will only say Futures as that is our only product type, but want to set this up so that it will just keep working when we introduce additional product types

**Comment by MadalinaRaicu** [comment]
deal ticket text above the button is descoped. 
<img width="1680" alt="Screenshot 2022-11-02 at 19 51 12" src="https://user-images.githubusercontent.com/16125548/199753474-bdaa1ba5-fe4e-477b-93c2-712c83ace7e3.png">
