### ISSUE TITLE
Voting on proposals does not update the percentages in the UI 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#1766]
## Description

1. Open an open proposal
2. Vote on proposal
3. UI updated to indicate user had voted but no change in the percentage (screenshot)

Expected Behaviour:
When users vote on a proposal, the percentage of the total votes should be updated to indicate if the proposal will pass or fail

![Screenshot 2022-10-17 at 17 03 24](https://user-images.githubusercontent.com/30622993/196394283-8e1fef85-d099-477d-bb28-ba9dd69141da.png)

**Comment by dexturr** [comment]
Blocked by: https://github.com/vegaprotocol/vega/issues/6532

**Comment by dexturr** [comment]
The core issue above has been closed, this will be unblocked after a release has been done.

**Comment by dexturr** [comment]
Just checked and as part of the morning release this is now on testnet. The math however does not appear to be adding up correctly, so must be cleaned up.

A single token voted for and the result was as below.

![Screenshot 2022-10-24 at 08 37 06](https://user-images.githubusercontent.com/26136207/197472447-6de379fb-5b71-48dd-a03e-c03f1a10e1bf.png)
