### ISSUE TITLE
Review and design viewport / screen sizing

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1787]
## Chore

There is something to be tidied up about the way the content scales to large screens (stretching too far width wise). 

This chore is to review how block explorer is laid out / responds to different screen sizes. 

## Tasks 

* Sketch out / define approach 
  * Consider how this relates to the navigation sidebar
  * Consider what would need to happen to the footer 
  * Consider whether the data density is too light (to Edd's point, other transaction lists are a bit more dense but also, not to go too far to make it unreadable)
* Mock it up with everything on screen showing how the end result of the navigation / list improvements should look / feel 
  
* Share approach / review with team
* Create a ticket for prioritisation for development

**Comment by joellecharlotte** [comment]
[Here is the link to the designs in Figma](https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Block-Explorer?node-id=1609%3A5187).

The top row under the section header **Transactions List** shows the designs for each breakpoint.

- Have shown a max width on a 2K monitor which is the >1536 breakpoint without the Nav Bar.
- From >1024 down the nav collapses.

The second row under the section header **Scroll Behaviour** shows the proposed scroll behaviour which is:

- Would be nice if the list is not constrained to it’s own scroll area but rather the entire page scrolls (with a fixed top nav and left nav if possible)
- Footer is not fixed, it lives at the end of the list. It’s also aligned to the content and not the Nav Bar.
- If there is a concern about the length of the list, could we add a “See more” button or do infinite scrolling? (Appreciate this is possible more complex to implement than this task allows for)

**Comment by neildawson** [comment]
[Slack thread](https://vegaprotocol.slack.com/archives/C033K0B1N2J/p1666791561981489)

**Comment by edd** [comment]
This ticket was written a while ago, and the general viewport approach has changed since then. The closes replacement tickets are #4070 and #4071
