### ISSUE TITLE
Update documentation links to remove `/docs/` segment

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1790]
## The Chore

After https://github.com/vegaprotocol/documentation/pull/327 is merged, the `/docs/` segment in documentation URLs. There's a redirect in place to catch these links and point them to the right place, but that redirect won't stick around forever.

### Example
https://github.com/vegaprotocol/frontend-monorepo/blob/9465543b2378fd8850fe26a2a6a3f8adf716bbe4/apps/token/.env.testnet#L10
https://github.com/vegaprotocol/frontend-monorepo/blob/9465543b2378fd8850fe26a2a6a3f8adf716bbe4/apps/token/.env.mainnet#L10

Both of these simply need `/docs/` removed.

## Tasks

- [ ] Find all links, across all apps that link to docs
- [ ] Remove the `/docs/` top level folder

**Comment by edd** [comment]
This ticket is equivalent to https://github.com/vegaprotocol/vega.xyz/issues/260

**Comment by pennyandrews** [comment]
I'm going to close this ticket as it duplicates the following tickets:

https://github.com/vegaprotocol/vega.xyz/issues/260
https://github.com/vegaprotocol/vegawallet-desktop/issues/381
https://github.com/vegaprotocol/frontend-monorepo/issues/1824
https://github.com/vegaprotocol/frontend-monorepo/issues/1825
https://github.com/vegaprotocol/frontend-monorepo/issues/1827
https://github.com/vegaprotocol/frontend-monorepo/issues/1826
