### ISSUE TITLE
Block Explorer TX list unavailable: Add Block Explorer api url for other environments

### ISSUE THREAD

**Issue by elmar-vega** [vegaprotocol/frontend-monorepo#1799]
In order for the Block Explorer translations lists to become functional again to update the API endpoint URLs to point to the new block explorer API service. This will allow the BE api to retrieve txs and display in the list for users to search etc...

Currently the BE API service will be enabled on the Vega mainent Observer data-nodes and done as part of the following devops issue: https://github.com/vegaprotocol/devops-infra/issues/1529. This will become part of standard datanode functionality from the validator core release of v0.58. This version contains performance enhancements for when the community conduct the governance vote to enable trading and the blocks containing much more information than in restricted mainnet today.

**Comment by gordsport** [comment]
Internal networks:
- https://github.com/vegaprotocol/devops-infra/issues/1548#issuecomment-1293296516

mainnet and sandbox TBC
