### ISSUE TITLE
https://token.vega.xyz/tranches page error

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#1803]
## Description
The vesting tranches pages do not work, the show "something went wrong" after which you need to refresh the whole page.

## Steps to Reproduce

1. Go to https://token.vega.xyz/tranches
2. Click on any of the tranches pages or go directly to e.g. https://token.vega.xyz/tranches/1

## Expected behavior

Access the tranches page

## Screenshots
<img width="850" alt="Screenshot 2022-10-20 at 13 23 08" src="https://user-images.githubusercontent.com/100769129/196936098-1e6e644d-1230-4cc7-8e11-ba279c833f03.png">
<img width="850" alt="Screenshot 2022-10-20 at 13 21 19" src="https://user-images.githubusercontent.com/100769129/196936108-0cfdef71-81d2-4b2d-a642-6c16209cffcc.png">

## Device details

**Desktop (please complete the following information):**

- OS: MacOS
- Browser  Chrome

**Comment by JonRay15** [comment]
Removing from known issues board since this was closed a long time ago
