### ISSUE TITLE
Present vote progress bar as an indication of result

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1820]
If I vote, while having minimal tokens, on day one of a proposal and then associate lots more, my vote is still just presented as 1% of the total

Relates to...
https://github.com/vegaprotocol/frontend-monorepo/issues/1766

No guarantee right now that the results in the visual are the outcome of the vote

## Tasks 

- [x] Speak to Dex to understand what's going on here 
- [x] Come up with a solution to solve the misleading "this is going to be the outcome" and the outcome being different problem
- [ ] Implement

**Comment by dexturr** [comment]
Related: https://github.com/vegaprotocol/vega/pull/6554

**Comment by neildawson** [comment]
[Miro exploration](https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764537187343305&cot=14)
[Slack thread](https://vegaprotocol.slack.com/archives/C037HSVGWES/p1666967957920019)

**Comment by neildawson** [comment]
Simplified the first concept:

![Image](https://user-images.githubusercontent.com/1080322/199686487-21c631d3-8d23-4bd9-9a06-462066b16ab5.png)

Got thumbs up from Calum and Dex

**Comment by ckpringle** [comment]
Need to consider how this works with the LP vote logic.
