### ISSUE TITLE
Governance Proposal - Errors submitting proposals using max deadlines

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#1837]
## Description

Seeing this issue similar to the previous min/max deadline bug but only seeing it on max deadlines.

### Steps to reproduce

1. Go to **update** asset proposal form
2. Fill in with valid fields
3. Click 'Use Maximum' for **both** vote and enactment deadline
4. Click submit
5. `PROPOSAL_ERROR_ENACT_TIME_TOO_LATE` Error seen

---------------------------------------------------------------------

1. Go to **new** asset proposal
2. Fill in with valid fields
3. Click on use maximum for all fields - Vote deadline, asset validation deadline and enactment deadline
4. `proposal_submission.terms.validation_timestamp: cannot be after or equal to closing time`
5. Change validation deadline to under the max
7. `PROPOSAL_ERROR_ENACT_TIME_TOO_LATE` Error seen

**Comment by sam-keen** [comment]
This appears to not be a frontend issue, these proposal types have the same enactment max deadlines and use the same deadline-deriving frontend methods as others that are working correctly. I'll raise this with core.
