### ISSUE TITLE
Network name with light theme not displayed

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/frontend-monorepo#1841]
When switching to the light theme in the block explorer, the network name is not displayed (I believe it actually is displayed but in white on white), see the screenshot

<img width="415" alt="Screenshot 2022-10-24 at 12 31 35" src="https://user-images.githubusercontent.com/4346460/197516407-038cdc78-737d-446f-8e5e-2d4e5ab8065b.png">

**Comment by edd** [comment]
Previously fixed
