### ISSUE TITLE
Show expiry time in trade page header

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1842]
We currently only show the date but not the time. We should show the time as well.

Current:
<img width="720" alt="Screenshot 2022-10-24 at 15 58 20" src="https://user-images.githubusercontent.com/6803987/197557569-cdc19dd6-1613-4ddb-8520-1272786d9adf.png">

## Tasks

- [ ] Adjust date format to include time

**Comment by MadalinaRaicu** [comment]
can this added in the settlement expiry tag? @mattrussell36
