### ISSUE TITLE
Handle overlapping text in order book

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1849]
We currently get over lapping text in the order book when its set to a high level of precision. We should add some css to handle overflow with an ellipsis

Seen on: https://stagnet1.console.vega.xyz/markets/18d2ff3b7aa9ac6403804487015a2cc8eefdb91a367ca8213e7ae81836576f45

![Screen Shot 2022-10-25 at 08 55 39](https://user-images.githubusercontent.com/6803987/197824057-57475658-c914-443a-84ba-a3fc58aa79a4.jpg)

## Tasks

- [ ] Truncate text with an ellipsis
- [ ] Ensure resizing the order book can show the full value

**Comment by bglownia** [comment]
```
white-space: nowrap;                   
overflow: hidden;
text-overflow: ellipsis;  
direction: rtl;
text-align: right;
```
