### ISSUE TITLE
Ledger entries date filtering

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1853]
## Story

**As a** trader
**I want** to view ledger entriese for a specific time period
**So that** I can inspect how my collateral was used more closely

## Acceptance Criteria

- [ ] I can filter by start date
- [ ] I can filter by end date

## Additional info

We might be able to leverage AgGrid's built in agDateColumnFilter

![Screen Shot 2022-10-25 at 22 50 57](https://user-images.githubusercontent.com/6803987/197945378-04847b8f-08ad-43b5-88df-2f1e2ba6f274.jpg)

**Comment by MadalinaRaicu** [comment]
Use date range filtering
```
 query LedgerEntries($partyId: ID!) {
  ledgerEntries(
    filter: {AccountFromFilter: {partyIds: [$partyId]}}
    groupOptions: {ByAccountField: [PartyId, AccountType, AssetId, MarketId], ByLedgerEntryField: [TransferType]}
    pagination: {first: 500}
    dateRange: {
      start: <date>,
      end: <date>
    }
  ) {
    edges {
      node {
        ...LedgerEntry
      }
    }
  }
```
