### ISSUE TITLE
TFE: Incorrect label in validator table

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#1870]
## Description

There's a row on the validator info page called "IP address", however the metadata that populates it is the "country" that a node operator provides.

The command that populated the below table was: 

```
vega announce_node --info-url="http://something/" --country="UK" -- name="candida" --from-epoch="19" --submitter-address="0x..."
```

## Expected behavior

The row is labelled country, not IP address.

## Screenshots

<img width="859" alt="Screenshot 2022-10-26 at 16 45 40" src="https://user-images.githubusercontent.com/62548908/198073138-0c4c1c97-72e2-42dd-8790-25d6b1f43e6f.png">

**Comment by dexturr** [comment]
Closed by #1917
