### ISSUE TITLE
Update BE api urls for newly provisioned environments

### ISSUE THREAD

**Issue by elmar-vega** [vegaprotocol/frontend-monorepo#1885]
Update the Block Explorer API urls for:

- [x] Devnet - https://be.devnet1.vega.xyz/rest/transactions
- [x] Stagnet 1 - https://be.stagnet1.vega.xyz/rest/transactions
- [x] Testnet - https://be.testnet.vega.xyz/rest/transactions
- [x] Stagnet 3 - https://blockexplorer.n01.stagnet3.vega.xyz/rest/transactions
- [ ] Stagnet 3 - https://be.stagnet3.vega.xyz
- [x] Mainnet - TBC
- [ ] Sandbox - TBC

Done for:

- [x] .env files
- [x] Netflify

Related to issue https://github.com/vegaprotocol/devops-infra/issues/1548#issuecomment-1293296516
and https://github.com/vegaprotocol/ansible/issues/344

**Comment by pennyandrews** [comment]
https://github.com/vegaprotocol/ansible/issues/344 is now with Daniel to pick up and get sorted for us, Gordon has chased.
