### ISSUE TITLE
Governance Proposal detail - number of days left to vote no longer displayed 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#1904]
## Description

The number of days left to vote used to be displayed in the proposal details page but is now missing. This is picked up by e2e test

## Steps to Reproduce
1. Create new proposal with 3 day vote deadline
2. go to proposal detail page

![Screenshot 2022-10-28 at 16 39 02](https://user-images.githubusercontent.com/30622993/198678099-d6d69765-2324-4e4a-be31-6c1a075137ec.png)

**Comment by ckpringle** [comment]
Solved by #1820
