### ISSUE TITLE
Validator table column heading mouseovers

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1913]
## Chore 

Add mouseovers for each data column. 

## Consensus 

- Stake: The total amount $VEGA staked to this validator including self-stake and all delegation.
- Normalised voting power: Voting power is the relative weighting given to the validator in tendermint consensus.  It is calculated based on the stake share of the validator minus any penalties due to overstaking or performance.
- Total stake share: The stake a validator represents as a share of total stake across the network.
- Total penalties: Total of penalties taking into account performance (considering proportion of blocks proposed against the number of blocks the validator was expected to propose) and any overstaking.
- Pending stake: The amount of stake that will be added or removed from the validator from the next epoch.

## Standby 

- Stake: The total amount $VEGA staked to this validator including self-stake and all delegation.
- Stake needed for promotion: The amount of stake needed for promotion to consensus, assuming constant performance in line with previous epoch.
- Total stake share: The stake a validator represents as a share of total stake across the network.
- Total penalties: Total of penalties taking into account performance (considering proportion of blocks proposed against the number of blocks the validator was expected to propose) and any overstaking.
- Pending stake: The amount of stake that will be added or removed from the validator from the next epoch

## Candidates 

- Stake: The total amount $VEGA staked to this validator including self-stake and all delegation.
- Stake needed for promotion: The amount of stake needed for promotion to standby, assuming constant performance in line with previous epoch.
- Total stake share: The stake a validator represents as a share of total stake across the network.
- Total penalties: Total of penalties taking into account performance (considering proportion of blocks proposed against the number of blocks the validator was expected to propose) and any overstaking.
- Pending stake: The amount of stake that will be added or removed from the validator from the next epoch.

## Acceptance Criteria 

- [ ] I can see a description (e.g. on hover) for each of the above column headings

**Comment by JonRay15** [comment]
Made some changes to normalised voting power based on discussion with Candida.

Also simplified the Total stake share decription because it mentioned it as a share relative to total across consensus validators and I wasnt sure that was actually true ... isnt it just the share of all stake on the network?
