### ISSUE TITLE
token: Add some unit tests

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1916]
## The Chore

Token site unit test coverage is low. I offered to add some. I'm not promising high-value tests, but some tests that increase coverage of things that right now are just trusted.

## Tasks

- [x] Add unit tests for the `token/lib` folder uncovered files

## Tests that are known failing, probably highlighting a bug
- [ ] Abbreviate number can produce '1,000K' which looks like a mistake

# Notes
This is a timeboxed task and probably shouldn't count as a sprint item until someone actually on the team picks up the result. If this ticket is still open after November 4th, 2022, something has gone wrong.

**Comment by pennyandrews** [comment]
It's the 4th November and this ticket is still open @edd 😆

**Comment by edd** [comment]
@pennyandrews I've done a PR with what I got done. It's not much, but, uh, it's some coverage? https://github.com/vegaprotocol/frontend-monorepo/pull/1963
