### ISSUE TITLE
Delay between token claim/credit and token site knowing about it

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#1935]
## Description

Due to the bad performance of the tranches query, we had to write an interim solution to get the site up and running once this query started dying. This serves all data from a JSON file which is generated every 6 hours currently, meaning that the data on the tranches site can be up to 6 hours out of date.

Bug-ish. Token dapp has a delay between the data about tokens being claimed/credited, and the dapp knowing about the actions.

This is a ticket to think about ways to resolve the problem. 

Options:

* https://github.com/vegaprotocol/frontend-monorepo/issues/1823
* Refactor the redeem page, vega wallet card and anywhere else it is possible to check for balances by using ethereum events. Still means some data is out of date but not all. Potential risk of crashing for high usage wallets, of which we know there are some.
* Some kind of indexers contract that presents a better API

## Expected behavior

Token site knows about tokens that a user, without a delay. 

## Screenshots
Photo from community member who had the problem on mainnet

![image](https://user-images.githubusercontent.com/62548908/199474383-c7909f5c-837e-454c-aa5d-36591285cf12.png)

## Additional context

Message from a user reporting the problem: 
There is a community member who has claimed the VEGA reward (incentive program on Fairground). But after claimed  website token.vega.xyz does not show the VEGA vesting he has. So he can't Redeem VEGA from tranches 11
I checked on Etherscan he has 50 VEGA vesting and it is also showing 50 VEGA lock on his Metamask wallet.
I asked him to clear the cache, refresh the page and use another browser but the problem is still not resolved

**Comment by ckpringle** [comment]
Test after completing Tranches service with API for Token frontend #1823

**Comment by gordsport** [comment]
Hey @candida-d 
This has been fixed with the governance site deployment yesterday - I plan to close by EOD unless you have any objections

( @pennyandrews )

**Comment by pennyandrews** [comment]
@dexturr says this is the result of the tranches service being integrated o this can be closed :)

**Comment by JonRay15** [comment]
Removing from known issues board since this was closed a long time ago
