### ISSUE TITLE
Design LP Dashboard in context to the website

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1939]
## The Chore

The plan for LP dashboard is to have it as part of the vega.xyz website, rather than as a stand alone app. Therefore we need to align the app with the website design system. 

We need to consider this from a styling point of view, as well as where it fits in the website, what we call it and how we talk about it and how we handle network switcher etc. 

There is a separate SPIKE ticket to explore and decide on the technical approach to this integration https://github.com/vegaprotocol/frontend-monorepo/issues/2207.

## Tasks

- [ ] UX sketches to decide/decide:
- Is this "markets" or is it "liquidity opportunities"
- Where the dashboard lives on the website (whether and where it needs to be sign posted from beyond the navigation) 
- What we call it / how we describe what it is showing us 
- What CTAs / links out do we need i.e. to Console / docs etc.  
- Decide whether the network switcher is still relevant and if so where it should live (as it won't be global to the site like it is on other apps)

- [ ] Visual designs to define how it should look in the context of the website design system

## Additional details / background info

![Image](https://user-images.githubusercontent.com/46783148/212874102-9cfb7d61-1301-466e-b1c5-65180cc6ca5a.png)

Latest LP Dashboard preview https://liquidity-provision-dashboard.netlify.app/

Latest miro board https://miro.com/app/board/uXjVPS_CqOk=/?moveToWidget=3458764543473916694&cot=14

**Comment by bigfandavid** [comment]
First iteration of design here: https://www.figma.com/file/ZQrh7fiFciTQ9GWD4Pp1Am/LP-Dashboard?node-id=1536%3A13160&t=91G2pWx8Y5FQTrSq-1

Have sent to LP team for review/feedback.
