### ISSUE TITLE
Accommodate long tables on details pages

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1942]
## The Chore

We need a pattern to handle tables with many fields (when there is more than one table on the page) so that a user can still see all of the content about a thing e.g. party without getting stuck in an endless scroll. 

Should be a pattern that applies to any table, but in particular we need this for the delegations and transactions on a party details page.

## Tasks

- [x] Agree approach
- [x] Sketch solution
- [ ] Implement
- [ ] Review and refine with team
- [ ] Merge

**Comment by neildawson** [comment]
As discussed in standup this morning, here's a mock-up (not a final design) of how we might show all transactions for a party on a dedicated page. Note the URLs and back buttons, which indicate where this page sits in the site hierarchy.

![image](https://user-images.githubusercontent.com/1080322/199758280-f48dd7b2-e713-4c9e-98b7-cd44f5bfcb21.png)
