### ISSUE TITLE
Collateral asset amounts does not update after switching key

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#1947]
## Description

When on https://console.fairground.wtf/ on the trading page and positions tab and you change the public key, the collateral tab refreshes but the amounts are stuck on the previous key.

## Steps to Reproduce

1. Go to https://console.fairground.wtf/
2. Watch the Collateral tab
3. Switch to another public key on the same wallet
4. Watch the collateral tab in the bottom left before and after the switch, amounts do not change to the latest wallet.

## Expected behavior

The selected wallets asset amounts should be shown.

## Screenshots
See video

## Device details

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome

https://user-images.githubusercontent.com/100769129/199694087-6a04204d-8164-4d6b-9890-d6ffdc904aeb.mov

**Comment by pennyandrews** [comment]
@mattrussell36 team want to add this to the sprint so we have, flag if you have any reason not too
