### ISSUE TITLE
Import explorer/api to monorepo

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#198]
https://github.com/vegaprotocol/explorer/tree/master/api is currently deployed to a different netlify site from the actual explorer. It's a bit messy. Let's add it here so we can redirect all of explorer.vega.trading to .xyz

Next: https://github.com/vegaprotocol/docs/pull/323

**Comment by dexturr** [comment]
I cannot make this work without deploying the function for every single app in the mono repo on netlify or adding hacky bash scripts as prebuild steps to strip out the function for some sites. I tried to cp the netlify toml before build but netlify does not detect the function in this case. Netlify monorepos are still a bit lack lustre in terms of their netlify config. So I think the cleanest solution is to keep the explorer API in its' own repo.

**Comment by edd** [comment]
This one isn't going to happen - this API will go away.
