### ISSUE TITLE
Governance and token dapp doesn't work properly without a wallet connection

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#1982]
The governance and token dapp needs to be functional for users who do not have or have not connected a wallet (Ethereum or Vega). This means that some pages need changes and some nav links should probably be swapped for different pages.

This ticket is to start a discussion and probably should drive the creation of more tickets where/if the work is not already planned to solve the issues.

~###  Vesting~

~This tab should show `/tranches` by default and use a button/link to allow people to go to the page to see their own vesting, which needs a wallet connection.~

~### Staking~

~When clicking a valdiator row in the table the validator page (e.g. [Commodum DAO](https://token.vega.xyz/staking/b861c11eb825d55f835aec898b3caae66a681a354bcb59651d5b3faf02b34844)) should load if no wallet is connected. Currently requires a wallet.~

~### Rewards~

~- [x] #1710 ~

~This page should list the total rewards paid per epoch (whether you have a key conected or not) and should work if you have no key connected. I think there may be work scheduled on this page already so it may just be a case of making sure it works with no connected key. Also is this going to be staking rewards or all rewards in future.~

**Comment by dexturr** [comment]
The staking changes are already live on Fairground and will be deployed to mainnet on the next release.
> When clicking a valdiator row in the table the validator page (e.g. [Commodum DAO](https://token.vega.xyz/staking/b861c11eb825d55f835aec898b3caae66a681a354bcb59651d5b3faf02b34844)) should load if no wallet is connected. Currently requires a wallet.

![Screenshot 2022-11-08 at 12 20 29](https://user-images.githubusercontent.com/26136207/200562205-126ab2e6-b615-4f19-8766-f5e47f4d2732.png)

So I am going to remove this from the scope of this ticket.

**Comment by pennyandrews** [comment]
The rewards section is already covered by this ticket https://github.com/vegaprotocol/frontend-monorepo/issues/1230 so removed from the scope of this ticket

**Comment by pennyandrews** [comment]
Vesting part covered by this ticket #2331
