### ISSUE TITLE
Display market status

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2004]
## Story

**As a** user
**I want to** see market status
**So that** I can decide whether to trade or not

## Acceptance Criteria

- [ ] https://github.com/vegaprotocol/specs/blob/master/user-interface/7002-SORD-submit_orders.md#7002-SORD-061

## Tasks

- [ ] Update trade header to include market status

**Comment by mattrussell36** [comment]
Have confirmed we want status in the header
