### ISSUE TITLE
[console] Set up Alpha-Lyrae font

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2006]
It would be good to make use of our AlphaLyrae font. 

## Tasks

- [ ] Figure out why next doesn't pick up _document.tsx. This is where the font gets loaded but the html here doesn't get rendere (we could just use _app.page.tsx)
- [ ] Add font declarations to tailwind config

**Comment by pennyandrews** [comment]
Done by @asiaznik
