### ISSUE TITLE
View market creation transaction placeholder

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2011]
## Story

As a
I want
So that

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by edd** [comment]
Dupe of #2111
