### ISSUE TITLE
Navigation to / from the markets page

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2036]
## Chore 

Work out what the navigation to and from the markets listing page should be.

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/207400245-ec824ca6-f246-4c83-b495-23dd41ef696a.png)

Logic 
* Common pattern on KUCOIN, Binance, Injective to have a tabbed "markets" view, the market switching modals should be improved separately but not as part of this ticket

**Comment by PeteWilliams** [comment]
I'd propose something simple like this:
![image](https://user-images.githubusercontent.com/1325606/201939297-df0f14a6-05e5-4c73-ab45-f3abb66ec397.png)

I don't think a 'Markets' link makes sense in the top nav, as 'Trading' - which links to a market - would be a child of it, but represented as sibling. And I don't think it helps to get rid of Trading as it's useful to have a quick link back to the primary interface/market you were just on.

The breadcrumb pattern makes it clear that this is a nav, that Markets will be a list, and that the next label is the selected market. It also fits the pattern that the dropdown is more of a quick switcher and the Markets link is the full monty.
