### ISSUE TITLE
Improve transfer type descriptions

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2039]
## The Chore

Transfer descriptions could do a bit more to help people understand what they're looking at

### New descriptions
Format: (enum from API) = Column text: Tooltip text

(TRANSFER_TYPE_LOSS) = Final settlement loss: Funds deducted after final settlement loss
(TRANSFER_TYPE_WIN) = Final settlement gain: Funds added to your general account after final settlement gain
(TRANSFER_TYPE_MTM_LOSS) = Mark to market loss: Funds deducted from your margin account after mark to market loss
(TRANSFER_TYPE_MTM_WIN) = Mark to market gain: Funds added to your margin account after mark to market gain
(TRANSFER_TYPE_MARGIN_LOW) =  Margin topped up: Funds deducted from your general account to meet margin requirement
(TRANSFER_TYPE_MARGIN_HIGH) = Margin returned: Excess margin amount returned to your general account
(TRANSFER_TYPE_MARGIN_CONFISCATED) = Margin confiscated: Margin confiscated from your margin account to fulfil closeout
(TRANSFER_TYPE_MAKER_FEE_PAY) = Maker fee paid: Maker fee paid from your general account when your aggressive order was filled
(TRANSFER_TYPE_MAKER_FEE_RECEIVE) = Maker fee received: Maker fee received into your general account when your passive order was filled
(TRANSFER_TYPE_INFRASTRUCTURE_FEE_PAY) = Infrastructure fee paid: Infrastructure fee paid from your general account when your order was filled
(TRANSFER_TYPE_INFRASTRUCTURE_FEE_DISTRIBUTE) = Infrastructure fee received: Infrastructure fee, paid by traders, received into your general account
(TRANSFER_TYPE_LIQUIDITY_FEE_PAY) = Liquidity fee paid: Liquidity fee paid from your general account to market's liquidity providers
(TRANSFER_TYPE_LIQUIDITY_FEE_DISTRIBUTE) = Liquidity fee received: Liquidity fee received into your general account from traders
(TRANSFER_TYPE_BOND_LOW) = Bond account funded: Funds deducted from your general account to meet your required liquidity bond amount
(TRANSFER_TYPE_BOND_HIGH)  = Bond returned: Bond returned to your general account after your liquidity commitment was reduced
(TRANSFER_TYPE_WITHDRAW) = Withdrawal: Funds withdrawn from your general account
(TRANSFER_TYPE_DEPOSIT) = Deposit: Funds deposited to your general account 
(TRANSFER_TYPE_BOND_SLASHING)  = Bond slashed: Bond account penalised when liquidity commitment not met
(TRANSFER_TYPE_STAKE_REWARD) = Staking reward received: Rewards for staking received into your general account
(TRANSFER_TYPE_TRANSFER_FUNDS_SEND) = Transfer sent: Funds deducted from your general account to fulfil a transfer
(TRANSFER_TYPE_TRANSFER_FUNDS_DISTRIBUTE) = Transfer received: Funds added to your general account to fulfil a transfer
(TRANSFER_TYPE_CLEAR_ACCOUNT) = Market accounts cleared: Market-related accounts emptied, and balances moved, because the market has closed
(TRANSFER_TYPE_CHECKPOINT_BALANCE_RESTORE) = Balances restored: Your balances were restored after a network restart
   

## Tasks

- [x] Add a hover/tool tip feature so the transfer types can have a short title and a longer description
- [x] Update fields in libs/types/src/global-types-mappings.ts

**Comment by MadalinaRaicu** [comment]
@candida-d  could you provide two more descriptions for the following?
  TRANSFER_TYPE_CLOSE = 'Close',
  TRANSFER_TYPE_WITHDRAW_LOCK = 'Lock amount for withdraw',

**Comment by MadalinaRaicu** [comment]
review types

**Comment by campbellssource** [comment]
only suggested change is: Trade -> order in 
> (TRANSFER_TYPE_MAKER_FEE_PAY) = Maker fee paid: Maker fee paid from your general account when your aggressive trade was filled
(TRANSFER_TYPE_MAKER_FEE_RECEIVE) = Maker fee received: Maker fee received into your general account when your passive trade was filled

But only on @candida-d's approval

**Comment by campbellssource** [comment]
rationale: when an order is filled is it because a "trade" happened. Trades are just trades. Orders are aggressive or passive IMO

**Comment by candida-d** [comment]
@campbellssource Makes sense, I'll update the issue body with that change.
