### ISSUE TITLE
Do not prevent order submission if margin check fails

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2040]
Even if the user does not have enough collateral we should still let them, on the UI, place an order. 

VEGA, the protocol, will reject the order if needed, but there are cases when the user places an order to short/sell and shorten the size of their previous position. VEGA might allow that order to go through.

The current state of the console prevents that from happening. 

We should display warnings and allow the user to place the order.

**Comment by MadalinaRaicu** [comment]
observed by @jeremyletang. Please feel free to update the description if it is wrong.

**Comment by jeremyletang** [comment]
This is correct. Basically the main thing to remember here is that the estimateOrder API, is first only and estimates, so not guaranteed to be the exact requirement, second this does account only for the worst case scenario for this single order you estimate and doesn't use the state of the market / existing position to calculate the estimate.
