### ISSUE TITLE
Update readme for running e2e tests

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2075]
## The Chore

The instructions need to be brought up to date: https://github.com/vegaprotocol/frontend-monorepo#running-tests implies you can just run them, then https://github.com/vegaprotocol/frontend-monorepo#vega-capsule mentions that 2 of the test suites require a nomad setup, but only contain partial instructions for getting that up and running.

## Tasks

- [ ] Ensure that it is clear for someone unfamiliar with the setup how to run all the tests

## Additional information

Probably worth updating to include:
- Links to nomda/capsule setup
- Links to console-test
- Explanation of wallet setup
- TBD @daro-maj  to update the list here

**Comment by dexturr** [comment]
@edd to review

**Comment by edd** [comment]
I think this is still unclear - It's got more text than it needs. I just want to know how to run the tests for a project I haven't run them for, without having to make a decision about Docker or Capsule. The original ticket is still valid.

**Comment by JonRay15** [comment]
This is clearly way out of date
