### ISSUE TITLE
Investigate market depth sequence number errors

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2085]
## The Chore

We have captured a lot of the following errors in Sentry which indicate that we are missing updates in the market depth subscription.

- Sequence number from delta is lower or equal to last sequenceNumber
- Sequence number gap between delta previousSequenceNumber and stored sequence number

These are manually captured in the market depth provider. This chore is to investigate and fix or creating issues for core to fix.

[Sentry Issue](https://sentry.io/organizations/vega-o3/issues/3734355796/?project=6300613&query=is%3Aunresolved&referrer=issue-stream)

## Tasks

- [ ] Verify if this is a core or frontend issue
- [ ] Fix if possible or create ticket for core

**Comment by bglownia** [comment]
There are two issues logged in sentry which are connected to market depth subscription.

First issue is that "Sequence number from delta is lower or equal to last sequenceNumber"
ie. previous update has sequenceNumber equal 100, in next update we got sequence number lower than 100 
[Sentry issue](https://sentry.io/organizations/vega-o3/issues/3734355796/?project=6300613&query=is%3Aunresolved&referrer=issue-stream)

Second issue is that  there is "Sequence number gap between delta previousSequenceNumber and stored sequence number"
ie previous update has sequenceNumber equal 100, in next update we got previousSequenceNumber not equal 100  
[Sentry issue](https://sentry.io/organizations/vega-o3/issues/3734154250/?project=6300613&query=is%3Aunresolved+Sequence+number+gap+between&referrer=issue-stream&statsPeriod=14d)

**Comment by bglownia** [comment]
Check if it happen that there are separate deltas for same market sent in same update batch
