### ISSUE TITLE
Show oracle details and proofs in market proposals

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2087]
## Story

As a voter on new markets
I want evidence of the market oracle's reputation
So I can decide if it is trustworthy

## Acceptance Criteria

- [ ] I can find oracle details and proofs for each new market proposal and update market proposal
- [ ] I can independently verify those proofs (e.g. look at the specification, links)

## Tasks

- [ ] Implement
- [ ] QA

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/9470695a-3449-4756-a1bd-3e9978c77cc8)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/fb00e63a-b2f9-4348-84cc-78dc2b2080e7)

## Additional details / background info
- Dependent on https://github.com/vegaprotocol/ux-and-visual-design/issues/79, see that ticket for background and design specs
- The oracle profile will also be shown in console, so ideally the same components should be used for consistency – see https://github.com/vegaprotocol/frontend-monorepo/issues/2086

**Comment by pennyandrews** [comment]
Questions about how this works in different environments - do we have a different set of trusted oracles on different environments

**Comment by sam-keen** [comment]
Also on hold pending #3985 being merged
