### ISSUE TITLE
CancelTransfer transaction

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2119]
There should be a bespoke, or slightly useful view for cancel transfers.

However, it's not possible to fetch a transfer by ID, so there is currently (until https://github.com/vegaprotocol/vega/issues/7461#issuecomment-1413664443 is merged) no way to display information about the transfer, so for now the default shared view is adequate.

## This 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/e32afdec-b848-4878-90c9-e03d681b58c0)

## Should look more like this:

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b9bfe904-496d-4744-95d5-aa9c28a912a8)

**Comment by edd** [comment]
Waiting on https://github.com/vegaprotocol/vega/issues/7462

**Comment by edd** [comment]
Now waiting for https://github.com/vegaprotocol/vega/issues/7461#issuecomment-1413664443. A cancel transfer is just an id of a transfer, so until we can fetch one by ID there's nothing worth displaying that isn't already shown in the default view.

**Comment by JonRay15** [comment]
THat Core chaneg is now merged so this shoul dcome into sprint.
