### ISSUE TITLE
Token - Transactions stuck on awaiting network confirmation using wallet v2 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2134]
## Description

Using the new wallet v2 flow transactions on Token app are getting stuck

## Steps to Reproduce

1. Connect latest vegawallet via cli 
2. Make sure there's no tokens associated
3. Go to create new freeform proposal
4. After submit, click yes to tx on vegawallet window
5. Stuck on awaiting network confirmation

## Expected behavior

When user confirms transaction on their vega wallet the transaction should be completed successfully or receive error message as to why it failed. 

![Screenshot 2022-11-16 at 12 17 18](https://user-images.githubusercontent.com/30622993/202419390-b5e6ff54-d011-4cd2-baeb-0c96cd118d80.png)

**Comment by sam-keen** [comment]
Closing as this turned out to be a core issue. Raised a bug which has been fixed: https://github.com/vegaprotocol/vega/pull/6891
