### ISSUE TITLE
Close position can be used over and over and keeps placing new orders

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#2142]
## Description

Using the close position does not remove open positions, they keep in the open positions tab and you can press and approve over and over and it opens / longs / short everytime.

## Steps to Reproduce

1. Go to https://console.fairground.wtf/#/markets/e503cadb437861037cddfd7263d25b69102098a97573db23f8e5fc320cea1ce9
2. Make a trade
3. Go to open positions tab
4. Click close, and approve
5. Click close and approve again
6. Click close and approve again

## Expected behavior

Should be removed after first close position instead it opens new longs/shorts.

## Screenshots

See video of the occurrences and screenshot of the orders

## Device details

**Desktop (please complete the following information):**

- OS: MacOs
- Browser Chrome
- Version Vega 0.62.1

https://user-images.githubusercontent.com/100769129/202436881-8dfa1d14-df35-409b-8e6f-d1fcb81eb476.mov

<img width="1646" alt="Screenshot 2022-11-17 at 10 17 19" src="https://user-images.githubusercontent.com/100769129/202436927-2202a3b4-007f-4bd2-aae7-97ed8b0b538f.png">

**Comment by macqbat** [comment]
can't reproduce it now, because request for cancel position currently seems to be not available in wallet api :-(
