### ISSUE TITLE
Change 'connect wallet' text in tabs to a button

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2148]
## The Chore

This chore is to replace placeholder text in the UI "Please connect Vega wallet" with a button. 

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by mattrussell36** [comment]
Closing this was done in https://github.com/vegaprotocol/frontend-monorepo/pull/2246
