### ISSUE TITLE
scrapped

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2164]

**Comment by PeteWilliams** [comment]
Dropping the current legal disclaimer here as it's hard to reproduce: 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/1325606/203308144-bd4b0a4e-b25d-46c3-82d4-12297387e4a9.png">

**Comment by PeteWilliams** [comment]
So… just spoken to Dave Mac and he did not recognise this content - it didn't come from him.
Looks like a ['starter for 10' from Barney](https://github.com/vegaprotocol/console/issues/6664#issuecomment-1183219279) has been built with the [intention to update it later](https://github.com/vegaprotocol/frontend-monorepo/issues/375#issuecomment-1203061376), but I think that bit may have been forgotten about.

**Comment by PeteWilliams** [comment]
One for @campbellssource to chase Dave Mac on.
