### ISSUE TITLE
LP filters out account balances based on user's pubkey

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2171]
Supplied value is `balance of bond accounts` * `siska network param` 

However, the bond accounts are filtered by the pub key of the user, rather than the pub key of each entry in the LP table. 

This needs to change, however we get account connections from account subscription that does not contain the party Id. 

For each entry we may need to query the bond accounts. 

![Image](https://user-images.githubusercontent.com/16125548/202703453-c37d7a19-dbc8-4dea-8608-dfab2274a98d.png)

**Comment by JonRay15** [comment]
Dependent on https://github.com/vegaprotocol/vega/issues/6862 (which now seems to be merged, but presumably needs to get to Stagnet3)
