### ISSUE TITLE
Add indicator of proposed chain upgrades

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2186]
WIP ticket.

```graphql
{
  protocolUpgradeProposals {
    edges {
      node {
        upgradeBlockHeight
        vegaReleaseTag
        approvers
        status
      }
    }
  }
}
```

Would let us know that a protocol upgrade is coming, and at what height.

**Comment by pennyandrews** [comment]
Edd is this ticket a duplicate of this one that Dex wrote https://github.com/vegaprotocol/frontend-monorepo/issues/1891?

**Comment by edd** [comment]
Yes
