### ISSUE TITLE
Pull in additional data columns: market code, product, price and 24h change, #LPs

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2206]
* Market code e.g. 
* Product type e.g. "Cash settled futures"
* Update label "committed bond" to "Total staked by LPs" 
 * Price and 24h change e.g. **16,543.11   ↑ 5.14%** currently on console here: 
<img width="676" alt="Screenshot 2022-11-24 at 09 23 25" src="https://user-images.githubusercontent.com/46783148/203761966-d9a820e3-e8c3-41ef-911c-5ff24d330ff2.png">

 * Number of LPs _(again we know this in the detail page right now so might be easy to grab?)_

**Comment by ciaran-** [comment]
This should all be in as of #2337
