### ISSUE TITLE
[console] Market dropdown doesn't update market status until the page is refreshed

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#2220]
Found a random bug when I was trying to bring markets out of liquidity auction.

After I added the orders, the markets came out of auction but for some reason the dropdown market list still showed them in auction even though I could move between the markets themselves and see they were now in continuus.

Had to refresh the page to get the dropdown to update with the new status.

![Image](https://user-images.githubusercontent.com/89918817/203792624-27064842-ac91-49e7-b780-8152dab9a5e2.png)

![Image](https://user-images.githubusercontent.com/89918817/203792646-b227cf70-e422-410a-992d-bdb2e2eefb14.png)

**Comment by MadalinaRaicu** [comment]
markets-provider (from the popover `markets-provider.ts`) is skipping updates, this needs to change
