### ISSUE TITLE
Add return per settlement asset to liquidity view

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2226]
## Story

As a potential LP 
I want to understand the sort of return the existing LPs are making
So that I can more easily understand how the conditions of the LP impact the fees earned

## Acceptance Criteria

- [ ] I can see % return per settlement asset of per individual LP in the liquidity view (calculated Total fees / Commitment) 
- [ ] I can see an explanation of the data e.g. on mouseover "The return received by this liquidity provider per unit settlement asset")

## Additional details / background info
Originally came up in the work on the liquidity dashboard.

**Comment by pennyandrews** [comment]
Discussed with Lewis and agreed that there are too many variables for the number to be meaningful and that people looking at the data should be sophisticated enough to get an idea of the sort of return based on the data we are already highlighted
