### ISSUE TITLE
Re-organise  mocks based on the approach we agree to as a team

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2257]
## The Chore

DETAILS TO BE DEFINED.

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by pennyandrews** [comment]
Closed as incorporated into this ticket https://github.com/vegaprotocol/frontend-monorepo/issues/2256 (hope you don't midn)
