### ISSUE TITLE
Network Stats/Status on Block Explorer

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2278]
We did a spike to explore whether network stats live together with the other landing page content or if it should be separate (or something else) on Block Explorer. We didn't agree on a solution hence the ticket needs to be refined, but we have plenty to go on for when it's time to pick up again.

## Story

As a
I want
So that

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

The following are excerpts from [the Miro doc](https://miro.com/app/board/uXjVPVRiSOM=/?moveToWidget=3458764537767813940&cot=14).

Proposal for updated homepage:

![Image](https://user-images.githubusercontent.com/1080322/201983162-ab6ca5e6-a8a1-4a19-9a5c-6e9edb9bb07c.png)

Proposal for new "Status" page:

![Image](https://user-images.githubusercontent.com/1080322/201983274-8522642d-7881-4c8a-8f7f-8ba233a88dd0.png)

This ticket has been de-prioritised. The above proposals have not been reviewed by any stakeholders yet. Calum suggested we show these proposals to Chris and Sunny as a strawman to get a sense of what they think community members may need.

We can pick this up when this ticket is reprioritised.

**Comment by JonRay15** [comment]
This is outdated .... kill
