### ISSUE TITLE
Remove request of all votes in favour of the votes of a party

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2286]
## The Chore

We currently request all votes and filter to the vote a specific party has. This is inefficient and data intensive. We should use the `voteConnection` on the party type for the useUserVote functions.

## Tasks

- [ ] Remove all instances of requesting all votes rather than a single vote
- [ ] Replace these, where needed, with calls for the selected pub keys votes under party (id: "") { votesConnection { ... ect. } }

## Additional details / background info

This is also being removed from core, so this will break the token frontend pretty soon.

**Comment by edd** [comment]
Explorer does have this query in one place - but it's just dumped out to a JSON field at the moment so it's easy to remove
