### ISSUE TITLE
Error handling: Wallet loses connection

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2298]
Currently if the wallet loses connection to Console, a "session not found" error (wallet v1 API) gets served to the user. Could this be handled better, for example by taking that message and serving a prompt for the user to re-authenticate/reconnect their wallet?

This issue might become redundant if Wallet API v2 is used on Console sooner than this is addressed.

![image](https://user-images.githubusercontent.com/62548908/205038913-038ed7d2-b27b-4af1-895f-102547c1c450.png)

**Comment by pennyandrews** [comment]
We think that we have resolved this but it's just not deployed yet. Putting it in just to check
