### ISSUE TITLE
Hosted wallet 

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#230]
It would be good to have a simple hosted wallet app that uses the desktop wallet ui along with the rest api client to allow users to create and manage hosted wallets for incentives and other testing purposes.

This will also make it easier to run incentives on console v2, explorer or other apps

**Comment by gordsport** [comment]
Closing as already implemented.

To manage a hosted wallet use the following URL:
 https://vega-hosted-wallet.on.fleek.co/
