### ISSUE TITLE
Remove `hostname` from `client.connect_wallet` calls

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/frontend-monorepo#2300]
## The Chore

Wallet will no longer accept a `hostname` property for the method `client.connect_wallet`

This is no longer needed as the service resolves it itself based on the `Origin` header and if not present the `Referer` header.

This helps prevents apps pretending to be other apps

## Tasks

- [ ] remove hostname field from method call

## Additional details / background info

Depends on:
- https://github.com/vegaprotocol/vega/issues/5769

**Comment by mattrussell36** [comment]
We are now using @vegaprotocol/wallet-client
