### ISSUE TITLE
TFE should work with Vega Capsule

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#2301]
Since getting the latest[ FE docker containers for vega capsule](https://github.com/vegaprotocol/frontend-monorepo/issues/2252) and re-testing vegacapsule using the [frontends config](https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_frontends.hcl) I see the following issue:

When trying to change the URL that its pointing to to get data:

<img width="951" alt="Screenshot 2022-12-01 at 16 44 32" src="https://user-images.githubusercontent.com/83510148/205110785-ddc91815-e260-4439-9673-caf9e97ab608.png">

`URL = http://127.0.0.1:3028/query`

This then presents me with the following error:

`This app only works on chain ID: 1440`

<img width="353" alt="Screenshot 2022-12-01 at 16 46 23" src="https://user-images.githubusercontent.com/83510148/205110867-9fb27cce-e3aa-4e62-9b21-c641686e07ad.png">

It does however seem to work as expected on BE and console (however I have yet to use these dApps in anger).

The correct chain ID is set in the [config](https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_frontends.hcl#L5), but that's for the ganache image. As far as I understand the FE should take the chain id from the request URL.

_Originally posted by @gordsport in https://github.com/vegaprotocol/frontend-monorepo/issues/2252#issuecomment-1333795401_

**Comment by gordsport** [comment]
@pennyandrews @dexturr 

Ive noticed this on mainnet too: `This app only works on chain ID: 1`

But clicking disconnect and it works OK. 

noticed on:
Chrome Version 107.0.5304.110 (Official Build) (arm64)


I do not see the same on safari or brave (maybe a caching thing in the browser, however didn't go away with Apple+Shift+R)

**Comment by dexturr** [comment]
It should be doing this already, we made this change months ago so likely something has gone incorrect during this.
