### ISSUE TITLE
Show volume by default

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2308]
## Story

As a potential liquidity provider
I want to immediately see the volume of the market
So that I can quickly assess whether to provide liquidity 

## Acceptance Criteria

- [ ] Default market view has volume study selected 
- [ ] Volume study is by default, smaller vertically than the market candles

## Tasks

- [ ] ...

## Sketch
<img width="1803" alt="Screenshot 2022-12-02 at 14 33 45" src="https://user-images.githubusercontent.com/46783148/205316763-8864ebe2-0afe-485a-a450-3a94f91d6c61.png">

**Comment by macqbat** [comment]
Works are needed here in the external library "_pennant_". I think we need something like _defaultSizes_ property in `candles-chart.tsx`, which we could pass by _pennat/Chart_ module to the _allotment_ module, which is ready to handle such a propery.

**Comment by johnwalley** [comment]
I've published a new release [v1.4.0](https://github.com/vegaprotocol/pennant/releases/tag/v1.4.0). This sets the sizes of studies to be half the height on the main content when a study is added or removed. This is roughly the behaviour of TradingView.

It's main downside is that is resets the layout when a study is added or removed. Losing any customisation the user has setup.

I wonder if this would suffice as an interim solution to unblock this feature?

I'll continue to work on a more flexible solution.
