### ISSUE TITLE
Collapse blocks with no transactions

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#232]
[ref](https://vegaprotocol.slack.com/archives/C8W4JQ27P/p1649346582354269?thread_ts=1649346418.169329&cid=C8W4JQ27P)

Collapse blocks when there are no transactions present within the block

**Comment by barnabee** [comment]
That was my initial feedback, I think the ideal situation if possible is to not segregate the transactions view by blocks at all. (though a "hide empty blocks" feature on the blocks view would make sense at some point) but just to focus on listing the most recent N transactions (plus pagination) with block number in the table, like Etherscan's [txs](https://etherscan.io/txs) pages does ([Slack ref](https://vegaprotocol.slack.com/archives/C8W4JQ27P/p1649346783868419?thread_ts=1649346418.169329&cid=C8W4JQ27P)).

**Comment by dexturr** [comment]
`${TENDERMINT_URL}tm/tx_search?query="tx.height<[CURRENT BLOCK ID]"&per_page="10"&order_by="desc"`

Should deliver the required data, but does not and 502s on testnet

**Comment by sam-keen** [comment]
@barnabee initial suggestion added, and I'll look further at what Dex has raised and attempt the continuous TXs list when testnet failures are resolved
