### ISSUE TITLE
Enter pubkey to see rewards and fees received

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2322]
## Story

As a user
I want to filter rewards and fees received by pubkey
So that I can easily search for different pubkeys to my own

Needs to be designed as a reusable pattern for vesting too (which is ETH not Vega).

## Acceptance Criteria

- [ ] I can 
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
<img width="834" alt="Screenshot 2022-12-05 at 16 15 14" src="https://user-images.githubusercontent.com/46783148/205686660-bd22e1e8-3c29-475f-ba07-52472158be73.png">

**Comment by JonRay15** [comment]
This has already been delivered under another ticket.
