### ISSUE TITLE
Error handling: Wallet API version mismatch

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2351]
When the wallet and Console are on different API versions, or there are API issues, the errors are helpful to someone who understands the API but not for a user who is just trying to complete a task. 

Without completely removing the API details, these errors could help users a bit more. I've hit 2, but I'm sure there are plenty of others. 

How about keeping some of the API error messaging but adding something above like ... 
"The Vega Wallet software you are running doesn't support the JSON-RPC API. You can try to update the software you are using or choose a different compatible Vega wallet software." 

This would be helpful for those situations where it's obviously the wrong wallet software version, or it needs API access it can't get because the wallet doesn't offer it. 
<img width="1180" alt="Screenshot 2022-12-07 at 12 40 27" src="https://user-images.githubusercontent.com/62548908/206223884-e3595f42-1990-453f-8b3d-f8603324d25b.png">
<img width="645" alt="Screenshot 2022-12-07 at 12 37 06" src="https://user-images.githubusercontent.com/62548908/206223898-3f140b15-14a3-400b-9603-de4cd8864bd1.png">
<img width="1673" alt="Screenshot 2023-01-23 at 10 35 19" src="https://user-images.githubusercontent.com/16125548/214021827-41e4eebb-9b63-41c7-b83d-49c67d532797.png">

**Comment by ValentinTrinque** [comment]
The error messages from the wallet API have been drastically improved. Let's use them first, and improve those ones, before introducing a mapping. This is much more future-proof than a mapping.

**Comment by MadalinaRaicu** [comment]
another example from @ValentinTrinque 
<img width="815" alt="Screenshot 2023-01-24 at 13 06 10" src="https://user-images.githubusercontent.com/16125548/214313243-a01563d3-55d1-473e-b3e3-f0f86bab013c.png">



Error message could be:
```
The version of the wallet service running at ... is not supported.
Reason: It doesn't expose the API version 2.
Solution: Update the wallet software to a version that expose the API version 2.`
```

**Comment by macqbat** [comment]
Scope of this task has been change according to conclusions from the thread: https://vegaprotocol.slack.com/archives/C8WS7M50E/p1674565800801239
Let's get rid of FE mapping errors, display error messages from the wallet api, Invalid wallet error has to stay, because it's just 404 on endpoint in wallet
