### ISSUE TITLE
Proposals unknown field error now showing

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2379]
## Description
There's been an unknown change that has caused a specific error to no longer show.

Scenario: Trying to submit a raw proposal with an unexpected json field
1. Navigate to raw proposal
2. Fill in json field with the following:
`{"rationale":{"title":"An example raw proposal with unique number of: ","description":"I propose that everyone evaluate the following IPFS document and vote Yes if they agree. [bafybeigwwctpv37xdcwacqxvekr6e4kaemqsrv34em6glkbiceo3fcy4si](https://dweb.link/ipfs/bafybeigwwctpv37xdcwacqxvekr6e4kaemqsrv34em6glkbiceo3fcy4si)"},"terms":{"newFreeform":{},"closingTimestamp":1671294175,"unexpectedField":"i shouldn't be here"}}`

3. Click Submit
4. Error message shown:
`Invalid params: the transaction is malformed`

Expected error message:
`*: unknown field "unexpectedField" in vega.ProposalTerms`

Expected error message is much more descriptive in telling the user which field is rejected by the api.

**Comment by pennyandrews** [comment]
Can we retest once the latest wallet is released  as it may have been resolved already
