### ISSUE TITLE
Gov proposal is missing details

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#2383]
If you look at this proposal in governance there arent that many details... just market, instrument, oracle.
https://token.fairground.wtf/governance/663a81c1e138744b51abe5d1e721f4f888a2bd59abfd00e188baf9335421c89c

no risk model
no price monitoring
no liquidity monitoring

Per @dexturr 

"The issue here is that the fields that are displayed in that need to be manually added as GQL does not support a wildcard character. I am sure that does request those fields though. I'll take a deeper look in 15 mins or so once my hands have unfrozen from the frigid north."

and also 

It's just missing, can you ticket and I'll get it propritised

**Comment by dexturr** [comment]
@JonRay15 I have added the risk model however the other two do not appear to be in the response. Would need API changes in order to faciliate this, unless I am missing something?

**Comment by JonRay15** [comment]
Core ticket raised for this https://github.com/vegaprotocol/vega/issues/7422
