### ISSUE TITLE
Problem connecting eth wallet through wallet connect

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2387]
## Description

On Fairground there seems to be some issues connecting to eth wallet using the wallet connect flow.

1. Unable to connect ledger wallet using wallet connect flow

- Click on connect eth wallet and connect using wallet connect
- Select Ledger
- The ledger app shows connected to Vega but the Token UI is not updated

2. Connecting to different eth wallet

- Connect wallet via metamask
- Disconnect eth wallet
- Try to connect using wallet connect flow
- No response from app to open the QR code etc.

**Comment by JonRay15** [comment]
Old
