### ISSUE TITLE
Proposal page no longer updates automatically to show what user voted for

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2398]
## Description

This has been introduced in regression where the proposal page no longer updates automatically when user votes for/against a proposal. 

1. Go to an open proposal
2. Vote for or against the proposal

Result:

![Screenshot 2022-12-14 at 12 13 36](https://user-images.githubusercontent.com/30622993/207593145-ec798cc4-a9ab-4819-9ddc-b44caa017e53.png)

3. Page updates when user manually reloads the page

![Screenshot 2022-12-14 at 12 18 11](https://user-images.githubusercontent.com/30622993/207593382-52175dda-fc4b-4d82-b519-d4f1cc22603f.png)

**Comment by sam-keen** [comment]
I was not able to replicate this issue. Closing for now

**Comment by sam-keen** [comment]
Banging my head against a brick wall with this one. I'll pick it up again soon when I don't want to throw my monitor out the window
