### ISSUE TITLE
Persist the market I last viewed 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2406]
## Story

As a user
I want Console to remember the market I was last looking at and load that market view when I close and re-open the dapp  
So that I don't have to browse the market list again to find the market I'm interested in 

## Acceptance Criteria

- [ ] I can close the browser tab/window that Console was open in and reopen in a new tab/window and be shown the market view I was last looking at (without the 'select a market to get started' modal opening) 

## Tasks

- [ ] Check local storage for a stored marekt ID in the startup logic before redirecting to market page

**Comment by mattrussell36** [comment]
I'm removing the second AC `The market opens in the same state I left it in, with all the same tabs open`. This will happen in a different area of the code base and we have a ticket that already captures that work
