### ISSUE TITLE
Hanging tilde in deal ticket estimations

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2414]
If there is no value we shouldn't render the tilde

![Screenshot 2022-12-14 at 18 00 04](https://user-images.githubusercontent.com/6803987/207754847-fcfa36b9-ae94-4953-acc9-496e88919cc4.jpg)

**Comment by asiaznik** [comment]
`value: estCloseOut && `~${formatValueWithMarketDp(estCloseOut)}`,` looks like it's ok now

**Comment by mattrussell36** [comment]
Yup this has been fixed
