### ISSUE TITLE
[capsule] First eth transaction not completing

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2422]
## Description

Currently there is an issue when building capsule fresh and performing an Ethereum transaction. The first transaction will always fail or take an unusual long time to complete. This causes the FE UI to freeze without ever showing that the transaction has been completed/submitted successfully. 

This is further investigated by ops:
https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1670270033616939

In the mean time a workaround was created to perform an eth transaction at the start of the test run with an explicit wait #2229 

Once this issue is fixed, the workaround should no longer be needed and can be deleted.

**Comment by pennyandrews** [comment]
Need support from the capsule guys Joe to check if they have a ticket for this

**Comment by pennyandrews** [comment]
@jtsang586 to create a ticket for Ops and flag with Gordon so it gets planned in

**Comment by jtsang586** [comment]
Ticket created for Ops to investigate here:
https://github.com/vegaprotocol/devops-infra/issues/1773

**Comment by JonRay15** [comment]
Capsule ... wont do
