### ISSUE TITLE
Remove the support for old `token` property and the other hacks

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/frontend-monorepo#2458]
Blocked by:
- #2457 
- https://github.com/vegaprotocol/vega/issues/6895

---

Remove the reading of the `token` property in the JSON-RPC payload.

**Comment by notbot00** [comment]
migrating the current implementation in https://github.com/vegaprotocol/frontend-monorepo/blob/develop/libs/wallet/src/connectors/json-rpc-connector.ts to use the newly released client (https://www.npmjs.com/package/@vegaprotocol/wallet-client) would ideally solve this, and require less maintenance from the frontend people, providing a unified interface.

it's ultimately up to you, if you want to implement it using the generated client or prefer to have more control with writing your own thing.

**Comment by mattrussell36** [comment]
We have already migrated to using vegaprotocol/wallet-client
