### ISSUE TITLE
Implement layout for portfolio page

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#248]
Link to deposits and withdraws
use existing components
deal with connected/not connected state

**Comment by PeteWilliams** [comment]
Initial design for Portfolio page: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=386%3A4673

Includes tabs for:
* Positions
* Orders
* History
* Fills
* Collateral
* Deposits
* Withdrawals
