### ISSUE TITLE
Ensure mainnet incident regarding delegations will not occur again

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2509]
## The Chore

During a mainnet incident in order to resolve a join issue the following PRs were raised:

https://github.com/vegaprotocol/frontend-monorepo/pull/2393
https://github.com/vegaprotocol/frontend-monorepo/pull/2392

We need an anologue of this solution for mainnet, ideally not using rest.

**Comment by pennyandrews** [comment]
Duplicate
