### ISSUE TITLE
Market selected no longer available - add link to all markets underneath

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2540]
Have a link to markets/all underneath “market not found” for a user to click on. Once they pick a market, that would update the marketID in local storage and fix it.

**Comment by mattrussell36** [comment]
Not sure this is worth doing as the last visited marketId is stored in local storage which is not shared between deployed environments. This issue only happens when running on localhost localhost.

**Comment by candida-d** [comment]
This also happens in prod, on testnet. If you have an outdated market in your cookies, you're redirected to a "market not found" error. cc @mattrussell36 

https://user-images.githubusercontent.com/62548908/211546806-9fea0b9b-b4b0-41c3-a9b9-e22b20374245.mov
