### ISSUE TITLE
Ledger entries and fills table goes blank when scrolling (stagnetRC v0.66.0)

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#2544]
## Description

When you scroll down to the end of ledger entries in console, it stops and then goes black, you can’t scroll up unless you re-sort the table.

## Steps to Reproduce

1. Go to (https://stagnet1.console.vega.xyz/#/portfolio)
2. Scroll down until the end and wait
3. It goes black, tries to scroll up, 
4. Resort the table based on e.g. Vega Time and the data should re-appear

## Expected behavior

The table should not go black.

## Screenshots

https://user-images.githubusercontent.com/100769129/211019936-6ecb4bee-54ba-43f3-a924-26ee4ac566f6.mov

## Device details

- OS: macOS
- Browser Chrome
- Version v0.66.0

**Comment by MadalinaRaicu** [comment]
@daunatv would you be able to provide your pubkey?

**Comment by pennyandrews** [comment]
May already be resolved by Bart but need to check and verify

**Comment by mattrussell36** [comment]
This also happens on the fills table. Its likely the same issue so worth investigating that too
