### ISSUE TITLE
Wallet client trace ID error

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/frontend-monorepo#2552]
## Description

When sending a transaction, we see this error:
```
 An internal error occurred: requesting the transaction review failed: the trace IDs between the request and the response mismatch: expected "...", got "..."
! The request has been canceled.
```

This is most likely due to sending a request two times from the dApps.

## Steps to Reproduce

The bug can't be reproduced consistently (at least we haven't found a way), it will require some further investigation.

1. connect your wallet to a dApp (e.g. console)
2. submit an order

## Expected behavior

Not having a request error.

**Comment by daunatv** [comment]
https://github.com/vegaprotocol/feedback/discussions/124
Looks like there is already a ticket and fix on its way
