### ISSUE TITLE
Wallet restarted but console does not show wallet is disconnected

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2555]
Try to place a transaction and it shows. “TRANSACTION FAILED - Something went wrong”
Users have:
1: go to console
2: restart wallet
3: place an order and error appears.

To the user it seems they still have their wallet connected. 
Only after refresh they realise they are not.

**Comment by daunatv** [comment]
Screen recording of the event.
https://user-images.githubusercontent.com/100769129/211351706-31b3a6be-e1b8-47fb-b9ef-43ae1e389719.mov

**Comment by mattrussell36** [comment]
I would suggest adding a bespoke message here such as 'Wallet service inactive' rather than just 'something went wrong'

**Comment by asiaznik** [comment]
The toasts inform now that the connection is lost 

![Image](https://user-images.githubusercontent.com/1980305/211853267-8a45fd0f-ff69-4611-9246-c591ba1947eb.png)

We can refine though the message and maybe also make it more visible (in the selected keys dropdown) that the connection is lost

**Comment by pennyandrews** [comment]
We could at least refine the message in the toast and investigate why Maciek's previous work around this is no longer working (or remove duplication if it is)
