### ISSUE TITLE
Filter ledger entries table by account type

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2559]
## Story

As a user
I want to be able to filter the ledger entries table by account type
So that I can inspect asset movement more closesly

## Acceptance Criteria

- [ ] I can filter by sender account type
- [ ] I can filter by receiver account type

**Comment by macqbat** [comment]
An additional issue has been created [here](https://github.com/vegaprotocol/vega/issues/7339) for make some improvements in API for this use case
