### ISSUE TITLE
Switch approve and faucet to use toasts instead of the dialog

### ISSUE THREAD

**Issue by asiaznik** [vegaprotocol/frontend-monorepo#2566]
comment (non blocking): lets not forget, to come back and switch these to use toasts instead of the dialog. These are more simple Ethereum transactions so if we have everything in place to make the switch now, I say lets go for it.

_Originally posted by @mattrussell36 in https://github.com/vegaprotocol/frontend-monorepo/pull/2495#discussion_r1061037927_

### Tasks
- [ ] UX
- [ ] Dev
- [ ] Test

**Comment by pennyandrews** [comment]
Need to consider how the toast works in the context of the dialog / overlay etc. from an experience pov
