### ISSUE TITLE
Blockchain explorer account asset balance sorting

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#2572]
## Description

When you access a public key on the blockchain explorer you see the balances of each asset, however there is no particular sorting that I can figure out. 

## Steps to Reproduce

1. Go to (https://explorer.fairground.wtf/parties/0x69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f)
2. View asset balance sorting
3. As you can see the same asset appears twice since it appears on Margin and Market, but they are not next to eachother.

1) Sorting should be done by asset name on first level with expandable header with total balance of the asset:

2) One expandable header row per asset with columns for the balance for the party in 
- general, 
- sum of all margin
- sum of all bond accounts for that asset, 
- **Along with a grand total.**

3) When you click the row to expand it, it would open up to show the individual per market accounts on a row each and one row (perhaps highlighted differently) for general account balance. 
Could still use just one row per market, using both the margin and bond columns as needed plus the grand total.
Similar to:
<img width="353" alt="Screenshot 2023-01-11 at 13 03 42" src="https://user-images.githubusercontent.com/100769129/211803258-defe0a16-ab0a-49d7-b0c4-5625bcae7229.png">

## Screenshots

<img width="853" alt="Screenshot 2023-01-11 at 11 59 19" src="https://user-images.githubusercontent.com/100769129/211794584-708acc21-a865-4cb2-9890-1a2e133757d2.png">

## Device details

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version Vega v0.66

**Comment by barnabee** [comment]
My comments from Slack:


> **(Michael:)** my :2cents:
> primary sort by asset then type (in a set order)...
>
>    - Genereal
>    - Margin
>    - Bond
>
> I think there are other types in the protos but are not used

The other account types mostly or all don't apply to individual parties. The best version of this IMO would be something like:

One expandable header row per asset with columns for the balance for the party in general, sum of all margin, and sum of all bond accounts for that asset, along with a grand total.

When you click the row to expand it it would open up to show the individual per market accounts on a row each and one row (perhaps highlighted differently) for general account balance. Could still use just one row per market, using both the margin and bond columns as needed plus the grand total.

**Comment by barnabee** [comment]
the levels at which I think balance info is generally useful/interesting:

1. How much money does someone have in total
2. How much of it is currently spoken for vs available (plus odds and ends like "being withdrawn"/"in the process of being deposited", etc.)
3. What is their total exposure to each market
4. How is that exposure made up between: margin on positions/orders, LP bond

**Comment by campbellssource** [comment]
IMO The rules for how we display these account breakdowns should be common and shared (at least loosely) across each app that shows account balances.
I'm going to document the requirements in the specs repo: https://github.com/vegaprotocol/specs/pull/1512

**Comment by edd** [comment]
@barnabee I've made a new ticket (#2672) to track what you've said, but in the meantime I'm going with Dan's suggestion A. @campbellssource I would have used your doc but I don't think it's in there - but it'll be easy to align my stuff with yours when you do.

For now: I'm doing what @daunatv wants because it'll be more useful than what exists now.

**Comment by edd** [comment]
Closing due to #5240
