### ISSUE TITLE
Add rewards pools to liquidity rewards and penalties page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#2573]
I think on this page https://docs.vega.xyz/testnet/concepts/liquidity/rewards-penalties we just need maybe another subheading on "Additional liquidity provider rewards" or words to that effect.  

It would just say something like:

"In addition to fees, anyone can fund reward pools that will pay out to LPs at the end of each epoch based on the proportion of fees they have received.  To learn more about this, and trading rewards in general see https://docs.vega.xyz/testnet/concepts/trading-on-vega/fees-rewards."

**Comment by pennyandrews** [comment]
Closing this as it's in the wrong repo. I've recreated it here https://github.com/vegaprotocol/documentation/issues/470
