### ISSUE TITLE
Move KeyValueTable into monorepo

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#258]
In the token application there is a component called `KeyValueTable`. We need to share this across multiple applications so i needs to be moved into UI toolkit. 

- [ ] Take the component at `apps/token/src/components/key-value-table`
- [ ] Move it into UI toolkit
- [ ] Remove all SCSS in favour of the new tail wind setup. Don't worry about matching greys exactly if it is not possible just find the closest. 
- [ ] Move over unit tests

**Comment by mattrussell36** [comment]
Would be good to add a story for it too 🕊️
