### ISSUE TITLE
Blue area on chart

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#260]
![image](https://user-images.githubusercontent.com/13255539/163351870-01b1cb3e-3316-49fb-a224-007321767b50.png)

iOS iPad safari

https://deploy-preview-255--vega-trading-app.netlify.app/markets/2a937feffa4cd672026d6525db443172c4c3cb947f4c330504c5f594310aacac?portfolio=orders&trade=orderbook

Could be just an old branch 👆

**Comment by edd** [comment]
This is also happening to me in #246, so a relatively up to date branch.

# Firefox, Safari, Brave on OSX
<img width="734" alt="Screenshot 2022-05-04 at 17 44 04" src="https://user-images.githubusercontent.com/6678/166734789-43a37aa9-7c17-4c6a-8806-1d53fab264da.png">
<img width="644" alt="Screenshot 2022-05-04 at 17 43 38" src="https://user-images.githubusercontent.com/6678/166734777-bb778ccf-90bb-44f1-96bd-c5b23fee7da7.png">

This only happens in light mode. Dark mode works fine. The blue is consistent between browsers.

As I was viewing it on a deploy preview, I was going in with no cookies set - so no theme preference or anything. I would click in to a market that has live activity and is not suspended, and consistently see the blue.

**Comment by johnwalley** [comment]
I think this was inadvertently fixed when I updated the background colours to be pure black and pure white. I can repro the behaviour on the branch you linked Edd but not on master.

**Comment by dexturr** [comment]
This is still present on OSX

**Comment by johnwalley** [comment]
Thanks. Will get to the bottom of it!
