### ISSUE TITLE
Order book fixes

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#2600]
## The Chore

- Remove horizontal lines (best-static-prices) from order book
- Order book scrolling to bottom
- TBD

There are horizontal lines on the orderbook that are placed on the best static prices.

<img width="653" alt="Screenshot 2023-01-12 at 12 14 03" src="https://user-images.githubusercontent.com/13255539/212063801-996240ec-fb08-41b0-98e4-2f55da3beef1.png">

However, these values come in a different stream/subscription than the orderbook data, and are often out of sync. This causes the order book to render in ways that don't make sense. creating user confusion. e.g.

<img width="859" alt="Screenshot 2023-01-12 at 12 21 27" src="https://user-images.githubusercontent.com/13255539/212065174-4ee9f58c-c8f6-4542-90a2-13e109575d53.png">

They are clearly in the wrong place here as they are both on the buy side which is not possible during continuous trading

Rather than attempt to get them in sync at this point this ticket is just to remove them and we can investigate bringing them back if/when users need them. As it stands we think it is only Liquidity providers or particularly savvy traders who would be interest in this data and may have better tools for dealing with it.

@mattrussell36 suggested this could be done as part of https://github.com/vegaprotocol/frontend-monorepo/issues/2156 or on its own

Note: these values Should still appear in the Market info section (in their current place)

## Tasks

- [ ] remove the lines (and associated logic) from the display

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1673267318202879

**Comment by mattrussell36** [comment]
@bglownia I'm happy to remove the lines if easier, but how easy will it be to also stream in the market data with a derived data provider?

**Comment by campbellssource** [comment]
Looks like a similar issue on depth chart.

![image](https://user-images.githubusercontent.com/13255539/215450439-9ed1fe09-b3cb-46f6-a748-08ae9771b399.png)

Deriving the mid from the order book data is defo nicer.

**Comment by bglownia** [comment]
I found found some bugs around scrolling and keeping selected price in center. There were some changes in header and footer height without adjustments in code that is responsible for counting which price is in center and adjusting scroll to keep in in center (if possible) after number of rows has changed.
