### ISSUE TITLE
No data records under Position tab/Trading

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2604]
### Discussed in https://github.com/vegaprotocol/feedback/discussions/100

<div type='discussions-op-text'>

<sup>Originally posted by **zouhairstitou** January  9, 2023</sup>
I have entered many trades, and there is no data, in fact the whole record line is missing. Nothing appears in the position tab. I was still in position but the tab was empty, all the time.

At the time i just wanted to know the realtime PnL.

</div>
Screenshots here: https://github.com/vegaprotocol/feedback/discussions/100#discussioncomment-4644690

**Comment by mattrussell36** [comment]
Closing. Fixed by https://github.com/vegaprotocol/frontend-monorepo/pull/2620
