### ISSUE TITLE
Show zero balance accounts

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2610]
## The Chore

Currently we filter out accounts which don't have any balance lets not do that and ensure all accounts are shown, even if they have 0 balance

## Tasks

- [ ] Remove filter for 0 balance accounts

## Additional details / background info
https://vegaprotocol.slack.com/archives/C037STCKMGC/p1673524175418019

**Comment by MadalinaRaicu** [comment]
![Screenshot 2023-02-01 at 15 56 58](https://user-images.githubusercontent.com/16125548/216095567-61540a10-ee00-44c8-8f00-8b03be2c3bbe.png)
I don't think we filter empty accounts anymore. 
Just did a complete withdrawal and the row still shows
