### ISSUE TITLE
Rename sender and receiver fields in ledger entry query

### ISSUE THREAD

**Issue by AnExsomnis** [vegaprotocol/frontend-monorepo#2618]
Related to latest changes in the ledger entries listing and filtering - we need to get consistent on the naming of 
Accounts from/to inside the objects.
In the core part we set everything to `FromAccount` and `ToAccount` from now on.
Please correct that accordingly in the FE part.

**Comment by gordsport** [comment]
Blocked by:

- https://github.com/vegaprotocol/vega/issues/7211
