### ISSUE TITLE
Links from LP Dashboard to Console

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2641]
## The Chore

1. Add ability to click on a market and it takes you to that market 
2. Add a "View All" button which takes you to the Console "Markets" screen 
3. Both links must go via the console.vega.xyz link which is the new interstitial

NOTE that currently you will not be able to link to specific pages for 1 and 2...but there is a ticket [here](https://github.com/vegaprotocol/ipfs-redirect/issues/6) which will allow for this.

## Acceptance Criteria

- [ ] When I am directed away from vega.xyz to a view on Console mainnet I am routed through the interstitial page warning me that I am leaving Vega
- [ ] When I am directed away it should launch a new tab and NOT a new window (observed on Safari)

**Comment by JonRay15** [comment]
We NEED to do a couple of things here .... I'm not sure about the more UX-y parts. 

I have added to the main description with this stuff.

**Comment by JonRay15** [comment]
This is now working ... but we've requested a hover over clicky thingy.

**Comment by ciaran-** [comment]
we now have a "hover over clicky thingy"

(mouse pointer!)
