### ISSUE TITLE
Market list disclaimer content for LP Dashboard

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2643]
## The Chore

We might want something like Coinmarketcap disclaimer - a "be careful when you swim in these waters..." These market exist... this is our understanding of the information... e.g. https://coinmarketcap.com/disclaimer/ - linked to / shown in context of the LP Dashboard. This chore is to define what that would be and what's needed.

[Proposed text from Dave](https://docs.google.com/document/d/1ZfCd_rys9p6DX9KL72HGIW_0QHD0HXt6fosxz-m9W6U/edit)(subject to change)

## Tasks

- [ ] Get draft wording
- [ ] Agree approach to display
- [ ] Finalise wording
- [ ] Finalise build

**Comment by JonRay15** [comment]
Think this is now covered by work on the website ... dont think we have our own disclaimer here.

**Comment by JonRay15** [comment]
Added a link to Dave's proposed text for this.  Need to agree approach for showing it .... do we have a pattern?

**Comment by JonRay15** [comment]
We think something like this ... doesnt need to be orange necessarily ... white would be fine too.



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/a8ad51fb-004b-44aa-8312-a44d4cdb5897)

**Comment by pennyandrews** [comment]
[@Ciaran](https://vegaprotocol.slack.com/team/U047YMLB4LA)
 we had a module that I recently removed from the key concepts and use vega pages that we could reuse for this. You can see the code I removed in this PR https://github.com/vegaprotocol/vega.xyz/pull/536/files

**Comment by ciaran-** [comment]
I don't seem to have access to the full text from Dave - sorry!

Below is a screenshot of the component on the page - is this what we want? Do we want the _whole_ disclaimer in that box or the button/link to another small page with the 'full' content? cc @ckpringle @JonRay15 



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6756742/ad6b410c-f859-4bd4-be17-d70517482e3a)

**Comment by pennyandrews** [comment]
I've slacked Dave (with all you guys included for visibility) asking him for access or to paste the content into the slack thread as I don't seem to have access any more either
