### ISSUE TITLE
New navigation token drop down behaviour

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2656]
## Description

When using the token drop down menu in the main site navigation, I can accidentally jump to the token landing page without ever seeing that there is a menu of icons, based on where I click. 

## Steps to Reproduce

1. Go to 'https://token.fairground.wtf/token'
2. Click underneath "Token" in the primary navigation
3. Notice you have jumped to the token page without seeing the token drop down. This behaviour does not occur if you click on the word Token, only on the space underneath. Suspect the bug is related to the tab pattern - it's like you click where the tab indicator would be and that's what's caused this problem.

## Expected behaviour

I'd expect a click to trigger the menu opening for the token sub menu, and that be **the only way you can reach the pages** contained within the token drop down.

**Comment by sam-keen** [comment]
@ckpringle a hover triggering the dropdown's not possible with our current solution. Hover is an inconsistent property for touch screens anyway, I think staying with a click controlling the behaviour is a safer solution for cross-device consistency. I've ensured no part of the link can take you to the Token route directly, the dropdown should open no matter what.
