### ISSUE TITLE
Show settled and trading terminated markets

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2661]
## Story

As a market proposer
I want see the markets that have been settled or are in the trading terminated mode
So that I know the status of the markets I settled

## Acceptance Criteria

- [ ] I can see another tab with settled or markets in trading terminated state
OR
- [x] I can see status on all markets

## Tasks

Refine ticket as first task

## Screenshot current view 
![image](https://user-images.githubusercontent.com/16125548/213177381-f71682c4-0f91-4540-9eb7-a3a8b44ea47c.png)

**Comment by MadalinaRaicu** [comment]
We are showing status but not displaying settled markets. 
Trading terminated markets should be visible too.

**Comment by pennyandrews** [comment]
Refine to focus around showing settled markets and work out if there is anything we can get from core on this

**Comment by campbellssource** [comment]
This has a blocked by core label but I can't see why it is?
@MadalinaRaicu @pennyandrews 
settled markets are coming back on API:

<img width="1027" alt="Screenshot 2023-01-27 at 12 54 00" src="https://user-images.githubusercontent.com/13255539/215091961-a8a4ac81-bfa8-4fd5-b62f-981793f8a361.png">

**Comment by MadalinaRaicu** [comment]
happy to remove the tag

**Comment by macqbat** [comment]
Is here still something to do, or we can close this one? "All markets" tab should display settled too provided that such a market doesn't have `TRADING_MODE_NO_TRADING` as tradingMode

**Comment by campbellssource** [comment]
I think there are a few groups/views we should have of markets...
- Markets that are "Open" i.e. Active or Monitoring auction 
- Markets that are "Proposed" i.e. Opening auction
- Markets that are "Closed" aka done. i.e. "Settled" and "Trading Terminated"
- Markets that are "rejected" these should never appear in console

So although technically a user can "Show settled and trading terminated markets" in console today, I think we should keep this ticket open and add a tab for the 3rd group. This is more appropriate.

I think "All markets" is the wrong label in this scenario
