### ISSUE TITLE
Notification component

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2665]
## The Chore

We have a notification component in ui-toolkit which needs to be b) added to figma/design system b) tweaked to align with the design system

Current:
![Screenshot 2023-01-18 at 10 53 50](https://user-images.githubusercontent.com/6803987/213269534-67b555bd-5089-4cab-866b-ed65781f43df.jpg)

![Screenshot 2023-01-18 at 11 00 09](https://user-images.githubusercontent.com/6803987/213270518-612df34c-9bd4-43e2-aabd-e684d28af23f.jpg)

## Tasks

- [x] Add to figma
- [x] Design tweaks
- [x] Dev

## Additional details / background info

This is currently used in two places
- Asset dialog, to warn of a pending asset proposal
- Trade page header, to warn of a pending market proposal

**Comment by joellecharlotte** [comment]
This has been added to the Figma Design System [here](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dAPP-Components?node-id=414%3A1634&t=QUBwYXc0m0JH4zlY-1).

Have started adding some [documentation](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dAPP-Components?node-id=548%3A20522&t=QUBwYXc0m0JH4zlY-1) to some of the components and will build these out as things progress. If there is anything that you think you be useful from a dev perspective to have documented then let me know 😄 

You can see an example of the notification [here](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1410%3A8517&t=cyMjdVPAmJxtYFNc-1) also.
