### ISSUE TITLE
Add syntax highlighter component to ui-toolkit

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#272]
Both explorer and token apps require syntax highlighting for JSON data. Lets have a ui-toolkit component for this to share component logic and theme setup.

- [syntax highlighter in explorer](https://github.com/vegaprotocol/frontend-monorepo/blob/e26caef36889a8b1fe79d2a3bca448699100149f/apps/explorer/src/app/components/syntax-highlighter/index.tsx)
- [syntax highlighter in token app](https://github.com/vegaprotocol/frontend-monorepo/blob/af43defd514f4b53f5a228968dceb2aa633623b9/apps/token/src/components/syntax-highlighter/syntax-highlighter.tsx)

**Comment by sam-keen** [comment]
Blocked by https://github.com/vegaprotocol/frontend-monorepo/pull/229. 

When unblocked, use the explorer syntax highlighter, as it will have the light theme added in #216
