### ISSUE TITLE
Allow Input to accept prepend/append elements

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#273]
Currently inputs only allow an IconName to be passed as the prop:
`<Input value='foo' appendIconName='hand-up' />`

However sometimes we need to be able to render something completely custom inside, a good example of this is for rendering currency symbols 'inside' the input:
`<Input value={amount} appendElement={<Lozenge>USD</Lozenge>} />`

It would be good to allow Input's props to take either a string (IconName) or a ReactNode for something custom. Props could end up something like:
```
interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  ...
  prependElement?: IconName | ReactNode;
  appendElement?: IconName | ReactNode;
}
```

If an IconName is passed we render an `<Icon />` component otherwise whatever is passed in.

- [ ] Update Input to accept generic element for prepending/appending
- [ ] Update [token-input](https://github.com/vegaprotocol/frontend-monorepo/blob/760753ea3d2f6cad6f3e2acb39f122b78097dd37/apps/token/src/components/token-input/token-input.tsx) to render currency

**Comment by gordsport** [comment]
Closing as in `Done`
