### ISSUE TITLE
Proposal format inconsistencies 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2732]
## Description

When submitting a proposal using the governance site. Certain proposals require the `changes` value e.g. new asset and new market.

However `update market` does not require `changes` and is included in the request when submitting the proposal. 

## Expected behaviour
All proposals should follow the same pattern of consistency and if not should be clearly indicated on the site and the documentation.

**Comment by pennyandrews** [comment]
We are not supporting creation of proposals on Governance right now so won't be addressing this for now
