### ISSUE TITLE
Switch network on wallet v0.8.2 requires a restart for the connect approval to work

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#2739]
## Description

If you open the wallet and are on e.g. sandbox, mainnet etc, and then switch to fairground, and try to connect to console, the popup in the wallet to choose which wallet to connect to does not appear. You first need to restart the wallet.

MacOS (amd)

## Steps to Reproduce

1. Open wallet v0.8.2 and choose "mainnet" or whichever, restart wallet
2. Go to https://console.fairground.wtf/ and try to connect by swtiching network to Fairground in wallet
3. No popup in the wallet appears

Restart the wallet after choosing Fairground, go to console and connect again and it works.

**Comment by pennyandrews** [comment]
We don't believe this is any longer relevant as we are on version 12.02 and have separated apps by network. Feel free to reopen or create a new ticket if you are still experiencing this
