### ISSUE TITLE
Unable to use 1password when asked for password in TFE and desktop wallet

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/frontend-monorepo#2743]
Im trying to use 1password to auto fill passwords in TFE.

Whenever there is an opportunity to enter a password the browser recognises that and drops a 1passord icon in the password text box. 

When user clicks on the icon the window closes
Expected to be able to select 1password password and it dropping into the text box.

**Comment by pennyandrews** [comment]
Note from Dex... On mainnet this effects nothing, on testnet it effects hosted wallet only, so popping in the icebox for now
