### ISSUE TITLE
Misleading info on withdrawing staking

### ISSUE THREAD

**Issue by Vegaklaus** [vegaprotocol/frontend-monorepo#2750]
## Description

When withdrawing from a validator, and then clicking on the name of another validator while the info-box telling me that the withdrawal was successful is still open, the info-box replaces the name of the validator and claims I removed stake from the other validator.
## Steps to Reproduce

On the desktop wallet (apple), withdraw stake from a Validator for the end of the epoch (let's call them bad-validator')

There's now a box saying '$1 Vega has been removed from 'bad-validator'
Click on another validator in the staking list on the right panel (e.g.,' good-validator')
The text in the box now changes to $1 Vega has been removed from 'good-validator'

## Expected behavior

The validator name should not change, or the info-box should disappear.

## Device details

**Desktop (please complete the following information):**

MacBook Air with A1 processor, Firefox browser.

**Smartphone (please complete the following information):**

**Comment by dexturr** [comment]
Fixed on current version, this was tested on an older version
