### ISSUE TITLE
Toast timeout

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2751]
## The Chore
Update toast behaviour:

- [ ] Toasts fade out after a certain period of time 
- [ ] I can see when the toast will fade out e.g. a progress bar 

Kraken Pro example
https://user-images.githubusercontent.com/46783148/214869144-af4d5ea3-87eb-48d8-aac5-e7d2af668acf.mov

**Comment by joellecharlotte** [comment]
Design and documentation added [here](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dAPP-Components?node-id=548%3A20129&t=QUBwYXc0m0JH4zlY-1).
