### ISSUE TITLE
Update asset proposal view formatting

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2760]
## Description

The formatting for showing the asset id in an update asset proposal needs fixing to not show special characters `$``

![Screenshot 2023-01-27 at 10 22 12](https://user-images.githubusercontent.com/30622993/215064050-05f90706-e78f-410c-974e-5dacdd70bc4e.png)

**Comment by pennyandrews** [comment]
Looks like this is no longer relevant

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/13c0150d-7011-4917-bf20-c83b14eed699)
