### ISSUE TITLE
Share of Reward precision

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/frontend-monorepo#2771]
Token Front End
Share of Reward precision needs to extend to show meaningful value
Currently showing 0% even though a % of the reward was paid out

![image](https://user-images.githubusercontent.com/86229849/215465895-1bf68513-3676-4e4b-b986-93b72b87c3a2.png)

**Comment by pennyandrews** [comment]
We have revamped rewards since this ticket so this is no longer applicable
