### ISSUE TITLE
FELT ACTION: Deploy Process

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2795]
## The Chore

The Frontend Project Leads have discussed and decided to move away from Netlify for our deploy process in favour of moving to Vercel.

A constraint is that console has to be deployed via IPFS when we launch Alpha Mainnet AND we would like to complete step 1 before Alpha Mainnet release.

## Agreed actions

- [x] Meeting to discuss the detail and agree a plan forward (before @dexturr goes away)
- [ ] Draft some tickets in preparation
- [ ] Refine them together in the meeting
- [ ] Prioritise tickets and decide how far we want to go by when and how the work will be distributed

## Steps captured to turn off Netlify & Implement S3

1. Docker build image for reproducible builds #2353 - done
2. Pipelines that can take the generic thing and env it up - done
3. Make apps pull from HTML not from build variables - WIP
4. Github workflow to tag a release / kick off pipelines - WIP
5. Work out how this applies to IPFS - done
6. Release logs - done
7. Use conventional commits to determine Major/minor version numbers
8. Bug reporting (which version bugs are coming from)

## Additional details / background info

https://miro.com/app/board/uXjVPZYKrS0=/?moveToWidget=3458764543487292484&cot=14
<img width="1292" alt="Screenshot 2023-01-31 at 12 12 27" src="https://user-images.githubusercontent.com/47143694/215758340-83086ffb-b65c-49a0-8955-c6686aa6fbc0.png">

**Comment by pennyandrews** [comment]
https://github.com/vegaprotocol/frontend-monorepo/issues/2896

**Comment by pennyandrews** [comment]
@edd  to create the other tickets

**Comment by edd** [comment]
@gordsport is aware that we need some Ops time to help us improve this. That's the only status update so far.
