### ISSUE TITLE
FELT ACTION: Console v Reusable lib

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2796]
## The Chore

Some of the libs in frontend-monorepo are pretty console specific and are hard for other apps to consume as they contain a lot of UI. We are keen to move to having libs that are more headless, almost just being business logic and helper logic and some hooks and work out of the existing libs which make sense to just be console focussed (even just in console and not shared libs) and which should be proper reusable shared libraries. UI should be mostly in the UI Toolkit

## Agreed actions

- [x] @mattrussell36 and @dexturr to discuss options offline and come back to the group with a proposed approach to this
- [x] Once the leads are happy with the approach, share the proposal for input / feedback from the wider frontend teams
- [x] Finalise and write tickets for the work required
- [x] Prioritise and distribute the work in the relevant backlogs

## Additional details / background info

https://miro.com/app/board/uXjVPZYKrS0=/?moveToWidget=3458764542836013200&cot=14
<img width="1350" alt="Screenshot 2023-01-31 at 12 11 42" src="https://user-images.githubusercontent.com/47143694/215759074-aa063f5a-4fe5-4557-a684-96273b92ee09.png">

**Comment by pennyandrews** [comment]
Penny to put a session in the diary for Matt and Dex when he's back

**Comment by mattrussell36** [comment]
Here are all the actions discussed. Will update with applicable tickets

- Start splitting out apps. Starting with wallet-ui (which is already split) we want to plan to start splitting out other apps
- Review deps for each lib and fix any bad practices. For example libs should not contain references to router Link components, or logging services such as Sentry
- [Clean up ui-toolkit](https://github.com/vegaprotocol/vegawallet-ui/issues/142). Remove unnecessary deps, ensure its testable and ensure the css is bundle in a manageable way
- Define explicit rules for module boundaries, and create custom eslint rules to enforce it
- Review UI components within libs and determine what should be moved to ui-toolkit for better documentation and easier re-use
- Add a notion page outlining best practices for monorepo libs/apps

**Comment by pennyandrews** [comment]
@mattrussell36 to add ticket to document (in notion, and repo where appropriate) outlining best practices for monorepo libs/apps

Once this is done and the tickets are linked together this issue can be closed

**Comment by mattrussell36** [comment]
Here it is: https://github.com/vegaprotocol/frontend-monorepo/issues/3419
