### ISSUE TITLE
Candle/depth chart switcher

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#280]
<img width="1110" alt="Screenshot 2022-04-20 at 14 29 21" src="https://user-images.githubusercontent.com/13255539/164242150-5ed62a3c-20a7-4fa2-861f-98399fa879ca.png">

The current implementation uses buttons to toggle between the candle chart and the depth chart. (Red in image)

This is different to both the new toggle component (Blue) and the tabs (Green).

These should change to use one of the blue or green styles. I suggest the tab style (green) as in the I'd hope that depth and candles are two separate views that can be arranged differently in the workspace.

**Comment by PeteWilliams** [comment]
I've updated the design to include tabs for candle chart/depth chart:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=12%3A9520
