### ISSUE TITLE
Error handling: Wallet connection lost

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2811]
Could the Console have a more specific/helpful error message for the one below? The word token here is sufficiently confusing in the context of the trading dApp that it is not clear this is a wallet token. 

This probably occurs when you connect your wallet, then restart the wallet app. Wallet API tokens are persisted only in the wallet app's session, so you'd need to reconnect and refresh Console. This might only show up when Console needs to be refreshed in order to reconnect. 

![image](https://user-images.githubusercontent.com/62548908/216028649-4a02bf22-202e-43b5-a972-b3011ec89e66.png)

Raised by @rebeccajsimmonds

**Comment by barnabee** [comment]
Yeah I think a toast might not be the best way to communicate an error that requires “logging in” again. Perhaps deserves a modal?

**Comment by mattrussell36** [comment]
I think something like 'Wallet service session has ended. Please restart your wallet' would be more appropriate here

**Comment by candida-d** [comment]
This is being improved on the wallet API side now https://github.com/vegaprotocol/vega/pull/7488 though maybe there's still a question about whether this should have its own special Console message. 
@mattrussell36

**Comment by MadalinaRaicu** [comment]
There is a wallet ticket raised that would change the error message: https://github.com/vegaprotocol/vega/pull/7488
