### ISSUE TITLE
Filtering order list causes a timeout

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2814]
## Description

When selecting a filter in the Orders tab, a Timeout error can occur. 

## Expected behavior

Orders can be filtered, no timeout. 

## Screenshots

![image](https://user-images.githubusercontent.com/62548908/216042732-20b11258-1478-4e00-8574-fe4c195b04a1.png)

## Additional context

Raised by Lewis

**Comment by mattrussell36** [comment]
- Consider enlarging timeout for orders query
- Consider limiting orders query by date range, and using date filter
