### ISSUE TITLE
"Unknown error" when closing wallet app

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2817]
Once I close the wallet application all I get is this in Console when trying to place an order. (see image below) 

* Confirm this is actually an 'unknown error'. 
* Is it possible to provide any extra guidance here, like "refresh console" or ... something?

Raised by @witgaw 

![image](https://user-images.githubusercontent.com/62548908/216096863-7d9a16b0-e392-4ac7-91d1-a17c37117dcf.png)

**Comment by mattrussell36** [comment]
You now get this toast and also get disconnected

![Screenshot 2023-02-08 at 07 03 54](https://user-images.githubusercontent.com/6803987/217567641-eb48d58e-3a23-4061-8f32-e6758c742cb3.jpg)
