### ISSUE TITLE
Update withdrawals table after transfer complete

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2819]
## The Chore

Update withdrawals dialog available amount in the withdrawals dialog.

## Demo

https://user-images.githubusercontent.com/119658839/216100821-948ef652-6cb0-4f2e-a76a-eeedc108caa3.mov

![Screenshot 2023-02-01 at 15 13 02](https://user-images.githubusercontent.com/119658839/216100879-46d5ac2d-3c29-4a55-9ca4-32e2cd20da5b.png)

![Screenshot 2023-02-01 at 15 12 06](https://user-images.githubusercontent.com/119658839/216100915-90e06989-8cab-4cf8-8546-dbcb3120dbce.png)

**Comment by mattrussell36** [comment]
This appears to be working now. @MadalinaRaicu could you verify

**Comment by daro-maj** [comment]
After the withdrawal is made, we see the status pending in the table, while the notification shows that the transfer is completed.
![Screenshot 2023-02-16 at 15 00 03](https://user-images.githubusercontent.com/119658839/219387963-81a7e333-bb2b-4f13-bf88-097caed1fbfe.png)

**Comment by MadalinaRaicu** [comment]
I am unable to reproduce this issue. It seems to work fine. 
We are using two different data sources for these. 
@mattrussell36  and @daro-maj  could you please check this video? 

https://user-images.githubusercontent.com/16125548/220371678-97277d38-9823-4c14-b04f-8ad197c08a29.mov

**Comment by MadalinaRaicu** [comment]
@daro-maj  I think you need to click on Complete withdrawal

**Comment by MadalinaRaicu** [comment]
I would close this ticket as it seems to work for me?
