### ISSUE TITLE
Buttons under tables cover table rows

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2825]
## The Chore

Under some tables we have actions, for example the deposit button on the collateral table. The placement of this button causes some issues:

- It prevents scrolling if your mouse is parallel to the button but appearing to be over the data grid,
- Takes up valuable space for showing data rows
- Looks visually untidy when the text has half covered by the button container element

![Screenshot 2023-02-01 at 22 08 39](https://user-images.githubusercontent.com/6803987/216245401-ecb67433-f93d-4510-982a-44bbb94d057a.jpg)

## Tasks

- [ ] UX/Design
- [ ] Dev
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1675181603517869?thread_ts=1675181200.687929&cid=C037STCKMGC

**Comment by macqbat** [comment]
smth like this:
![image](https://user-images.githubusercontent.com/338931/221204094-d6b3ec3c-7a08-4a7d-b777-53354679b04c.png)
has been done already on order table (visible only when there are any open orders)

**Comment by neildawson** [comment]
@joellecharlotte collateral tab has transfer and deposit at once

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/1080322/222200680-43552194-5169-42cb-9c78-cee216010a46.png">

**Comment by pennyandrews** [comment]
@mattrussell36 @neildawson review and create tickets for any furtheriteration we want on this
