### ISSUE TITLE
Governance nav drawer doesn't have 'token' dropdown

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#2856]
Recently, the 'token' dropdown was added to the navbar. That change wasn't passed through to the nav drawer, and currently those nav items aren't available through it. 

- [ ] Make sure nav drawer has the same nav items accessible as the navbar

<img width="438" alt="Screenshot 2023-02-06 at 10 36 55" src="https://user-images.githubusercontent.com/2410498/216950116-c0125e32-3df4-4c4d-88bf-a2702e91e9b2.png">

**Comment by joellecharlotte** [comment]
[Linked to this Slack message](https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1676544523727049) that has two options attached - will update the ticket with the final solution once I get feedback from @sam-keen

**Comment by joellecharlotte** [comment]
Hi @sam-keen a

[Here is the Figma link](https://www.figma.com/file/DUHzxECUu0Pe1TyRI4wL4C/dApp-Navigation?node-id=2268%3A7988&t=j8mika4WC980FlS0-1) to the chosen approach, I went with the one that utilises the solid yellow background as the second option feels like a bit of a hybrid monster of old and new...

<img width="1790" alt="Screenshot 2023-02-22 at 17 02 30" src="https://user-images.githubusercontent.com/113684458/220703914-59caff78-3e8e-4919-a43b-73d2a366dda1.png">

**Comment by notbot00** [comment]
current implementation:

<img width="650" alt="Screenshot 2023-03-29 at 11 03 05" src="https://user-images.githubusercontent.com/105208209/228501821-df7d5f18-ff92-4836-ab32-62ab8f57fbc6.png">

still not sure if anything else needs to be done on this, as the Token menu item is now showing on the mobile drawer.
