### ISSUE TITLE
[Token]: Token drop down menu should not be opaque on tranches page 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2875]
The Token dropdown menu z-index needs to be higher than content in the 'main' component

![Screenshot 2023-02-08 at 10 42 30](https://user-images.githubusercontent.com/30622993/217510107-51b88119-ddd9-45f1-9973-9f20abbbfab4.png)

**Comment by neildawson** [comment]
The menu also goes behind some elements on [the validators page](https://token.fairground.wtf/validators)

![Image](https://user-images.githubusercontent.com/1080322/218729385-083649bc-5436-4284-b539-161dcd6cdcd6.png)
