### ISSUE TITLE
Add a 'common' project option in commitlint.config-ci.js

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#2895]
https://www.conventionalcommits.org/en/v1.0.0/ doesn't appear to give us a way to specify a list of apps affected by a change (i.e. (trading, governance) doesn't work). 

As a less desirable fallback, add a 'common' option in commitlint.config-ci.js so that we can specify a multi-app change.

**Comment by sam-keen** [comment]
Unnecessary ticket, syntax for multiple apps is a comma separated list, no spacing i.e. (trading,governance)

**Comment by pennyandrews** [comment]
@sam-keen told me to close this ticket (again) as it's not needed (again) 😆

**Comment by sam-keen** [comment]
tempted to open it one more time...
