### ISSUE TITLE
Max width for explorer content

### ISSUE THREAD

**Issue by asiaznik** [vegaprotocol/frontend-monorepo#2916]
**suggestion (non-blocking)**: This component should have a max width on it. 

There's no current standard - lots of other pages need it to, so this could be a follow up ticket. But something like `xl:max-w-3xl`.

<img width="1483" alt="Screenshot 2023-02-14 at 18 13 30" src="https://user-images.githubusercontent.com/6678/218823637-56d47a4e-0b8b-4619-8796-f3b13b26e999.png">

(Note: I'm not pretending to have a giant monitor, but I zoomed out to emphasies the problem)

_Originally posted by @edd in https://github.com/vegaprotocol/frontend-monorepo/pull/2914#discussion_r1106194560_

**Comment by asiaznik** [comment]
I think the best approach is to change the layout of the explorer a bit so it will have a max width.

**Comment by pennyandrews** [comment]
Hey @asiaznik @edd  there is a ticket already for this and some initial design work done for it, just a matter of prioritisation https://github.com/vegaprotocol/frontend-monorepo/issues/1787 so closing this as a duplicate
