### ISSUE TITLE
[Token]: When navigating to a new validator after unstaking, it appears you have unstaked the validator you have navigated not the validator you have just unstaked from

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2949]
This has been fixed on fairground and will be fixed on the next deployed release:

- https://github.com/vegaprotocol/frontend-monorepo/issues/2750

**Comment by gordsport** [comment]
Hey @candida-d 
This has been fixed with the governance site deployment yesterday - I plan to close by EOD unless you have any objections

( @pennyandrews )

**Comment by pennyandrews** [comment]
Agree this can be closed, but will let you do it when you are satisfied @gordsport
