### ISSUE TITLE
Improve market under proposal UI

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2958]
## The Chore

The notification component used for showing when a market is under proposal looks out of place

## Tasks

- [ ] Review feedback and determine if we can improve the messaging and contextual feedback about what kind of proposal it is
- [ ] UX/Design
- [ ] Change notification component to a market banner component
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1676514068669039

**Comment by mattrussell36** [comment]
Blocking this as it may be changing in current design work

**Comment by JonRay15** [comment]
Dupe of #4387
