### ISSUE TITLE
My rewards design review

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2984]
The rewards work got merged without a design review so we want to go through the latest version of this and make sure we catch and tidy up anything that doesn't adhere to the design 
 
- Design review, switcher is larger than is on the current design (ui toolkit component so will need to consider impacts)
- Should the asset be name or symbol? It's inconsistent between the two views so we need to look into that and decide
- The percentages disagree with the tool tips currently

Sam and Joëlle to go through this together

**Comment by pennyandrews** [comment]
Hey Michael, the tickets you raise will be considered and prioritised separately from this ticket as it's just making sure that the design that has already been done has been implemented properly
