### ISSUE TITLE
Paginate proposals list

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2990]
## User Story

As a Governance dapp user
I want to see a paginated list of all proposals
So that I can browse proposal information without the page taking forever to load / falling over due to the volume of data

Note the following issues should be considered here:
- #5452 
- #5468 

## Acceptance Criteria

- I can view the most recent n proposals and use a common pagination UI pattern (that is consist with other paginated lists in the dapp i.e. rewards) to click to view the next n proposals, and the next
- I understand what number page of data I am currently viewing
- I understand when there are more proposals to view, and when there isn't 
- There is a way to find a specific proposal I'm interested in without having to browse page by page to find it
- I can filter by proposal type
- I can filter by proposal status (Accepted / Rejected / Ongoing)

## Tasks
- [ ] Implement (utilising existing libraries/common components if at all possible i.e. rewards pagination recently implemented)
- [ ] QA Test (including adherence to design, verify a/c are met and no bugs/defects/regressions have been introduced) 
- [ ] Release

**Comment by notbot00** [comment]
depends on: https://github.com/vegaprotocol/frontend-monorepo/issues/794
(ui component for the pagination is in there)

**Comment by jtsang586** [comment]
Pagination for proposals list was never implemented as there were some issues with rewards pagination which was supposed to use the same UI components. Moving this back to backlog
