### ISSUE TITLE
Market List Mega Dropdown

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#30]
- Dropdown containing the market table

**Comment by PeteWilliams** [comment]
Current design:

https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1064%3A11521

![image](https://user-images.githubusercontent.com/1325606/174778194-d08e61f5-3dd6-4cf9-b091-096438749aa5.png)

**Comment by MadalinaRaicu** [comment]
Note: we don't have yet a way to save preferences so I can't add the 'My markets' section yet

**Comment by PeteWilliams** [comment]
> Note: we don't have yet a way to save preferences so I can't add the 'My markets' section yet

@MadalinaRaicu The intention was that this would be any markets you have an open position on, rather than saving a list of favourites. Hopefully that's possible?

**Comment by MadalinaRaicu** [comment]
> > Note: we don't have yet a way to save preferences so I can't add the 'My markets' section yet
> 
> @MadalinaRaicu The intention was that this would be any markets you have an open position on (or perhaps have _ever_ had a position on, but I'm presuming that's more complicated), rather than saving a list of favourites. Hopefully that's possible?

noted. looking into it
