### ISSUE TITLE
If a TX is missing when a user arrives on a TX details page, try again for a few seconds

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3004]
## The Chore

If a user opens up a transaction very quickly after submitting it, the block explorer may not be able to render it yet. This is because the TX may still be in the mempool, not in a block, and we have no API access to pending TXs. The workaround: display a 'softer' error message, and try checking again a few seconds later. This will cover *most* situations, but not (for example) rejected TXs or very delayed TXs

If the poll fails, add a 'Retry' button to manually try again

**Comment by asiaznik** [comment]
PR: https://github.com/vegaprotocol/frontend-monorepo/pull/3195
