### ISSUE TITLE
Association link should take you to the root of the associate flow (during/after an association)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3013]
## Description

Users wanted to jump back to the beginning of the associate flow (e.g. to associate from Vesting after having done Wallet).

This button doesn't take you to the association (with a blank form) like users want it to, if you are already on the associate page. I guess because the URL is the same as the page I am on.

<img width="1404" alt="Screenshot 2023-02-27 at 13 56 25" src="https://user-images.githubusercontent.com/13255539/221583274-ae5a21b6-825a-4621-8898-a508daed3637.png">

## Steps to Reproduce

1. associate
2. optional: change eth wallet (to another key with Vega you want to associate) 
3. hit associate
4. nothing happens

https://user-images.githubusercontent.com/47143694/226574331-8dea86a4-1248-4757-9ed8-69b8081f66b8.mov

The same thing happens if you attempt to get to the beginning of the process from any nav, e.g. the header.
I expect it is true of disassociate too.

## Expected behavior

I am taken back to the beginning of the form - or there is a way for me to get there

back to the form: 
<img width="1403" alt="Screenshot 2023-02-27 at 13 59 54" src="https://user-images.githubusercontent.com/13255539/221583338-3e31657a-52d2-4bca-a0f5-d69420959934.png">

on Testnet

## Notes

We could do this with a modal or a hashbang URL

**Comment by notbot00** [comment]
@campbellssource i've just tried this out, but i wasn't able to reproduce it, i get the expected flow:

<img width="775" alt="Screenshot 2023-03-20 at 12 46 16" src="https://user-images.githubusercontent.com/105208209/226342755-55ef22e8-2ad1-46c0-be6d-b15f6abfc0b4.png">

can you confirm which version was this on / whether it's still an issue somewhere?

**Comment by sam-keen** [comment]
@pennyandrews I've spent some time researching this issue. Any change would require a fairly significant refactor and I'm wondering whether the issue justifies the cost. Potential fixes include:

- Refactoring current flows to display the associate/dissociate form whilst a tx is in progress (requires reworking shared components that deal with other transactions too, such as tranche redemption. This might have unintended side effects for those flows).
- Replacing the current tx status display with a modal, allowing the form to be visible underneath.
- Importing the Console way of doing things with toasts (potentially the quickest, but also the largest unknown).

None of the options are non-trivial, and require that we rework how we get associated/non-associated data from the wallet.
