### ISSUE TITLE
Improved error messaging for faucets disabled during incentive / SIMS

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3017]
## The Chore

When we have chosen to restrict the volume of test assets in circulation during an incentive / SIMS on fairground, we currently display this "error" message to users trying to faucet the asset. 

<img width="700" alt="Screenshot 2023-02-27 at 16 37 50" src="https://user-images.githubusercontent.com/46783148/221638518-3920a939-f010-47a7-85c1-d2b4c3598ed3.png">

This chore is to update the language to explain why faucet is not available and sign post what someone can do to take part (so they are not put off / given a dead end) e.g. where to go to take part in the incentive (and get the test asset to deposit) or to another market which is not part of the incentive.

## Tasks

- [ ] Identify when this occurs 
- [ ] Come up with appropriate language / solution 
- [ ] Implement 
- [ ] Test

**Comment by pennyandrews** [comment]
Think this has been fixed by one of Matt's recent PRs - check this

**Comment by mattrussell36** [comment]
Can confirm this has already been fixed as part of a different PR

Changes were made to show a more friendly error message inline in the form

![Image](https://user-images.githubusercontent.com/6803987/226767445-c7195079-f22a-4d99-b3c1-0bed2acb9a6b.jpg)
