### ISSUE TITLE
Orderbook improvements

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#303]
- [x] make orderbook header sticky
- [x] ask and bid relative volume bars should be both relative to maximum bid or ask volume
- [x] align cumulative bid and ask pars to left
- [x] if there is both big and ask cumulative volume at same price level make bars 50% in height and display ask bar above bid bar
- [x] replace zoom in zoom out buttons with dropdown
- [x] lower decimal places together with increasing price level group range (if decimal places is 4 and we round after dividing by 100 decimal places should be 2)
- [x] mark mid price (horizontal borders in contrast colors)
- [x] show number in cumulative volume column
- [ ] show indicative uncrossing volume instead of volume if market is in auction mode
- [x] fill gaps in data with zero valued volumes
- [ ] replace native scroll bar with mini scroll bar which will not cover any part of data

**Comment by campbellssource** [comment]
another thought if we know the market is in continuous trading I'd like to style the zeros on the other side of the book to make it really clear where the mid/best prices are. 
<img width="465" alt="Screenshot 2022-04-28 at 11 42 04" src="https://user-images.githubusercontent.com/13255539/165735748-4e2a72f7-a5e9-4ddc-aa4d-4a8d31bd17f8.png">

Tempted to say that we don't show the 0 in these cases (just a blank space). But only on side where there theoretically where there should not be any orders.
this additional rule required now that we show all prices, not just ones where there are orders.
so you'd still see a zero for the 2n'd best bid price, but there wouldn't be any 0's in the bid column above the best bid.
