### ISSUE TITLE
Governance site moving between pages keeps you in the same scroll position

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3032]
## Description

Normally when I go to website.com/A and then scroll down a bit, then click a link to website.com/b in a web browser I'll end up at the top of page b.

But on the governance site this is not the case :( 

I think this is caused by the magic that means the page loads without a redirect (even though the URL changes).

## Steps to Reproduce

https://user-images.githubusercontent.com/47143694/226573598-974fc7e2-48f3-4eaf-b42d-95f887210ee6.mov

## Expected behaviour

The same as a normal page load. I'm at the top of the new page (unless there is an anchor link e.g. website.com/b#something

**Comment by notbot00** [comment]
@campbellssource can't seem to reproduce this either, whenever i navigate somewhere, the page bounces back to the very top 🤔 can you confirm you get the same result? if not, can you let me know what browser / setup you're using?
