### ISSUE TITLE
Using token app / rewards - something went wrong

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/frontend-monorepo#3036]
Connected an eth wallet and vega wallet
clicked rewards

<img width="415" alt="image" src="https://user-images.githubusercontent.com/86229849/221947104-962e36a9-c64c-45ed-9734-5da01d4e51f3.png">

**Comment by sam-keen** [comment]
Hi @vega-paul, could you provide some extra details please:

What network were you pointing at?
What version of the wallet were you using?

Thanks
