### ISSUE TITLE
Proposal page: Your vote does not update after changing your vote

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3083]
We think this has been fixed - @jtsang586 to verify

## Description

Changing your vote does not update the "your Vote" status until page refresh.

## Steps to Reproduce

- Vote on a proposal
- go away
- come back
- click change vote
- vote the other way

## Expected behavior

The your vote changes to your latest vote instantly

## Screenshots

https://user-images.githubusercontent.com/13255539/222748758-43ba3b56-7e49-4ad1-96ad-1e436a74f011.mov

**Comment by jtsang586** [comment]
Retested and issue seems to now be fixed. Closing ticket
