### ISSUE TITLE
Switching Vega keys does not update the page or wallet side bar until page reload.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3085]
## Description

When I use the switch key feature I expect the side bar and all other content to update to my newly selected key, however, it does not.

I can reproduce this only when switching from a key that has a large number of assets, associated tokens to etc to one that doesn't. see the video, in the first section it doesn't switch then I reload and it does. then I can switch from my second key to the first without issue

https://user-images.githubusercontent.com/13255539/222774676-c1cce271-8acc-4616-9e3b-97b3de6f010e.mov

If I refresh the app, then it does register the new key I had selected.

**Comment by campbellssource** [comment]
Note I am also getting...
> no resource corresponding to this id

When I nav to a validator page from one of my empty keys. mentioning incase it is related

**Comment by notbot00** [comment]
could be related to https://github.com/vegaprotocol/frontend-monorepo/issues/3344, as @campbellssource pointed out, will need to investigate if handing 404s would solve this issue.

**Comment by sam-keen** [comment]
I'm not currently able to replicate this. Have asked Michael to try to replicate.

**Comment by dexturr** [comment]
Could this be due to the other pubkeys not existing on the Vega chain and having no data?
