### ISSUE TITLE
Quick fixes to existing voting status UI

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3097]
## Chore

Quick fixes to existing voting status UI if we don't go ahead with #3601 

## Sketch
<img width="809" alt="Screenshot 2023-03-06 at 13 40 00" src="https://user-images.githubusercontent.com/13255539/223126185-c3ae8606-6850-4404-a883-ba01c268818f.png">

## Tasks
- if 0.0000000001% show "less than 0.01%"
- Show unit on all absolute values
- fix some of the spacing
- show what the % are of i.e. "12% of all VEGA tokens have voted" instead of "12%"

**Comment by campbellssource** [comment]
See also https://github.com/vegaprotocol/frontend-monorepo/issues/801

**Comment by pennyandrews** [comment]
Superseeded by many other tickets now
