### ISSUE TITLE
Participants didn't look at the details on the validator page struggled to find the place to add stake

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3104]
## Description

This is a usability bug.

User testing participants felt like they had enough info from the validators list to choose a validator, so once they got to the validator page it felt like it was too hard to find the area to add stake.

<img width="592" alt="Screenshot 2023-03-07 at 08 18 02" src="https://user-images.githubusercontent.com/13255539/223364028-f3d6abeb-6da9-4c41-aefa-3568d7acdcfa.png">

- [ ] consider other layouts or design changes that make managing stake easier
- [ ] choose what to implement

**Comment by pennyandrews** [comment]
No longer applicable as this is now right at the top

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/4794154d-666e-4e7f-a75c-7c9ce30b479d)
