### ISSUE TITLE
Trades liquidating at different price to that shown on Console

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3108]
Users have reported trades being liquidated at prices that do not match exactly the value shown on the deal ticket estimate and on the positions tab in Console.

The reason for this is that liquidation level on Vega is not simple and static as users may be used to on other platforms.  On Vega the liquidation level is determined by the following factors:

1. The entry price 
2. The current market price
3. Their current margin level, taking into account all positions across all markets
4. The risk factors set on the market parameters 
5. The current slippage on the order book 

Since some of these can change, the liquidation price after a position is entered will not remain static on the price originally shown on the deal ticket estimate.  Furthermore, the estimate on the positions tab is also currently not 100% accurate since in reality liquidation may occur anywhere in a given range based on changes to the above factors. 

We are working on changes to be able to more accurately show that range of prices in which the position may be liquidated which should make this aspect of the exchange more transparent.

**Comment by pennyandrews** [comment]
Duplicate, covered in another tiicket
