### ISSUE TITLE
Orderbook to show trades at price in the last XXX (default to 24 hours)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#314]
Blocked by: https://github.com/vegaprotocol/vega/issues/5702

In this image the column on the right shows a sum of the trades that have happened in the last 24 hours (this can be changed via the drop down).
<img width="813" alt="Screenshot 2022-04-27 at 13 40 19" src="https://user-images.githubusercontent.com/13255539/165520003-2ad9f79c-830e-4241-9ca6-c26c3317bf35.png">

This allows the user to see where recent trading activity has happened as apposed to where the passive orders are.

- Scale 100% is the max value for any of the price level
- Aggregation of trades works in with the controls under the price column for the rest of the component
- Tell the user what this is showing (e.g. tooltip)

**Comment by gordsport** [comment]
@gordsport - requires data-node API implementation
