### ISSUE TITLE
The explorer uses the term Party but perhaps public key is better?

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3140]
## Description

A user was confused in of the term Party and Parties in the explorer, to be fair a term used on trading platforms but perhaps not explorers where address or public key is mostly used.
We are using the term public key as well under the menu for parties.

## Steps to Reproduce

1. Go to (https://explorer.fairground.wtf/parties)

## Screenshots

<img width="619" alt="Screenshot 2023-03-09 at 12 58 36" src="https://user-images.githubusercontent.com/100769129/224016690-d166f5ab-bfef-4630-9924-62921821f81e.png">
<img width="503" alt="Screenshot 2023-03-09 at 12 33 55" src="https://user-images.githubusercontent.com/100769129/224016693-b4071f1c-a171-4ca2-8e7f-d24c5ad8d4a8.png">

**Comment by pennyandrews** [comment]
@neildawson one for your 'aligning how we refer to concepts across our apps / touchpoints' project

**Comment by mattrussell36** [comment]
Lets align everything in explorer to use 'pubkey'
