### ISSUE TITLE
Evaluate the API for downloading CSV for ledger entries

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3146]
Ahead of implementing the download CSV features in the UI for ledger entries in this ticket https://github.com/vegaprotocol/frontend-monorepo/issues/2320 we would like to evaluate the API to ensure that it works and gives us what we need to be able to implement the feature. 

Once we are sure we can then prioritise the frontend tickets to implement

- [ ] Write ticket(s) in the vega repo for the core work we need to be able to use this api endpoint to achieve the story #2320

**Comment by macqbat** [comment]
Seems to we are blocked on this issue now https://github.com/vegaprotocol/vega/issues/8203

**Comment by pennyandrews** [comment]
@Maciek Gordon confirmed this morning that the core ticket to unblock our CSV export of Ledger Entries is complete and deployed to Stag3 last night so we should be able to get this work over the line now https://vegaprotocol.slack.com/archives/C02MV2GQ20Y/p1682388664264399
