### ISSUE TITLE
Rewards: instead of `0` show something else to indicate a `0.0001` reward

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3163]
## The Chore

The rewards page shows either `-` for no reward, or a number if there was one. it only ever shows 0decimal places.

So if the reward was `0.01 BTC` they might mistakenly think they got no reward.

<img width="1037" alt="Screenshot 2023-03-13 at 11 09 16" src="https://user-images.githubusercontent.com/13255539/224684968-6aed79fd-3635-4aa0-a5c5-d2b9f948e217.png">

<img width="805" alt="Screenshot 2023-03-13 at 11 02 46" src="https://user-images.githubusercontent.com/13255539/224683581-7435eb8c-a86a-4054-bfbb-cfe0bf8f18c7.png">

This ticket to choose and implement an alternate design.

## Options (see comments for more)

- show `<0` or "more than zero" 
- show `>1` or "less than 1"
- Consider using the `Quantum` to render a useful number e.g. https://github.com/vegaprotocol/specs/pull/1512

## Tasks

- [ ] decide on an option
- [ ] do it

## Additional details / background info

https://github.com/vegaprotocol/frontend-monorepo/issues/2473
https://github.com/vegaprotocol/frontend-monorepo/issues/2132

**Comment by pennyandrews** [comment]
Fixed
