### ISSUE TITLE
Pull contract addresses from core

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/frontend-monorepo#318]
go to https://n03.stagnet2.vega.xyz/playground

query{networkParameters{key value}}

 {
        "key": "blockchains.ethereumConfig",
        "value": "{\"network_id\": \"3\", \"chain_id\": \"3\", \"collateral_bridge_contract\": { \"address\": \"0xffC1eb64e22fd5E29816c633eE84088EEEe879E5\" }, \"staking_bridge_contract\": { \"address\": \"0x7896C9491962D5839783CB6e0492ECebd34Bb35F\", \"deployment_block_height\": 11177313 }, \"token_vesting_contract\": { \"address\": \"0x9F10cBeEf03A564Fb914c2010c0Cd55E9BB11406\", \"deployment_block_height\": 11177353 }, \"confirmations\": 3}"
      },

replaces the hardcoded values with the ones from gprahQL query

**Comment by gordsport** [comment]
decommission the contracts we don't need anymore (claim codes / others?)

web3 wrapper does this
