### ISSUE TITLE
Make UI toolkit nav bar scale for bigger screens (not fixed width)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3199]
## The Chore

Right now, our nav bar is constrained to a fix width - whereas usually you would expect the background colour (at least) of the navigation to be _full_ width. Navigation components may be centre aligned. 

<img width="2557" alt="Screenshot 2023-03-15 at 09 41 25" src="https://user-images.githubusercontent.com/46783148/225270123-218d8e35-1228-41b0-9786-170fe9094015.png">
<img width="2559" alt="Screenshot 2023-03-15 at 09 41 09" src="https://user-images.githubusercontent.com/46783148/225270164-d313177d-6bef-4987-b863-59ab736e06dc.png">
<img width="2558" alt="Screenshot 2023-03-15 at 09 45 17" src="https://user-images.githubusercontent.com/46783148/225271146-fffd6e22-1dcd-4f64-95ca-10f1d2970190.png">

## Tasks

- [ ] Design (this may already be done, but may want to decide whether the Vega icon is top left or top left of the content area type thing) 
- [ ] Decide if we do the same for banners
- [ ] Implementation
- [ ] Testing
- [ ] Etc.

**Comment by joellecharlotte** [comment]
Adding some detail around the behaviour of banners against the top nav. Propose that the banner also spans the full width of the viewport and will either have centre-aligned content eg. Mainnet Sims or left-aligned if it's a utility-type message eg. Network Upgrade Notification.

![Nav + Banner Alignment Documentation](https://user-images.githubusercontent.com/113684458/230361803-9bb25b12-dce7-473a-9d6d-c4f3a1db3dc9.jpg)
