### ISSUE TITLE
Trading home page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#323]
Lets remove the dummy content on the home page and instead make a simple application road map. It would be great if this could be easily editable perhaps via mdx.

**Comment by MadalinaRaicu** [comment]
what about this [one](https://github.com/vegaprotocol/frontend-monorepo/issues/305)? 
I am working on it and it still needs more [review](https://github.com/vegaprotocol/frontend-monorepo/pull/424). 

Here's a screenshot from what I have locally:

<img width="722" alt="Screenshot 2022-05-17 at 22 51 17" src="https://user-images.githubusercontent.com/16125548/169007194-ad8a60e8-3e2f-4179-9639-a50e486f198b.png">

**Comment by campbellssource** [comment]
This can probably be closed as dup of #305
