### ISSUE TITLE
Update close position to use reduce only order

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3240]
## The Chore

Change close position batchMarketInstruction to use a reduce only order so that new positions are not unintentionally re-opened due to market movements

## Tasks

- [ ] Dev
- [ ] Test

**Comment by macqbat** [comment]
Currently  adding boolean flag `reduceOnly` into method's payload causes wallet api error. Seems to it needs to be handled firstly on wallet api side - passing of this param to the core api.
