### ISSUE TITLE
Add generic announcement banner

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/frontend-monorepo#3244]
Create a generic component to connect to the [announcements repo](https://github.com/vegaprotocol/announcements) and pulls in the correct announcement from the static data there, so that the apps can display a banner.

**Comment by pennyandrews** [comment]
Hey @notbot00, might be a stretch, but I was wondering whether this component could be consumed by the website as well so it's a one time update and it reflects everywhere type scenario??

**Comment by notbot00** [comment]
i would need to publish this library so that the website (and potentially the wallet - even tho we don't do that in there) can use it, it's absolutely doable.

**Comment by pennyandrews** [comment]
Cool @notbot00, obvs don't worry about it as part of this ticket but I might create a separate ticket for another time to do this if it looks like we are going to use these banners lots more

**Comment by notbot00** [comment]
@pennyandrews turned out publishing from the monorepo is extremely easy, just added an extra line in my PR. also added a website namespace for the announcements repo config, so someone can just wire it in to the website with basically close-to-zero effort.

**Comment by joellecharlotte** [comment]
For reference [here are the Notification Banners in the Design System](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dAPP-Components?node-id=1162%3A9279&t=Sji9ZdCzMC6DbXKj-1) which include the existing Announcement Banner and the new Utility (Generic?) Banner.
