### ISSUE TITLE
Display relevant message when network is down

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/frontend-monorepo#3283]
Instead of showing "No data", display something meaningful when the network is not reachable.

## Acceptance Criteria

- [ ] If no nodes in the datanode switcher are reachable then display message "No available data nodes detected, potential network outage" (This is common component

![Image](https://user-images.githubusercontent.com/105208209/227960671-dda9cb56-3c61-4575-b11c-e6f7a22ac889.png)

**Comment by pennyandrews** [comment]
Need to handle the scenario where it's just one / some nodes that are down rather than the whole network - could just replicate the same as Console to keep it consistent and as easy as possible

**Comment by ckpringle** [comment]
![Image](https://user-images.githubusercontent.com/46783148/235902839-29fd247e-5d15-4c8f-b241-1767d57f53f5.png)
