### ISSUE TITLE
Review monorepo lib deps

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3298]
Depends on https://github.com/vegaprotocol/vegawallet-ui/issues/142

## The Chore

A lot of our libs are dependent on things they shouldn't be. For example

- Router implementation
- Logging (Sentry) services

There are likely more issues than are listed above. This ticket is to review each lib and make fixes where possible.

## Tasks

- [ ] Review libs
- [ ] Define scope of code changes
- [ ] Make fixes

**Comment by JonRay15** [comment]
@edd can we decide if we are ever actually going to do this and if not get rid of it ..... it irks me.
