### ISSUE TITLE
Orderbook: always show the same number of decimal places in order book

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3305]
<img width="342" alt="Screenshot 2023-03-29 at 11 47 21" src="https://user-images.githubusercontent.com/13255539/228512498-b67638f7-2ccc-4c90-ad92-b18d58966e2f.png">

Note how most of the prices and volumes are shown to the same number of decimal places except where there are trailing zeros.
e.g. 
`0.350` is shown as
`0.35`

In the order book this is not desired. it would be better to always show the same number of decimals for each row.
This could be set by the number of DP on the [quote](https://github.com/vegaprotocol/frontend-monorepo/issues/2132) and [position](https://github.com/vegaprotocol/specs/blob/master/user-interface/9001-DATA-data_display.md#size).

This makes all the numbers align and easier to read.

It would also make sense to trim trailing zeros on the price column when this is used.

<img width="443" alt="Screenshot 2023-03-29 at 12 04 14" src="https://user-images.githubusercontent.com/13255539/228514382-758a0b1b-1789-41cc-927b-603e02853860.png">

## The Chore & tasks

- [x] Ensure that we do not hide trailing zeros when showing volume and price
- [x] unless the user has grouped/aggregated the order book, then we can trim trailing zeros from the price column

## Additional details / background info

I know that [this ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/2132) exists but I felt this might be small and actionable enough to squeeze into an upcoming sprint.

You can see this is a standard pattern on other platforms. e.g. kraken pro:

<img width="425" alt="Screenshot 2023-03-29 at 12 10 23" src="https://user-images.githubusercontent.com/13255539/228516061-a4f83259-595b-4ccd-be52-ad26bad0586c.png">

**Comment by MadalinaRaicu** [comment]
For whoever picks this up please use `addDecimalsFixedFormatNumber` instead of `addDecimalsFormatNumber` from the utils  lib
