### ISSUE TITLE
Unable to submit proposals with maximum deadline enactment

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#3323]
## Description

This seems to be a recurrence of a previous bug:  https://github.com/vegaprotocol/frontend-monorepo/issues/1837

Error message seen when trying to submit proposal using maximum deadlines

![Screenshot 2023-03-30 at 11 55 35](https://user-images.githubusercontent.com/30622993/228856847-7691c96a-ddb9-49d1-a6a8-f4bee68f3929.png)

**Comment by pennyandrews** [comment]
Joe to retest and let us know if still valid issue

**Comment by jtsang586** [comment]
Unable to reproduce anymore - closing
