### ISSUE TITLE
Unable to scroll right or left in the chart when zoomed in (Console)

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3329]
## Description

When using the console chart, if you are zoomed out and see the whole timeline you can drag and scroll the chart, but if you are zoomed in, you cannot.

## Steps to Reproduce

1. Go to https://console.fairground.wtf/#/markets/1e428b5f136b70eacf2fceaa1591ac192f2c6c6099449e2d1ea486d547a65be2
2. Click on the chart with it fully zoomed out
3. Scroll down to drag to scroll the timeline, it works
4. Zoom in and do the same thing, does not work

## Screenshots

https://user-images.githubusercontent.com/100769129/229059666-ddb1f52b-4ebd-4800-babe-105bd8c916cf.mov

## Device details

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Mac
- OS: MacOS
- Browser Chrome & Firefox

**Comment by mattrussell36** [comment]
@daunatv this has been fixed
