### ISSUE TITLE
numberDecimalPlaces is not included in Explorer Settlement oracle specification or Proposal governance page

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3333]
## Description

Within a market proposals `dataSourceSpecForSettlementData` there is a key filter that specifies the number of decimals to send for settlement

```
 "key": {
"name": "prices.BTC.value",
 "type": "TYPE_INTEGER",
"numberDecimalPlaces": "5"
```
This is important since it is needed in order to know how to send the settlement price in terms of decimals. 
There seem to be no way to find it in proposal, console or explorer.

## Steps to Reproduce

1. Go to ['...'](https://validator-testnet.governance.vega.xyz/proposals/9ea36df2b16fc396c34c79843e9f47b21ebede726657d57bb59dffbcd4e2076b) or https://validator-testnet.explorer.vega.xyz/oracles/e385156c00669eca7a567bf0a038e6d035551569aaaa8dce58ef53f53a478a01
2. search for numberDecimalPlaces

## Expected behavior

numberDecimalPlaces should be available.

## Screenshots

<img width="861" alt="Screenshot 2023-03-31 at 13 43 44" src="https://user-images.githubusercontent.com/100769129/229111554-b904eb3d-01d6-4ab0-87a1-6a6e193b8de0.png">
<img width="861" alt="Screenshot 2023-03-31 at 13 43 12" src="https://user-images.githubusercontent.com/100769129/229111565-54a25155-ef6d-4881-b0d0-092de501ac27.png">

**Comment by jtsang586** [comment]
Blocked by core for testing 
https://github.com/vegaprotocol/vega/issues/9206
