### ISSUE TITLE
Deposits are not arriving on Fairground testnet

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3336]
## Description

When depositing an asset, they do not arrive in your wallet on fairground after the required ETH blocks has passed.

Proof of deposit into `69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f`
https://sepolia.etherscan.io/tx/0xc80f6cafad549836c94732864fae6dbb92ca8fd517972da7847bafcf8910942e

Proof of assets DAI-C not arriving
https://explorer.fairground.wtf/parties/69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f

## Steps to Reproduce

1. Go to consol https://console.fairground.wtf/#/portfolio
2. Deposit an asset
3. Wait until it should have been completed
4. No asset in wallet

## Screenshots

https://user-images.githubusercontent.com/100769129/229132291-a1308b76-b72c-453a-952d-55a0d9be7537.mov

## Device details

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Mac
- OS: MacOS
- Browser Chrome
- Version v0.70.0

**Comment by mattrussell36** [comment]
Closing as this was a core bug that is now resolved
