### ISSUE TITLE
Chart has a dotted line for price which is not the current price - Fairground v0.70.0

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3339]
## Description

Not sure what price is indicated on the dotted line on the chart, it is not current price so is it average? 
Does not seem to change unless you switch TF, so looks to be average price which is a bit strange.

## Steps to Reproduce

1. Go to[ '...'](https://console.fairground.wtf/#/markets/1e428b5f136b70eacf2fceaa1591ac192f2c6c6099449e2d1ea486d547a65be2)
2. See the dotted line and change TF and see how it changes

## Expected behaviour

Should it not be the current price or what is it meant to indicate?

## Screenshots

<img width="1381" alt="Screenshot 2023-03-31 at 17 41 02" src="https://user-images.githubusercontent.com/100769129/229167367-a5635e0e-ec2d-4473-ab7d-597111b738c1.png">
<img width="1381" alt="Screenshot 2023-03-31 at 17 40 53" src="https://user-images.githubusercontent.com/100769129/229167406-3152d285-e395-411f-8a11-873d9f835869.png">
<img width="1381" alt="Screenshot 2023-03-31 at 17 40 31" src="https://user-images.githubusercontent.com/100769129/229167433-9e2bc53f-bacc-4dad-ac07-0cd89f38697c.png">

**Comment by mattrussell36** [comment]
@daunatv the dotted line is the close price of the latest candle. I think it looked broken before due to a combination of the chart panning bug and/or a network upgrade causing a gap in the chart. Going to close, but please verify and re-open if necessary
