### ISSUE TITLE
Enhance governance proposal toasts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3365]
Just had a toast pop up on Console telling me about a spam pow proposal.

Which was very nice, and I enjoyed it, but it did then drop off a few seconds later, and Barney loaded console and he doesnt see it.  What is the logic for when they come up?  It feels like it just came up at the exact moment the proposal was made (13:40) and then dropped off.

I think firstly the timer on it disappearing was a bit brief.  I didnt manage to dismiss it before it automatically dropped off, suggest this should be raised.

Then the more complex bit is I think ideally Console would show you any proposals that have occurred since you were last here.  You shouldnt need to be actively using Console at the time of proposal to get notified.

Alternatively I guess you could just always bring up toasts for any active proposals on each load and let the user dismiss them, although depending on how many proposals we see that might get painful.

Depends a bit on how many proposals we think will ever be open at one time.  Network params probably not many, but I guess once we're live there might be a number of market proposals open ALL THE TIME ... at least if we're vaguely successful. 

Maybe grouped notifications is an option.  Probably needs a bit of thought and design.

**Comment by pennyandrews** [comment]
Deleting this as the toast time on screen issue has already been resolved, and the rest is incorporated in this notification history ticket https://github.com/vegaprotocol/frontend-monorepo/issues/3315
