### ISSUE TITLE
Detail what derivatives are

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#338]
## Task
As a user I would like a primer on what derivatives are, what vega does, what the benefits are and why I should make a trade (i.e. to speculate) - Link to https://vega.xyz/key-concepts 

## ACs
-

**Comment by gordsport** [comment]
Closing as nice to have - may be reopened later

Design needed

**Comment by pennyandrews** [comment]
Closing this as Console-lite is on hold indefinitely
