### ISSUE TITLE
Screen flickering when clicking on next rewards page

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#3449]
We'll take a quick look and if there is a very quick fix we will do it, otherwise will kick to icebox

## Description

As seen from the attached video when clicking to go the next page for rewards the screen sometimes flickers due to the loading text appearing and disappearing quickly. 
The transition could be smoothed out perhaps removing the loading text.

Related to: https://github.com/vegaprotocol/frontend-monorepo/issues/794

https://user-images.githubusercontent.com/30622993/232447696-1be35571-8ab7-46e0-9338-73133477d97e.mov

**Comment by pennyandrews** [comment]
This is due to volume of data so we don't believe we can fix without more thorough pagination functionality from core
