### ISSUE TITLE
Validator readiness

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3482]
## The Chore

We identified data available for this spike https://github.com/vegaprotocol/frontend-monorepo/issues/2991 but need to now decide how we want to use / display it. 

Where do we display which validators have voted for the upgrade proposal?

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by pennyandrews** [comment]
Agreed with Jon Ray that we have enough now in the network upgrade proposal details page about validator votes that we no longer need this
