### ISSUE TITLE
Acceptance criteria for `1005-VEST` View and redeem vested tokens

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3494]
There are A/Cs drafted here but not yet approved 
https://github.com/vegaprotocol/specs/blob/user-interface-placeholders-for-all/user-interface/1005-VEST-vesting.md

**Comment by jtsang586** [comment]
Closing this ticket as all the possible ACs are included. The remaining ones for redeeming vested tokens will still be missing as the amount of work required to set this up in capsule outweighs the benefits
