### ISSUE TITLE
Look into using magic strings for features / step defs in tests

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/frontend-monorepo#350]
Can we use a magic string then?
.feature
```
| Field         | Value    |
| To (Vega key) | current |
```

.page.js

```
if (key === 'current') key = cy.getEnv('VegaKey')
```

Not sure of the exact syntax but I would like anyone to be able to run these tests without needing a specific wallet, which will make capsule integration easier

_Originally posted by @dexturr in https://github.com/vegaprotocol/frontend-monorepo/pull/309#discussion_r859631395_

**Comment by dexturr** [comment]
@jtsang586 has already done this in another PR
