### ISSUE TITLE
Error is visible in console about failed to estimate fee 

### ISSUE THREAD

**Issue by daro-maj** [vegaprotocol/frontend-monorepo#3531]
Fixed by #3216 

## Steps to Reproduce

1. Go to Trading page
2. Click on market
3. Change size
4. See error in console / network

## Expected behavior
No error visible 

`{errors: [{message: "failed to estimate fee", path: ["estimateOrder"],…}], data: null}
data
: 
null
errors
: 
[{message: "failed to estimate fee", path: ["estimateOrder"],…}]
0
: 
{message: "failed to estimate fee", path: ["estimateOrder"],…}`

## Screenshots
![Screenshot 2023-04-25 at 09 41 45](https://user-images.githubusercontent.com/119658839/234223511-0660f809-481f-49de-884d-39c30ca8c6c7.png)

**Comment by asiaznik** [comment]
👋  I can't replicate the issue. Can you check again, please?
