### ISSUE TITLE
Improve risk dialog warning

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#3564]
## The Chore

Make risk dialog warning on fairground env more appropriate than is now, as it talks about risk of funds which isn't appropriate on fariground.

## Tasks

- [ ] Work out better message
- [ ] Implement to the code base

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1682688971423049

**Comment by barnabee** [comment]
Probably just replace the warning with some welcome text / explanation of Fairground, perhaps links
