### ISSUE TITLE
Token FE, invalid token address on vesting page

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#357]
The token address displayed on the vesting page (pointing to testnet) is currently shown as 0X0

<img width="931" alt="Screenshot 2022-05-04 at 11 35 53" src="https://user-images.githubusercontent.com/30622993/166666081-21eda773-f5a2-4654-8dab-7fdb3681d61f.png">

Clicking on `Show this token in your Ethereum wallet` returns `MetaMask - RPC Error: Invalid address "0x0"`

<img width="1683" alt="Screenshot 2022-05-04 at 11 37 42" src="https://user-images.githubusercontent.com/30622993/166666216-13c49a5f-0218-4755-bdd1-4c50bc0c5aa7.png">

**Comment by gordsport** [comment]
Close as wont fix
