### ISSUE TITLE
Liquidity provision rewards not being displayed, incorrect totals

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3572]
We believe this is probably a core issue but will investigate and verify and transfer to /vega repo if this is the case

## Issue 1 Description

The reward pools are receiving 1000 for maker fees paid, 1000 for maker fees received and more as you can see in total but LP is on included on the page.

However disregarding that LP is not included looking at epoch 4327, the price making pools is 3 for one epoch which makes little sense to me since it was not changed.
 

### Steps to Reproduce

1. Go to https://validator-testnet.governance.vega.xyz/rewards
2. Check epoch 4327

<img width="921" alt="Screenshot 2023-05-02 at 11 37 19" src="https://user-images.githubusercontent.com/100769129/235636944-873c9716-de9a-447a-9191-beacd34b63bc.png">

## Issue 2 Description

The new rewards screen is not showing the LP ones. 

![Image](https://user-images.githubusercontent.com/89918817/235215212-06e7b1e6-8423-4ab0-87f3-a902cfcf7f39.png)

This shows 1000 + 1000 = 4000.

Looking at the API for epoch 4152 there are LP rewards.

https://api-validators-testnet.vega.rocks/api/v2/rewards/epoch/summaries

You can see them here

![Image](https://user-images.githubusercontent.com/89918817/235215351-73ff1cd9-3e99-48e1-9c77-a7489412b53e.png)

So it should be 2000 worth of LP rewards so 4000 in total.

**Comment by ckpringle** [comment]
I think this is just a case of pointing the existing column at ACCOUNT_TYPE_REWARD_LP_RECEIVED_FEES instead of ACCOUNT_TYPE_FEES_LIQUIDITY
