### ISSUE TITLE
Get wallet link should be external link which opens new tab

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#3591]
As this is common component we are hoping the console team will pick this up - @mattrussell36 🙏 

## Description

When user has no Vega wallet connected the `Get a Vega Wallet` and `Having trouble?` should be external links that opens a new tab when clicked on. 

![Screenshot 2023-05-03 at 11 34 19](https://user-images.githubusercontent.com/30622993/235886464-00d4e976-ff1b-45f8-8a99-8b489c7a4a91.png)

![Screenshot 2023-05-03 at 10 57 44](https://user-images.githubusercontent.com/30622993/235886411-1556b4ea-a95b-4a0a-aadf-7907882f4c57.png)

**Comment by pennyandrews** [comment]
@ckpringle can you refine or remove it if is covered elsewhere, THANKSA!!!

**Comment by mattrussell36** [comment]
This is done
