### ISSUE TITLE
Make single markdown component with consistent configuration

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#3605]
## Problem 

React Markdown component does not behave like a markdown renderer in some places such as Console and Explorer

## Task

Create a component that can render markdown text so that it can be used:

- [ ] wherever ReactMarkdown is used in the codebase
- [ ] in Oracle Full Profiles for provider.description_markdown

**Comment by edd** [comment]
Hey I'm just doing the back half of https://github.com/vegaprotocol/frontend-monorepo/issues/2998 which involves adding ReactMarkdown to the proposal view on governance. Given it's already in the codebase, it seemed to make sense.

For reference, it's in two places I know of:
- Used in the proposals list on explorer
- Used on the proposals detail view (Proposal-header.tsx) in governance

If you do drop it from the codebase, these are the two places i know ofthat need to be changed.

**Comment by MadalinaRaicu** [comment]
Thanks @edd  
I have managed to re-use the existent ReactMarkdown component in oracle full profile 
 https://github.com/vegaprotocol/frontend-monorepo/pull/3707 and I feel like closing this issue
