### ISSUE TITLE
Navigation underneath LP dashboard table

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3646]
## Bug description 

The website navigation appears underneath the LP dashboard table content. It should instead overlay the content (like any other page).

## Screenshot

![Image](https://user-images.githubusercontent.com/46783148/237045720-42617e36-0b9e-4f72-bca8-8f879c7a3dea.png)

**Comment by JonRay15** [comment]
Think this is done?  Or at least no longer relevant because the title takes up enough space?

The drop down thingy is excessivly large ... but thats a website question.
