### ISSUE TITLE
Reflect network upgrade status

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3651]
## The Story

As a user 
When a network upgrade is in progress 
I want to understand the current status of the network upgrade i.e. % of validators have pre-voted as ready to bring their nodes back up again 
So that I have a better idea of when to expect the upgrade to have completed 

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

## Notes

Might be best placed to go on the announcement banner

Good information is available from Tendermint/CometBFT REST API - but there is a small problem: you need to query 2-3 endpoints and merge them.

Showing this for only open proposals will limit the performance overhead of this task so we are proposing to go for that, rather than for all proposals

Fryd is required to write some sort of script / service to get this data

**Comment by JonRay15** [comment]
I think this is covered by https://github.com/vegaprotocol/frontend-monorepo/issues/3534

We will handle this in block explorer, and if governance or console want to link here they can do.
