### ISSUE TITLE
Node checker shouldnt stop you selecting a node that is failing the checks

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3672]
## The Chore

The node checker function on the apps is a bit ropey and stops you selecting nodes that are actually fine.  We should disable that part so that even if it thinks the node is bad it still lets you select it anyway.

## Tasks

- [x] Do it 
- [ ] Test it 
- [ ] Tell Jon Ray

**Comment by pennyandrews** [comment]
Duplicate ticket
