### ISSUE TITLE
My Stake precision is a little too accurate!

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3679]
## Steps to Reproduce

1. Go to 'governace app
2. Click on staking
3. Connect a wallet 

## Expected behavior

I dont need to see all these decimal points 

<img width="764" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f4c9fc23-3181-4ebe-a381-025240e2b262">

We should be clipping it at 2 DP like the other stuff on the page.

## Screenshots

See above

## Device details

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 0.71.4 and 0.12 for dektop wallet

**Comment by pennyandrews** [comment]
Duplicates https://github.com/vegaprotocol/frontend-monorepo/issues/3571
