### ISSUE TITLE
My stake empty state / not connected

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3691]
## Description

When I go to "My stake" there was / should be an empty state with connect to see my stake. That seems to have hidden in favour of the empty tables in the screenshot below.

<img width="1511" alt="Screenshot 2023-05-10 at 10 13 40" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/2796cc2e-c38f-4585-b9e7-97506a38415b">

## Expected behavior

<img width="947" alt="Screenshot 2023-05-10 at 10 15 56" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/a9480e5e-838f-4582-83af-7ed2a021ad97">

## Device details

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by pennyandrews** [comment]
Duplicates A/C in this ticket already prioiritsed https://github.com/vegaprotocol/frontend-monorepo/issues/2404
