### ISSUE TITLE
Overstaked penalty 0 or higher

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3696]
**_Calculations for this (or decision not to make any calculations in the client) are up for debate in[ this ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/3700) so parking this for now until we know how to proceed._**

David is seeing negative overstaked penalty figures in the governance dapp

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/4e42bc88-f53b-4044-845c-124eab20820b)

Jon is investigating, follow the conversation here https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1683715338911629

**Comment by sam-keen** [comment]
Looks like a short term improvement is to ensure penalties are no lower than 0. I'll do that in this ticket and we can look at broader changes separately
