### ISSUE TITLE
View treasury + other reward programs / balances

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#370]
New page on token.vega.xyz that

- Introduces the treasury and key data about it
- lists the active rewards from the treasury (with a link to also show historical rewards
- links to details about each treasury rewards programs

**Comment by gordsport** [comment]
@campbellssource - please can you review the priority on this.

Seems we can see the reward type and could show this.

**Comment by campbellssource** [comment]
Assigning this to @ckpringle as he is leading the design. Feel free to change the description to reflect the stuff that needs to be done front end side and not covered on Vega.xyz or elsewhere.

**Comment by JonRay15** [comment]
@campbellssource just so I'm clear ... is this ticket about expanding how MY rewards are presented to ME when I open token.vega or is this about some additional page that just talks about holistically what rewards are out there?

@ckpringle and I already have some ideas around the latter, the landing page, and we see that as living on vega.xyz.  

I would expect we still also need the personalised view within token.vega at some point, but we havent been thinking about that.  Are you expecting us to or are have you already done that / are planning to do that?

**Comment by ckpringle** [comment]
I suggest we close this issue. The idea being it's faster and easier to get a landing page up separate from token front end. This landing page would link to token front end to see rewards you have earned. 

See https://app.asana.com/0/1201793103707836/1202904677906603/f

In the future (even if not for trading launch) rewards won't *just* be in Vega tokens, so having the list of rewards I can earn as only a part of the vega token site doesn't feel right.
