### ISSUE TITLE
Add fallback Ethereum RPC provider

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3730]
## The Chore

Add a fallback Ethereum RPC provider (similar to what is on the governance app), so that we can query smart contract values without having a connect Ethereum wallet

## Tasks

- [ ] Add fallback provider
- [ ] Ensure you an successfully query for data from ethereum with no wallet connection

**Comment by mattrussell36** [comment]
I think we should make the wagmi switch before we spend efforts here

**Comment by JonRay15** [comment]
Going to assume this is covered by WAGMI and close it since this is now implemented.
