### ISSUE TITLE
Expose withdrawal signature bundle 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3741]
This is being developed by the Console team https://github.com/vegaprotocol/frontend-monorepo/issues/3546 and we are hoping we can then just utilise this in Governance also

**Comment by JonRay15** [comment]
Looks like this is nearly done in console ... although the fact they're using toasts doesnt scream "reusable component for governance app".... 😬 

https://github.com/vegaprotocol/frontend-monorepo/issues/3546
