### ISSUE TITLE
Update console mainnet link in network switcher

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3745]
## The Chore

The mainnet link in the network switcher will need to link to the 'accessible' page that then redirects to the url on ipfs

## Tasks

- [x] Find out what the stable link is: https://vega.trading
- [ ] Update the links in our env files

**Comment by edd** [comment]
See also https://github.com/vegaprotocol/frontend-monorepo/issues/1754
