### ISSUE TITLE
Notice about the risks of Trading on Start up (and legal warning)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#375]
From: https://github.com/vegaprotocol/console/issues/6664

Derivatives should be used only by appropriate persons. We'd like to ensure that only appropriate persons use the software we create. This ticket to design and implements some sort of message in Console to inform potential users, and potentially discourage non-approporate people from using it

- [ ] Read some of the rationale behind regulations (and talk to legal)
- [ ] draft a message
- [ ] Have legal team review / iterate the message
- [ ] Design for how and where the message appears in console
- [ ] Build it (via UI-toolkit?) into console

Also required:
- [ ] hide this information in testnet (check with Dave Mac - is there other info that could/should be testnet copy)
- [ ] Consider how this interacts with the landing dialog

-----

Reading:
https://3commas.io/blog/the-risks-of-margin-trading-and-how-to-do-it-properly from a trading client (not an exchange) for its users about the risks of trading
https://www.fca.org.uk/news/press-releases/fca-warns-younger-investors-are-taking-big-financial-risks
> The FCA advises consumers to consider five important questions before they invest: 
> Am I comfortable with the level of risk?
> Do I fully understand the investment being offered to me?
> Am I protected if things go wrong?
> Are my investments regulated?
> Should I get financial advice?

IG and CFD providers are required to have something like this on their site:
> Spread bets and CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. 68% of retail investor accounts lose money when trading spread bets and CFDs with this provider. You should consider whether you understand how spread bets and CFDs work, and whether you can afford to take the high risk of losing your money.

https://www.sec.gov/news/speech/mjw-speech-032114-protecting-retail-investor

----

additional requirement:

make it clear that this is alpha software

----

https://uniswap.org/terms-of-service

**Comment by barnabee** [comment]
See also https://github.com/vegaprotocol/console/issues/6664#issuecomment-1183219279

**Comment by barnabee** [comment]
Also worth noting here that any of these sorts of warnings should be agreed across the project team + legal and regs and standardised rather than coming from the individual front end project teams.

**Comment by campbellssource** [comment]
To aid discussion here is a mock up of the text above:
<img width="1480" alt="Screenshot 2022-07-20 at 20 22 34" src="https://user-images.githubusercontent.com/13255539/180064882-7f4728ae-41c6-4ac8-a384-9b6920f0b1f4.png">

- Should there be an affirmation that the user is making by clicking something. As well as no way to dismiss the modal/use the app until affirmed?
- In the mock up the headings are changed to give you a sense of what the risk is rather than the type.

but as mentioned these warning need to be worked on more generally

**Comment by campbellssource** [comment]
Minor update. There was some discussion about the copy in the dialog, that is not resolved. I suggest we build and merge the feature and update the copy later if needed

**Comment by gordsport** [comment]
Requirements:
Needs to be easy to change as its expected that the text will/may change regularly. Text will likely need to be different between networks (testnet/mainnet) - other option is we only show on mainnet but need to confirm with Dave if this is OK

Questions:
How does this work with the current landing page?
