### ISSUE TITLE
Something went wrong: failed to get party for ID on governance page, needs to clear cookies and data

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3758]
## Description

Seems like, at least after one has connected to fairground and mainnet, that the mainnet party ID gets this error.
Something went wrong: failed to get party for ID

## Steps to Reproduce

1. Go to https://governance.vega.xyz/proposals/a4a16e250a09a86061ec83c2f9466fc9dc33d332f86876ee74b6f128a5cd6710
2. Click on connect wallet
3. Scroll down to '[....'](https://governance.fairground.wtf/) and connect to that instead 
4. Go back to https://governance.vega.xyz/proposals/a4a16e250a09a86061ec83c2f9466fc9dc33d332f86876ee74b6f128a5cd6710
5. connect and see the error on the page see image

## Screenshots

<img width="1022" alt="Screenshot 2023-05-14 at 16 56 22" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/e593a3f5-91fe-4a79-b8e6-68fd2cac6e97">

## Device details

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version Desktop v0.12.1

**Comment by sam-keen** [comment]
Thanks for reporting @daunatv. We have a fix in progress for this (https://github.com/vegaprotocol/frontend-monorepo/issues/3742), so closing this ticket as a duplicate.
