### ISSUE TITLE
Rewards table per epoch is not formatted correctly(fairground)

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3784]
## Description

Rewards per epoch page does not format correctly.
https://governance.fairground.wtf/rewards

## Steps to Reproduce

1. Go to ['...'](https://governance.fairground.wtf/rewards)
2. Click on check epoch 6722
3. The table looks strange in terms of formatting

## Screenshots

<img width="1058" alt="Screenshot 2023-05-16 at 13 47 58" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/fb76dc65-5204-45e9-82fe-5ce54960fbf8">

**Comment by daunatv** [comment]
Does not take the LP rewards into account either 
https://api.n06.testnet.vega.xyz/api/v2/rewards/epoch/summaries
Should have been 47 at the time of the screenshot.

**Comment by JonRay15** [comment]
This may be duplicative of https://github.com/vegaprotocol/frontend-monorepo/issues/3572 which is already in progress

**Comment by ckpringle** [comment]
This ticket is just formatting, #3572 is for the "totals" problem.
