### ISSUE TITLE
Multiple wallets needed for different states in trading app

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/frontend-monorepo#380]
Currently for the tests we have only 1 wallet set up to run the tests which is set in git.secrets as `CYPRESS_TRADING_TEST_VEGA_WALLET_PASSPHRASE`

Some of the tests require the wallet to not have an approved tokens state as we check for certain validations and unhappy paths with the user not approving tokens before attempting to deposit . Some deposit tests are failing because the wallet has been approved and the tests are looking for a not approved validation .

We need to set up 2 wallet mnemonics and store them as cypress envs : 
CYPRESS_TRADING_TEST_VEGA_WALLET_PASSPHRASE_APPROVED
CYPRESS_TRADING_TEST_VEGA_WALLET_PASSPHRASE_NOT_APPROVED

**Comment by dexturr** [comment]
Use the second key from the same mnemonic, rather than introducing a second mnemonic. This can be achieved by passing the account index into the createEip1193 bridge function
