### ISSUE TITLE
Show Multsig penalty in the staking penalties tooltip

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3802]
## The Chore

This isnt actually an issue since we dont show thie currently but if we do part 2 then IF a multisig issue occured the overall penalty would jump to 100% and it wouldnt be obvious why since we dont currently show this.

We should conditionally show this in the penalty popup.  If `rewardScore.multisigScore` for any validator is zero then add to the popup "Multisig Penalty: 100%", otherwise dont show it.  I would get rid of the Total Penalties in the popup since we already know that, its in the table.  Then you can just append that message when relevant.

<img width="171" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/9b6ef64f-eef6-4414-bdb7-b557abc17cbd">

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by edd** [comment]
I put a comment on the PR that closes this that I'm not sure I like 100% as an indicator here. It's not inaccurate, but it also asks more questions than it answers. @sam-keen told me that it makes sense in context with other indicators though.
