### ISSUE TITLE
Token Frontend: Testnet has a bad proposal and token.fairground.wtf handles it poorly

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#382]
Related: https://github.com/vegaprotocol/vega/issues/5339

See https://github.com/vegaprotocol/vega/issues/5339 for what is being returned. 
<img width="506" alt="Screenshot 2022-05-06 at 11 39 56" src="https://user-images.githubusercontent.com/6678/167116696-c7a074c8-02ff-4a9f-8c76-1d886bee7eba.png">

<img width="858" alt="Screenshot 2022-05-06 at 11 39 23" src="https://user-images.githubusercontent.com/6678/167116692-e0c9a71d-d0ae-4d28-a2f6-b8899eb6647b.png">

# Tasks
- [ ] Filter out crazy proposals that break the schema, render the good ones.

**Comment by dexturr** [comment]
Closing as this had been addressed seperately
