### ISSUE TITLE
Adjust closed proposals sort order on the proposals page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3823]
This ticket https://github.com/vegaprotocol/frontend-monorepo/issues/3681

....could have been clearer. 

The sort that has now been applied seems to have beenn applied across ALL proposals whether Open or Closed.  So it means that now to find the most recently closed proposals you have to scroll right to the bottom of the page. 

We need different sort orders on Open vs Closed proposals.

Open ones leave as defined in that ticket.

Closed ones:
- Enacted shoudl be sorted by `enactmentTimestamp` with most recent at the top 
- Rejected should be sorted by `closingTimestamp`with most recent at the top (since they dont have enacted)

**Comment by jtsang586** [comment]
Re-opening ticket as closed proposals are not sorted by `enactmentTimestamp`
