### ISSUE TITLE
It's not obvious how to remove the market list on the left of the console

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/frontend-monorepo#3837]
## Description

It's not obvious how to remove the market list on the left of the console, and it's not obvious to make the window smaller. When I am trading on the market, I do not need to see the list of other markets, so it will be useful to make the market window disappear 

<img width="326" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/92106936/97e17a1b-b902-4130-841e-a895d53f0045">

**Comment by mattrussell36** [comment]
Blocking this as this will likely get superseded by incoming design changes captured in other tickets
