### ISSUE TITLE
Wrong decimal places in Estimated Liquidation Price 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/frontend-monorepo#3839]
Estimated Liquidation Price is currently using decimal place of 10, it should be the same as market decimal 
Estimated Margin is currently using decimal place of 13, it should be the same as asset decimal

<img width="283" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/92106936/f7843952-a028-47e5-9e61-a77c6e3545c5">

**Comment by bglownia** [comment]
I made PR but it looks like it is working as expected, changing from asset decimals to market decimals are giving wrong results 

On the left: current version, using asset decimals
On the right: proposed change to market decimalsPlaces 


![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1754247/7b7be851-a37c-4523-b600-1561ca3e99c4)
