### ISSUE TITLE
CONSOLE-V2 Error message / modal improvements for when a user attempts to approve an asset they have 0 balance on or 0 eth/insufficient gas to cover fee

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/frontend-monorepo#384]
If the user attempts to approve a token for deposit of which they have 0 balance on , a long error message appears on the whole page

<img width="663" alt="Screenshot 2022-05-06 at 13 30 35" src="https://user-images.githubusercontent.com/87758526/167132170-c1e64753-90a5-4bb7-b93e-a69c34accb3e.png">

insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"insufficient funds for intrinsic transaction cost","code":"INSUFFICIENT_FUNDS","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":60,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8af03808459682f008489195ab282b76994dc335304979d378255015c33abff09b60c31ebab80b844095ea7b3000000000000000000000000f009c66c6afc9661143fd7ce1edb02c1961a6510000000000000000000000000000000000001bc16d674ec7ff21f494c589c0000c080a093cf97331e5f64af20fb3aeb744a860a5b44c43d7556f577a9717e31e763fb9ba039e608a3a89f8a851a6368bdb710f318f38f7447c34b7937bbd06914b189f6fb\"],\"id\":60,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://ropsten.infura.io/v3/4f846e79e13f44d1b51bbd7ed9edefb8"},"method":"sendTransaction","transaction":{"type":2,"chainId":3,"nonce":0,"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x89195ab2"},"gasPrice":null,"gasLimit":{"type":"BigNumber","hex":"0xb769"},"to":"0xDc335304979D378255015c33AbFf09B60c31EBAb","value":{"type":"BigNumber","hex":"0x00"},"data":"0x095ea7b3000000000000000000000000f009c66c6afc9661143fd7ce1edb02c1961a6510000000000000000000000000000000000001bc16d674ec7ff21f494c589c0000","accessList":[],"hash":"0x2eee73f2f4c10a7a649ab8365231a9fdf0d56a3bdfdb6b79f78df9f0e95e1707","v":0,"r":"0x93cf97331e5f64af20fb3aeb744a860a5b44c43d7556f577a9717e31e763fb9b","s":"0x39e608a3a89f8a851a6368bdb710f318f38f7447c34b7937bbd06914b189f6fb","from":"0xF2790d397002781702d7723FE2e5DD0a5e9A7127","confirmations":0},"transactionHash":"0x2eee73f2f4c10a7a649ab8365231a9fdf0d56a3bdfdb6

**Comment by gordsport** [comment]
Closing as resolved with formatting
