### ISSUE TITLE
Remove PNL column from closed markets list

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/frontend-monorepo#3847]
Remove realisedPNL column from closed markets list

## Tasks

- [x] Remove pnl column from closed markets list
- [x] Update specs
- [x] Test

## Additional information

<img width="1275" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/92106936/07c42d13-faa9-4647-802a-2b6b936644ac">

**Comment by bglownia** [comment]
unrealisedPNL and realisedPNL are not modified in any way on frontend. They are displayed as delivered in response.

**Comment by mattrussell36** [comment]
@Jiajia-Cui are you able to add any additional details? As bart has mentioned we don't do anything to the values returned via the API. There could be a core bug, can you remember how and when you got this value? Or can yo recreate it?

**Comment by Jiajia-Cui** [comment]
> @Jiajia-Cui are you able to add any additional details? As bart has mentioned we don't do anything to the values returned via the API. There could be a core bug, can you remember how and when you got this value? Or can yo recreate it?

I do not have additional details, I checked some feature tests which cover the PnL when market is terminated, and they seem fine. So I am not sure whether it's Core or Front-end.
