### ISSUE TITLE
Hide proposal details for freeform proposals

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#3876]
## Description

Freeform proposals should have proposal details removed in the proposal details page if there are no fields within the proposal parameter.

![Screenshot 2023-05-22 at 15 44 47](https://github.com/vegaprotocol/frontend-monorepo/assets/30622993/d6d5585b-de16-4c91-a143-b6f065fc32a9)

**Comment by pennyandrews** [comment]
Example proposal from Jon:

{
  "rationale": {
    "title": "An example freeform proposal",
    "description": "I propose that everyone evaluate the following IPFS document and vote Yes if they agree. [bafybeigwwctpv37xdcwacqxvekr6e4kaemqsrv34em6glkbiceo3fcy4si](https://dweb.link/ipfs/bafybeigwwctpv37xdcwacqxvekr6e4kaemqsrv34em6glkbiceo3fcy4si)"
  },
  "terms": {
    "newFreeform": {},
    "closingTimestamp": 1685553047
  }
}
