### ISSUE TITLE
Improve react router configuration for path section

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3895]
## The Chore

The router config in Explorer needs a refactor. I think. At the very least it needs another pair of eyes. Specifically navigating from /party/:id to party/:id/accounts by clicking on the Show All button triggers an error on first load that could only be caught with React.Suspense. This makes me feel like I've configured it poorly.

## Tasks

- [ ] Review the React Router setup for parties

**Comment by pennyandrews** [comment]
dd to review and either move to the backlog or close accordingly
