### ISSUE TITLE
Governance - funds unlocked toast not auto closing

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#3897]
## Description

When user tries to make a withdrawal. 

The funds unlocked toast is displayed (screenshot) but does not auto close and requires user to click on the close button to close the toast

## Expected behavior

1. When user clicks on complete withdrawal the toast should close automatically. Preventing user clicking on the withdrawal again generating an error
2. After a period of time the toast should close by itself? 

![Screenshot 2023-05-23 at 11 23 01](https://github.com/vegaprotocol/frontend-monorepo/assets/30622993/030e0c7c-165e-4b8f-bc20-18a7d953300e)

**Comment by mattrussell36** [comment]
@jtsang586  this is by design to let the user copy their withdrawal details
