### ISSUE TITLE
Governance - Unclear error trying to withdraw with eth wallet disconnected

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#3898]
## Description

User tries to withdraw funds with their Eth wallet disconnected but fills in form to withdraw to valid Eth wallet address. 

Results in following Error shown in the toast: 
`ERROR OCCURRED
You are on the wrong network`

## Expected behavior

Error should be clearer indicating Eth wallet needs to be connected to make a withdrawal

## Screenshots

![Screenshot 2023-05-23 at 11 55 59](https://github.com/vegaprotocol/frontend-monorepo/assets/30622993/3868c64c-3130-49dd-af3a-7fe08aedb0e0)

## Sketch

From https://github.com/vegaprotocol/frontend-monorepo/issues/3364:

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/1f349e8d-abaf-4a26-bee5-4ed705b1c99d)

**Comment by neildawson** [comment]
@asiaznik wrote a better error message for this and added it to https://github.com/vegaprotocol/frontend-monorepo/issues/3364
