### ISSUE TITLE
Can not resize console tabs when in `View as` mode

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#3903]
## Problem 

Can not resize console tabs in `View as mode` 

## Demo 

![Image](https://user-images.githubusercontent.com/16125548/240290221-5de6ffe8-fe0b-4d8d-be46-06ec610b433c.png)

**Comment by pennyandrews** [comment]
Matt has also seen this without going into view as mode so thinks there may be something fishy going on :)

**Comment by MadalinaRaicu** [comment]
@asiaznik fixed this in one of his previous PRs.
