### ISSUE TITLE
Show some asset by default on Portfolio page

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/frontend-monorepo#3911]
## Description

When you click on "Portfolio" to go view your assets, we have "General" selected by default for account type, but no default for assets, meaning you're looking at a blank page. Feels like we should default to _some_ asset. Bonus points for, perhaps, your account with the highest balance, or last traded? I welcome thoughts on the correct account to show, but I feel like _any_ account is better than no account?

## Steps to Reproduce

1. Go to "Portfolio" page.

## Expected behavior

Some asset is selected, and so some balance is displayed.

## Screenshots
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/7438348/c7080394-40cf-42a9-aaab-6236c40bd894)

## Device details

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 113.0

**Smartphone (please complete the following information):**

**Comment by asiaznik** [comment]
I've made the chosen asset persisted, so switching tabs back and forth won't force a user to select it again (first by default if non chosen though)
