### ISSUE TITLE
NX_APP_VERSION in make-release script

### ISSUE THREAD

**Issue by asiaznik** [vegaprotocol/frontend-monorepo#3918]
Blocked by https://github.com/vegaprotocol/devops-infra/issues/1921

bump the version
commit
tag the commit

Further details on release/deployment in notion here: 
https://www.notion.so/vegaprotocol/Releases-and-deployment-f61517d6e7c6488ea0606e48f11b489a?pvs=4

**Comment by asiaznik** [comment]
mainnet

tag
push to main
wait for ipfs deployment and the dns record to be updated
once complete, only then create the release and add the ipfs notes

**Comment by mattrussell36** [comment]
Blocking this as we should wait for https://github.com/vegaprotocol/devops-infra/issues/1921 which will affect how this will work
