### ISSUE TITLE
governance.vega.xyz After associating the associated balance is not refreshed

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/frontend-monorepo#3921]
One the token website

I had some tokens unassociated and some tokens unassociated...
Started a transaction to associate the maximum unassociated tokens.
Was pending for 50 confirmations, the pending transaction box was spinning.
When 50 blocks were comfirmed the pending transacion box froze
Saw that the associated and unassociated balances did not change
I was able to attempt a new associated transaction again for the maximum amount.
Clicked around a few pages and back again, associated was still not correct.
Refreshed browser tab - all ok  unassociated was 0, associated was correct.

**Comment by JonRay15** [comment]
Closing
