### ISSUE TITLE
Margin warning is way too shouty

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#3922]
The not enough margin warning is far too big and shouty IMO. This should be like a simple line of text or small highlight or something, as it's not a massive error condition to have the ticket in a state like this.

<img width="1912" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/b5257a58-3c8f-4f3b-b613-0313178c4848">

**Comment by mattrussell36** [comment]
I've added this one to the [design change epic](https://github.com/vegaprotocol/frontend-monorepo/issues/4077) as I think we'll probably want to consider this along with other deal ticket changes
