### ISSUE TITLE
Rewards decimals wrong for USDT

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#3924]
The decimals are wrong for USDT rewards displayed in either the assets view or rewards view or both. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/0db5b802-b123-46e6-937b-26a6257b55f2)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/82f421f8-6f2d-4c10-86c4-0630f795fb64)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/f9283ad6-1c10-4221-9267-a4278a7b341d)

**Comment by JonRay15** [comment]
Can we make sure this is right for USDC too?

**Comment by JonRay15** [comment]
We had a very minorr reward in the last epoch .... could be geniunley that minor or could be a decimals thing

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fa607f05-32a5-4ec3-9090-6c04837211b9)
