### ISSUE TITLE
Trading update notification shown on latest version

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3934]
## Description

There appears to be a bug with the update notification that says there is an update even when the user is on the latest version

## Steps to Reproduce

1. Go to https://console.vega.xyz
2. Observe the IPFS CID in the url
3. Click on update notification
4. Compare the CID

## Expected behavior

The CID should be different, because if the user is on the latest release it should not show an update notification

## Screenshots
<img width="1118" alt="Screenshot 2023-05-24 at 14 08 36" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/b95a5dc7-abf1-48c9-8b4a-9cd5a996c478">

**Comment by pennyandrews** [comment]
Resolved. This was a result of release process growing pains
