### ISSUE TITLE
explorer.vega.xyz/oracles Data and Display

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/frontend-monorepo#3935]
1/ For internal oracle specs we dont show a user friendly dts only an epoch timestamp

2/ oracles page shows matched data "X" but when clicking on the oracle ID we navigate to a page which shows just the oracle selected but with matched data "0"

3/ At least one market is live at time of this issue so we dont have an internal oracle terminating this market

4/ The settement oracle for the live market has matched data X - Im guessing this shows a tick when the timestamp and price is reached?

5/ Settlement condition for live market is OPERATOR_GREATER_THAN "0" - this wont settle if the mark price is actually 0 which is possible I think.

6/ The signers address links to etherscan which shows no transactions? is this correct?

**Comment by edd** [comment]
Addressed in #5135
