### ISSUE TITLE
Add front end applications for mainnet mirror environment

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#3986]
There is a mainnet mirror environment that has been set up to be an exact mainnet version replica of mainnet. This network is currently running as seen [here in stats](https://stats.vega.trading/#mirror)

In order to be able to fully leverage the network for its intended purpose we need to deploy the front end applications:

### Tasks:

- [ ] Deploy the FE applications pointing at mainnet mirror
- [ ] Append name in drop down with "testnet"

### Additional information

The mainnet mirror URLs / API details can all be found in the following location:

- https://github.com/vegaprotocol/ansible/blob/master/inventories/mainnet-mirror.yaml

**Comment by pennyandrews** [comment]
@mattrussell36 thinks this is done and good to close
