### ISSUE TITLE
Governance site making excessive Ethereum RPC calls

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#4002]
## Description

The Governance homepage, proposals view, etc. (which should not need to communicate with Ethereum RPC) are making tons of calls (multiple calls every few seconds, forever) to the Pokt (or whatever is configured) RPC endpoint.

It does this even when no Ethereum wallet is connected.

This is unnecessary if no Ethereum wallet is connected, and probably unnecessary even then. In fact it is unclear whether this endpoint is needed for anything other than WalletConnect scenarios, except maybe on some of the token subsite pages, as by the time you are interested in Ethereum data you've probably connected a wallet with its own RPC provider.

## Steps to Reproduce

1. Go to https://governance.vega.xyz
2. Open devtools > network
3. Filter on "pokt"
4. 🤯

## Expected behavior

No results in filtered network view.

## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/9f8fdb66-9f69-450a-aba4-fec0ac326eb1

## Additional context

Re: discussion [in #engineering-leadership-team](https://vegaprotocol.slack.com/archives/C04G76YK351/p1685523889439599?thread_ts=1685485535.310199&cid=C04G76YK351)

**Comment by pennyandrews** [comment]
Short term solution has been to revert back to using Infura. Long term solution ticketed here for prioritisation https://github.com/vegaprotocol/frontend-monorepo/issues/4011
