### ISSUE TITLE
Midnight not showing correctly on chart.

### ISSUE THREAD

**Issue by ben-vegaprotocol** [vegaprotocol/frontend-monorepo#4007]
## Description

Midnight appears to show incorrect value in the time section of the chart.

## Steps to Reproduce

1. Visit console trading page. 
2. See issue

## Expected behavior

we should be showing 00:00 at midnight 

## Screenshots

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/665c0420-3599-490e-b007-0b315888d906)

**Comment by mattrussell36** [comment]
These values are the day of the month.
