### ISSUE TITLE
Governance dapp journey map

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4013]
## Chore 

As a team 
We want a way to capture improvements against the relevant part of the journey 
So that we keep in mind the "bigger picture" of what you can do on the dapp even when it's not being actively developed 

## Draft map 

https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764555446922117&cot=14

**Comment by JonRay15** [comment]
Odds of looking at this any time soon ... slim
