### ISSUE TITLE
Portfolio page - Tables

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#404]
As an extension to the work started here:
- https://github.com/vegaprotocol/frontend-monorepo/issues/248

This issue needs to be broken down and refined

**Comment by PeteWilliams** [comment]
Have added designs with both a simple version for initial release and a future state that'll take a bit more work.

The simple version should hopefully be possible in AG Grid, whereas the future state includes multi-cell rows, some basic data visualisations and filters. Would be good to discuss if any one these things are possible in the near-term.

https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1562%3A27750
