### ISSUE TITLE
Console, Account History, show plot of total = general + bond + margin

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#4045]
Offer an option here to plot total = general + bond + margin
<img width="367" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/69d8d26c-ba70-48a2-aafd-ef098676eefd">

**Comment by mattrussell36** [comment]
@davidsiska-vega Just to make sure we prioritise this correctly, can you provide some extra context about your intention/goal here

**Comment by davidsiska-vega** [comment]
The options I have are:
- bond; probably not the most exciting, it's going to be stable and it's mostly entirely under the party's control. So not an interesting view IMO.
- margin: very volatile, looking at the graph I can't see a trend that can inform me e.g. about how my trading is going
- general: if I have a position / orders then it's very volatile and again I can't see a trend hat can inform me e.g. about how my trading is going

What you want is the total balance in an asset to see whether you're making or losing money.

**Comment by JonRay15** [comment]
This screen is dead .... we will never do this .... killing
