### ISSUE TITLE
Stagnet1 - a market in opening auction has extremely high margin requirement in console

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4046]
## Description

Console seems to calculate required margin incorrectly in stagnet1, see the difference when I use wallet command to send order, it works but Console seems to thinkt it should not.

## Steps to Reproduce

1. Go to a market in opening auction on stagnet1 e.g. https://trading.stagnet1.vega.rocks/#/markets/e683ab0471ebf10ca658e05b7853e587e8dc372c3803eb8b9127873e52a8cfd0
2. Click on sell order and see if you get it to work, probably says that you need extreme amount of margin.
3. Do the same order using wallet command and you will see that it is accepted
`{
    "pubKey": "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f",
    "propagate": true,
    "orderSubmission": {
        "marketId": "e683ab0471ebf10ca658e05b7853e587e8dc372c3803eb8b9127873e52a8cfd0",
        "price": "186355",
        "size": "70",
        "side": "SIDE_SELL",
        "timeInForce": "TIME_IN_FORCE_GTC",
        "type": "TYPE_LIMIT"
    }
}
`

## Device details

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome

## Video

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/7939bca6-e308-4697-a9d3-3a72851c216b

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/b0925b06-d7b1-461f-8889-764b1b13bbb9

**Comment by mattrussell36** [comment]
@macqbat  Sounds like this is hard to reproduce. Suggest we:

- double check correct decimal values are used
- double check the maths
- add a market sim test to have a reproducible market state we can check the maths against
