### ISSUE TITLE
Release breaking changes

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#405]
[Slack ref](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1652774549772619)

The fields in freeform have changed to be available for all types of proposal as can be seen in this git diff:
https://github.com/vegaprotocol/data-node/pull/531/files#diff-defbaa444c5bb49e909094a88a13fae871c901e268b1b49c4b906b7439a726c6R2407-R2457

This is currently on stagnet2 at time of writing and so should be fixed there.

- [ ] We need to change the query in: `apps/token/src/routes/governance/proposal-fragment.ts` to instead of querying for the fields url, description and hash from free form to query the rationale property for every proposal.
- [ ] Regenerate the types
- [ ] Fix any type errors

**Comment by gordsport** [comment]
Closing as in `Done`
