### ISSUE TITLE
Updated oracle for Update Market proposal not linked to in Console

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4052]
## Description

Dan created two Update Market proposals (seen here in the proposals list on Governance on fairground)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/08cd67bb-09d5-43b4-847f-2252e0fbce8e)

At the time he couldn't view the proposals on governance (covered in this ticket https://github.com/vegaprotocol/frontend-monorepo/issues/4201) but could view in Console and in this Console view of the proposed market update, the link to the oracle specs does not take you to the latest Oracle, in this case
https://explorer.fairground.wtf/txs/6E166FA4123B856AFFAB6072D63EB8C86324EB0AF079C8DCE99C28EF3360CA61

It seems like I am not able to settle with the new oracle specs either.

**Comment by JonRay15** [comment]
This is on these two proposals which can be seen in the proposals screen

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/96ca275f-4c30-46f0-b44c-c70926540138)

**Comment by pennyandrews** [comment]
The part of this ticket about the update proposals not being viewable is now covered here https://github.com/vegaprotocol/frontend-monorepo/issues/4201 as was a duplicate. I have now repurposed this ticket to just focus on the Oracle part.

**Comment by mattrussell36** [comment]
@JonRay15 @daunatv I've opened up a Pr that will work around [the core bug](https://github.com/vegaprotocol/vega/issues/8453) that is causing this issue. Worth noting that the core bug has been fixed and we may want to wait for the next version to hit fairground.

CC @sam-keen @MadalinaRaicu
