### ISSUE TITLE
Unable to sort liquidity table because row id is undefined 

### ISSUE THREAD

**Issue by daro-maj** [vegaprotocol/frontend-monorepo#4079]
## Description

Unable to sort liquidity table because row id is undefined.

## Steps to Reproduce

1. Go to liquidity table
2. Click the sort button on status column 
4. See error - first line disappeared 

## Expected behavior

User can sort table.

## Screenshots
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/bfd60649-1dd0-4368-941e-05d03488db6b)

**Comment by pennyandrews** [comment]
May need to file a ticket with core for why we are seeing things with ID null
