### ISSUE TITLE
Cancel Iceberg Orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4097]
## Story

As a
I want
So that

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by neildawson** [comment]
Barney pointed out we shouldn't need to do anything special for this. Iceberg is not a new order type, it's an option for a standard order, so the existing close order functionality will do the trick.
