### ISSUE TITLE
Weird overlay when wallet view is open

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/frontend-monorepo#410]
This doesn't look pretty:
<img width="720" alt="Screenshot 2022-05-17 at 13 28 35" src="https://user-images.githubusercontent.com/4346460/168800961-091bfac9-a723-4d23-b456-b02aba46952b.png">

**Comment by dexturr** [comment]
@notbot00 does #429 fix this?

**Comment by notbot00** [comment]
> @notbot00 does #429 fix this?

it does, indeed, @dexturr . closing this.
