### ISSUE TITLE
Order list not ordered

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/frontend-monorepo#413]
This might be a feature, but I'd expect this list to be order from the most recent order I placed to the oldest:
<img width="1512" alt="Screenshot 2022-05-17 at 13 40 08" src="https://user-images.githubusercontent.com/4346460/168802736-68e3d438-3205-4c25-aae2-1d4608b55157.png">

**Comment by MadalinaRaicu** [comment]
https://github.com/vegaprotocol/frontend-monorepo/pull/514
