### ISSUE TITLE
Add estimated time of upgrade to the proposal details

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4146]
## Story 

As a user 
I want to understand _when_ a network upgrade is being made 
So that I can adjust my behaviour / plan ahead as needed 

## Acceptance criteria 
- [ ] On the detail view of a network upgrade proposal, there is a way to see the estimated time to upgrade i.e. **Estimated time to upgrade: 1h56m (13:00 UTC)**
- [ ] On the list (card) view of proposals there is a way to see the estimated time to upgrade i.e. **Estimated time to upgrade: 1h56m (13:00 UTC)**
- [ ] When a network upgrade proposal block number has been passed, I can see that i.e. the time to upgrade is replaced with **Estimated upgrade complete: 24 May 2023 13:00UTC)**

## Background 

Console ticket here https://github.com/vegaprotocol/frontend-monorepo/issues/3319. 

It should be reasonably straightfoward to add estimated time of proposal to these pages. 
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fb6c6f45-1ea7-4ef7-9112-d8f089be54a9)

It would need to be added as a new line after "Upgrade Block Height" 
Would be calculated as:

Time to upgrade = `(upgrade block - current block) * average block time over last 25 blocks` 
Therefore Estimated: `vegatime + time to upgrade`

Pretty sure all of these can be found on /statistics

**Comment by ckpringle** [comment]
Dependent on https://github.com/vegaprotocol/frontend-monorepo/issues/3259 and https://github.com/vegaprotocol/frontend-monorepo/issues/3319
