### ISSUE TITLE
Filter should filter out ALL governance proposals that don't match the search term

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4164]
## Description

On the proposal page, when I click filter... I can see a search bar and enter a proposal ID or proposer ID. Currently, entering a valid proposal ID _does_ filter the list of governance proposals but not the list of network upgrades, which stay on the screen. The result is it feels / looks like your search hasn't worked at all because the first "search results" bear no relevance to the ID you searched! 

This chore is to hide network upgrade proposals when searching by proposal ID or proposer ID. 

## Acceptance criteria 

- [ ] When I search by proposer ID or proposal ID, the list of results returned are only for relevant proposals that match either of those terms

## Steps to Reproduce

1. Go to 'Proposals'
2. Click on 'Filter'
3. Search for a proposal ID (go find a proposal to copy one from first)
4. See issue

## Screenshots
<img width="848" alt="Screenshot 2023-06-22 at 12 31 28" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/15752bf0-2c28-43fc-80b3-b4748b8f986c">

**Comment by pennyandrews** [comment]
Resolved by #4145 @jtsang586 if you could double check that would be amazing
