### ISSUE TITLE
Block Explorer: navigating back to transaction list loses filter

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#4237]
## Steps to Reproduce

1. Go to transaction list in Block Explorer
2. Click on 'filter' and set any filter
3. Verify that you are now shown a filtered subset of transactions and the selected filter is set
4. Click on a link on the page (e.g. a tx ID, block height, etc.) to navigate away
5. Click 'back' on the browser

## Expected behavior

Browser returns to the filtered transaction list visible in step 3 (actual: the filter is lost and all txns are shown)

## Device details

**Desktop:**

- OS: macOS
- Browser: Firefox
- Version: 114.02

## Additional context

N/A

**Comment by edd** [comment]
I'll leave this open because it's true, but this is already covered in https://github.com/vegaprotocol/frontend-monorepo/issues/4215. The underlying API change is merged so I'll be able to work on it when that is out.

**Comment by pennyandrews** [comment]
Closing as this is a dupe with the ticket Edd has reference below
