### ISSUE TITLE
Apollo Link Timeout causing enoent errors in build/runs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4258]
## Description

A new error has popped up since 

This is the same as: https://github.com/drcallaway/apollo-link-timeout/issues/62

## Steps to Reproduce

1. `rm -rf node_modules`
2. `yarn`
3. `yarn run env-cmd -f apps/explorer/.env.stagnet1 yarn nx run explorer:serve` (or similar

## Expected behavior

No build time errors

## Screenshots

<img width="1219" alt="Screenshot 2023-07-04 at 13 38 53" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/a1ad3379-5819-4fbf-a844-789d2fcf2acc">

**Comment by JonRay15** [comment]
Follow up with Edd next week.  Could it be in any way related to (or fixed by) the changes Bart made to the apollo library?
