### ISSUE TITLE
Governance AC - Warning needed when user has less than min required equity share

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4262]
## The Chore

There's been a core change where update market proposal is no longer rejected when user submits an update market proposal without the minimum required equity share.

There needs to be a warning as specified in the AC that user does not have required equity share.

> if market change: **must** be warned if the amount equity like share I have is less than the minimum required equity like share to propose a change (due to Spam protection or network params) (<a name="3002-PROP-022" href="#3002-PROP-022">3002-PROP-022</a>)
> - **should** see my equity like share in that market

**Comment by pennyandrews** [comment]
Remove Acceptance Criteria as no longer applicable based on change to core behaviour

**Comment by JonRay15** [comment]
Joe just doing now.
