### ISSUE TITLE
Re-enable BE E2E tests

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4266]
## The Chore

#4263 Disabled some tests as they were failing due to a combination of outdated types and a new NX error style. The protos will be updated when 0.72.0 is tagged, so for now we have disabled the affected tests

## Tasks

- [ ] Regenerate types
- [ ] Unskip tests

**Comment by JonRay15** [comment]
Same with this one.

**Comment by JonRay15** [comment]
Wont do
