### ISSUE TITLE
Change param used to paginate through transactions for 0.72.0

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4272]
## The Chore

Related: #4215 . In v0.72.0 the meaning of 'after' has changed and thus the existing pagination is broken. This ticket is for a quick fix to support 0.72.0 before working on #4215

## Tasks

- [ ] Work out what replaces after (first or last probably)
- [ ] Switch to that

**Comment by pennyandrews** [comment]
No longer needed as Jeremy fixing in next release
