### ISSUE TITLE
Transaction appearing twice in transactions list

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4274]
Art noticed that a transaction is showing twice in the transactions list on block explorer. 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/b9f9318c-f3ff-4cee-b635-fdc072a9d749)

He has confirmed that this is only a display bug as there is only one transaction showing on etherscan. 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/fc434ca4-5be2-4933-97e5-1532adeb41e9)

**Comment by pennyandrews** [comment]
Thinking this will be fixed when the pagination works again

**Comment by JonRay15** [comment]
Will be fixed by https://github.com/vegaprotocol/frontend-monorepo/issues/4373

Closing
