### ISSUE TITLE
Mainnet-mirror applications show stagnet1 network

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/frontend-monorepo#4288]
## Description

When you visit the `explorer.mainnet-mirror.vega.xyz` it uses stagnet1 data-node. The same is for all of the application

## Steps to Reproduce

1. Go to explorer.mainnet-mirror.vega.xyz

## Expected behavior

Mainnet mirror applications should show the mainnet mirror applications 

## Screenshots

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1239637/e5642c9e-8625-46c6-85da-4726d25edccd)

**Comment by pennyandrews** [comment]
This has been fixed by DevOps
