### ISSUE TITLE
Z-index issues

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#429]
We have some z-index issues with the hovered candle data and border on chart and the Toggle component having higher values the overlay background.

<img width="1496" alt="Screen Shot 2022-05-18 at 6 01 04 PM" src="https://user-images.githubusercontent.com/6803987/169163088-567c1019-7b7c-49e1-8ce2-25b828046f88.png">

**Comment by MadalinaRaicu** [comment]
ah, yes. I tried to handle this in my PR. https://github.com/vegaprotocol/frontend-monorepo/pull/424/files#diff-1a450fe1bce39104bcd5b2c6b764f71945dbbd98f3f5b4bb7aae39138bda92ac

**Comment by MadalinaRaicu** [comment]
or we can remove the z-index from the buttons, but I guess there was some reasoning for that being added in the first place.

**Comment by sam-keen** [comment]
Initially the selected button had a different coloured border to the non-selected option, but because the design called for them to have their borders overlap, I needed to mess with z-indexes. Though with the design as it is now we can remove z-index and position properties entirely
