### ISSUE TITLE
Simplify fee display to better display paid fees for a user

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/frontend-monorepo#4294]
## Issue

Currently the fees displayed in a fill for a user will show the paid infrastructure/liquidity fees from the total trade whether the user viewing the trade was the one who paid them (the aggressor) or not. This was previously required because it was unclear whether a trade happened as part of exiting an auction and the fees were not split between the two buckets (buyer_fee and seller_fee). It appears that the fees are now split correctly, 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/702798/d199762d-5506-4b9e-aa6b-6a4194c9f760)

so the display logic can simplify to something like:

```
infra_fee = seller_fee.infra_fee if is_seller else buyer_fee.infra_fee
liq_fee = same
maker_fee_chosen = seller_fee.maker_fee if aggressor == seller else buyer_fee.maker_fee
maker_fee = maker_fee_chosen * (-1 if role == maker else 1) 
```

This will mean that users who did not pay any fees for the trade (because they were the maker side in continuous trading) can more clearly see this and there is no risk of them thinking they paid fees when they did not.

**Comment by JonRay15** [comment]
We adjusted a bunch of thios 



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ddc63852-9d10-41b9-ad2d-854cfd8805e7)
