### ISSUE TITLE
Show new SLA parameters in market proposals

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4316]
## The Chore

The launch of liquidity SLAs will introduce new parameters to market proposals, which we need to display in Governance.

## Tasks

- [ ] Show new SLA parameters in market proposals

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/126c9445-90c3-403c-8986-65c49b9ff48d)

## Acceptance Criteria

- [ ] I can see all 5 of the new fields listed under market parameters above in the governance app on new proposals

## Additional details / background info
- [Planning thread in Slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1689162667366119)

**Comment by JonRay15** [comment]
I want to double check this is ok to close

**Comment by JonRay15** [comment]
This should be on the Governanfe App not the BE.

**Comment by JonRay15** [comment]
Confirmed with Madalina that the fields are there on the API so we just need to expose them in the governance app.

**Comment by JonRay15** [comment]
Madalina accordion probably does tis already, but we should confirm before closing

**Comment by sam-keen** [comment]
Confirmed, seen on stagnet1

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/2410498/71470ee6-a77c-4520-be2b-cdbe6918b340)
