### ISSUE TITLE
Console Chart intervals is missing important timings for trading

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4332]
## Story

Looking at the charts you can choose the following intervals:
1m
5m
15m
1H
6H
1D

We might not need all intervals and I understand why weekly or monthly are not there right now, even though they should be in the future.
## Acceptance Criteria
Would at least want the following added short term

30m
2H
4H
12H

And the following additional ones Longterm
3D, 1W, 1M

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
<img width="536" alt="Screenshot 2023-07-14 at 14 38 42" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/6ee998f4-dc07-4275-9470-ade7acf385e7">

<img width="391" alt="Screenshot 2023-07-14 at 14 45 02" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/8c866e3c-ef04-47a4-b5b6-cda220baa65e">

**Comment by mattrussell36** [comment]
Worth noting we already have this issue to support non time based intervals:

https://github.com/vegaprotocol/pennant/issues/779

**Comment by mattrussell36** [comment]
@barnabee

Barney thoughts on suggested intervals requested here? Do we want other ones too?

**Comment by pennyandrews** [comment]
Core ticket for tracking https://github.com/vegaprotocol/vega/issues/8867
