### ISSUE TITLE
Block Explorer proposals page Closing and Enactment date columns differ in date time formatting

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/frontend-monorepo#4356]
Currently the formatting for date time in Closing and Enactment columns in the Governance proposals page is different. These should probably both use the formatting from the Closing column

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/702798/f17a9ec0-8f25-4605-b6d9-b6ea7cc00217)

**Comment by edd** [comment]
https://github.com/vegaprotocol/frontend-monorepo/blob/develop/libs/proposals/src/components/proposals-list/use-column-defs.tsx#L114-L137

🤔
