### ISSUE TITLE
Orderbook pin mode: Move with mid OR pin to price

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#440]
The current implementation of the Orderbook works out a sensible place to centre the order book when it first loads (based mid, with some rules to handle auctions etc). It then stays pinned to that price. if the mid price moves suddenly out of view, the user will not see it.

This ticket to enhance the behaviour so that the view will stayed pinned to the mid price when ever it updates. Unless the user has manually scrolled the order book, if this has happened then the book stays pinned to that price. 
A button should appear in "pinned to price mode" that allows the user to re-pin the view to the mid.

**Comment by gordsport** [comment]
Closing as completed as part of:
- https://github.com/vegaprotocol/frontend-monorepo/pull/312
