### ISSUE TITLE
Governance - proposal details page no longer shows full proposal json

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4438]
This seems to be happening on all proposal types

![Screenshot 2023-07-31 at 11 15 42](https://github.com/vegaprotocol/frontend-monorepo/assets/30622993/20c647e7-b739-4ddf-bb47-1145fdbbcd66)

**Comment by JonRay15** [comment]
This is because we dont have automatic REST API switcher.

I will ticket that seperately and we can assess the criticality as part of normal prioritisation.
