### ISSUE TITLE
Console shows 'Something Went Wrong. An unknown error occurred' when browser wallet denies a connection request from console

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/frontend-monorepo#4441]
## Description

Console does not appear to handle a scenario where a user chooses to 'deny' a connection request. The below error is shown after clicking 'Deny' in the browser wallet

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/37066267/064f3cc2-0b8d-4f96-bdd6-795685b52156)

## Steps to Reproduce

1. Ensure you have a mainnet build of browser wallet, chrome was used for this scenario https://github.com/vegaprotocol/vegawallet-browser/releases/tag/v0.6.0
2. Open the mainnet wallet and complete the onboarding process, you should see the 'view wallet' screen when you are done
3. Ensure browser wallet is pinned to your toolbar for ease of access
4. Go to console (mainnet)
5. Click on 'Connect Vega Wallet', this appears multiple times in console, it does not seem to matter which 'connect' button you use.
6. Click 'Connect Web Wallet'
7. You should see a '1' appear on the browser wallet icon to indicate actions needs to be taken, open the browser wallet extension
8. 'Connect to dapp' screen should be shown. Click 'Deny' to deny the connection request
9. Observe 'Something went wrong' error is shown in console (as per screenshot in description)

## Expected behaviour
Expected to see a message stating the connection request was denied by the wallet.

## Device details

**Desktop (please complete the following information):**

- OS: Ubuntu (wsl)
- Browser chrome
- Version browser wallet 0.6.0 with mainnet console

**Comment by mattrussell36** [comment]
Pretty sure we get this error when no healthy node is found during the getChainID check.

**Comment by daro-maj** [comment]
issue is still visible:


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/4f71c050-c9c5-4375-b5f4-f48627613fb1)

**Comment by daro-maj** [comment]
works good


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/e6759495-fdd3-4482-9747-ebd6464a93e5)
