### ISSUE TITLE
Remove support for hosted wallet

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4464]
Likely closed by https://github.com/vegaprotocol/frontend-monorepo/issues/4370

## The Chore

The hosted wallet connection option is no longer required so it can be removed

## Tasks

- [ ] ACs reviewed/updated
- [ ] Dev
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C8WS7M50E/p1690892871839569

**Comment by macqbat** [comment]
done in https://github.com/vegaprotocol/frontend-monorepo/pull/4492
