### ISSUE TITLE
Fairground Governance on explorer and TFE issue "failed to get asset for ID failed"

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4473]
## Description

Cannot access governance page on the explorer
https://explorer.fairground.wtf/governance

`"Something went wrong: failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID"`

Might be related to why governance page does not load as well
https://governance.fairground.wtf/

Oracles also seems to not be working:
https://explorer.fairground.wtf/oracles
Oracle data could not be loaded

## Screenshots

<img width="1393" alt="Screenshot 2023-08-02 at 17 03 51" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/20c0e9e2-c4fd-4352-8acc-b72fa8f6e9a1">
<img width="963" alt="Screenshot 2023-08-02 at 17 06 31" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/31e112e1-3d6d-4c72-8ead-a680fa20c673">

**Comment by JonRay15** [comment]
Looks like #4364 should cover this
