### ISSUE TITLE
Use market code instead of market name in positions table 

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#4480]
## Story

As a user
I want see market code in positions table
So that market column show same value as in other places

## Acceptance Criteria

- [ ] Code is rendered for the market in the positions table

## Tasks

- [x] ACs reviewed and/or updated
- [x] Dev
- [x] Test

**Comment by mattrussell36** [comment]
I've reviewed the specs here and we don't need to make any changes
