### ISSUE TITLE
Improve "new proposal" user journey

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#4481]
### Discussed in https://github.com/vegaprotocol/feedback/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **jubiliance** August  3, 2023</sup>
Hey team,

I think from a user experience perspective and as someone who has submitted a couple of proposals now it's a bit annoying that when you click on "New Proposal" (https://token.vega.xyz/proposals) it redirected to Vega Docs/tutorials. I know this is intended, but I think I'd prefer to just be taken to a page where I can submit my proposal straightaway instead of digging through the tutorial docs.

Having a separate button or small link to tutorials underneath would be much better in my opinion, or even have this on the page where you submit the JSON proposals</div>

------------
Suggested plan of action:

- [ ] Change button text to 'New Proposal'
- [ ] Direct the 'New Proposal' button to the raw proposal screen
- [ ] On the raw proposal screen, include a 3-step process for proposals:
      1. Sense check your proposal idea on [the forum](https://community.vega.xyz/c/governance/)
      2. Use the proposal templates in [the docs] (relevant network link to the proposals index page)
      3. Submit on-chain below
- [ ] Make the links/text prominent (i.e. not gray on black)
- [ ] Remove explorer link
- [ ] Check with Emil to see if this protobuff encode / decode is of any use for validating the raw JSON

**Comment by JonRay15** [comment]
Validation options:

1. Protobuff encoder & decoder (Emil has something) 
2. Preview tab (the issue here is still that thing that the Core governance API output is different to the inbound proposal shape)

Can we explore these?  But in another ticket probably!
