### ISSUE TITLE
Fairground - Browser wallet does not support stop orders

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4489]
## Description

Browser wallet runs in to an unsupported transaction when trying to make a stop order you receive "unsupported transaction type"
## Steps to Reproduce

1. Go to console and trade
2. Choose stop order and try to trade

## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/323f9995-ceac-4c43-8d89-9e6719228fa8

**Comment by emilbayes** [comment]
Fix pending in https://github.com/vegaprotocol/vegawallet-browser/pull/472

**Comment by emilbayes** [comment]
This is fixed in `v0.6.1`
