### ISSUE TITLE
Place Order button can be spammed, easy to send multiple transactions unintentionally to wallet

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/frontend-monorepo#4514]
## Description

If I place an order via the 'Place Order' button in console, I can immediately spam it again after, it is simple to unintentionally send multiple requests to the wallet. I would have expected the place order button to potentially be disabled for some period of time? 

The 'PLACE ORDER' button stays in the state shown below after placing the shown order, I can click this repeatedly to queue any number of orders.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/37066267/8e36ba2f-c0d7-4af0-a43d-5ca29903d4f9)

## Steps to Reproduce

1. install browser wallet mainnet https://github.com/vegaprotocol/vegawallet-browser/releases/tag/v0.7.0
2. onboard using the wallet. Use the recovery phrase pinned in mainnet-debug-wallets channel on slack! This has funds allocated so place order will be enabled.
4. Go to mainnet console
4. click 'Connect Wallet'
5. approve the connection
6. place an order (USDT), then immediately place more orders
7. observe can submit multiple
8. deny the transactions in wallet.

## Expected behavior

Would have expected the button to be disabled whilst order is not approved or denied, however there may be a better way to handle this.

- OS: wsl/ubuntu
- Browser chrome
- Browser wallet version: 0.7.0

**Comment by mattrussell36** [comment]
Refinement:

- Lets disable the button whilst its being throttled
- Lets also change the text to 'Sending to wallet' whilst disable
