### ISSUE TITLE
Improve market navigation

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#456]
### Background

Currently, to change markets you need to click 'Trading' and then select from the list:

![Image](https://user-images.githubusercontent.com/1325606/169993258-1cccb0c6-e400-420c-9e15-493f0b98e92a.png)

![Image](https://user-images.githubusercontent.com/1325606/169993326-74f860d8-3c1c-4639-8ef9-925cb2a5cd7b.png)

I think we'll need something a bit more clear/intuitive before we go live.

The design we want to eventually have is to have a line of market information at the top which includes a link that opens a mega-dropdown of markets:

![Image](https://user-images.githubusercontent.com/1325606/169992743-62ba0239-e61a-4dd5-8d50-44cd891c8b27.png)

![Image](https://user-images.githubusercontent.com/1325606/169992859-c9165b18-c361-4bc6-9aa9-5bfac491c705.png)

### Proposal
I'd suggest we change the market title to use the proposed style and use it to open the [existing Markets table](https://alpha.console.vega.xyz/markets) in a modal.

![Image](https://user-images.githubusercontent.com/1325606/170057599-6b0df7a3-899d-4358-868e-ab94c38f8ec5.png)

![image](https://user-images.githubusercontent.com/1325606/170292368-36e9bfab-c9b4-494c-a100-73804a15984d.png)

The 'Trading' nav item no longer needs to go to the market list, so it would not be clickable when you are in the trading view. However, when you are on the portfolio page, clicking 'Trading' would then take you back to the trading view for the last market you had selected.

**Comment by MadalinaRaicu** [comment]
This ticket https://github.com/vegaprotocol/frontend-monorepo/issues/445 gets completely changed by this piece of work. 
I will use some unmerged logic from it, and create another branch for this ticket.
