### ISSUE TITLE
show leverage information

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#461]
In order for users to discover markets and see all market data we need to have market discovery.

- [x] Show key market data in a clear nice UX way
- [x] Panel to see additional market details (already ticketed?)

This all covered in:

- https://github.com/vegaprotocol/frontend-monorepo/issues/445

**Comment by edd** [comment]
I've edited the top comment just to make it clear that #445 covers the *body* of the ticket, but doesn't address the title of the ticket, which is what still requires some design work

**Comment by campbellssource** [comment]
To clarify I think this ticket is about adding something like this:
<img width="462" alt="Screenshot 2022-06-08 at 10 18 59" src="https://user-images.githubusercontent.com/13255539/172580779-73729dfc-920f-4e87-b230-cc637f4cc2fa.png">

Where there is a `3x` or similar next to a market that shows how much leverage you can get on a market.
it is computed by "1 over the risk factor".

**Comment by campbellssource** [comment]
☝️ This is partly based on an assumption that there may well be markets proposed with different risk models (and consequently different leverage) but for the same underlying/oracle. e.g.
BTC/USD Jan (x5)
BTC/USD Jan (x10)

**Comment by campbellssource** [comment]
The leverage amount should also be shown in the market details page

**Comment by campbellssource** [comment]
Okay. so after some checking with others. My assumption is wrong.
> Sort-of-duplicate markets:
Leverage and risk params unlikely (highly discouraged) — max reasonable leverage should be offered by the market and traders should use segregated accounts to manage it if they want to take less. We should not be including leverage in market names/descriptions IMO. Leverage should be considered configrable up to the maximum, which probably won't be a round number and may change.
Same underlying / different oracle or different but similar settlement asset (DAI vs USDC etc.) are much more likely but still somewhat discouraged where there's not a clear reason to do so. Changing the oracle or having spot markets to switch between settlement assets is generally preferable.

So there is some work to do on documenting how `name` and `code` and code are used (perhaps name contains the oracle, and the settlement is a key value to highlight / filter on. e.g.
name: "BTC/USD Jan (oracle description)" settled in BTC.
<img width="675" alt="Screenshot 2022-06-08 at 15 54 54" src="https://user-images.githubusercontent.com/13255539/172648563-7b3a9c75-8d22-4bc7-bc07-aff374f7716e.png">
