### ISSUE TITLE
Fills (all my trades / fills for specific order)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#462]
As a user of the console I would like to see all my fills, ideally this would be for all my trades AND for a specific order.

### Dependancies:

We need to check with the data-node team if data-node has a fill by party id API? (workaround could be to get all then filter out)

**Comment by gordsport** [comment]
MVP - a fills table and we can iterate over it in  he future

**Comment by PeteWilliams** [comment]
There's an initial design here which keeps it simple with just one value per cell:

https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A26466

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/1325606/174821419-cf4f66e8-9650-4e19-b28b-4facfdaf84b2.png">


And a slightly more complicated version here which does some multi-cell stuff, if any of that is possible yet…?
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1562%3A28772

**Comment by mattrussell36** [comment]
@PeteWilliams Definitely keeping it simple for now with a single value for cell. We have to also get the data side of things (including pagination) working.
