### ISSUE TITLE
Explorer: update oracle type display for perps

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4640]
source specs coming 
* settlement (future, perps)
* termination (futures)
* settlement schedule (perps)

_Originally posted by @MadalinaRaicu in https://github.com/vegaprotocol/frontend-monorepo/pull/4631#discussion_r1308433149_

**Comment by MadalinaRaicu** [comment]
I am updating this here https://github.com/vegaprotocol/frontend-monorepo/pull/4590/commits/425d77f271a1539e35912e8f90331b7bb3bbc7e8

**Comment by edd** [comment]
Thanks @MadalinaRaicu
