### ISSUE TITLE
Explorer TX view: b64 view is for a different TX than the JSON view

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4683]
## Description

https://explorer.fairground.wtf/txs/0x60770BA3D737FAAB37D8BC8AE1AE0618795FC38C2C2C6E49CE4B584ED3D69644

## Steps to Reproduce

1. Follow link above
2. Click on View Details
3. Click on Base64 selector
4. Decode the b64

## Expected behavior

It is the same as the JSON

**Comment by JonRay15** [comment]
Blocking issue 
https://github.com/vegaprotocol/vega/issues/9280

**Comment by JonRay15** [comment]
BLocking issue is fixed so this is done
