### ISSUE TITLE
If a block number in the url is in the future, fail more gracefully

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#4692]
If a block number in the url is in the future, just tell the user instead of "something went wrong". 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/db8577da-1d49-428c-89ac-5c61ffa46907)

**Comment by edd** [comment]
`useFetch` hook is obscuring the error because tendermint is correctly returning an error header and an error body. todo: improve `useFetch`
