### ISSUE TITLE
Apps do not recognise a wallet being disconnected

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#4717]
## Chore

Disconnect the user when the connection is closed in Desltop Wallet or CLI Wallet. This could be done by polling or possibly using window blur and focus events.

Note. This ticket has been edited to only concern json rpc connections

## Tasks

- [ ] ACs
- [ ] Dev
- [ ] Test

### OG bug report

From Dex:

"I think there is a bug in both console and governance that when a wallet is disconnected the apps do not realise it. This is a hark back to the desktop/cli wallet days, but IMO:

- A CLI/DW wallet should be polling some easy endpoint (version) and when the connection drops should handle a disconnected state
- A BW should (but does not yet) emit an event when a disconnect takes place (same as eth) so that when a wallet is disconnected the app can handle the disconnected state"

## Acceptance Criteria

- [ ] If Console / Governance attempt to send a transaction of any sort and they get back a 401 / 404 from CLI wallet they should treat that as being disconnected and clear any existing connections from the UI
- [ ] If Console / Governance attempt to send a transaction of any sort and they get back a disconnected status in the JSON RPC they should treat that as being disconnected and clear any existing connections from the UI.

## Additional Info 
There will be some other disconnect event stuff on a later ticket

**Comment by mattrussell36** [comment]
@dexturr how long til BW will emit a disconnect event?

**Comment by dexturr** [comment]
@matt https://github.com/vegaprotocol/vegawallet-browser/pull/466

**Comment by JonRay15** [comment]
But we need Emil to come back
