### ISSUE TITLE
Account transaction history (deposits and withdrawals)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#472]
As a user I want to see # Account transaction history (deposits and withdrawals to and from the Eth bridge ).   

In Scope for 🤠: A simple view to see that the transactions (in/out) with link to explorer (Vegascan/Etherscan?) 

As users user this it is expected we will iterate over the simple view to give a more enhanced UX, however this is out of scope for this first release.

**Comment by PeteWilliams** [comment]
The initial designs are here: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1760%3A26053

The intention is that deposits and withdrawals would go in their own tabs in the bottom part of the screen.

Deposits:
![image](https://user-images.githubusercontent.com/1325606/175965661-bb659c78-2609-46ac-be84-3e9d98b27afd.png)


Withdrawals:
![image](https://user-images.githubusercontent.com/1325606/175965694-6f039ecc-afab-421e-b8a6-6183e4e6c273.png)


They would also be included in the History tab though as this would show all transactions - though that's probably beyond the scope of this ticket.

**Comment by PeteWilliams** [comment]
Current thinking for a view of deposits/withdrawals in the History tab:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2270%3A29712

**Comment by PeteWilliams** [comment]
Latest designs here:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1562%3A27750

And I've created individual tickets here:
https://github.com/vegaprotocol/frontend-monorepo/issues/created_by/PeteWilliams

'History' as a single table has sort of gone as a concept, and we've got a separate tab for Closed positions, and a new tab for 'System transactions' (eg fees, liquidations, margin increase/decreases etc)
