### ISSUE TITLE
Asset Governance details

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#475]
See bellow

**Comment by gordsport** [comment]
@gordsport - get clarification on the asset governance APIs

**Comment by campbellssource** [comment]
Changes:
1- add a new status rule for the listing page.
Before an asset is usable on Vega it needs a transaction on the bridge contract to white list it.
This change is to add a rule to show "waiting for smart contract listing" instead of "passed" if the asset still has a status of pending.

**Comment by campbellssource** [comment]
2. The UI should give the user the data that is required to whitelist the asset on the bridge
<img width="1914" alt="Screenshot 2022-07-30 at 10 28 58" src="https://user-images.githubusercontent.com/13255539/181904396-a68a56cf-79b0-4772-8d34-d5886926be47.png">

**Comment by campbellssource** [comment]
See the the VOTE section of the Front end acceptance critea for more into. This link to WIP, check to see if latest has been merged. https://github.com/vegaprotocol/specs/blob/Add-interface-acceptance-criteria/user-interface/1004-VOTE-vote.md

**Comment by campbellssource** [comment]
Consider having a button to execute the whitelist function with connected wallet

**Comment by campbellssource** [comment]
![Image](https://user-images.githubusercontent.com/13255539/185553795-1eeddd32-4b82-4e96-a36b-380b71d32bb5.png)

**Comment by campbellssource** [comment]
blocked by: https://github.com/vegaprotocol/vega/pull/5944

**Comment by dexturr** [comment]
Splitting the whitelist functionality into its' own ticket: [1444](https://github.com/vegaprotocol/frontend-monorepo/issues/1444)
