### ISSUE TITLE
Fairground console redirects you to mainnet

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4767]
## Description

Seems to be no way to connect to console on fairground
Going to the link console.fairground.wtf/ redirects you to https://vegaprotocol.eth.limo/
And switching to mainnet in the mainnet as the video shows, takes you to mainnet again.

## Steps to Reproduce

1. Go to console.fairground.wtf/ 

## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/fea45639-dffd-4e43-867b-bc198d657b5a

**Comment by JonRay15** [comment]
This is fixed
