### ISSUE TITLE
Remove the CTA from the onboarding deposit inlay when on the deposit screen

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4771]
## The Chore

When you are in onboarding flow you click on the blue Deposit button and it opens up the deposit sidepanel for you. 

But the problem is once you're here, you still get the onboarding blue button on screen, which presents issues:

1. You now have the actual deposit button above it which will actually MAKE the deposit, so its confusing there is still the blue one
2. You might think clicking the blue one would actually now deposit but it wont ... it will just keep reloading the deposit panel, which is confusing

<img width="388" alt="Screenshot 2023-09-13 at 13 17 12" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/05f2b375-6e33-4583-8af6-43ae8c7fc13b">

Either we need to get rid of the blue deposit button completely, or maybe we could grey it out, make it unclickable, and change the text to "Complete deposit on screen" or something?

## Tasks

- [ ] Decide on exact implementation
- [ ] Build it
- [ ] Test it

**Comment by mattrussell36** [comment]
I suggest we
- Make the deposit button link to the standalone deposit page like was actually intended.
- Only show the GetStarted component on the deal ticket.
