### ISSUE TITLE
Modals stacking and dont look nice

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4774]
## The Chore

We get looks of diff size modals stacking on each other which doesnt look very clean. 

Arguably we need some Joelle magic on these to work out some uber-modal of something ... but for now I suggest we just make them all the same size so they stack neatly on top of each other?

Impacts
- Onboarding modal 
- Connection modal (changes in #4775 might make sense to do in parallel with this)
- Legal disclaimer (which is behind the onboarding modal below ... this is covered in #4772 )

## Tasks

- [x] Decide what to do .... is making the same size ok?
- [x] Do it
- [ ] Test it

## Additional details / background info
<img width="689" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7ebff5e1-0e58-4def-83eb-00abbafcfcd2">

<img width="712" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/5d454e67-e4af-4fd7-b884-7d4ae3209da6">

<img width="719" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/e208771f-f2e1-4d68-8d68-2744c817b2cd">

**Comment by macqbat** [comment]
carry it out to the main branch
