### ISSUE TITLE
Column spacing on withdrawals list is too wide

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#4778]
## Description

On the withdrawals tab the columns should be [auto] sized to show more data - the first screenshot is how the table opens on my machine and the second is more like how it ought to look.

## Acceptance Criteria 

- [ ] Check on default column spacing on a 13in screen

<img width="1596" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/a2ffddae-81d8-4305-b1a5-2bfd81f45641">

<img width="1600" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/0d7b474b-4b84-44ac-98ce-62d5465a3037">

**Comment by JonRay15** [comment]
Superseded by assets rework
