### ISSUE TITLE
Confirm that perp related fields can be viewed on governance proposals

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4789]
## The Chore

Madalina is building the accordion for this on #4428 

## Tasks

- [ ] Check in governance app that all expected fields are displayed properly
  - [ ] Settlement schedule
  - [ ] Think thats it!

**Comment by sam-keen** [comment]
4428 in progress as of 27th Sep

**Comment by sam-keen** [comment]
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/2410498/37a3400c-228c-445b-802c-c361994a372c)

Settlement schedule data seen on stagnet
