### ISSUE TITLE
No accounts message shown on collateral

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#4810]
## Description

A no accounts message is shown on the Collateral ag grid even if you have assets available.

## Steps to Reproduce

1. Go to mainnet
2. Connect wallet
3. Select Collateral

## Expected behavior

No accounts should not be displayed

## Screenshots

<img width="1170" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/2bba5f30-d922-4240-8c22-f8be6f5b0566">

**Comment by mattrussell36** [comment]
Closing as dupe of #4794
