### ISSUE TITLE
Unable to resize columns in Open and Proposed markets

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#4811]
## Description

- [ ] I am unable to resize columns for Open and proposed markets.. This may also be affecting other columns using ag grid.

## Steps to Reproduce

1. Go to mainnet
2. Click on markets
3. Try to resize column

## Expected behavior
I should be able to resize

## Screenshots

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/d33245eb-fd05-4e12-8ceb-2c1857fd5aef)

**Comment by mattrussell36** [comment]
This is very likely a unemoised/mutable default col def
