### ISSUE TITLE
Correct the red candle colour on the volume study

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4823]
## The Chore

For some reason the red candle on the volume chart is a darker and less visible red than the price and MACD one, this should presumably be the same ... the current dark one isnt very visible.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f8ca2472-e841-49de-82c5-37e7c614c339)

## Tasks

- [x] Change the colour to match the other charts
- [x] Test it

**Comment by mattrussell36** [comment]
@JonRay15 @barnabee @MM0819 are we all on board that we want the red/green of the volume bars to match the candles? They used to match but then we decided to reduce the contrast to give prominence to the candles. Has this already been discussed and agreed?

**Comment by barnabee** [comment]
@mattrussell36 I don't mind much if they match or not but red volume bars are nearly invisible so they definitely need to be brighter. Possible Jöelle might be able to advise, if you don't feel able to take a decision on the right solution.

**Comment by JonRay15** [comment]
Fixed by https://github.com/vegaprotocol/frontend-monorepo/pull/4881
