### ISSUE TITLE
Layout breaks when allotment stops responding

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4826]
## Description

In certain occasions the Allotment component breaks. It becomes unresponsive to clicking and dragging panes to resize and it also stops responding to changes in size of the parent container.

## Steps to Reproduce

Its hard to reproduce. TBD.

## Expected behavior

- Resizing panes within the grid should always work
- Resizing the browser window should resize the Allotment panes
- Opening/closing the sidebar should resize the Allotment panes

## Screenshots

Sidebar closed.. Allotment not growing to take space
![image (1)](https://github.com/vegaprotocol/frontend-monorepo/assets/6803987/fc44cce4-0c9a-4f2c-b309-c54ad0fb12a8)

## Device details

All

## Additional context

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1695151966865259

**Comment by bwallacee** [comment]
@mattrussell36 I view console as 0ac70c4ccc7f961614fe49b93e639ddf916269b7dcf8391db264cefeadf5a6b7
then all i do is pull the positions grid up and the entire of console freezes. I am using Firefox v118.0.

this is on mainnet

**Comment by JonRay15** [comment]
This is the one Barney pointed out yday ... it impacts Firefox on Mac only

**Comment by JonRay15** [comment]
Needs to be picked up by someone on a Mac.

**Comment by bwallacee** [comment]
Just re tested on fairground and it's definitely still an issue.
