### ISSUE TITLE
Make close position us max possible size

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4834]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] Confirm max possible size with core
- [ ] Use that for the close position transaction (rather than open volume) so that there is no chance of fills happening whilst the tx is going through

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1695104903200239

**Comment by bwallacee** [comment]
Is there any reason that this max size could change?
if so, what would be the issue if the max size of core was reduced and we have higher in console?
