### ISSUE TITLE
Explorer oracle view JSON loads a ton of data for a perps oracle

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#4849]
Clicking on "JSON" on https://explorer.fairground.wtf/oracles/ff2f717886dcb856238c4d0035a0bc39770a36ab2a975dcf9053796c5c67b38f 

loads a lot of data (after using 100% cpu for about 20s and freezing the page). 

It would be nice to 
1, maybe load just the latest 10 values with an option to load more
2, actualy print and format the latest 10 values with a timestamp above the JSON button...

**Comment by edd** [comment]
Covered now. There's still a big pile of JSON in the code section, but now the data is better formatted above.
