### ISSUE TITLE
Closing all my positions on a market with browser wallet not working

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4851]
## Description
Trying to close all positions on the perps market using browserwallet and the X down by the position in console results in the wallet getting stuck in an error.

`"TypeError: r is not iterable\n    at batchMarketInstructions (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:56:1960089)\n    at jo (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:10:62863)\n    at jl (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:10:119685)\n    at kc (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:10:108841)\n    at yc (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:10:108769)\n    at bc (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:10:108632)\n    at ic (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:10:103768)\n    at w (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:1:9694)\n    at MessagePort.R (chrome-extension://nmmjkiafpmphlikhefgjbblebfgclikn/popup.js:1:10226)"`

## Steps to Reproduce

1. Go to https://vegafairground.eth.limo/#/markets/c467ebc497abb1eb546f6ed77f2d82ab5ae05fb26bfa3c1d611d782b1adada29
2. open a postion
3. click on the X in open position in console to try to close

**Comment by JonRay15** [comment]
This def works
