### ISSUE TITLE
Explorer - Show liquidity SLA parameters 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4868]
## The Chore

In Core version `v0.73.0` new market proposals now contain new liquidity SLA parameters which are currently not displayed in the market page in block explorer

Example of SLA parameter:
`"liquiditySlaParameters": {
          "priceRange": "0.95",
          "commitmentMinTimeFraction": "0.5",
          "performanceHysteresisEpochs": 2,
          "slaCompetitionFactor": "0.75"
        }`

Accordion has been updated by @MadalinaRaicu to display these.

These need to be added to here.

https://explorer.fairground.wtf/markets/c467ebc497abb1eb546f6ed77f2d82ab5ae05fb26bfa3c1d611d782b1adada29

**Comment by MadalinaRaicu** [comment]
@jtsang586 @JonRay15 

These should be added in the explorer market details as well. 
The reason why these are not visible in fairground it is because we haven't released the version that has them yet

**Comment by edd** [comment]
It's now released and as @MadalinaRaicu said, displayss fine
