### ISSUE TITLE
Explorer - Recurrence of "failed to get asset for ID failed" bug

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4871]
## Description
There's a recurrence of an existing bug where the proposal page is returning an error.
Linked to: https://github.com/vegaprotocol/frontend-monorepo/issues/4473

On Fairground
> Something went wrong: unsupported proposal terms changes failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID failed to get asset for ID

On Stagnet1:

> Something went wrong: unsupported proposal terms changes

**Comment by edd** [comment]
Can't currently reproduce
