### ISSUE TITLE
Stats page after applying a code

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4890]
As a user 
I want to see the stats for the referral set I joined 
So that I know what discounts I a receiving

## Acceptance Criteria 

- [x] I can see the current tier I'm in 
- [x] I can see the discount I am receiving
- [x] I can see my referral code and can easily copy / share it
- [x] I can see the combined volume of teh set 
- [x] I can see how much more volume we need to reach the next tier
- [x] I can see how many epochs I have been in the set
- [x] I can see how many more epochs I need to move up to the next tier
- [x] I can see the normal headline tiers and how it works sections from the homepage

## Sketches

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b0b625cf-0864-4eb1-93f2-d3e9cb59fec0)

**Comment by asiaznik** [comment]
Yes, it should
