### ISSUE TITLE
Live preview of referral set you're joining

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4893]
As a user who is applying a code
I want to see the benefits of the code I'm applying
So that I can understand this BEFORE I make the immutable transaction to join that code. 

## Acceptance Criteria 

- [x] I can see a preview of the details of the set I am joining when I type the code into the "APPLY" section 
- [x] This could be via a two click process, or we could respond to text being typed
- [x] I can see all the info from the referee stats page appear below
- [x] Once I finish applying the code I see  "CODE APPLIED"
- [x] Aferwards that disappears and we are left simply with the new stats page

## Sketch

Suggestion here is we simply preview the info that we will already have on the referee stats page as below

<img width="542" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d6856c28-05da-4907-bcca-08d7f9364544">

**Comment by bwallacee** [comment]
@asiaznik @JonRay15 
For the preview is showing your referral code "worth it" as we have already entered it in the box.
Also the same as elsewhere, should this be "your referral code" When it was someone else's.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/ecb304cd-9793-43fe-8fa2-1f31a5429a78)

**Comment by JonRay15** [comment]
I think its fine
