### ISSUE TITLE
Investigate the weird governance site hanging bug

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4896]
## Description

There is a weird bug where wen you try to load the governance app you just get the loading symbol at the top of the page for ages.  

You can fix it by clearing your local storage. 

@mattrussell36 suggested this might be to do with infura rate limiting, but not sure. 

## Steps to Reproduce

1. Go to governance site 
2. It might hang - NO CLUE how reproduce it specfically

## Expected behavior

it shouldnt hang

## Device details

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Comment by JonRay15** [comment]
Joe has seen this when moving from stagnet to testnet too.

Sam suspects it may be linked to wallet connections being kept in local storage somehow.

**Comment by sam-keen** [comment]
I couldn't replicate this consistently. It may be being seen during issues with the networks. I'll keep this ticket around and if we get any more info on when/why it's happening we'll take another shot at it.

**Comment by edd** [comment]
Closing this, as the PR that targeted has failing tests that suggest a problem, and the issue can't reliably be recreated.
