### ISSUE TITLE
Unit separator display discrepancy

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#4909]
## Description

This was reported by a community member in a different locale, this is likely a formatting issue arising from that. It appears the same value can be displayed with different thousand unit separators. See screenshot.

## Expected behavior

Consistent use of units separators, based on user's locale settings.

## Screenshots

![f8680bd7-af19-4e72-9978-cd07ea4024ac-1](https://github.com/vegaprotocol/frontend-monorepo/assets/2410498/a55d3433-f59a-474c-9e07-af4e98eda573)

## Device details

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version unknown

## Additional context

A similar display issue was recently reported for the Governance app. The 'toNumberParts' function was augmented to return the correct separator, which might come in handy here as well. https://github.com/vegaprotocol/frontend-monorepo/pull/4678/files

**Comment by JonRay15** [comment]
Checked on mainnet and working
