### ISSUE TITLE
Liquidity providers view

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#491]
design from console
![Image](https://user-images.githubusercontent.com/13255539/174765226-adc4161a-f331-4afc-8f56-3a5937d09faf.png)
- [ ] check if all columns are needed
- [ ] check for other feedback from team/users
- [ ] find a place to put it in Console V2
- [ ] Liquidity data that applies to the whole market (not specific provisions)
- [ ] Consider including the market.account.liquidity balances which is the sum of fees to be distributed in the next liquidity epoch 

See https://github.com/vegaprotocol/frontend-monorepo/issues/625 as there is some liquidity info that was left out of the market info panel. e..g liquidity monitoring target stake etc.
<img width="591" alt="Screenshot 2022-06-23 at 10 25 15" src="https://user-images.githubusercontent.com/13255539/175265729-ed48cc30-1ee0-4c3b-9de1-7b16689135cf.png">
if these don't go into this ticket, please raise another.

**Comment by PeteWilliams** [comment]
Initial designs here: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2794%3A43617

Proposal is to show market-level liquidity in the market info panel:
![Image](https://user-images.githubusercontent.com/1325606/183942190-a8593ef4-196d-489c-bcb9-465123f6f44d.png)

The link will then open up a modal showing liquidity detail at a provider level:
![Image](https://user-images.githubusercontent.com/1325606/183952412-c8f8930d-8df1-490f-882b-de6ec8815bf2.png)

There is also an MVP version which only shows the liquidity provider data without the market spec and 'my provision' sections. To be discussed how much more work is involved and what's sensible for the first iteration. 


When a market is in a liquidity auction, we should also have a link in the market status tooltip which opens the modal:
![Image](https://user-images.githubusercontent.com/1325606/183944067-9950a189-4e93-404a-8392-2888ab82cd71.png)


I do have some outstanding questions which I'm hoping to speak to David about when he's back from holiday, but this should be enough to make a start.
* What is Average entry valuation and how it is used?
* How are obligation/supplied used at this point?
* Is seeing inactive markets useful at this point?

I think tooltips may be required to explain some of the column headings, but think @candida-d would be better placed to do that.

**Comment by campbellssource** [comment]
Have asked on slack about whether best "Static" bids and asks should be shown in here too, I think they are useful to liquidity providers. there may be other market data, but I wouldn't let that block this.
