### ISSUE TITLE
Token - Withdrawal stuck on Preparing when rejecting transaction

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#492]
Currently it looks like there isn't an appropriate state in Token for when the user rejects a transaction from the Vega wallet.

Steps to reproduce:

1. Have some tokens staked
2. Go to withdrawal and try to withdraw rewards
3. Transaction prompts confirmation from Vega wallet
4. Reject transaction
5. Go back to rewards page and withdrawal is stuck on Preparing

Expected behaviour:
When user rejects transaction the token page should prompt that transaction was rejected and allow user to try to make another withdrawal.

**Comment by dexturr** [comment]
Closing as can no longer replicate, behaviour appears correct
