### ISSUE TITLE
Not able to pay fee's to close position

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#4934]
## Description

Have a large position open on perps market, 95%+ of your settlement asset used.
In the example it was a perps market and 5 USD was available for fee's of a postion of 3900 USDT notional value.

## Steps to Reproduce

1. Go to 'perps market , https://vegafairground.eth.limo/#/markets/2fb61fb4a0ab63c7644d523efbd61b5236d90c7877b5b749c98f22988bac61ee
2. Open a large position which makes it so you have very little free capital left
3. Wait for a funding to happen
4. Try to close position
5. Deposit a lot of funds and try to close again

## Expected behavior

Should be able to close the position but is not due to not having enough to pay the fee's.

See example
https://explorer.fairground.wtf/txs/AEEE3017688B9E81853064BB0CE2A4A538310E141E8A763C7C54354C3EE70C6E

## Screenshots

<img width="341" alt="Screenshot 2023-09-29 at 07 04 28" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/66d37842-ecb1-4019-b113-e164dc1d894e">
<img width="1654" alt="Screenshot 2023-09-29 at 07 04 18" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/9b46a157-7c34-4056-98c4-fffbdd1531f1">
<img width="1347" alt="Screenshot 2023-09-29 at 07 03 55" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/2bf039b5-f766-446d-8e31-3a96f17e1e36">
<img width="1343" alt="Screenshot 2023-09-29 at 07 03 32" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/2cd7a5f2-ca14-4acd-b3a0-4a80b459523c">
<img width="1351" alt="Screenshot 2023-09-29 at 07 12 04" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/46fc9f47-ef7d-4d77-bfa4-219e16faf7ae">

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/61959fc2-4b8d-4cdb-a8a1-0d2658e4f8ea

**Comment by JonRay15** [comment]
This is core working as designed .... and certainly not a Console bug.  Closing.
