### ISSUE TITLE
Can't view settled market

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#4947]
## Description

Should be able to open a settled or otherwise closed market in the trading tab in Console

## Steps to Reproduce

1. Markets tab
2. Click on 'Closed markets"
3. Select a closed market (try clicking market name, etc.)
4. Nothing happens

## Expected behavior

Market should open in markets tab, should show price history etc. and should be able to see market info but deal ticket should be disabled (though visible if it was previously visible in the markets tab).

## Device details

Desktop:

- OS: macOS
- Browser: Firefox Developer Edition
- Version: 118.0b9

**Comment by macqbat** [comment]
I was needed to add some long path to route displaying closed market. Here https://github.com/vegaprotocol/frontend-monorepo/issues/4961 is a proposal of refactoring a little bit navigation in console, for avoid such not nice looking path.

**Comment by JonRay15** [comment]
Looks good .... and cannot access deal ticket


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/81f82f87-984b-4b6f-8e04-3eec676c0910)

**Comment by barnabee** [comment]
If you switch back to another market does it get stuck on the info panel or return to the deal ticket if that was open previously?
