### ISSUE TITLE
Governance transfers - Source can be empty

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4999]
## Description
Governance transfer proposals can have empty `source` for transfer if the source is from the network treasury. 
The current UI as seen in the screenshot shows the transfer to as blank. 

If the source is empty and from the network treasury then the UI should show transfer One off transfer from `Network treasury` to 69464e…dc6f

![Screenshot 2023-10-09 at 09 47 05](https://github.com/vegaprotocol/frontend-monorepo/assets/30622993/26e3fd39-08ea-47a8-ad42-5e757f6827a9)

**Comment by JonRay15** [comment]
We should have one network treasury account for every asset in the system. 

So we should be able to identify that hopefully
