### ISSUE TITLE
Bug Report: Market display spacing is too big

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5019]
### Discussed in https://github.com/vegaprotocol/feedback/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **Osthumus** September 13, 2023</sup>
### Problem encountered

 -When opening markets cannot see the asset.

- There is lot of gaps between rows so cannot see all the components. Would be nice if the space between is decreased and everything can fit in the screen. 

Both the rows and columns have too much empty space. Maybe space between columns is just too much which is unnecessary. It could be reduced so that all columns could be displayed. (I am using a 13" laptop. Maybe the console could identify the screen size and rearrange the column space accordingly instead of having fixed column spaces for all screen sizes.)

![Screenshot 2023-09-13 203121](https://github.com/vegaprotocol/feedback/assets/122043524/46eb1ad8-d3d7-4c24-9747-94807f0b9f58)

### Observed behaviour

 -When opening markets cannot see the asset.

### Expected behaviour

can see all the assets

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. Observe the error
...
```

### Network affected

Mainnet

### System information

Windows 11/ Firefox

### Screenshots and videos

_No response_</div>

**Comment by JonRay15** [comment]
I am marking this as priority 2 because I think at minimum optimising the column spacing for a 13in monitor is something that could and should be fixed before the October release.  Less concerned about rows as not sure it can be improved too much (or needs to be).

**Comment by mattrussell36** [comment]
We've agreed to not work on this because we have lots of potential changes incoming for this page

**Comment by MadalinaRaicu** [comment]
Until we get those changes prioritized we can use the autosize within onGridReady data grid event. 
As we do in the other data grids.
Addressing this here together with other snags, such as moving the "settlement asset" column. 
https://github.com/vegaprotocol/frontend-monorepo/pull/5324
