### ISSUE TITLE
Ensure market LP view can handle Core API changes to liquidity provision status

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5031]
## The Chore

Core changes on this ticket might require minor changes to cover off. 

https://github.com/vegaprotocol/vega/issues/9757

## Tasks

- [ ] Review the Core implementation
- [ ] Make changes
- [ ] Test it

**Comment by JonRay15** [comment]
The core changes for this are in flight currently so I expect we'll get them on staging in the next day or so .... therefore we should respond to this.

**Comment by MadalinaRaicu** [comment]
https://github.com/vegaprotocol/vega/pull/9810
