### ISSUE TITLE
Error when executing grapql queries received from frontend

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/frontend-monorepo#5040]
## Description

The system tests download and execute all of the graphql queries generated by frontend.
As part of that test , there are 2 graphql queries failing to execute.

Jenkins Failure:

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/62/testReport/junit/tests.rewards/trading_rewards_test/Call_tests___full_o_r___test_graphql_queries/

Failing Query1:

`fragment UpdateVolumeDiscountProgram on Proposal { terms { change { ... on UpdateVolumeDiscountProgram { benefitTiers { minimumRunningNotionalTakerVolume volumeDiscountFactor } endOfProgramTimestamp windowLength } } }}  fragment UpdateReferralProgram on Proposal { terms { change { ... on UpdateReferralProgram { changes { benefitTiers { minimumEpochs minimumRunningNotionalTakerVolume referralDiscountFactor referralRewardFactor } endOfProgramTimestamp windowLength stakingTiers { minimumStakedTokens referralRewardMultiplier } } } } }}  fragment UpdateMarketState on Proposal { terms { change { ... on UpdateMarketState { updateType market { decimalPlaces id tradableInstrument { instrument { product { __typename ... on Future { quoteName } ... on Perpetual { quoteName } } name code } } } updateType price } } }}  fragment NewMarketProductField on Proposal { terms { change { ... on NewMarket { instrument { product { __typename } } } } }}  query Proposal($proposalId: ID!, $includeNewMarketProductField: Boolean!, $includeUpdateMarketState: Boolean!, $includeUpdateReferralProgram: Boolean!, $includeUpdateVolumeDiscountProgram: Boolean!) { proposal(id: $proposalId) { id rationale { title description } reference state datetime rejectionReason party { id } errorDetails ...NewMarketProductField @include(if: $includeNewMarketProductField) ...UpdateMarketState @include(if: $includeUpdateMarketState) ...UpdateReferralProgram @include(if: $includeUpdateReferralProgram) ...UpdateVolumeDiscountProgram @include(if: $includeUpdateVolumeDiscountProgram) terms { closingDatetime enactmentDatetime change { ... on NewMarket { decimalPlaces metadata riskParameters { ... on LogNormalRiskModel { riskAversionParameter tau params { mu r sigma } } ... on SimpleRiskModel { params { factorLong factorShort } } } instrument { name code futureProduct { settlementAsset { id name symbol decimals quantum } quoteName dataSourceSpecForSettlementData { sourceType { ... on DataSourceDefinitionInternal { sourceType { ... on DataSourceSpecConfigurationTime { conditions { operator value } } } } ... on DataSourceDefinitionExternal { sourceType { ... on DataSourceSpecConfiguration { signers { signer { ... on PubKey { key } ... on ETHAddress { address } } } filters { key { name type } conditions { operator value } } } } } } } dataSourceSpecBinding { settlementDataProperty tradingTerminationProperty } } } priceMonitoringParameters { triggers { horizonSecs probability auctionExtensionSecs } } liquidityMonitoringParameters { triggeringRatio targetStakeParameters { timeWindow scalingFactor } } positionDecimalPlaces linearSlippageFactor quadraticSlippageFactor } ... on UpdateMarket { marketId updateMarketConfiguration { instrument { code product { ... on UpdateFutureProduct { quoteName dataSourceSpecForSettlementData { sourceType { ... on DataSourceDefinitionInternal { sourceType { ... on DataSourceSpecConfigurationTime { conditions { operator value } } } } ... on DataSourceDefinitionExternal { sourceType { ... on DataSourceSpecConfiguration { signers { signer { ... on PubKey { key } ... on ETHAddress { address } } } filters { key { name type } conditions { operator value } } } } } } } dataSourceSpecBinding { settlementDataProperty tradingTerminationProperty } } ... on UpdatePerpetualProduct { quoteName dataSourceSpecForSettlementData { sourceType { ... on DataSourceDefinitionInternal { sourceType { ... on DataSourceSpecConfigurationTime { conditions { operator value } } } } ... on DataSourceDefinitionExternal { sourceType { ... on DataSourceSpecConfiguration { signers { signer { ... on PubKey { key } ... on ETHAddress { address } } } filters { key { name type } conditions { operator value } } } } } } } dataSourceSpecBinding { settlementDataProperty settlementScheduleProperty } } } } metadata priceMonitoringParameters { triggers { horizonSecs probability auctionExtensionSecs } } liquidityMonitoringParameters { triggeringRatio targetStakeParameters { timeWindow scalingFactor } } riskParameters { ... on UpdateMarketSimpleRiskModel { simple { factorLong factorShort } } ... on UpdateMarketLogNormalRiskModel { logNormal { riskAversionParameter tau params { r sigma mu } } } } } } ... on NewAsset { name symbol decimals quantum source { ... on BuiltinAsset { maxFaucetAmountMint } ... on ERC20 { contractAddress lifetimeLimit withdrawThreshold } } } ... on UpdateNetworkParameter { networkParameter { key value } } ... on UpdateAsset { quantum assetId source { ... on UpdateERC20 { lifetimeLimit withdrawThreshold } } } } } votes { yes { totalTokens totalNumber totalEquityLikeShareWeight } no { totalTokens totalNumber totalEquityLikeShareWeight } } }}`

Failing Query2:

`fragment UpdateVolumeDiscountPrograms on Proposal { terms { change { ... on UpdateVolumeDiscountProgram { benefitTiers { minimumRunningNotionalTakerVolume volumeDiscountFactor } endOfProgramTimestamp windowLength } } }}  fragment UpdateReferralPrograms on Proposal { terms { change { ... on UpdateReferralProgram { changes { benefitTiers { minimumEpochs minimumRunningNotionalTakerVolume referralDiscountFactor referralRewardFactor } endOfProgramTimestamp windowLength stakingTiers { minimumStakedTokens referralRewardMultiplier } } } } }}  fragment UpdateMarketStates on Proposal { terms { change { ... on UpdateMarketState { updateType market { decimalPlaces id tradableInstrument { instrument { product { __typename ... on Future { quoteName } ... on Perpetual { quoteName } } name code } } } updateType price } } }}  fragment NewMarketProductFields on Proposal { terms { change { ... on NewMarket { instrument { product { __typename } } } } }}  fragment ProposalFields on Proposal { id rationale { title description } reference state datetime rejectionReason party { id } errorDetails terms { closingDatetime enactmentDatetime change { ... on NewMarket { instrument { name code futureProduct { settlementAsset { symbol } } } } ... on UpdateMarket { marketId } ... on NewAsset { __typename name symbol decimals quantum source { ... on BuiltinAsset { maxFaucetAmountMint } ... on ERC20 { contractAddress withdrawThreshold lifetimeLimit } } } ... on UpdateNetworkParameter { networkParameter { key value } } ... on UpdateAsset { quantum assetId source { ... on UpdateERC20 { lifetimeLimit withdrawThreshold } } } } } votes { yes { totalTokens totalNumber totalEquityLikeShareWeight } no { totalTokens totalNumber totalEquityLikeShareWeight } }}  query Proposals($includeNewMarketProductFields: Boolean!, $includeUpdateMarketStates: Boolean!, $includeUpdateReferralPrograms: Boolean!, $includeUpdateVolumeDiscountPrograms: Boolean!) { proposalsConnection { edges { node { ...ProposalFields ...NewMarketProductFields @include(if: $includeNewMarketProductFields) ...UpdateMarketStates @include(if: $includeUpdateMarketStates) ...UpdateReferralPrograms @include(if: $includeUpdateReferralPrograms) ...UpdateVolumeDiscountPrograms @include(if: $includeUpdateVolumeDiscountPrograms) } } }}`

Both these queries , seem to have an error here where the element **changes** does not exist.

`... on UpdateReferralProgram { changes {`

Correcting the above mistake locally , I can run the first query BUT the second query I can't get it to execute.

## Steps to Reproduce

Run the below system test on Jenkins

System Test Name - test_graphql_queries
System Test Branch - develop

## Expected behavior

No errors.

## Screenshots

NA

## Additional context

Jenkins Run:

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/62/testReport/junit/tests.rewards/trading_rewards_test/Call_tests___full_o_r___test_graphql_queries/

**Comment by edd** [comment]
The cause of this is: https://github.com/vegaprotocol/vega/pull/9719. I can't see a governance PR to reflect this

**Comment by MuthuVega** [comment]
Thanks @edd - BUT no matter what I can't get the second query to work locally after making the necessary modifications.

**Comment by MuthuVega** [comment]
Working Query1 after modifications:

Had to remove the element `changes` and `endOfProgramTimestamp` under `... on UpdateReferralProgram`


`fragment UpdateVolumeDiscountProgram on Proposal { terms { change { ... on UpdateVolumeDiscountProgram { benefitTiers { minimumRunningNotionalTakerVolume volumeDiscountFactor } endOfProgramTimestamp windowLength } } }}  fragment UpdateReferralProgram on Proposal { terms { change { ... on UpdateReferralProgram { benefitTiers { minimumEpochs minimumRunningNotionalTakerVolume referralDiscountFactor referralRewardFactor } windowLength stakingTiers { minimumStakedTokens referralRewardMultiplier } } } } }  fragment UpdateMarketState on Proposal { terms { change { ... on UpdateMarketState { updateType market { decimalPlaces id tradableInstrument { instrument { product { __typename ... on Future { quoteName } ... on Perpetual { quoteName } } name code } } } updateType price } } }}  fragment NewMarketProductField on Proposal { terms { change { ... on NewMarket { instrument { product { __typename } } } } }}  query Proposal($proposalId: ID!, $includeNewMarketProductField: Boolean!, $includeUpdateMarketState: Boolean!, $includeUpdateReferralProgram: Boolean!, $includeUpdateVolumeDiscountProgram: Boolean!) { proposal(id: $proposalId) { id rationale { title description } reference state datetime rejectionReason party { id } errorDetails ...NewMarketProductField @include(if: $includeNewMarketProductField) ...UpdateMarketState @include(if: $includeUpdateMarketState) ...UpdateReferralProgram @include(if: $includeUpdateReferralProgram) ...UpdateVolumeDiscountProgram @include(if: $includeUpdateVolumeDiscountProgram) terms { closingDatetime enactmentDatetime change { ... on NewMarket { decimalPlaces metadata riskParameters { ... on LogNormalRiskModel { riskAversionParameter tau params { mu r sigma } } ... on SimpleRiskModel { params { factorLong factorShort } } } instrument { name code futureProduct { settlementAsset { id name symbol decimals quantum } quoteName dataSourceSpecForSettlementData { sourceType { ... on DataSourceDefinitionInternal { sourceType { ... on DataSourceSpecConfigurationTime { conditions { operator value } } } } ... on DataSourceDefinitionExternal { sourceType { ... on DataSourceSpecConfiguration { signers { signer { ... on PubKey { key } ... on ETHAddress { address } } } filters { key { name type } conditions { operator value } } } } } } } dataSourceSpecBinding { settlementDataProperty tradingTerminationProperty } } } priceMonitoringParameters { triggers { horizonSecs probability auctionExtensionSecs } } liquidityMonitoringParameters { triggeringRatio targetStakeParameters { timeWindow scalingFactor } } positionDecimalPlaces linearSlippageFactor quadraticSlippageFactor } ... on UpdateMarket { marketId updateMarketConfiguration { instrument { code product { ... on UpdateFutureProduct { quoteName dataSourceSpecForSettlementData { sourceType { ... on DataSourceDefinitionInternal { sourceType { ... on DataSourceSpecConfigurationTime { conditions { operator value } } } } ... on DataSourceDefinitionExternal { sourceType { ... on DataSourceSpecConfiguration { signers { signer { ... on PubKey { key } ... on ETHAddress { address } } } filters { key { name type } conditions { operator value } } } } } } } dataSourceSpecBinding { settlementDataProperty tradingTerminationProperty } } ... on UpdatePerpetualProduct { quoteName dataSourceSpecForSettlementData { sourceType { ... on DataSourceDefinitionInternal { sourceType { ... on DataSourceSpecConfigurationTime { conditions { operator value } } } } ... on DataSourceDefinitionExternal { sourceType { ... on DataSourceSpecConfiguration { signers { signer { ... on PubKey { key } ... on ETHAddress { address } } } filters { key { name type } conditions { operator value } } } } } } } dataSourceSpecBinding { settlementDataProperty settlementScheduleProperty } } } } metadata priceMonitoringParameters { triggers { horizonSecs probability auctionExtensionSecs } } liquidityMonitoringParameters { triggeringRatio targetStakeParameters { timeWindow scalingFactor } } riskParameters { ... on UpdateMarketSimpleRiskModel { simple { factorLong factorShort } } ... on UpdateMarketLogNormalRiskModel { logNormal { riskAversionParameter tau params { r sigma mu } } } } } } ... on NewAsset { name symbol decimals quantum source { ... on BuiltinAsset { maxFaucetAmountMint } ... on ERC20 { contractAddress lifetimeLimit withdrawThreshold } } } ... on UpdateNetworkParameter { networkParameter { key value } } ... on UpdateAsset { quantum assetId source { ... on UpdateERC20 { lifetimeLimit withdrawThreshold } } } } } votes { yes { totalTokens totalNumber totalEquityLikeShareWeight } no { totalTokens totalNumber totalEquityLikeShareWeight } } }}`

**Comment by MuthuVega** [comment]
Second query with exactly the same modifications BUY no joy.

`fragment UpdateVolumeDiscountPrograms on Proposal { terms { change { ... on UpdateVolumeDiscountProgram { benefitTiers { minimumRunningNotionalTakerVolume volumeDiscountFactor } endOfProgramTimestamp windowLength } } }}  fragment UpdateReferralPrograms on Proposal { terms { change { ... on UpdateReferralProgram { benefitTiers { minimumEpochs minimumRunningNotionalTakerVolume referralDiscountFactor referralRewardFactor } windowLength stakingTiers { minimumStakedTokens referralRewardMultiplier } } } } }  fragment UpdateMarketStates on Proposal { terms { change { ... on UpdateMarketState { updateType market { decimalPlaces id tradableInstrument { instrument { product { __typename ... on Future { quoteName } ... on Perpetual { quoteName } } name code } } } updateType price } } }}  fragment NewMarketProductFields on Proposal { terms { change { ... on NewMarket { instrument { product { __typename } } } } }}  fragment ProposalFields on Proposal { id rationale { title description } reference state datetime rejectionReason party { id } errorDetails terms { closingDatetime enactmentDatetime change { ... on NewMarket { instrument { name code futureProduct { settlementAsset { symbol } } } } ... on UpdateMarket { marketId } ... on NewAsset { __typename name symbol decimals quantum source { ... on BuiltinAsset { maxFaucetAmountMint } ... on ERC20 { contractAddress withdrawThreshold lifetimeLimit } } } ... on UpdateNetworkParameter { networkParameter { key value } } ... on UpdateAsset { quantum assetId source { ... on UpdateERC20 { lifetimeLimit withdrawThreshold } } } } } votes { yes { totalTokens totalNumber totalEquityLikeShareWeight } no { totalTokens totalNumber totalEquityLikeShareWeight } }}  query Proposals($includeNewMarketProductFields: Boolean!, $includeUpdateMarketStates: Boolean!, $includeUpdateReferralPrograms: Boolean!, $includeUpdateVolumeDiscountPrograms: Boolean!) { proposalsConnection { edges { node { ...ProposalFields ...NewMarketProductFields @include(if: $includeNewMarketProductFields) ...UpdateMarketStates @include(if: $includeUpdateMarketStates) ...UpdateReferralPrograms @include(if: $includeUpdateReferralPrograms) ...UpdateVolumeDiscountPrograms @include(if: $includeUpdateVolumeDiscountPrograms) } } }}`

**Comment by edd** [comment]
This approach will not work. The front end code relies on the fields that you are removing in this query. The actual change is more like this:

[unnest-changes.patch](https://github.com/vegaprotocol/frontend-monorepo/files/12895010/unnest-changes.patch)

However then you will hit a generation problem caused by the GraphQL schema (https://github.com/vegaprotocol/vega/issues/9784) and if you then work around that you might hit a front end testing bug (https://github.com/vegaprotocol/vega/issues/9784) and give up for the day
