### ISSUE TITLE
Size should be in units of `quoteAsset` not using tags and metadata

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#5048]
## Description

Currently the units on the deal ticket for the size component use metadata tags. This should be using quoteAsset field from the market.

## Acceptance Criteria

- [ ] Size on the deal ticket shoudl be in units of quoteAsset

## Additional information

https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1697447640371409

**Comment by MadalinaRaicu** [comment]
@dexturr @JonRay15 

The quote name has been used for the Price not Size. 
Historically we did not have a unit for the size and we may end up keeping the **base** from the metadata tags. 
`getAssetUnit` method should be renamed as it is misleading. 

https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1697719831923909?thread_ts=1697447640.371409&cid=CAHA5EX0F

This is how it looks like for ETHUSD market if we use quote name for size. 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/d644a606-397d-4b30-ab2a-4100284771c1)
