### ISSUE TITLE
Step validation will not work in some locales

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#506]
follow up (non-blocking): This will not work depending on the localisation of the platform (ie. if commas are used instead of peroids. Will need to add logic for this.

_Originally posted by @dexturr in https://github.com/vegaprotocol/frontend-monorepo/pull/486#discussion_r889936201_

**Comment by dexturr** [comment]
https://github.com/vegaprotocol/frontend-monorepo/commit/780da89c74ed459f5c4b50a7ce12828a46067fd3#diff-deb3f2b58a99a0659165cc5c0f39471658bb9de6828bd2138dd9e2411905dbc9

**Comment by asiaznik** [comment]
It seems `input[type=number]` returns value of an input normalized in a way that `.` is a decimal separator (regardless of locale).

In a case someone types `,` but its locale is set to e.g. `en-GB` then `input[type=number]` ignores the value returning `""` - resulting in validation error of empty value (Firefox; Chrome seems to not care).

Maybe it'd be better to just in case normalize incoming value to `.`?

**Comment by dexturr** [comment]
@asiaznik Great point, sound like we don't need this in that case. Great spot.
