### ISSUE TITLE
Validation for VEGA staked parameter on referral site

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5065]
## The Chore

When a user tries to create a referral code but has not met the criteria for the minimum level of staked Vega, we need to provide them feedback and a way to go stake. 

## Acceptance criteria 

- [x] After connecting their wallet, when users staked tokens is less than referralProgram.minStakedVegaTokens, we display a message, and the user cannot continue on to generate a referral code 
- [x] There is a link to stake on the governance site 

## Additional details / background info

![Image](https://github.com/vegaprotocol/vega.xyz/assets/46783148/a7390215-2d2d-4e05-a87f-82bf702b721d)

**Comment by bwallacee** [comment]
@asiaznik Do i just need to have vega in my wallet or do I need to have it staked?
Also does this work per keypair or if any of them have vega I would be able to make a code?

**Comment by asiaznik** [comment]
You have to have it staked for the connected pub key.
