### ISSUE TITLE
Add tooltip for closed positions tab 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5070]
### Discussed in https://github.com/vegaprotocol/feedback/discussions/183

<div type='discussions-op-text'>

<sup>Originally posted by **zouhairstitou** October 16, 2023</sup>
I have discovered it lists both closed positions as well as closed orders. 

I think it is word having a hover tip that is consists also of the closed orders a.k.a orders cancelled before even getting filles</div>

**Comment by JonRay15** [comment]
I completely agree with this .... In fact I may have raised it somewhere ... in case I didnt, I approve this change.

**Comment by JonRay15** [comment]
In fact ... I included it in the changes to support this ticket. 

https://github.com/vegaprotocol/frontend-monorepo/issues/5110

So I will close this
