### ISSUE TITLE
Notification does not update after transaction failed

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5074]
### Discussed in https://github.com/vegaprotocol/feedback/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **zouhairstitou** October 16, 2023</sup>
Thanks for changing the margin evaluation before any submission, as i have posted earlier in another feedback.

Back the gui returns a message of ongoing confirmation trial that does not stop while the explorer registers failure.

The screenshot shared below went on for long time and i had to close it manually,

Thanks
<img width="709" alt="margin check failed but no feedback message on site" src="https://github.com/vegaprotocol/feedback/assets/30356393/11d62548-8fcf-4944-8117-6815d768f954">
</div>

**Comment by JonRay15** [comment]
Has never been reproduced
