### ISSUE TITLE
Deposit button wont override an already open deposit

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5108]
## The Chore

If you already hae the deposit form open and have set the asset in it. 

Then if you then press the yellow deposit button becaue you dont have assets foor the market you're on it will not override the values you've already set in the form. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/46bb662d-1159-420d-a666-063e7aabf7fb)

In my opinon it should override and refresh the form to be to the asset you clicked the deposit button for. I had to close the deposit form manually and then press the button to get the asset I wanted. 

## Tasks

- [ ]
- [ ]

**Comment by bglownia** [comment]
@JonRay15 I checked this and it works fine for fine for me. "Make a deposit" button always sets asset to current market settlement asset.

**Comment by JonRay15** [comment]
It def doesnt work ... and its also a problem from the rewards page if I try to hit the redeem button on a reward pool
