### ISSUE TITLE
Improve view on margin levels

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5118]
## Story

As a trader
I want to be able to easily see my margin health from the context of my positions
So that so that I can easily tell if my position will be affected

### Covered in other ticket

Outlined on #5525 is a new simplified approach to showing the margin health on the position for a given market.  That ticket covers this for both isolated mode and cross mode.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/268db6ab-cff9-4621-ba8b-3fc5837feed7)

### Changes for this ticket 

The only thing left then is the overall view of collateral which you access from the collateral screen.

We think this should be a simplified view.  Only show the breakdown of how the collateral is allocated, do not show anythign about margin health or various levels etc.

eg.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/104d21b0-9384-4a46-97bf-198d560b9614)

That is all that is needed.

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

We want to be able to show something like the margin breakdown from Collateral 

<img width="673" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/8a0aabd0-aeac-43b3-b32a-d923f1d8b715">

When you hover over the Position margin / leverage cell

<img width="224" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7053d96e-214e-425f-b4dd-3e0e10e4c0d3">

We woudl probabaly also want to see some version of the breakdown as below

<img width="283" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f638cd8e-567d-455c-9003-2d8827f9bfd7">

**Comment by JonRay15** [comment]
I am advising to put this on hold. 

Have discussed with Barney today and its not clear that we really know what we want.  I think it needs more thought, and needs to be considered alongside isolated margin too.  Kick it back into TODO and I'll stick a UX flag on it.

**Comment by JonRay15** [comment]
Per Barney:

As a trader I want to kno ... 

How much money I have in total
How much money I have available to use (general account balance)
The maintenance margin required for each position
The liquidation price for each position
How much capital is actually allocated to each position (margin acct. balance)
The amount allocated to each position as a percentage of my total
The effective leverage of each position
How much is locked as LP bond to each market
How much is locked for other reasons

**Comment by JonRay15** [comment]
I continue to think a lot of this shoudl be UX'd as part of sorting out isolated margin.  If we can get a single isolated margin view for a single market working that can potentially be built upon for cross margin.

**Comment by JonRay15** [comment]
Two numbers to show on cross
- Maintenance level
- Margin + General
