### ISSUE TITLE
[BUG] Transfer between ACCOUNT_TYPE_VESTED_REWARDS and ACCOUNT_TYPE_GENERAL

### ISSUE THREAD

**Issue by davidedaji** [vegaprotocol/frontend-monorepo#5183]
https://github.com/vegaprotocol/frontend-monorepo/blob/06cfd79415e8a57b3edddece133e818ea662729f/libs/accounts/src/lib/transfer-form.tsx#L299C1-L299C60

In my opinion bug is that the system checks the wrong "From account" - it should check the amount in "ACCOUNT_TYPE_VESTED_REWARDS" but for some reasons it checks the amount on "General"

**Comment by davidedaji** [comment]
It got fixed

**Comment by davidedaji** [comment]
Does not work anymore

**Comment by JonRay15** [comment]
I have done this many times over the past couple of months and it works fine, so whatever this issue was has been resolved now.

**Comment by davidedaji** [comment]
Fixed long time ago;
