### ISSUE TITLE
Loss socialisation story telling

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#520]
If your PnL is lower than you were expecting it may be because you experienced loss socialisation.

As a user of the console I want the UI to tell me this has happened (and why?)

MVP - transfers view by market/transfer type in a table.
price change: mark to market transfer..... do one row that aggregates (expand button). Discuss with Barney if needed.

Scope of this is to get an MVP out to the users and expand post trading being enabled.

Blocked by: https://github.com/vegaprotocol/vega/issues/7450

**Comment by PeteWilliams** [comment]
Initial thoughts here:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2276%3A30549

A toast would be shown when loss socialisation occurs:
![Image](https://user-images.githubusercontent.com/1325606/177307896-4349d506-cc0d-4d6a-a7f5-756763382167.png)

And then shown under the history tab:
![Image](https://user-images.githubusercontent.com/1325606/177308222-0a380aa3-5034-49bc-a9bc-81d92f22fc10.png)

**Comment by campbellssource** [comment]
Worth someone sense checking the statement in the ticket description 
> If your PnL is lower than you were expecting it may be because you experienced loss socialisation.
Does your PnL appear lower or do you just have your position reduced in size and "realise" a profit/loss early?

**Comment by barnabee** [comment]
IMO the key place all storytelling about your balance/P&L happens is the ledger entries view. I am not really sure what story telling would be needed for loss socialisation beyond making sure it's shown properly in the ledger view and maybe highlighting that it had happened to a position (annotation on position view linking to the filtered ledger entries for loss socialisation on that market?), or showing a notification, or something like that.

It's important to remember that if Vega works well then loss socialisation will almost never happen in mainnet. It might happen a bit more early on if things go wrong in odd ways, but in general it ought to be rare. It's also ubiquitous among derivatives platforms in crypto particularly and I've never seen any giving it much attention. The financial adjustment would just show up as aa line item in your accounting / balance history (i.e. ledger entries) view on any other plaform.

I'm not sure we have enough evidence it'll happen often or that much more than the ledger entries view is needed to build anything bespoke for this without real mainnet feedback, given the number of other improvements we could make.

But very happen to put this out to wider discussion and prioritisation, it'd just  be good to have that discussion before we spend a lot of time on something like this.

**Comment by barnabee** [comment]
@campbellssource re: your question:

> Does your PnL appear lower or do you just have your position reduced in size and "realise" a profit/loss early?

Your total (general + margin for the market) balance of the settlement asset, and therefore P&L, would be lower than you would have calculated and would expect purely based on your entry price and the current market price and/or the price you closed the position at if loss socialisation had been applied, yes.
