### ISSUE TITLE
Explain/PnL doesn’t include fees paid

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#521]
Scope:

**Must have:** 
Make it clear how it is presented to the user  includes/does not include fees
(show as default net of fees, then show with fees too) - is this something supplied by data-node?

**Nice to have** (subject to a new ticket based on effort and what data-node has):
take data / aggregate data (does this exist / data-node work)

**Comment by PeteWilliams** [comment]
I'd suggest showing this in a tooltip on the P&L column header, ideally with the ability to toggle fees:

![Image](https://user-images.githubusercontent.com/1325606/176187024-04b39c5f-78d4-4292-a3be-ffcf6f8fdf96.png)

My hunch is that it would be more useful to include fees by default if possible and then allow the user to exclude them.

**Comment by PeteWilliams** [comment]
I'd suggest showing this in a tooltip on the P&L column header, ideally with the ability to toggle fees:

![Image](https://user-images.githubusercontent.com/1325606/176187024-04b39c5f-78d4-4292-a3be-ffcf6f8fdf96.png)

My hunch is that it would be more useful to include fees by default if possible and then allow the user to exclude them.
