### ISSUE TITLE
Fees page referral and volume discount issues

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5215]
## Description

The fees page isn't correctly displaying my referral discounts.

## Steps to Reproduce

1. Using the market-sim I have gotten to 3% discount for my wallet (Happy to pair on this step)

1. Go to the fees page

1. Notice issue

## Expected behaviour

- [x] I expect my referral discounts to correctly show on the fees page (we are unable to confirm if this is actually an issue)
  - [x] I now think this is because Ben's key was the referrer and is NOT eligible for discounts
  - [x] Proposed solution is if key is detected to be a referrer we should replace the content of the 4th tile with:

```
Connected key is owner of the referral set `code`

As owner, it is eligible for commission not fee discounts.  

See <referral page> for more information.
```

- [x] We should remove trailing zeros from the 1st tile (see my screen in comment)

- [ ] I think it is fine for the 3rd and 4th tiles to show the actual running volume and the actual referral set volume if there is no program live, but it might be slightly confusing to users ... therefore...
  - [ ] We believe the APIs do not return data if no active program so we should detect this and display "no active referral / volume program"

- [x] We have to ensure the 2nd tile (discounts) still shows zeros for both if there are no programs and I think we should have an info icon next to each 0 saying "No active referral programs" and "No active volume discount programs" appropriately.

- [x] The total discount in tile 2 is being calculated simple as `volume discount + referral discount`.... it should be `1 - (1 - vol discount)(1-ref discont)`
  - [x] ie. in my screen it is 15% & 0.1% so would be `1 - (1 - 0.15)(1 - 0.001) = 1 - (0.85)(0.999) = 0.15085`

- [x] I also expect the bottom table to be called "Fees by market"

- [x] I expect the total fee after discount to be calculated as `fee before discount x (1 - total discount)`.  I think right now it is doing `fee before discount x discount` which is why its showing zero when discount is 0%.

- [x] There seems to be an edge case where if there is no volume discount program the referral program details in tile 4 and in the static table underneath do not show up either ... they should be independent

## Screenshots

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/14a0b332-1ab0-4cb1-8cb8-aa9f3f51e87b)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/9b03a64c-67d4-4f12-8925-820c6987f858)

## GraphQL from both pages:
# Referral page:
`{"data":{"currentReferralProgram":{"id":"2cd4bbedc2b98fd94d3d718aec0ff2b0c5e64a8270486aa5a5b18365cb31ce9d","version":1,"endOfProgramTimestamp":"2024-05-07T10:05:17Z","windowLength":1,"endedAt":null,"benefitTiers":[{"minimumEpochs":1,"minimumRunningNotionalTakerVolume":"100","referralDiscountFactor":"0.01","referralRewardFactor":"0.01","__typename":"BenefitTier"},{"minimumEpochs":2,"minimumRunningNotionalTakerVolume":"200","referralDiscountFactor":"0.02","referralRewardFactor":"0.02","__typename":"BenefitTier"},{"minimumEpochs":3,"minimumRunningNotionalTakerVolume":"300","referralDiscountFactor":"0.03","referralRewardFactor":"0.03","__typename":"BenefitTier"}],"stakingTiers":[{"minimumStakedTokens":"10","referralRewardMultiplier":"1","__typename":"StakingTier"},{"minimumStakedTokens":"100","referralRewardMultiplier":"2","__typename":"StakingTier"},{"minimumStakedTokens":"1000","referralRewardMultiplier":"3","__typename":"StakingTier"}],"__typename":"CurrentReferralProgram"}}}`

[{"data":{"referralSetStats":{"edges":[{"node":{"atEpoch":6,"partyId":"33dda391f017d42fbe600ecae34071c35692487b4b196016826f2814184e67e3","discountFactor":"0.03","rewardFactor":"0.03","epochNotionalTakerVolume":"10450","referralSetRunningNotionalTakerVolume":"10000","rewardsMultiplier":"1","rewardsFactorMultiplier":"0.03","referrerTakerVolume":"0","__typename":"ReferralSetStats"},"__typename":"ReferralSetStatsEdge"}],"__typename":"ReferralSetStatsConnection"}}}]

# Fees page:
`{"errors":[{"message":"failed to get current volume discount program","path":["currentVolumeDiscountProgram"],"extensions":{"code":13,"type":"Internal"}}],"data":{"currentReferralProgram":{"benefitTiers":[{"minimumEpochs":1,"minimumRunningNotionalTakerVolume":"100","referralDiscountFactor":"0.01","__typename":"BenefitTier"},{"minimumEpochs":2,"minimumRunningNotionalTakerVolume":"200","referralDiscountFactor":"0.02","__typename":"BenefitTier"},{"minimumEpochs":3,"minimumRunningNotionalTakerVolume":"300","referralDiscountFactor":"0.03","__typename":"BenefitTier"}],"windowLength":1,"__typename":"CurrentReferralProgram"},"currentVolumeDiscountProgram":null}}`

**Comment by JonRay15** [comment]
More evidence here 

It looks clear to me that its doing `fee before discount x discount` to get the final fee instead of `fee before discount x (1 - discount)`

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/63960e18-c62b-4c0f-b4cf-1fff355831a9)

**Comment by JonRay15** [comment]
Mine looks fine for referrals in fairground ... so either some PR has broken it or you have a local issue. 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fb236dd8-ce9a-45c4-98b0-695338137cc1)
