### ISSUE TITLE
Close a position

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#522]
## Story
As a user of the console
I want to be able to close positions
So that I can control profits and losses

## Acceptance criteria

- [ ] I can close a position from the positions table
- [ ] All orders are simultaneously cancelled
- [ ] I am shown that orders will be cancelled

## Additional information

But I think it's important that we update the 'confirm in wallet' dialog to show what's being closed.
So for just a position:
![image](https://user-images.githubusercontent.com/1325606/192995036-c3049319-e34d-482c-b33b-7a1a06960e95.png)

For a position with orders: 
![image](https://user-images.githubusercontent.com/1325606/192995051-4fe3da6a-4285-4e4f-8540-879bedb6dc69.png)

It also feels like if we are linking orders and positions strongly like this, we should show the number of open orders an a column in the position table:
![image](https://user-images.githubusercontent.com/1325606/192995166-0bd2a83f-868e-4944-9ab9-60fba44327c6.png)

**Comment by PeteWilliams** [comment]
Closing orders is dealt with in https://github.com/vegaprotocol/frontend-monorepo/issues/471

Closing positions would work in a similar manner.

We'd have a close button at the end of the position row:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/1325606/174827848-bedcbf26-e4c3-4753-9c86-14f6fe10e733.png">

And then it would follow the same confirmation mechanism as opening a position:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1771%3A29642

We could also have a 'close all' button - perhaps one for a separate ticket?

**Comment by PeteWilliams** [comment]
Proposed design here:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2610%3A33607

This shows the mechanism for closing positions on markets with and without open orders.

A slight change from what we talked about @campbellssource, in that it seemed to make more sense to close your position first (as this is the live thing, and the market might be moving fast), and _then_ prompt them to close their orders. Unless there's a reason we need to close the orders before the position?

**Comment by campbellssource** [comment]
@PeteWilliams I think we do need to cancel orders then, close position. Otherwise there is a risk that you'll end up with open position, if you have orders that are being hit, while the position is being closed

**Comment by PeteWilliams** [comment]
> @PeteWilliams I think we do need to cancel orders then, close position. Otherwise there is a risk that you'll end up with open position, if you have orders that are being hit, while the position is being closed

That's a risk, but isn't that better than not being able to close your crashing position because you've got dozens of orders (that might not be hit) that you need to close first? Seems more of a rekt-risk to me.

**Comment by PeteWilliams** [comment]
Updated design now that we can close orders with positions in one transaction.

Add a different button for positions with open orders so it's clear it will close both:
![image](https://user-images.githubusercontent.com/1325606/192994927-12a81fc2-e464-4c90-9cbc-0cf761f6804f.png)

But I think it's important that we update the 'confirm in wallet' dialog to show what's being closed.
So for just a position:
![image](https://user-images.githubusercontent.com/1325606/192995036-c3049319-e34d-482c-b33b-7a1a06960e95.png)

For a position with orders: 
![image](https://user-images.githubusercontent.com/1325606/192995051-4fe3da6a-4285-4e4f-8540-879bedb6dc69.png)

It also feels like if we are linking orders and positions strongly like this, we should show the number of open orders an a column in the position table:
![image](https://user-images.githubusercontent.com/1325606/192995166-0bd2a83f-868e-4944-9ab9-60fba44327c6.png)

**Comment by mattrussell36** [comment]
@PeteWilliams showing the different button states, 'close' vs 'close and cancel orders' is not feasible right now. The positions api doesn't provide us with a way of knowing if there are open orders or not on a position. We can however show this information in the dialog.

**Comment by PeteWilliams** [comment]
In which case, I think we're better off going down this route:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2610%3A33607

![image](https://user-images.githubusercontent.com/1325606/194845473-2e6b75c7-42c0-492d-8a45-2a0878e34414.png)

So if there are orders, show them in the modal and give them the choice or closing both order and position, or just the position.
