### ISSUE TITLE
Enhance deal ticket info for fee discounts

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5244]
The way discounts are displayed in the deal ticket & tooltip have led to some confusion.

1. The -40% next to fees, at a glance, looks like 40% fees, but even -40% fees doesn't imply "saving 40% on fees".
2. Tooltip isn't clear that the "volume discount" is subtracted from the total, so it actually looks like another fee. This could be better expressed, perhaps with a minus. 
3. Rename "Volume discount":
* Either rename to Fee discount (volume tier X) 
* OR lump all 'fee discounts' together in one line as a collective % & value, and let people see the breakdown on the fees/discounts tab.
4. How the 40% is calculated has also caused confusion. Per @wwestgarth: "this fee bit on stagnet for me seems odd to say the volume discount fee is 40% when 0.0072/22.5 is more like 0.032%". But the maths are more like: 
> Total fee (discounted) is 0.0108
> Discount is 0.0072
> Fee before discounts = 0.0072+0.0108 = 0.018
> Discount = 0.018 * 0. 4 = 0.0072
Not sure how best to handle this but it's not an obvious one. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62548908/4d3448ab-8e4b-4739-b5eb-53a49b7853fd)

## Acceptance criteria
- [x] Table rows are structured as outlined in [this comment](https://github.com/vegaprotocol/frontend-monorepo/issues/5244#issuecomment-1807695420)
- [x] Prefix with '-' for discounted percentages and amounts
- [x] Check that the maths is correct for discount calculations
- [x] Combine all discounts together into one 'Discount' row. This is either the volume discount or the referral discount or the combined discount value if both are applied

**Comment by wwestgarth** [comment]
Thinking about this over the weekend, I think _usually_ when you see a discount being applied to something you see the total, then you see the total with the discount applied. So something like this would make it clearer:
```
Infra     0.05% 0.0675
Liquidity 0.01% 0.00135
Maker     0.02% 0.0027
Subtotal        0.108

Discount    -40% -0.0072 (maybe in red)
Total     0.08% 0.0108

```

**Comment by mattrussell36** [comment]
With volume discount
Infra             0.05%    0.0675
Liquidity         0.01%   0.00135
Maker             0.02%    0.0027
Subtotal                    0.108

Volume discount     -40%  -0.0072

Total fee          0.08%   0.0108

With referral discount
Infra               0.05%   0.0675
Liquidity           0.01%  0.00135
Maker               0.02%   0.0027
Subtotal                     0.108

Referral discount   -40%   -0.0072

Total fee          0.08%    0.0108
```

With both volume AND referral
```
Infra              0.05%.  0.0675
Liquidity          0.01%  0.00135
Maker              0.02%   0.0027
Subtotal                    0.108

Volume discount     -40%  -0.0072
Referral discount   -40%  -0.0072
Total discount      -80%  -0.0144 (maths prob wrong here)

Total fee          0.08%   0.0108
```
