### ISSUE TITLE
Discuss E2E testing maintainability and making it easier for anyone to contribute

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/frontend-monorepo#5249]
## The Chore

When looking at the console-test repo (currently being integrated into monorepo) I have some opinions on the code regarding maintainability, reusability and also how easy it would be for anyone to contribute. This isn't a 'fix everything _NOW_' kind of thing, but definitely everything new should implement whatever we come up with. I think we should chat about the following things to start with:

- mass duplication of logic
- mass duplication of selectors - these could implement a pattern similar to browser wallet where we reference locators declared in the front end so tests do not break when they change
- magic values buried deep in logic with the tests very dependent on these values
- unrecognisable code, in that all logic is in the tests at a super granular level, meaning reuse is not possible with out taking a lot of time to figure out what the code is doing.

I think the blast radius in this test framework when things go wrong is currently quite large. @bwallacee and I have chatted and have agreed to discuss the best way to approach test code moving forward and how we can make it easier to maintain and contribute to.  Anyone should be able to dive into this test framework and contribute to the tests without great effort in an ideal world. 

## Tasks
- [ ] Schedule in a meeting
- [ ] Ben/Dale to update this task list with actions

**Comment by JonRay15** [comment]
Not a priority anymore.
