### ISSUE TITLE
Problems with node switcher

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5291]
**Block Explorer:**

- Change could be updated to be more obvious

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/c247312c-2a70-4cb7-b305-16d2a39ad5c0)
Also should we match console and have an icon to show current connected node health
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/ecb5879a-04dc-4abf-8d11-fd507df346c1)

**Relevant to all apps:**

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/9a757f06-3005-47cd-bddd-2571c2421423)

Suggestions:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/715547a7-08e4-494e-8d5b-5ef980a010b5)

- It's not clear what node i am currently connected to if i select a different one e.g. image above i am connected to the second in the list.

- Do we want to sort the list by response time?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/d912c37f-9383-473a-8665-23a8a04c2e58)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/3108920b-f8dc-4953-a19d-79a66f776ded)

- Other shows https:// and could be interpreted as you dont need to enter (you do need to enter)

- Font size of the node url is smaller than the rest of the fonts

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/733e3ba1-bc5c-4290-bb22-9f60c2a318e1)

- If you are selected on the one you are connected to we still show connect to this node ( but greyed out) could we just update the text as well to say you are connected to this node 

- There is no hover mouse cursor update on the different nodes
- I'm not sure i am a fan of the font used for response time and block
- Connected Node header could be changed to Node switcher or something
- Do we want the node health green/red circle displayed here somewhere?

**Comment by mattrussell36** [comment]
@JonRay15 adding refine to this one. Theres lots of good suggestions but we need to drill down what the actual changes should be
