### ISSUE TITLE
When wallet isn't connected in console then transfer window is unfriendly

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#5296]
When wallet isn't connected in console then transfer window is unfriendly

In particular "select asset" or "select account" just don't react. Perhaps the whole view should somehow indicate that without a connected key this is not usable. 

<img width="321" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/489aef88-94c2-4c45-add8-558ef5fafaf4">

**Comment by JonRay15** [comment]
Looka like this was adjusted 



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1549e2e1-81ee-4aed-91ba-dd6346ae2c6b)


Closing this
