### ISSUE TITLE
Hide margin estimations for perps markets

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5302]
## The Chore

There is a problem with margin estimations in core for perp markets. Wrong values are returned from the api in the specific case of when the oracle has not sent any data points. To avoid confusion we should hide it

## Tasks

- [ ] Hide margin estimation for perps markets
- [ ] Or better: Hide margin estimations for perps markets that haven't received a data point from an oracle

**Comment by gordsport** [comment]
The root cause of this issue has been resolved ad the validators deployed to mainnet v0.73.5 on the 20th Nov '23

The hiding of the margin estimation has been reverted with the network deployment now fixing the root cause
