### ISSUE TITLE
Empty index price in console

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5323]
## Description

So creating a market using ETH oracle, Chainlink, but not using the first value seems to be working in the explorer for receiving prices, see image,  but the console is not displaying anything even though there are funding payments happening. 

```
  "ethOracle": {
                    "address": "0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43",
                    "abi": "[{\"inputs\":[],\"name\":\"latestRoundData\",\"outputs\":[{\"internalType\":\"uint80\",\"name\":\"roundId\",\"type\":\"uint80\"},{\"internalType\":\"int256\",\"name\":\"answer\",\"type\":\"int256\"},{\"internalType\":\"uint256\",\"name\":\"startedAt\",\"type\":\"uint256\"},{\"internalType\":\"uint256\",\"name\":\"updatedAt\",\"type\":\"uint256\"},{\"internalType\":\"uint80\",\"name\":\"answeredInRound\",\"type\":\"uint80\"}],\"stateMutability\":\"view\",\"type\":\"function\"}]",
                    "method": "latestRoundData",
                    "normalisers": [
                      {
                        "name": "btc.price",
                        "expression": "$[1]"
                      }
                    ],

```

This is the default we have in our [docs](https://docs.vega.xyz/mainnet/tutorials/proposals/new-perpetuals-market) and have been recommending. 
The problem is that this latestAnswer is depreciated and latestRoundData should be used.

`"ethOracle": {
                    "address": "0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43",
                    "abi": "[{\"inputs\":[],\"name\":\"latestAnswer\",\"outputs\":[{\"internalType\":\"int256\",\"name\":\"\",\"type\":\"int256\"}],\"stateMutability\":\"view\",\"type\":\"function\"}]",
                    "method": "latestAnswer",
                    "normalisers": [
                      {
                        "name": "btc.price",
                        "expression": "$[0]"
                      }
                    ],
`
## Steps to Reproduce

1. Go to create a market with the values shown for oracle
2. Go to console and check the price updates as well as explorer
3. Explorer shows price updates for oracle and console shows funding payments index price

## Screenshots
<img width="1273" alt="Screenshot 2023-11-21 at 15 49 22" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/a1d6de4d-db24-4bf7-818e-c59b0c7d1598">

<img width="1160" alt="Screenshot 2023-11-21 at 15 49 09" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/e1ee31d3-7f2b-4419-afdb-2ecec3adda66">

<img width="1049" alt="Screenshot 2023-11-21 at 15 46 18" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/33630c99-9805-401a-a7cd-f6c86172fea9">

<img width="1363" alt="Screenshot 2023-11-21 at 11 31 34" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/9c06b4d7-c850-4578-8679-66b05cabf29b">

**Comment by daunatv** [comment]
@candida-d might be good for you to follow this as well since we should probably update the doc's templates afterwards.

**Comment by edd** [comment]
Just catching up here...

1. I agree that we should update the templates to use `latestRoundData` instead. If we follow the guidance of the docs and check the value *and* the updated at, that seems ideal... but I'm not sure what the expression for that looks like, so someone more capable than me should work out what that looks like
2. All of the current networks/markets using eth contract oracles that are looking at `latestAnswer` and should probably be updated to use `latestRoundData`. 
3. I don't think this needs to happen immediately as the filters on most oracles already require the result be `> 0`. So the ramifications are:
    1. `latestResult` stops existing on a contract -> this is unlikely to happen to any existing market. The function has been deprecated since at least 2021.
    2. `latestResult` returns stale data -> possible

**Comment by mattrussell36** [comment]
I've been unable to produce this. So closing.
