### ISSUE TITLE
Missing I18N translations

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5371]
Here is a rubbish doc full of screenshots of missing translations:
https://docs.google.com/document/d/1nLzdMZeOzCh8r7FYe9UVifmyAXAC5fan3yEP5vlF0CM/edit

**Comment by JonRay15** [comment]
Needs fixing ... but i18 not live yet so can wait a sprint.

**Comment by JonRay15** [comment]
Also missing enums, also have some issues with keys to labels and more.
