### ISSUE TITLE
New approach for pending market updates

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5391]
## The Chore

We think using the market banner will cover this. 

But agree it with Barney.

## Tasks

- [ ]
- [ ]

**Comment by mattrussell36** [comment]
@JonRay15 thought we got sign off on this the other day on a call, but please confirm if you have a mo

**Comment by mattrussell36** [comment]
@barnabee you cool with using the market banner here? This replaces the orange card which was pushing the header stats too tall
