### ISSUE TITLE
Volume and Epochs to next tier no longer populating in referrals view

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/frontend-monorepo#5399]
## Description

In the referrals view, 'volume to next tier' and 'epochs to next tier' remain at zero, regardless of trades placed and epochs in set. See example below:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/37066267/66f3ec56-ec62-49a6-9de6-330892a716b9)
**Epochs to next tier:** In the above screenshot, I have two epochs in my set and I am in tier 2. Therefore the epochs to next tier value should be 1, given the next tier is tier 3 and Min epochs is set to 3 for this tier.

**Volume to next tier**: In the above screenshot, you can see that the 'combined running notional over the 1 epoch' (I think we should adjust the wording here!) is 221, so volume to next tier should be 79 given that the volume required for the next tier is 300, it is currently 0. 

## Steps to Reproduce

1. Go to referrals e2e test (Referrals/test_referrals.py) https://github.com/vegaprotocol/frontend-monorepo/pull/5349
2. comment out the assertions in the check_tile_values method
3. put a page.pause() inside check_tile_values _after_ the initial navigation to referrals
4. run the test `poetry run pytest -k "test_referral" -s --headed`
5. Observe at each pause the mentioned values remain at zero

## Expected behavior

Volume and epochs to next tier update corresponding to volume traded and number of epochs in set

- Browser: chrome

**Comment by JonRay15** [comment]
@dalebennett1992 has checked
