### ISSUE TITLE
Bug: Disappearing tooltip, can't click on link

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5436]
### Discussed in https://github.com/orgs/vegaprotocol/discussions/200

<div type='discussions-op-text'>

<sup>Originally posted by **DA686RK** November 25, 2023</sup>
**Problem encountered**

When you move the mouse cursor over the tooltip, information appears in the "Size / conditional" column. It offers to read the information "More about position resolution" on the link.
But the window disappears if you move the cursor away from the tooltip icon.

https://github.com/vegaprotocol/feedback/assets/78697904/b84109cd-c91c-4474-8ff1-4a12cb26ef41

</div>

**Comment by JonRay15** [comment]
This has been changed in the PR for the margin levels ticket on #5118 so we need to get agreement from Barney to deploy this.
