### ISSUE TITLE
Volume in the referee table on the referrer stats page is not aggregating properly

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5457]
## Bug Definition

We've observed a case where the main tiles are assessing the running volume for the set as 221. 

But the voliume of the individual referee is coming in at 331 which is including their previous epoch. 

Implies the query on the referree stats endpoint here isnt using windowLength properly

Core have determined this is an API bug and have scheduled a fix to resolve.

## Impact

This data is not used in calculation of the discount tiers, which are correct. The only impact is that if users add up the individual referee contributions they will find they do not match the overall volume of the set which could cause confusion. Since this is not financial / trading data and users will not be making trading decisions on this basis we do not believe this warrants an emergency fix.  Therefore tagging this to the known issues board until this can be resolved in the next release.

**Comment by mattrussell36** [comment]
@asiaznik can you verify if this is a core issue core issue or not

**Comment by asiaznik** [comment]
There seems to be discrapancy between `totalRefereeNotionalTakerVolume` (aka `PeriodVolume`) and sum of `epochNotionalTakerVolume`s.

I believe the observed issue is due to the condition in `datanode/sqlstore/referral_sets.go` which includes **one more** epoch than needed:
```
epoch_range as (select coalesce(max(id) - %d, 0) as start_epoch, coalesce(max(id), 0) as end_epoch
    from epochs
    where end_time is not null
```

It looks to me like the `aggregationEpochs` (`%d`) should be reduced by 1.

**Comment by asiaznik** [comment]
I'd appreciate if someone could verify this 🙏 
@guoguojin @jeremyletang @JonRay15

**Comment by ValentinTrinque** [comment]
Indeed, the epoch range is off by 1.

**Comment by JonRay15** [comment]
@bwallacee has confirmed he's happy this is working.
