### ISSUE TITLE
Final referral testing on fairground

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5458]
- [x] Check the ACs on this ticket https://github.com/vegaprotocol/frontend-monorepo/issues/5298
- [x] Make sure to test that staking changes the multiplier as expected.
- [x] Make sure we dont get a recurrence of the 7th tier issue Dale found
- [x] Make sure close position works

### BUG On the referrer stats page 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/70cffbf5-5765-4dd1-9750-a26e9bbf02b7)

Base commission is good

Staking multiplier is correct 

But I have a rounding / precision nightmare going on...and 5% x 1.1 should be giving me 5.5% if I'm not mistaken?

Looking at the graphQL ... I'm not totally sure how to query it directly as the referrer (but Art must be doing it somehow) ... but if I look at the set I see the below:

```

          "node": {
            "partyId": "f8382994c9cd12507d6152b47d1cec2177a02c8c54c3a8741761503a5b0d1124",
            "wasEligible": true,
            "discountFactor": "0.1",
            "rewardFactor": "0.05",
            "rewardsMultiplier": "1.1",
            "rewardsFactorMultiplier": "0.055",
            "epochNotionalTakerVolume": "0",
            "referrerTakerVolume": "0",
            "referralSetRunningNotionalTakerVolume": "182577",
            "atEpoch": 10532
```
So the API seems to be correctly giving me 0.055 but something is wrong on our end.

### When I have a wallet but I have no funds

When trying to join from a key with no funds this is the message:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2d91f174-e0f6-4248-91b0-a78ac915deba)

A minimum of 10 what?

It should say:

"To protect the network from spam, you must have at least `spam.protection.applyReferral.min.funds` qUSD of any asset on the network to proceed" (and we should put our normal qUSD tooltip on there).

###  When I am brand new 

The site detects that I am new and hits me with the onboarding modal on top of the referral page .... it is clunky and unecessary.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/8053e377-6359-432f-9c2c-4d018da3dbae)

IMO if I'm landing via a referral link:

1. I know I'm coming in via a link, I'm not a brand new user that needs this onboarding flow
2. It makes more sense to present me the onboarding flow through the screen which we already basically do .... we land with a code, we tell you if you need a wallet, we tell you if you need funds, and we handle the deposit all on screen.... the only thing you might claim we're missing is the up front view on the steps in that we hide the need for a deposit from you until after you have the wallet. 
3. If we leave this here: 
    4. If you click explore you get shot off to the most traded market and lose your code etc. 
    5. If you click connect you might get sent off to the wallet download which is OK 
    6. Once you come back from the wallet download you get sent to the guided deposit page, and therefore lose the referral page and your code ... this is cleaner using the popout sidebar the way the referral page handles it

I think we have to either:

1. Not show the onboarding modal if you're navigating in via a referral code... handle onboarding on the page
2. The onboarding modal needs to know you're in the "Referral onboarding flow" and therefore show you something a bit different ... probably a step for "Apply referral code" should be in the list, and maybe it should have some fun text .. "You've landed on Consoel from code 724hjk34hj43.... start your onboarding below" or something.... the onboarding flow would also need to store your code so when you return from the guided deposit page it can populate it again for you

Personally the path of least resistance is 1 in my view, what do you think? Maybe we can revisit 2 next week, but in the interest of getting a release out tonight I think 1 is more achievable?

**Comment by mattrussell36** [comment]
@JonRay15 I think option 1 with regard to on-boarding is the best option for now.

Honestly I think we need to rethink the whole on-boarding implementation. I would suggest we look at creating a specific page to direct users to for wallet/deposit/referral code guidance /onboard or something like that

**Comment by JonRay15** [comment]
Bug on the final commission is fixed 


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d6ee2b73-735b-4b65-a3c9-d7efb73dd816)

**Comment by JonRay15** [comment]
No funds message has been corrected BUT we still dont have a tooltip on the qUSD



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/a4a752ba-1da3-4233-8d9a-45267c2dc52b)

**Comment by JonRay15** [comment]
I want to include this tooltip from the referrer stats page ... but I will put that in another ticket.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/06db2ece-e2c1-4ed5-ad6f-a4189f5b5360)
