### ISSUE TITLE
Volume / Change incorrectly displayed as -

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5465]
## Description

Console is "flip flopping" on volume and change displayed within some of our e2e tests.

After investigating I can see that volume of 1 is coming through in graphql but console is incorrectly displaying -

**I have seen similar behaviour for the funding rate and index price**
## Steps to Reproduce

1. Run market-sim test `test_market_selector_filter`
2. See error

## Expected behaviour

Volume and change is correctly displayed

## Screenshots

![image (6)](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/c883312b-1365-44b2-a5fd-14b025cf048a)

**Comment by MadalinaRaicu** [comment]
If the candle is older than 24hrs then console should display `-` but it should have a tooltip with the change from the last 5 days.
