### ISSUE TITLE
Referee rewards appear to be calculated on volume alone, epochs are disregarded which leads to inflated rewards

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/frontend-monorepo#5483]
## Description

Rewards appear to be disregarding the number of epochs. This means someone with 1 epoch in the set could be eligible for the same rewards as a key with 60 epochs 'in set'

In my test scenario I have a referral scheme that looks like this:
`  "minimum_running_notional_taker_volume": 800,  
"minimum_epochs": 8,
        "referral_reward_factor": 0.08,
        "referral_discount_factor": 0.08,`

Party A is the referrer
Party B is the referee
The steps taken are as below

1. Party B places a trade of size 8, vol 115, we have not progressed through any epochs at this point
2. Move forward one epoch
3. Go to the Party B referrals page, the page shows no discount. 7 epochs still required for the next tier. This is as expected
4. Go to the Party A referrals page
5. Observe the page shows 8% base commission rate, there have not been enough epochs to warrant this. There have been three epochs since Party A set up the referral scheme, 1 since Party B applied the code.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/37066267/b71e1e33-4a1e-4827-b60d-b1589c43b428)

Querying graphql also shows a reward factor of 0.08, and a discount factor of 0. reward factor should also be 0.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/37066267/7221082a-51af-47f8-8539-a902d98472c5)

## Expected behavior

Expected to not be qualified for any rewards, despite the volume qualifying for a reward, the number of epochs does not.

cc @asiaznik

**Comment by JonRay15** [comment]
Confirmed with research this is working as designed, we can close.
