### ISSUE TITLE
Activity streak benefit tiers show as empty array

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5495]
## Description

On explorer (testnet and mainnet) the activity streak benefit tiers are populated, but explorer renders them as an empty array 

## Steps to Reproduce

1. Go to ['network parameters'](https://explorer.vega.xyz/network-parameters#rewards-activityStreak)
2. See empty array
3. Compare to API results for same netparam

**Comment by edd** [comment]
The network parameter view is correct. The rewards configured by network parameters are currently unpopulated. Other rewards can be inspected with [the relevant queries](https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-get-current-volume-discount-program).

The in-console rewards views use the correct APIs, so no data is missing.
