### ISSUE TITLE
Switch for dark / light time seems broken 

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/frontend-monorepo#550]
When switching from dark to light theme, some compone stays in the initial color. This is broken either if you load the app in dark or light them initially (see recordings).

https://user-images.githubusercontent.com/4346460/173781165-f1de2425-9801-42fe-8ec7-cf0c2f36d30b.mov

https://user-images.githubusercontent.com/4346460/173781189-fe9c4de8-060a-4dbb-b408-0a8066f9e668.mov

**Comment by sam-keen** [comment]
Duplicate, fixed in #588.
