### ISSUE TITLE
Stop the fees tootip on the fills table from disappearing

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5502]
Stop the fees tooltip on the fill page from disappearing as it disappears quickly and makes it hard to read all the information

https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/c6e9ca37-41da-4ff6-b064-72f0122353d2

**Comment by MadalinaRaicu** [comment]
addressed by #5416
