### ISSUE TITLE
Ways to Connect Vega Wallet (Minimum Viable UX)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#555]
As a user
When I have clicked the/a Connect Wallet button in the dapp
I want to understand the options for how to connect my wallet based on the type of wallet I have  
So that I have the information I need to successfully connect my wallet (and don't immediately see an error message!)

Acceptance Criteria

- There is a way to select a connection method / wallet type: ([0002-WCON-002](https://github.com/vegaprotocol/specs/blob/user-interface-SORD-only/user-interface/0002-WCON-connect_vega_wallet.md#0002-WCON-002))
- There is a way to easily access help should I need to troubleshoot my connection i.e. link to https://docs.vega.xyz/docs/mainnet/tools/vega-wallet ([0002-WCON-040](https://github.com/vegaprotocol/specs/blob/user-interface-SORD-only/user-interface/0002-WCON-connect_vega_wallet.md#0002-WCON-040))
- There is a way to get a Vega wallet (in case I don't already have one) i.e. link to https://vega.xyz/wallet/ ([0002-WCON-036](https://github.com/vegaprotocol/specs/blob/user-interface-SORD-only/user-interface/0002-WCON-connect_vega_wallet.md#0002-WCON-036))
- (Custom URL field in image handled by another ticket - https://github.com/vegaprotocol/frontend-monorepo/issues/561) 

<img width="464" alt="Screenshot 2022-09-01 at 17 04 09" src="https://user-images.githubusercontent.com/46783148/187960856-d14371b5-ccbb-41e9-a19a-3f9bccf9057f.png">

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, [this PR](https://github.com/vegaprotocol/specs/pull/1181#) has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
Covered in 0002-WCON-039

**Comment by pennyandrews** [comment]
This is blocked as it is a common component that is currently being developed in Console, once done it should be a case of TFE gets it for free (but we'll want to verify :) )
