### ISSUE TITLE
Support LP fee setting enhancements

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5552]
## The Chore

Latest Core changes will mean there are now three ways to set fees:
   - Using LP commitments (same as now)
   - Weighted average of the fee values provided on the commitments instead of using the top one
   - Set a single fee on the market manually and update via governance

## Tasks

- [ ] Update the market info to make sure we can see this new market param
- [ ] Add a tooltip offering some explanation of these settings (@candida-d can assist)
- [ ] Check Console 
- [ ] Check Explorer

**Comment by MadalinaRaicu** [comment]
should it be another panel? 
<img width="342" alt="Screenshot 2024-02-08 at 18 15 30" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/72df83f8-cbe6-4cf3-91db-d7880d4e689a">
I feel like this should be inside current fees panel (based on the API structure)
<img width="397" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/aa9c3dae-9cb7-4c02-863c-053bc3fa14f8">
