### ISSUE TITLE
Click to Connect Vega Wallet (Better UX)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#556]
As a user
When I have clicked the/a Connect Wallet button
I want to see the options for how to connect my wallet based on the type of wallet I have and be able to launch them from the dapp
So that I can connect more quickly and don't need to go find my app / app window 

Acceptance Criteria
- I only see the wallet connect options that are relevant to the network I currently have selected in my dapp - i.e I don't see hosted Fairground wallet if my dapp is connected to mainnet
- If I click on an application that I don't have on my device - Desktop Wallet App - then there is a way to help me get it 
- There is a way to launch the wallet apps listed, and if not possible (CLI) there is a way to provide the guidance of what to do instead

<img width="670" alt="Screenshot 2022-06-15 at 18 18 29" src="https://user-images.githubusercontent.com/46783148/173887292-a84c36cd-c37c-49c5-802b-a1571cbc287b.png">

Epic for Context [Connect a Vega Wallet Flow.pdf](https://github.com/vegaprotocol/frontend-monorepo/files/8909418/Connect.a.Vega.Wallet.Flow.pdf)

**Comment by campbellssource** [comment]
Since this ticket was raised, [this PR](https://github.com/vegaprotocol/specs/pull/1181#) has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.

**Comment by campbellssource** [comment]
There is a commented out AC for launching and app with something like `Vegawallet://` in 0002-WCON-006

**Comment by ckpringle** [comment]
Closing this ticket for now as the approach has changed slightly and been reflected in https://github.com/vegaprotocol/frontend-monorepo/issues/555
