### ISSUE TITLE
Connecting Vega Wallet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#557]
As a user
When I have opened / run my Vega Wallet Desktop App, CLI App or Hosted Fairground Wallet
I want to see that the dapp has recognised that the wallet service is running /connecting and give me information about what to do / will happen next
So that I know what to expect / have to do and can continue the connection process

Acceptance criteria 
-

<img width="454" alt="Screenshot 2022-09-01 at 17 02 36" src="https://user-images.githubusercontent.com/46783148/187960581-c61ab568-8413-4b82-bab2-b4f96fea64b4.png">

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181# has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
I think this one is covered in: 0002-WCON-009

**Comment by pennyandrews** [comment]
This is blocked as it is a common component that is currently being developed in Console, once done it should be a case of TFE gets it for free (but we'll want to verify :) )
