### ISSUE TITLE
When market is in proposed console says terminated 

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5574]
## Description
When market is proposed the console says that it is terminated and you can't trade which is not correct
<img width="1385" alt="Screenshot 2024-01-05 at 18 42 57" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/25e366c0-e443-4b6a-883d-9603f679bf20">

**Comment by MadalinaRaicu** [comment]
This happened because the market was in `No trading` mode, so I suggest we switch `Trading terminated` to `No trading`

cc @mattrussell36 @daunatv
