### ISSUE TITLE
Choose wallet to connect with dapp (desktop wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#558]
As a user
When I have opened / run my Vega Desktop Wallet app and a dapp is trying connect
I want to see that the dapp  is requesting to access a wallet and be able to select one
So that I can choose which of my wallets I want to approve to use with the dapp

## Acceptance Criteria
- [ ] I can automatically see a list of my wallets to connect to the requesting dapp 
- [ ] I can choose to cancel the connection (reverting back to landing state / screen of wallet app) 
- [ ] We've decided whether that's enough for cancel or if we need another story for the dapp wallet connect UI e.g. to do something there too.

<img width="465" alt="Screenshot 2022-09-01 at 17 02 08" src="https://user-images.githubusercontent.com/46783148/187960485-7bc02699-ce47-475a-a297-2826d6131d10.png">

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181 has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
I think this is covered in 0001-WALL-017

**Comment by ckpringle** [comment]
Blocked dependant on the v2 integration

**Comment by ValentinTrinque** [comment]
It is not blocked per se. The integration on the service needs the front end to ensure it's working fine. So both sides are going to be implemented in the same PR

**Comment by pennyandrews** [comment]
Replicated in correct repo https://github.com/vegaprotocol/vegawallet-desktop/issues/348
