### ISSUE TITLE
Choose Vega Wallet to Connect (CLI wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#560]
As a user
When I have opened / run my Vega CLI Wallet app and a dapp is trying connect
I want to see that the dapp is requesting to access a wallet and be able to select one
So that I can choose which of my wallets I want to approve to use with the dapp

Acceptance Criteria
-

Epic for Context [Connect a Vega Wallet Flow.pdf](https://github.com/vegaprotocol/frontend-monorepo/files/8909418/Connect.a.Vega.Wallet.Flow.pdf)

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181 has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
I think this is covered in 0001-WALL-017

**Comment by pennyandrews** [comment]
Closing this as I believe it has already been done
