### ISSUE TITLE
Fees column order seems to have changed on FG

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5609]
## The Chore

It is showing like this 

<img width="1329" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4d13128d-d568-41ec-a15f-c70e1e519d54">

But in mainnet the Total is on the left .... the liquidity fee should be further to the right 

<img width="1483" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/3f3288b5-fa60-4942-8fbb-83019d9687c5">

## Tasks

- [ ]
- [ ]

**Comment by bglownia** [comment]
@JonRay15 
columns were rearranged in this PR
https://github.com/vegaprotocol/frontend-monorepo/pull/5530
