### ISSUE TITLE
Choose Vega Wallet to Connect (hosted wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#561]
As a user
When I have clicked on the 'enter a custom wallet location' link 
I want to be able to enter the location of the wallet I want to connect
So that I can choose which of my wallets I want to approve to use with the dapp

Possible dependency on https://github.com/vegaprotocol/frontend-monorepo/issues/230 https://www.notion.so/vegaprotocol/Hosted-wallet-for-fairground-10d759029b4d4a10a47865ad3f79edb3

<img width="985" alt="Screenshot 2022-09-01 at 16 59 59" src="https://user-images.githubusercontent.com/46783148/187960040-e90c618b-4997-455f-8e33-1377a2928826.png">
<img width="697" alt="Screenshot 2022-09-01 at 17 00 17" src="https://user-images.githubusercontent.com/46783148/187960091-2bc4d28f-b35c-4380-9508-c66fb1cda368.png">

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181 has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
Covered in 0002-WCON-003

**Comment by pennyandrews** [comment]
This is blocked as it is a common component that is currently being developed in Console, once done it should be a case of TFE gets it for free (but we'll want to verify :) )
