### ISSUE TITLE
Remember my last used key when reconnecting to the browser wallet

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5611]
## The Chore

What we need to achieve and who for

## Tasks

- [ ]
- [ ]

## Additional details / background info

* Wallet replies with a list of keys that the dApp is permitted to use from `listKeys`.
* Console can persist the last used key and automatically select that key
* If the key is not found or there does not exist a last used key we should just select the first key in the list

**Comment by mattrussell36** [comment]
@JonRay15 This appears to be working fine with browser wallet and desktop wallet. Was there a specific wallet that this wasn't working for? Closing for now, but re-open if necessary
