### ISSUE TITLE
MOBILE - Markets table disappears if you open and close withdraw

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5614]
The markets table disappears if you open and close withdraws.

Reproduce steps:

1. open closed market table
2. open withdraws
3. close withdraws
4. notice markets table has disappeared (comes back on page refresh)

https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/ace5dc08-a4cf-4ecf-aec2-45dbd068f9fc

**Comment by mattrussell36** [comment]
Closing because we don't actually show the deposit/withdraw buttons here anymore. Also we have some incoming tickets that change this
