### ISSUE TITLE
Choose Vega Wallet to Connect (fairground hosted wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#562]
As a user
When I have opened the wallet.fairground.wtf URL and a dapp is trying connect
I want to be able to  specify a wallet and enter my passphrase
So that I can choose which of my wallets I want to use and approve the connection to use with the dapp

Possible dependency on https://github.com/vegaprotocol/frontend-monorepo/issues/230 https://www.notion.so/vegaprotocol/Hosted-wallet-for-fairground-10d759029b4d4a10a47865ad3f79edb3

<img width="1080" alt="Screenshot 2022-09-01 at 16 59 06" src="https://user-images.githubusercontent.com/46783148/187959881-faeba2f4-2a97-4865-8370-4cc69f84dd97.png">

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
if the user/pass is correct you will not see
>  see that the dapp is requesting connect to a wallet

it'll just be connected.

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181 has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
See 0002-WCON-039 onward

**Comment by pennyandrews** [comment]
Closing as had migrated to vegawallet-desktop repo
