### ISSUE TITLE
Approve Vega Wallet Connection (desktop wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#563]
As a user
When I have chosen the wallet I want to connect in my Vega Desktop Wallet App 
I want to enter my passphrase to authenticate and approve the connection of my wallet to the dapp
So that I can  securely use my assets in the dapp

## Acceptance criteria 
- [ ] I can enter my password to approve connection 
- [ ] I can choose not to provide password, pressing cancel (reverting wallet to default / landing state)

<img width="310" alt="Screenshot 2022-09-01 at 16 58 04" src="https://user-images.githubusercontent.com/46783148/187959617-69cf7dd9-085a-4b2b-b34a-f6e5efbd1af5.png">

Epic for Context [Connect a Vega Wallet Flow.pdf](https://github.com/vegaprotocol/frontend-monorepo/files/8909418/Connect.a.Vega.Wallet.Flow.pdf)

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181 has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
I think 0001-WALL-022 covers this.

**Comment by campbellssource** [comment]
I think this ticket should be in https://github.com/vegaprotocol/vegawallet-desktop and may be a dupe

**Comment by ckpringle** [comment]
Blocked dependant on the v2 integration

**Comment by pennyandrews** [comment]
Recreated in the right repo https://github.com/vegaprotocol/vegawallet-desktop/issues/349
