### ISSUE TITLE
Error: Something went wrong: failed to get party for ID on the governance rewards page 

### ISSUE THREAD

**Issue by daro-maj** [vegaprotocol/frontend-monorepo#5634]
## Description

Error: Something went wrong: failed to get party for ID on the governance rewards page 

## Steps to Reproduce

1. Go to https://governance.fairground.wtf/rewards
2. Connect vega browser wallet
3. Switch from total distributed to entered by me 
4. See error: Something went wrong: failed to get party for ID

## Screenshots
![Screenshot 2024-01-17 at 11 59 47](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/e9ac2689-dd66-48a8-96ba-d4faf36320e3)

**Comment by MadalinaRaicu** [comment]
I have seen this on mainnet as well. I am not sure if it is related. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/80abf5c5-b694-4d36-a0f7-c50de87898fc)

**Comment by edd** [comment]
Thanks for looking in to this @MadalinaRaicu. I think the governance page is just rendering an error where it should be saying 'no rewards earned'. This key has no accounts or balances, and thus no rewards, so I'll just improve the error handling
