### ISSUE TITLE
Approve Vega Wallet Connection (CLI wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#564]
As a user
When I have chosen the wallet I want to connect in my Vega CLI Wallet App 
I want to enter my passphrase to authenticate and approve the connection of my wallet to the dapp
So that I can  securely use my assets in the dapp

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
Since this ticket was raised, https://github.com/vegaprotocol/specs/pull/1181 has acceptance criteria for connecting to a wallet. The ACs on this ticket should be added to ones in the specs repo as these are what we write tests against.
see 0001-WALL-017

**Comment by campbellssource** [comment]
I think this ticket should be in https://github.com/vegaprotocol/vegawallet

**Comment by pennyandrews** [comment]
Closing as I believe this is done
