### ISSUE TITLE
Approve Vega Wallet Connection (hosted-wallet)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#565]
As a user
When I have opened my hosted wallet location
I want to be able to specify a wallet and enter my passphrase
So that I can choose which of my wallets I want to use and approve the connection to use with the dapp

Acceptance Criteria
- I can see that the dapp is requesting connect to a wallet

Possible dependency on https://github.com/vegaprotocol/frontend-monorepo/issues/230 https://www.notion.so/vegaprotocol/Hosted-wallet-for-fairground-10d759029b4d4a10a47865ad3f79edb3

<img width="1017" alt="Screenshot 2022-09-01 at 16 56 27" src="https://user-images.githubusercontent.com/46783148/187959248-426c3cc7-9eeb-4ad5-ad8c-10ead8b86d53.png">

**Comment by campbellssource** [comment]
The hosted Wallet is set to auto approve so this is not needed

**Comment by ckpringle** [comment]
Agree - from the above and conversation with Matt, this isn't a thing anymore.
