### ISSUE TITLE
Vega Wallet Connected

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#566]
As a user
When I have approved the connection of my wallet from my wallet app
I want to see confirmation of the connection in the dapp 
So that I know it was successful and that I am now able to stake, trade and govern on Vega with the dapp

<img width="653" alt="Screenshot 2022-09-01 at 16 54 28" src="https://user-images.githubusercontent.com/46783148/187958823-dc977760-e96d-4833-ace4-5f5c034d4230.png">

Flow for context: ![X-platform-ux - Latest wallet connect flow](https://user-images.githubusercontent.com/46783148/187964852-542d98e7-17c7-4e5c-ad59-9887febf1dda.jpg)

**Comment by campbellssource** [comment]
I think this needs to be expanded a bit for some different scenarios and perhaps needs to prompt to select a key. see 0002-WCON-014 in https://github.com/vegaprotocol/specs/pull/1181#

**Comment by pennyandrews** [comment]
This is blocked as it is a common component that is currently being developed in Console, once done it should be a case of TFE gets it for free (but we'll want to verify :) )
