### ISSUE TITLE
Reward page is not looking nicely when using many reward types

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5677]
## Description
When using reward types that are e.g. Average position, average position market a, average position market b etc the tables gets mixed up and are not usable.

https://governance.fairground.wtf/rewards
<img width="1078" alt="Screenshot 2024-01-26 at 12 20 42" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/1cb622fe-17cd-4cc4-9869-9b5a1b863e54">

## Acceptance Criteria

- [ ] Filter out all reward types except global rewards and infra fees since these are the ones relevant for stakers

**Comment by JonRay15** [comment]
Wont do this ... this screen is being decommissioned as this is all now in Console.

Have asked about it

**Comment by JonRay15** [comment]
Someone needs to pick this up for the release as its properly bugged out in FG now

**Comment by mattrussell36** [comment]
@JonRay15 I've made a change to correctly filter out reward types that aren't relevant for the table. Just wanted to double confirm which reward types were expected. Can you confirm what types we want to show?
