### ISSUE TITLE
Improve vesting rewards tooltip 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#5679]
The vesting accounts tooltip doesn't reference the fact that rewards may be locked. It would also be clearer if the number was listed as 25%.

It could also send people to the docs site for more info.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62548908/1303adfb-0955-4253-98b0-61e629a7de11)

See it in action at https://governance.fairground.wtf/rewards as 69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f

Also, I know this site is less likely to be updated, but it seems users are still referring to it for information. And at the moment the wallet sidebar doesn't always match the main section of this rewards page, as there can be rewards that aren't reflected in the main table. Should they just be limited to staking rewards only with a link to console for full rewards?

**Comment by mattrussell36** [comment]
@candida-d can you provide some screenshots with what your seeing about the rewards main table not being in sync with data shown in the sidebar?
