### ISSUE TITLE
Not able to add any info to the textbox for private teams allowed keys

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5699]
## Description

Creating a solo team team does not work since clicking the create button does nothing
https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/ce04fddf-8222-4091-982c-77e5342703af

## Acceptance Criteria

- [x] If using Solo Team the private box and the box to input keys should be hidden
- [x] The title should be chaged to "Create a solo team"
- [x] the create button should actually work
- [x] The edit team button is currently a blue blob

**Comment by JonRay15** [comment]
This is specfiic to the Solo team .... which you cannot add ppl to.

So it works .. but it would be clearer if the box was hidden copletely

**Comment by JonRay15** [comment]
OK the create part definitely doesnt work
