### ISSUE TITLE
Change loader component to not use Math.random

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#570]
Loader component causes issues when its rendered server side. See here https://github.com/vegaprotocol/frontend-monorepo/pull/507#discussion_r896528340

![Image](https://user-images.githubusercontent.com/47143694/214879993-3cbdb266-8415-4fd9-8f44-edabd439808f.png)

**Comment by macqbat** [comment]
Reopened, because there is still some things to improve: let's have one static version with no re-rendes in interval basics on css animation only
