### ISSUE TITLE
Large loss socialisation in console before closing a position

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5720]
## Description
A user reported a bug where it gets info that they have a big loss socialisation, the number is huge as you can see they have not closed any positions nor have they have had anything near those values.

<img width="1093" alt="Screenshot 2024-02-01 at 16 26 25" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/379fd881-4275-4cec-b0a2-7fe623574f09">

**Comment by JonRay15** [comment]
This is a Core bug which is bein addressed here

https://github.com/vegaprotocol/vega/pull/10573
