### ISSUE TITLE
Leaderboard ranking gets changed when searching

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5729]
## Description

Go to https://vegafairground.eth.limo/#/competitions/teams and start searching for a team, the one you search for suddenly becomes number 1, I guess it only does count on the filtered response.

## Steps to Reproduce

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/dd91a79c-af9e-4fc7-a2c7-30ab7821200b

**Comment by JonRay15** [comment]
haha ... yes ... indeed it does ... we should fix
