### ISSUE TITLE
Token Front End should display the correct reward types on screen

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/frontend-monorepo#573]
Currently the staking / rewards view on TFE shows a long list of rewards for a Vega wallet. However there are duplicates marked 'staking' when actually the type is now returned from the API, so user can see if they have staking reward, infra reward, etc

<img width="894" alt="Screenshot 2022-06-16 at 08 42 34" src="https://user-images.githubusercontent.com/149245/174038312-9b1d540a-4ed1-41d6-8e6e-b405ec1b6eef.png">

**Comment by gordsport** [comment]
**Notes:**
there is a `rewardType` which on the smaller one (in this example) will be infraFees. The type is being send from core/data-node correctly however needs to be presented correctly in the UI.
