### ISSUE TITLE
Console is not showing browser wallet errors in toasts

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#5736]
## Description

Console is not showing browser wallet errors in toasts

## Steps to Reproduce

1. Attempt to place an invalid tx on console (e.g. transfer without enough money in account)
2. Place transaction
3. Observe generic error toast without error message saying "you don't have enough funds"

The result is all transaction placed by browser wallet that are rejected in the CheckTx or DeliverTx phase within tendermint are not shown to the user. Resulting in confusion as to what went wrong with the transaction.

## Expected behaviour

I should see the decoded error message that is returned from the transactions endpoint.

## Additional context

Generally the problem here is that the connectors are not presenting a generic interface for errors, the connectors do not conform to an interface properly which is causing the implementation details to leak into other areas of the code.

The error handling function relies on implementation details within the JSON RPC connectors that are not guaranteed to be consistent with the other connectors. Utilising types that are specific to this connector to create an error handling implementation that is tied to specific connectors defeating the purpose of extracting to an interface.

https://github.com/vegaprotocol/frontend-monorepo/blob/develop/libs/proposals/src/lib/proposals-hooks/use-vega-transaction.tsx#L44-L55

Each connector should have the following:

```
sendTx() {
try {
    await sendTransaction() // In some manner
  } catch (e) {
    throw new TransactionError(hash, message, data) 
  }
}
```

Where TransactionError is a consistent type that extends Error. Handling of connector specific errors should be done within this catch, for example the "NO_SERVICE" error in the above linked function.

**Comment by JonRay15** [comment]
This might go away with the work Matt has been doing on the connection box.
