### ISSUE TITLE
Token frontend change page width in Proposal

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#574]
Page width is changed when going from Governance to specific Proposal. In result of that, part of Wallet widgets are cut off
<img width="1440" alt="Screenshot 2022-06-16 at 14 25 18" src="https://user-images.githubusercontent.com/24473278/174080177-821beaeb-d681-49d2-92db-d3ee46ee21b4.png">
<img width="1440" alt="Screenshot 2022-06-16 at 14 21 00" src="https://user-images.githubusercontent.com/24473278/174080203-bfeccb97-2957-4c2d-a660-3aae8a55f2ba.png">
.

**Comment by sam-keen** [comment]
Fixed this as part another ticket
