### ISSUE TITLE
Show Node switcher on Loading screen of console

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5759]
### Fix the loading spinner thingy

- [ ] It seems one of these issues is caused specifically by the app (both Governance & Console) thinking that it has a token from a wallet connection and then the wallet wants the connection to be approved via the wallet being unlocked to load the page

### Show node selector on timeout

- [ ] If it is NOT the above problem and it is just datanode taking ages so console is taking too long to load, show the option to open the manual node switcher and manually choose a node.

After x time (3 seconds maybe)
Show a message 

> “It looks like you’re connection is slow, try switching to another node… ”

with a CTA to open the manual node switcher.

Can we also detect the conditions of that Lovali node?  Ie. if its just "no data" can we detect that and prompt the node switcher too?

### Add copy button to node selector

- [ ] Its infuriatingly hard to copy a node address from this screen ... can we add a copy button

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/6a43e225-320f-4bea-91dc-ef3e20847074)

**Comment by JonRay15** [comment]
Just had this issue again ... here is a screenshot of console 



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0d6d9899-3bab-492d-ad2c-6d9a42bf7b0d)

**Comment by JonRay15** [comment]
Unlocked wallet ... still gettin this 



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/433134a0-0a32-4bef-97e5-365ce2b1006e)

**Comment by JonRay15** [comment]
Fixed it the only way I know how ... cleared all local storage
