### ISSUE TITLE
Tweaks to explorer asset view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5802]
## The Chore

The asset view is a bit screwed up currently ... it is showing account balances for things ike this:

<img width="1136" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c6859fbf-eab7-4db3-a6a8-3024b902a983">

When those things only ever have a balance for a split second at the end of ann epoch when the transfer comes in before it is distributed as rewards.

We think we should change this ...

## Option 1

- [ ] Only display the following accounts for each asset 
  - [x] ACCOUNT_TYPE_NETWORK_TREASURY
  - [ ] ACCOUNT_TYPE_INSURANCE (this is per market so you'll have to pull in the market name too from the markets API)
  - [x] ACCOUNT_TYPE_GLOBAL_INSURANCE

## Option 2 

- [ ] Just display any account that has a "non-crumb" balance
- [ ] Assess the crumbiness of a balance by showing any account with more than 10 `quantum` of that asset in it

## Additional details / background info

- [x] Obviously we'll always need to adjust all balances for asset decimals
- [x] Do this in the component as it applies everywhere

**Comment by edd** [comment]
<img width="704" alt="Screenshot 2024-04-22 at 15 00 22" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/677376e5-8b59-4283-b280-1652ad286293">

<img width="783" alt="Screenshot 2024-04-22 at 15 00 43" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/60988002-d26d-443e-89dc-f1024737d8e3">
