### ISSUE TITLE
Reward card colour changes

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5803]
## The Chore

We are re-using some colours on the reward cards on the rewards ad competitions page.

Suggest we change it to be 

- [x] Liquidity provision - blue
- [x] Price making - pink
- [x] Price taking - Green
- [x] Average position - Orange
- [x] Relative returns - purple
- [x] Returns volatility - yellow
- [x] Network / boring rewards - White
  - [x] Staking rewards
  - [x] Validator ranking
  - [x] Market creation

**Comment by asiaznik** [comment]
Should we display "Ended" or something else for cards like that:

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/e7599653-a9fa-4978-8bfd-399b7ad621fd)

It says ended in -27 epochs, which is technically fine, but I think we could do better, e.g. "Ended", etc.
