### ISSUE TITLE
Update reward cards to play nicely with new transfer API default page size

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5804]
## The Chore

The default page wise for transfer API will change from 1000 to 50 because Edd doesn't have enough buckets to handle the data :-D

## Tasks

- [ ] check rewards page
- [ ] check competitions page

## Additional details / background info

Core 🎫  https://github.com/vegaprotocol/vega/issues/10685

Pagination bug 🎫  https://github.com/vegaprotocol/vega/issues/10837

**Comment by asiaznik** [comment]
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1709735484822469
