### ISSUE TITLE
Check all console queries to ensure they do not rely on a default page size of 1000

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#5805]
## The Chore

in 0.74.x, the transfers API is getting a smaller default page size: https://github.com/vegaprotocol/frontend-monorepo/issues/5804. Formerly it was 1000. Now it is 100.

Queries can provide a bigger page than 100 if they need it.

This ticket is to check all queries/pages to make sure they're not built relying on a default page size of 1000

**Comment by mattrussell36** [comment]
All queries in console use pagination
