### ISSUE TITLE
Check all explorer & governance queries to make sure they don't rely on a page size of 1000

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#5806]
## The Chore

in 0.74.x, the transfers API is getting a smaller default page size: https://github.com/vegaprotocol/frontend-monorepo/issues/5804. Formerly it was 1000. Now it is 100.

Queries can provide a bigger page than 100 if they need it.

This ticket is to check all queries/pages to make sure they're not built relying on a default page size of 1000

## Tasks

```[tasklist]
### Tasks
- [ ] Proposals Data Provider does not suport pagination
```

**Comment by mattrussell36** [comment]
The only query using this appears to be 

https://github.com/vegaprotocol/frontend-monorepo/blob/feat/squid-sdk/apps/explorer/src/app/routes/treasury/TreasuryTransfers.graphql

which is set to get the first 200
