### ISSUE TITLE
Changes to market info for mark price, funding, and settlement

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#5809]
## High Level

We need to fix the market info so that it shows appropriate information for futures and perps for the mark price, funding and settlement info. At the moment these are slightly confused between perp and future so we need to clear that up.

We also want to seperate out the data source "config" from the data source "spec".
- "Config", meaning which data sources are being used (and how) to drive mark price / funding etc will live in the [market accordian](https://explorer.vega.xyz/markets/4e9081e20e9e81f3e747d42cb0c9b8826454df01899e6027a22e771e19cc79fc) which is shared between Explorer and Console
- "Spec", meaning the actual technical specification of those external data sources will live in the [Explorer](https://explorer.vega.xyz/oracles/c4791bc15a1c6608e52c78843c6065562ee8be8e562cd2766b319594818eabda) page and hopefully this will help simplify what we show in the accordian

Finally, we want to do soome minor cleanup / consolidation of other items on the market info to make it more understandable.

### Add Mark Price section to the market accordian for both Perps and Futures

- [x] Add new header for "Mark Price" (tooltips can be taken from [here](https://docs.vega.xyz/mainnet/tutorials/proposals/new-perpetuals-market#mark-price-configuration))
  - [x] Composite Price Type - Median / Weighted
  - [x] Sources (list all, first two will always be there, external sources there can be 0 to many)
    - [x] Trade price
    - [x] Book mid price
    - [x] External source 1 to n 
    - [x] Median price
  - [x] If median just list them, if weighted then for each source show "Weight: XX%"
  - [x] For each source show the source staleness tolerance "Staleness Tolerance: Xm" 
  - [x] For the TWAP of the book mid price show the cashAmount and convert for asset decimals
  - [x] For the twap of the trade price show the DecayWeight & DecayPower
  - [x] For each external source provide a link to the [oracle page in explorer](https://explorer.vega.xyz/oracles/c4791bc15a1c6608e52c78843c6065562ee8be8e562cd2766b319594818eabda)
  - [x] If the config is source weighted and a source has zero weight dont show it at all
  - [x] If the config is `COMPOSITE_PRICE_TYPE_LAST_TRADE` simply display "Last trade price"
  - [ ] If the config is `COMPOSITE_PRICE_TYPE_UNSPECIFIED` simply display "Unspecified"

#### Example output Median

- Composite price type : Median
- Sources
  - Trade price 
    - Staleness tolerance: 1m
    - Decay weight : 1
    - Decay power : 1
  - Book price
    - Staleness tolerance: 1m
    - Cash amount : 1000 USDT
  - Price oracle 1
    - Staleness tolerance: 1m
    - Oracle specification (link)
  - Price oracle 2
    - Staleness tolerance: 2m
    - Oracle specification (link)
  - Median price
    - Staleness Tolerance: 1m

#### Example output Weigted

- Composite price type : Weighted
- Sources
  - Trade price 
    - Source Weight : 20%
    - Staleness tolerance: 1m
    - Decay weight : 1
    - Decay power : 1
  - Book price
    - Source weight : 30%
    - Staleness tolerance: 1m
    - Cash amount : 1000 USDT
  - Price oracle 1
    - Source weight : 50%
    - Staleness tolerance: 1m
    - Oracle specification (link)
  - Median price
    - Staleness Tolerance: 1m

#### Example config

```
"markPriceConfiguration": {
                        "decayWeight": "1",
                        "decayPower": "1",
                        "cashAmount": "5000000",
                        "sourceWeights": [],
                        "sourceStalenessTolerance": [
                            "1m0s",
                            "1m0s",
                            "1m0s",
                            "1m0s"
                        ],
                        "compositePriceType": "COMPOSITE_PRICE_TYPE_MEDIAN",
                        "dataSourcesSpec": [
                            {
                                "external": {
                                    "ethOracle": {
                                        "address": "0x719abd606155442c21b7d561426d42bd0e40a776",
                                        "abi": "[{\n    \"inputs\": [\n      {\n        \"internalType\": \"bytes32\",\n        \"name\": \"id\",\n        \"type\": \"bytes32\"\n      }\n    ],\n    \"name\": \"getPrice\",\n    \"outputs\": [\n      {\n        \"internalType\": \"int256\",\n        \"name\": \"\",\n        \"type\": \"int256\"\n      }\n    ],\n    \"stateMutability\": \"view\",\n    \"type\": \"function\"\n    }]",
                                        "method": "getPrice",
                                        "args": [
                                            "/2FJGpMREt3xvYFHzRtkE3X3n1glEm1mVICHRjT9Cs4="
                                        ],
                                        "trigger": {
                                            "timeTrigger": {
                                                "every": "60"
                                            }
                                        },
                                        "requiredConfirmations": "3",
                                        "filters": [
                                            {
                                                "key": {
                                                    "name": "eth.price",
                                                    "type": "TYPE_INTEGER",
                                                    "numberDecimalPlaces": "18"
                                                },
                                                "conditions": [
                                                    {
                                                        "operator": "OPERATOR_GREATER_THAN",
                                                        "value": "0"
                                                    }
                                                ]
                                            }
                                        ],
                                        "normalisers": [
                                            {
                                                "name": "eth.price",
                                                "expression": "$[0]"
                                            }
                                        ],
                                        "sourceChainId": "100"
                                    }
                                }
                            }
                        ],
                        "dataSourcesSpecBinding": [
                            {
                                "priceSourceProperty": "eth.price"
                            }
                        ]
                    }
                },
```

### Expand Funding section to the info for perps

- [x] Currently funding section just contains scheulde, scaling factor, upper bound, and lower bound.... these are fine
- [x] Add the "Index Price" showing simply the contract address and a link to the [Explorer page](https://explorer.vega.xyz/oracles/c4791bc15a1c6608e52c78843c6065562ee8be8e562cd2766b319594818eabda) taken from the `dataSourceSpecForSettlementData` section
- [x] Add a section for "Internal composite price"  (this is identical to above including the last price and unspecified part)
- [x] Remove the section under "Oracle" since this is now covered by the Index Price section and the explorer page

```
"internalCompositePriceConfig": {
                                    "decayWeight": "1",
                                    "decayPower": "1",
                                    "cashAmount": "50000000",
                                    "sourceWeights": [
                                        "0",
                                        "0.999",
                                        "0.001",
                                        "0"
                                    ],
                                    "sourceStalenessTolerance": [
                                        "1m0s",
                                        "1m0s",
                                        "10m0s",
                                        "10m0s"
                                    ],
                                    "compositePriceType": "COMPOSITE_PRICE_TYPE_WEIGHTED",
                                    "dataSourcesSpec": [
                                        {
                                            "external": {
                                                "ethOracle": {
                                                    "address": "0x719abd606155442c21b7d561426d42bd0e40a776",
                                                    "abi": "[{\n    \"inputs\": [\n      {\n        \"internalType\": \"bytes32\",\n        \"name\": \"id\",\n        \"type\": \"bytes32\"\n      }\n    ],\n    \"name\": \"getPrice\",\n    \"outputs\": [\n      {\n        \"internalType\": \"int256\",\n        \"name\": \"\",\n        \"type\": \"int256\"\n      }\n    ],\n    \"stateMutability\": \"view\",\n    \"type\": \"function\"\n    }]",
                                                    "method": "getPrice",
                                                    "args": [
                                                        "/2FJGpMREt3xvYFHzRtkE3X3n1glEm1mVICHRjT9Cs4="
                                                    ],
                                                    "trigger": {
                                                        "timeTrigger": {
                                                            "every": "60"
                                                        }
                                                    },
                                                    "requiredConfirmations": "3",
                                                    "filters": [
                                                        {
                                                            "key": {
                                                                "name": "eth.price",
                                                                "type": "TYPE_INTEGER",
                                                                "numberDecimalPlaces": "18"
                                                            },
                                                            "conditions": [
                                                                {
                                                                    "operator": "OPERATOR_GREATER_THAN",
                                                                    "value": "0"
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    "normalisers": [
                                                        {
                                                            "name": "eth.price",
                                                            "expression": "$[0]"
                                                        }
                                                    ],
                                                    "sourceChainId": "100"
                                                }
                                            }
                                        }
                                    ],
                                    "dataSourcesSpecBinding": [
                                        {
                                            "priceSourceProperty": "eth.price"
                                        }
                                    ]
                                }
                            }
                        },
```
See e.g. https://api.n00.stagnet1.vega.rocks/api/v2/markets 

### Correct the settlement data for Futures 

- [x] For futures market it should be simple
  - [x] There is still mark price config as above 
  - [x] There will be on funding section 
  - [x] The "Oracle" section should be renamed "Termination & Settlement"
    - [x] Add the Termination oracle showing simply the contract address with a link to explorer
    - [x] Add the Settlement oracle showing simply the contract address with a link to explorer

**Comment by JonRay15** [comment]
There are two other modes for composite price:

- COMPOSITE_PRICE_TYPE_UNSPECIFIED
- COMPOSITE_PRICE_TYPE_LAST_TRADE

In both these cases the rest of the spec will be empty so simply display the text "Last price" or "Unspecified"


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2dfabf68-63b5-4905-a34a-263118459acd)
