### ISSUE TITLE
Weird unnecessary scroll bar on portfolio can't be scrolled

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5833]
There is a scroll bar on portfolio that isn't required but also can't be scrolled all the way across to the left:
https://vegafairground.eth.limo/#/portfolio
key: deb93af569474ae0d1b05c2fe83def238e4545be72778139c67df7c2af855fc2

<img width="1174" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/570ba12c-531f-4875-a31d-5170fef75c05">

**Comment by JonRay15** [comment]
Its all getting reworked anyway so killing this
