### ISSUE TITLE
Explore adding a historic candle diff to Vaguer

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5836]
## The Chore

We have seen cases where datanodes have no candle data exists on a given node despite that node having a perfectly good response time, current block, and a good score on Vaguer.

Anyvalid node right now 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/454c1425-175a-47ec-9d83-277c7c644604)

Diff between AnyValid node and Darling node on candles
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/82ba86d2-6982-41d1-8854-de872fa605d5)

You get no indication whatsoever in Console that you are looking at borked data.

## Tasks

- [x] Explore whether we can add some sort of candle diff to Vaguer
- [ ] Explore options for getting Vaguer score into the node picker - cant remember why we still havent done this

**Comment by edd** [comment]
https://github.com/vegaprotocol/vaguer/pull/37
