### ISSUE TITLE
flash of wallet error when on wrong network

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5870]
I have connected my ethereum wallet and get in a state when the page constantly flashes showing an error.
MetaMask Version
11.7.5

fairground:
ca64516a5223c3d1f0d4ababc98600ff14f185a5

## Screenshots

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/fefef661-5e15-43c6-b86f-c8799097397a)

https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/7fc82924-d747-4554-a5ed-85711cb89d01

**Comment by JonRay15** [comment]
Try this on some different brosers

**Comment by bwallacee** [comment]
Can't recreate it anymore on chrome. Closing
