### ISSUE TITLE
Wrong trading view chart on mainnet console

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/frontend-monorepo#5878]
The BTC market show the chart of the LDO market.

<img width="1562" alt="Screenshot 2024-02-28 at 12 46 52" src="https://github.com/vegaprotocol/frontend-monorepo/assets/4346460/28126b08-76d0-4ff5-bdd6-3e8f353a13ce">

**Comment by JonRay15** [comment]
Fixed
