### ISSUE TITLE
Show percentage spread on market overview spread column

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#5887]
At the moment we show spread as an absolute value:
<img width="157" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/036a922f-8412-4751-a7b4-41b5e554fe09">

Could we add percentage (relative to mid say)? Maybe for spread we may prefer to show bps (basis points).

**Comment by JonRay15** [comment]
Going to include this in the  market page overhaul ... dont do it yet,

**Comment by JonRay15** [comment]
Included as AC on #5095
