### ISSUE TITLE
Black screen when trying to connect vega wallet that is in get started state

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5931]
Currently if you try to connect to vega wallet that is in the get started state, you get a black screen with no messaging.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/bc5cb75a-22c1-4291-b2ec-6f625bb63e9b)

**Comment by JonRay15** [comment]
Fixed in Matt's changes
