### ISSUE TITLE
Market Details component links to wrong chain for arbitrum oracles

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#5956]
I am looking at the eigenLayer points proposal: https://explorer.vega.xyz/markets/fc37a1eedb6e57b86823e2fc42480a0b9236aea556c1d7df49be697a93f8f2a0
and 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/ceb4f8ce-548e-4b21-9a74-6a6338c8bb0a)

the View on Etherscan https://etherscan.io/address/0x302461E6dBF45e59acb3BE9a9c84C0a997779612 takes me to an address that doesn’t exist. I think since in the proposal we have
```
"sourceChainId": "42161"
```
it’s not actually Ethereum it’s Arbitrum since this is in network parameters:
```
{
      "network_id": "42161",
      "chain_id": "42161",
      "confirmations": 3,
      "name": "Arbitrum One",
      "block_interval": 50
    }
```

**Comment by edd** [comment]
Aha - `oracles/4126133c5a3777cfa7f03b9d1dd46db4644376873d5284b73e1f1b1baf963109` does the correct linking. The market details panel does not.
