### ISSUE TITLE
Checking out current margin triggers unwanted order

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#6003]
### Discussed in https://github.com/orgs/vegaprotocol/discussions/211

<div type='discussions-op-text'>

<sup>Originally posted by **brunswyck** March 13, 2024</sup>

https://github.com/vegaprotocol/feedback/assets/5129017/d956e906-23fb-4aec-8748-2c47b64f328a

</div>

**Comment by daunatv** [comment]
Retested this on Fairground and click to check margin does indeed act as as if you pushed the place order button
