### ISSUE TITLE
Vega reward pot decimals have gone haywire on fairground

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6022]
## Bug description

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/a18b750b-5b9c-499c-b36d-8ab190187ad9)

## Tasks

- [ ] Only show 2 DP for VEGA, or use quantum formatting ideally

**Comment by MadalinaRaicu** [comment]
Not sure this is the best approach. I believe this is not a bug.

**Comment by JonRay15** [comment]
Testnet asset config issue ... closing
