### ISSUE TITLE
Allow more space for market codes in the market selector

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#6028]
## The Chore

We need to allow more space in the market selector to accomadate longer codes for points markets

## Tasks

- [ ]
- [ ]

![image (2)](https://github.com/vegaprotocol/frontend-monorepo/assets/6803987/85ba67ce-9c3e-473e-b5bd-41ab1e5e7f3c)

**Comment by MadalinaRaicu** [comment]
we should enlarge the popover a bit to have enough space for names and prices 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/f77cc6f4-44b6-42ba-9191-25afaa423962)
