### ISSUE TITLE
Add governance transfers to rewards cards

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6048]
## The Chore

Filter for reward cards needs to include governance transfers

These can be identified by filter `RecurringGoveranceTransfer`

## Tasks

- [x] update queries and conditions

**Comment by MadalinaRaicu** [comment]
the thing with `RecurringGovernanceTransfers` is that the dispatchStrategy is null so there are fields that we’re missing to build the content of the cards

**Comment by MadalinaRaicu** [comment]
Possibly not needed after https://github.com/vegaprotocol/vega/pull/10947
RecurringTransfers should include RecurringGovernanceTransfers
