### ISSUE TITLE
[trading] Displaying "trading mode continuous"

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#609]
I don't think this "trading mode continuous" is a useful bit of information
<img width="563" alt="image" src="https://user-images.githubusercontent.com/62546419/174879187-f4f4a2ba-fb43-4af6-b41d-aca6cbe15404.png">

This is the default trading mode and for the foreseeable future there will only be one: "continuous trading". To me it's actively confusing as the market is often in auction and it still says "trading mode continous". I'd suggest we remove that field entirely.

**Comment by PeteWilliams** [comment]
@davidsiska-vega The intention here was that this would show whether the market is in auction, or in standard mode.

It looks at though it's using `tradingMode` which, as you say, always shows 'continuous'. It looks like if we used `data.marketTradingMode`, it would return Continuous/OpeningAuction/MonitoringAuction.

If that's right, would you be happy with using this and having 'Standard/Auction' displayed here?
I'm assuming that 'standard' is more intuitive to a user than 'continuous' and that they don't need the granularity of opening/monitoring auction here - though that will still be available in the market data tab.
