### ISSUE TITLE
Transaction list in portfolio

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6101]
## Story

As a user
I want to see a full list of transactions I have made
So that I know what I have done

## Acceptance Criteria

Note; this ticket is a stepping stone to a large rework of the portfolio page, but for now we will aim to create the transaction list simply in teh current AG grid structure.  After this we can move it into the new design Joelle is working on.

- [x] Modify the Collateral / Deposits / Withdrawals table in Portfolio to be Collateral & Transaction List, where this list combines all of deposits, transfers and withdrawals into a single structure
- [x] Need a way to fetxh some number of deposits, withdrawals and transfers for the connected key and order them by timestamp descending, such that we can load more if needed and dont lose any rows
- [x] A list of all transactions showing the following columns
  - [x] Type (deposit, transfer in, transfer out, withdrawal)
  - [x] Asset code (looked up from assets API)
  - [x] Datetime
  - [x] Amount (converted with asset decimals from assets API)
  - [x] To / From
  - [x] Status 
- [x] To / From field will be conditional
  - [x] For deposit it will always be the source ERC20 address
  - [x] For transfer TO the current key show the sender Vega key
  - [x] For transfer FROM the current key show the recipient Vega key
  - [x] For withdrawal show the ERC20 address
- [ ] Status will also be conditional
  - [x] For deposit: 
    - [x] Show "Pending (X / Y Confirmations)" 
    - [x] Then show "Complete"
  - [x] For withdrawal
    - [ ] ~~Show "Pending - approve in wallet" while waiting for wallet~~ N/A
    - [x] Then "Pending - sent from network" once a txHash is available
    - [x] Then "Complete - received on target network" once a ref is available (i think)
  - [x] For transfer 
    - [ ] ~~Show "Pending - approve in wallet" while waiting for wallet~~ N/A
    - [x] Then "Complete" once done ... dont think it is worth an interim message when its so fast
- [x] Should be possible to filter on the type to view only deposits / transfer / withdrawals
- [x] There is currently a consditional "deposit" and "make withdrawal" button .... remove these since there will be a new panel due to #6267 
- [x] Make sure we are showing all withdrawals correctly; there is a suspision in mainnet currently that we're doing something wrong here and hence not showing failed withdrawals ... but with extra Console validation now its very hard to verify this 
  - [x] Must ensure if there are STATUS_REJECTED withdrawals we are showing them... this might mean we need to be able to sign withdrawals under the required minimum and send them so Core fails them instead of Console / VegaWallet
  - [x] Must ensure we're showing STATUS_OPEN withdrawals when they appear ... this will be very brief since it only lasts the time it takes the validators to process, but we need to show it
  - [x] If it is STATUS_FINALISED and there is no txHash that means it has not been finalised on ethereum and we need to show a status for this, and a prompt to "Complete withdrawal"
  - [x] IF it is STATUS_FINALISED and has a txHash then it is fully complete
- [x] Ensure that transfers both TO and FROM are shown
- [x] Ensure that pending and failed / rejected withdrawals are shown
- [x] Show the chain name in brackets after the asset code
- [x] If there are incomplete withdrawals 
  - [x] We should pin these to the top of the list and potentially highlight them in some way
  - [x] We should add some sort of indicator to the menu to highlight the Portfolio page in the nav so they know to go there and complete it.

## Sketch

Suggest the easiest way to initially build this thing is to enhance the current table which shows collateral / deposits / withdrawals

That way we can do the backend work and just dump it into new tabe here. 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b0cbf7b8-3950-4b94-8143-e1caa327944b)

Then in the long term Joelle is doing a redesign of this page to land on somethign more like the below.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/6c65d000-1e2d-4ba7-96df-2ec6f4654836)

## Additional details / background info

Summary of logic:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1cf08646-261c-4afe-89ec-7727c9a92f3a)

**Comment by mattrussell36** [comment]
@JonRay15 I don't think its worthwhile showing a pending state for transfers. There isn't a great way to acheive this and the value is super low

**Comment by JonRay15** [comment]
See PR for comments and feedback .... there are two new bits at the bottom
