### ISSUE TITLE
Update eligibility checks to use the intra-epoch numbers from Core once available

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6134]
## Description

When setting up a reward with a notional average position requirement that starts in the same epoch as you sent it, the console rewards indicates that you do not fulfil the average position requirement, you do however receive the reward.

## Steps to Reproduce

1. Setup a reward with notional average position requirement that starts in the same epoch as you set it up.
2. Check rewards page and see if you fulfil the requirement. 

## Expected behavior

Since the requirement is fulfilled you should qualify for the reward.
See the screenshot where one reward says I have 127k+ average position, while the new reward I just setup that requires 95k says that I do not fulfil the requirement. 

## Screenshots
![Screenshot 2024-03-28 at 13 13 57](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/96bb1f9e-bc85-4259-a2d2-a1f9506740f2)

**Comment by JonRay15** [comment]
Wil be covered by https://github.com/vegaprotocol/vega/issues/11056

**Comment by JonRay15** [comment]
Closing this and covering under #6075
