### ISSUE TITLE
Mainnet - Competitions and Rewards are not visible in console

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6137]
## Description

Even though there are games and rewards active they are not visible in Console.

## Steps to Reproduce

1. Go to (https://vegaprotocol.eth.limo/#/competitions) and or https://vegaprotocol.eth.limo/#/rewards
2. See that there are no rewards live according to them
3. See this example of a reward that should be visible for games (and rewards page)
A: https://explorer.vega.xyz/txs/dbf2f58833cb30ee26eb8736e70fa6348d9c62457278a2e7e9b215346f5d1a7e
And this for rewards (but not games)
B: https://explorer.vega.xyz/txs/a8aca94f3e8aa58201b89ff7782b5e005fa4564dbcc201d34e4aa326142555b0

## Expected behavior

A: should be visible on rewards and games page
B: should be visible on rewards page

## Screenshots
![Screenshot 2024-03-28 at 19 49 00](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/f140c299-d402-443c-8d8e-a6250096ec7e)

![Screenshot 2024-03-28 at 19 48 50](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/b9a578bb-0f05-4e60-a670-0971cc22181a)

**Comment by MadalinaRaicu** [comment]
pushing [v0.25.10](https://github.com/vegaprotocol/frontend-monorepo/releases/tag/v0.25.10) to Fairground should fix the issue

**Comment by bwallacee** [comment]
Retested and i believe we can close this
