### ISSUE TITLE
Bug: Can't exit the pop up after transaction is complete on governance dApp

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#6174]
### Discussed in https://github.com/orgs/vegaprotocol/discussions/213

<div type='discussions-op-text'>

<sup>Originally posted by **edoatvega** April  5, 2024</sup>
<img width="517" alt="Screenshot 2024-04-05 at 09 55 01" src="https://github.com/vegaprotocol/feedback/assets/99248850/5fabcf7a-55de-4557-a9df-8d1ef250211f">

After you vote using the governance dApp UI and the transaction complete pops up you can’t exit out of it</div>

**Comment by JonRay15** [comment]
Potentially this is a new regression.
