### ISSUE TITLE
Node switcher

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/frontend-monorepo#622]
Some users will want to know where the website is reading 

Suggest doing this in the footer.

<img width="1440" alt="Screenshot 2022-06-22 at 13 55 17" src="https://user-images.githubusercontent.com/13255539/175034109-62d3f2d8-4490-443a-adc4-0e94d020a7ff.png">

This opens a component that is shared across apps for switching between known nodes.
https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-system?node-id=1386%3A67731

Moved this from https://github.com/vegaprotocol/token-frontend/issues/931

**Comment by campbellssource** [comment]
For mobile a scroll bar to deal with the horizontal overflow would be acceptable (as this is something that will be common given the fact we want to support data rich tables and user customisation).
But something like [this (Figma link)](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-system?node-id=3736%3A93119) would be preferable:
<img width="1507" alt="Screenshot 2022-06-27 at 12 17 21" src="https://user-images.githubusercontent.com/13255539/175929554-dd0c646b-2462-48c5-9fc3-fc4869cbde7f.png">
Notes: it would be good to find a general patter for turning an AG grid into a card on smaller view ports but this table it probably not an AG grid.
Also, The mock up uses a proposed UI toolkit item "[breakdown](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-system?node-id=1115%3A69458)"

**Comment by notbot00** [comment]
was done as part of https://github.com/vegaprotocol/frontend-monorepo/issues/718
