### ISSUE TITLE
Market info is missing some details. e.g. open interest, liquidity, IDs, Risk

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#625]
The current market info is missing some detail.

- [x] **Open interest**
```
{
  markets{
    data{
      openInterest
    }
  }
}
```
This, along with 24 hour volume gives the user a sense of how popular the market is. it is also of interest to liquidity providers. 
This is a sum size of all the open positions. (note: futures are zero sum so if 10 people are long 10 there are also 100 contracts short. so an open interest of 100)
This should be displayed as a regular int without any unit. (it's tempting to put the price in here but in some cases that could be invalid (e.g a has rate). if anything the unit is "Futures" aka "contracts.
This should go after bid/offer volume in the Market data section

- [ ] **24 hour volume**
This can be retrieved from the `market.candles(1h, since 24 hours ago).volume` but it would be neater to have this in  `markets.data.24 traded volume`
This, along with open interest, gives the user a sense of how popular the market is. It is also of interest to liquidity providers.
This is a sum of the contracts that have matched or traded in the last 24 hours. like open interest it would be zero sum.
It should be shown after open interests, without a unit.
(This [data node ticket](https://github.com/vegaprotocol/vega/issues/5688) could also give us 24 traded vol)

- [ ] **Insurance pool**
```
{
  markets{
    accounts{
      type
      asset {
        id
      }
      balance
    }
  }
}
```
Where type == `Insurance`
This represents an amount of tokens (the settlement asset) that have been "collected", for the purposes of preventing loss socialisation. (There may be other uses I don't know)
It should be displayed after 24hour volume. with a unit of the settlement asset. 👇 (I guess this will already be in memory)
```
{
  markets{
    tradableInstrument{
      instrument{
        product{
          ...on Future{
            settlementAsset{
              symbol
            }
          }
        }
      }
    }
  }
}
```

- [x] **Total fee**
This is just a sum of all the fees. and it the main number most traders will care about (although we do need to display the others)
![Image](https://user-images.githubusercontent.com/13255539/175259609-639366b0-6e80-42d0-8c4e-ce826ce4159c.png)

**Liquidity info** Wait until we do more thinking on this: https://github.com/vegaprotocol/frontend-monorepo/issues/491 it could be that some liquidity info goes in this panel and some goes in a dedicated one, or all of it goes in the dedicated panel
 
**Oracle details** to be done in a [separate ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/626):
```
{
  markets{
    tradableInstrument{
      instrument{
        product{
          ...on Future{
            oracleSpecBinding{
              tradingTerminationProperty
              settlementPriceProperty
            }
            oracleSpecForSettlementPrice{
             ...
            }
            oracleSpecForTradingTermination{
              ...
            }
          }
        }
      }
    }
  }
}
```

- [x] **Market ID** 
```
markets{
    id
}
```
This is useful for API users who will need the market ID to submit orders it

- [x] **product type**
```
{
  markets{
    tradableInstrument{
      instrument{
        product{
          ...on Future{
```
the `...on Future` here is to show that this instrument is on of the built in product types.
At the moment there are only futures, but in the future this to include things like `spot`, `Perpetual`, `Contract for difference` `European option`, `inverse future`.

This product type should be show after the market name and code.

- [x] Market **code**
each market intrument has both a name and a code. The code should be shown after name. The code will be used instead of name in some places where space is a premium

- [x] **Instrument ID** (optional)
This is optional as I think right now it doesn't have any utility. In the future it will be possible to have more than one market use a single instrument.

- [x] **All the risk model spec**
```
{
  markets{
    tradableInstrument{
      riskModel{
        ...on LogNormalRiskModel{
          tau
          params {
            r
            mu
            sigma
          }
          riskAversionParameter
        }
      }
    }
  }
}
```

- [x] Labelling issue: Instrument
The "Instrument" section only contains detail on the settlement asset. implying that the settlement asset **is** the instrument, but actually the instrument is the "type of derivative", at the moment they are all "Futures", but one day there will be Perpetuals, Inverse futures, Options, CFDs etc.
I suggest including all the info from xxx 👇 .
```
{
  markets{
    tradableInstrument{
      instrument{
        product{
          ...on Future{
            xxx
          }
        }
      }
    }
  }
}
```
![Image](https://user-images.githubusercontent.com/13255539/175263596-da347306-aa75-4dde-85d1-8dd3dd6a18b3.png)

- [x] **Metadata**
Display all the meta data on a market. raw json If needed, and typed where known.
<img width="569" alt="Screenshot 2022-06-23 at 11 52 44" src="https://user-images.githubusercontent.com/13255539/175282816-cf8c06ac-4885-4bd3-a323-b445edf4b6a5.png">

- [x] **Liquidity monitoring spec**
 ```
{
  markets{
    liquidityMonitoringParameters{
      triggeringRatio
      targetStakeParameters{
        timeWindow
        scalingFactor
      }
    }
  }
}
```
This to go after the price monitoring section.

----

screenshot at time of writing this ticket.
![Image](https://user-images.githubusercontent.com/13255539/175254149-dd8f4eec-a526-4e35-9e02-40604d128135.png)

**Comment by campbellssource** [comment]
added metadata tags to ticket description

**Comment by daunatv** [comment]
Would argue that if we do have price monitoring trigger details then they should also include the triggering prices as displayed in console v1. Might not be the user they are aiming at but without the actual trigger prices, they do not give me much information.
<img width="388" alt="Screenshot 2022-07-01 at 16 01 12" src="https://user-images.githubusercontent.com/100769129/176904848-02f27f6e-f711-41aa-b641-59a2800e5793.png">
<img width="367" alt="Screenshot 2022-07-01 at 16 00 09" src="https://user-images.githubusercontent.com/100769129/176904860-7bcc1c07-e0ac-49c6-8f26-9a7e426f3003.png">

**Comment by campbellssource** [comment]
Another thing that is missing from market info: could be picked up as part of this ticket
https://github.com/vegaprotocol/frontend-monorepo/issues/707

**Comment by MadalinaRaicu** [comment]
Few things to be added:

- [ ] total fees added in https://github.com/vegaprotocol/frontend-monorepo/pull/889
- [ ] 24 hour volume
- [ ] insurance pool
- [ ] Oracle details to be done in https://github.com/vegaprotocol/frontend-monorepo/issues/626
