### ISSUE TITLE
Add Oracles info to Console V2

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#626]
Follow on from https://github.com/vegaprotocol/frontend-monorepo/issues/625 This to add details about the oracle a market uses.

## Background

When someone proposed a market they also define 2 oracle specifications (or re-use an existing ones).
`oracleSpecForTradingTermination` is used to create an event to [terminate the market](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0043-MKTL-market_lifecycle.md#trading-terminated),
`oracleSpecForSettlementPrice` is used as the price to [settle](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0043-MKTL-market_lifecycle.md#settled)  positions that are still open.

```GraphQL
{
  markets{
    tradableInstrument{
      instrument{
        product{
          ...on Future{
            oracleSpecForSettlementPrice{
              id
            }
            oracleSpecForTradingTermination{
              id
            }
          }
        }
      }
    }
  }
}
```

These IDs reference an **oracle Specification**:
```GraphQL
{
  oracleSpecs{
    id
    status
    pubKeys
    createdAt
    updatedAt
    filters{
      key {
        name
        type
      }
      conditions {
        value
        operator
      }
    }
  }
}
```

Each specification is "Listening" to a transaction type **Oracle Submission**
See [WIP docs](https://deploy-preview-121--vega-docusaurus.netlify.app/docs/testnet/tutorials/oracles#3-submit-the-message-to-the-chain-1) Which might already be [live](http://docs.vega.xyz/docs/testnet/tutorials/oracles).

You can see all oracles submissions with
```GraphQL
{
  oracleData{
    data{
      name
      value
    }
    broadcastAt
    matchedSpecIds
	}
}
```

When an oracle submission matches a filter it creates a **Binding**.
You'll see a `broadcastAt` and the specID that it matches.

note: some names are [up for debate](https://github.com/vegaprotocol/vega/issues/5689).

## Design + UX requirements

I suggest that the market info at very least should include the `oracleSpecForTradingTermination` and `oracleSpecForSettlementPrice` IDs. At a minimum it could link to the block explorer that should show all the [raw oracle information](https://github.com/vegaprotocol/frontend-monorepo/issues/633).
But ideally Console would also show this information...

**Comment by PeteWilliams** [comment]
I've added this to the Market info tab under Market spec: 
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2375%3A31753

For now I've just included the pice and termination IDs and a link to the block explorer for full details. Perhaps we can look at adding more info once we've got some user feedback on what's useful.
![image](https://user-images.githubusercontent.com/1325606/182111150-6e038bc6-8e04-411b-9544-b15fa0fd3868.png)

**Comment by candida-d** [comment]
@MadalinaRaicu - I think this is semi-blocked by this core work: https://github.com/vegaprotocol/protos/pull/514

**Comment by MadalinaRaicu** [comment]
adding Oracle Price and Termination IDs in this PR https://github.com/vegaprotocol/frontend-monorepo/pull/1050
