### ISSUE TITLE
Remaining market icon snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6287]
## General size / alignment issues 

All the places we use this seem to be misaligned slightly in various ways ... and the latest change to make the icons bigger has made some of parts of the app look a little cramped.

### Markets page

Here is pretty good ... size looks good ... but it looks to me like the product pill is just slightly lower than it should be.  Here given that we have the description below I guess we cannot middle align _everything_ .... but can we 

- [x] Make sure the code + product + status icon are all middle aligned on teh top row.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f3b64184-95cd-45a7-9012-3f0d3a507eff)

### Markets page top gainers / new listings

Here I think 
- [ ] We need a slightly smaller version of the icons because there isnt enough space up here.  
- [ ] I also think we might be clipping off the end of the market code?  I can see a hint of a T from USDT in the below? We probably need to add a ... treatment here as I dont want to wrap the code.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d61a635b-6c96-4e23-9571-98922ba1044c)

In the original sketches we had a smaller version of the icons as below so lets follow this approach.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/36680878-a97f-411e-b16f-b3afb1a39c25)

### Trading market dropdown 

Here again in terms of size 

- [ ] I think we need a slightly smaller version of the icons, similar to what we used above, because otherwise this is a bit cramped.  
- [ ] We also need to check the mobile version looks good with the new smaller size as that is also very cramped currently.

In terms of alignment, the market code seems to be slightly higher than middle-aligned, and the product / status icons are both aligned a little lower.  

- [x] Can we just get all 4 parts (icons, code, product, status) all middle aligned.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d48b77aa-a17a-40b9-b2d0-536747cd2ca5)

### Market header

Here I think the icons and the code are aligned .... but the product pill isnt actually a pill ... and its aligned slightly high.  Can we 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f9582773-1501-4817-b86b-6386967e9394)

- [x] Make the product a pill
- [x] Make 4 things middle aligned
- [ ] Use the same reduced size of icons that we use in the dropdown so the header icon is not inconsistent with the dropdown once activated

## Fee page 

Fees page currently just has a market code... lets make this consistent with the markets page.

- [ ] Add full icons / product / status / description package to the fees page with same sizing / alignment as the main market list

Like this 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0d1c8335-a5cd-400c-b691-10400deffefa)

**Comment by MadalinaRaicu** [comment]
@JonRay15 this is the product pill in Figma

<img width="409" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/6f89ee2b-4dbf-4c9c-89dd-517a0dc7f142">

when you say to make it a pill you mean it should look more like... it has rounder corners?
