### ISSUE TITLE
Fractional Orders - form validation needs to be improved

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#630]
When trying to place an order for a market with position decimal places set to `0`. The form allows the user to place an order that it below 1 (i.e. 0.1).

As seen from the attached video, the UI indicates that you cannot make an order below 1 but the button is not greyed out at 0.1 but behaves correctly at a couple more decimal places.

Expected Behaviour:
Form validation should be more responsive so user cannot place order for fractional orders when position is set to 0 

https://user-images.githubusercontent.com/30622993/175341886-bc18054d-a3bf-4857-89ca-2bb43fa8f3e0.mov

**Comment by mattrussell36** [comment]
Closing as fixed
