### ISSUE TITLE
New markets page snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6316]
## The Chore

Feedback for further improvements to the markets page

### Sorting issue

- [ ] 24h volume is sorting by the raw number (correction ... it is sorting by .... I dont know what ... it seems pretty random!) when ideally it would sort by the USDT equivalent given below
- [ ] Same issue for open interest 
- [ ] 24h Change is sorting by lord knows what ... it seems to think zero (no change) is the lowest number possible and its sorting the other stuff seemingly at random - weirdly the "Top gainers" section is sorting just fine

### DP issues

- [ ] The 24h volume and open interest as expressed in _contracts_ should be given to the marketDp of the market 
- [ ] The 24h volume and open interest as expressed in _USD_ should be given to ZERO DP

### Column width

I have lost the edge of the "open interest" column on a 13in monitor with 90% zoom on Chrome.  If I go to 100% I lose it almost completely.  Therefore in both cases I have a horizontal scroll bar. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/72a49bff-435c-4b46-8b9d-a30a38c63872)

- [ ] Adjust default column widths so we fit all columns on a 13in monitor at 100% zoom

### Column widths on Proposed & Closed

- [ ] On these panes it looks like we need wider columns because theres just dead space on the far right?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2ae90983-24ad-4507-adf6-cf225990d4c0)

### Spacing / padding

- [x] In my opinion the rows still need more top and bottom padding... it feels a bit dense for this "websitey" vibe we are going for.
- [ ] I think the icons could be a little bigger too 
- [ ] I think the font of the "primary" info in the table (market code, price etc) could be bigger to distinguish it more from the "secondary" grey info

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0a0de688-d8a2-4416-88f1-a3c8bbfe914f)

### 24h change section

It seems like the spark line graph doesnt fill the entire height of the row? The chart starts from maybe a third of the way up? But then it goes to the very top? 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2a4e0620-a3d7-4262-a077-e91576a2bf58)

I'm conscious this is a share component with the market dropdown so anythign we do here will impact that too.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/9b43a071-25fc-42a1-ad6b-9981b5296421)

Its particularly jarring on things in auction where they get this weird grey bar.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/87d4c1a0-4460-4ae4-ae9b-fc9189df18ce)

Not sure exactly is the best course of action ... I can think of two:

1. Fill the full row top to bottom, but given we have the fill under the line that will mean a lot of filled in space.  We would likely need to cut it off somewhere so maybe we have a margin top and bottom but lets have _the same_ margin since at the moment it is only really occupying the top 2/3 of the row
2. If we think that is going to lead to too much filled space, could we do that but not have the gradient fill under the line?  It seems to me that it is that gradient - and trying to work out where it stops - that is causing the issue here? If I look at other examples most dont have that gradient under the line so dont face this problem

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4794e52a-20bd-4d33-ba95-27f35ac50ca8)

- [ ] Decide what to do about the spark line and do it

**Comment by bwallacee** [comment]
Alignment here on the price change can be improved.
![image (31)](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/b99c3d53-b86a-4f44-9fa0-da66cc1ddda0)

**Comment by daunatv** [comment]
Assume this is the issue you are referring to in terms of sorting, where in the example SOL should end up on top considering the volume.

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/1f404ad2-0e4a-4fed-ae6f-aa8613680c86

**Comment by witgaw** [comment]
I'd be nice to always have two decimal places for 24h notional (grey numbers below 24h volume figure) to easily tell the difference between markets.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/9922111/0115fb45-bf9d-4f22-a8b9-8944d72d8e54)

**Comment by JonRay15** [comment]
I am bumping this up the list because the sorting bug is still there .. and the DP issue is still there. 

I also think we should simply show ZERO DP on the $ values ... If there is $411,031.45 of volume I absolutely do not care about the 45c!
