### ISSUE TITLE
token.vega.xyz loads forever when wallet in other EVM chain

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#632]
### Discussed in https://github.com/vegaprotocol/feedback/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **dealdi** June 21, 2022</sup>
I was trying to access token.vega.xyz but got stuck forever on the loading screen. It turns out my ETH wallet (MetaMask) was connected to another chain (Avalanche). Maybe there should be an error message when users are in the wrong network/chain instead of an infinite loading screen.

</div>

**Comment by dexturr** [comment]
THis doesn't appear to be an issue anymore, given it's age I suspect this was fixed as part of the migration to the new web3 library. I see an error message (that could be improved) as per #714 so i am closing this
