### ISSUE TITLE
Oracles in block explorer

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#633]
Oracles are a key concept in Vega they deserve an item in the left hand nav.

I think the page should facilitate a few use cases:
- As a user I want to follow a link from a market description to a specific oracle spec to find out more about the oracle
- ...I want to see the definition of the oracle spec
- I want to see all `Submit oracle` transactions and their contents (regardless of matched spec)
- I want see bindings to events in markets (I imagine this is an "internal transaction"  
- I want to see what oracles are already used (and perhaps can be re-used)

Suggest the page appears after markets in the left hand Nav

![Image](https://user-images.githubusercontent.com/13255539/175525923-cee1e7ed-66c4-40bb-8641-b5e3ebad5fa1.png)

# MVP
A single page that lists the results of a single query as raw JSON
```GraphQL
query{
	oracleSpecs{
    status
    id
    createdAt
    updatedAt
    pubKeys
    filters{
      key{
        name
        type
      }
      conditions{
        value
        operator
      }
    }
    data{
      pubKeys
      matchedSpecIds
      broadcastAt
    }
  }
}
```
Warning this returns a GQL error if there is no data on any specs
Issues: this only shows oracle events that did match specs, hence MVP.

# MVP +1
2 pages, the second one to list results of 
```GraphQL
query{
	oracleData{
    pubKeys
    data{
      name
      value
    }
    matchedSpecIds
    broadcastAt
  }
}
```

**Comment by campbellssource** [comment]
# UI instead of JSON
The [list of oracle specifications](https://www.figma.com/file/0HjGqW6cXErEsPNB0lHINs/Block-explorer-%2B-status?node-id=624%3A24101)
<img width="1202" alt="Screenshot 2022-07-04 at 15 22 39" src="https://user-images.githubusercontent.com/13255539/177173793-8c81e6a0-c2c2-4c7e-bd19-e721580dab36.png">
Links to each  [Oracle specication page](https://www.figma.com/file/0HjGqW6cXErEsPNB0lHINs/Block-explorer-%2B-status?node-id=624%3A24306)
<img width="994" alt="Screenshot 2022-07-04 at 15 23 37" src="https://user-images.githubusercontent.com/13255539/177173917-16c30fd8-20a2-463a-80f4-6adfdececc34.png">

Notes
- the count of markets may not be possible with current API
- The sound of data events (each `specs.data{}`object counts as one event) is optional
- `Name` is probably a key piece of information and ideally would be included in all pages (first column in specs page) and title of single spec page. but I'm not sure how robust this is.
- Filters could possibly be typed i.e. shown as UI rather than raw data but again I'm not sure how strict the options are and this risk obscuring the data if the schema changes
- Should include all oracles (either show a column for status) or have them hidden below a link that says "Show Unused" specs
- Ideally there would be a back link from an oracle back to each market that uses it (as well as any proposals for that market) but this in not in current API
- time stamps to by converted to humane values
- public keys to link to public key page in block explorer
- sort data events so that newest is at the top
- clicking a row in the oracles specifications list opens the page for that oracle specification

**Comment by campbellssource** [comment]
# Hypothesis: Showing a list of oracle names (instead of specification) on the top level oracle page satisfies all use cases with the simplest UI

In this world the top level oracles page would list all oracle `name`s. it would get this list from all events and specifications.
```
query{
   oracleSpecs{
    filters{
      key{
        name
      }
    }
  }
  oracleData{
    data{
      name
    }
  }
}
```

The enables a user to find an event by the human readable `name`.
e.g.
<img width="1463" alt="Screenshot 2022-07-04 at 15 40 48" src="https://user-images.githubusercontent.com/13255539/177176724-fe9536c4-832d-42f3-b302-85e509c630bc.png">
Selecting one of these rows would take you to a page that
- lists all specs that use that name
- list all markets that use a spec with that name
- list all events with that name (whether they matched an oracle or not)
- From there you could link to a specific spec, event or market

Very rough example:
<img width="836" alt="Screenshot 2022-07-04 at 15 44 13" src="https://user-images.githubusercontent.com/13255539/177177267-e4a0ca2a-5f9c-41f9-812b-f5b38520ca14.png">

Note: at time of writing the API doesn't facilitate this

**Comment by barnabee** [comment]
The problem with using name from the oracle spec is that I think it might not be very unique. IIRC nothing will contain the word Coinbase for Coinbase Oracle, for example. Some oracles may not even expose a ticker code, you may just get back something like "price". 

We might be better off including the name/code from the market in this list. Or we may even question whether an oracle tab on the market page in block explorer would be better than a separate oracles section for finding oracle specs, as it's not clear to me how much sense they make without the surrounding market context 🤔 

I like the idea of an oracle data page showing a list of all the data that has been delivered to any oracle spec too, that would be cool and could link to info about the market status, the settlement or state change that the data triggered, etc.…

**Comment by sam-keen** [comment]
@campbellssource OracleData now comes in as part of OracleSpecs, so the PR associated with this ticket covers a JSON blob of the data required for MVP+1. Everything else will require a separate ticket as we discussed, thanks
