### ISSUE TITLE
Fetch rejection reason in stop order TX details 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6363]
## The Chore

Fetch rejection reason in stop order TX details 

## Tasks

- [ ]
- [ ]

## Additional details / background info

https://explorer.fairground.wtf/txs/0x01073A3B988E64CD8496A2DE244DC031822EB8A395563D05F0D22BAE2C175E40

```
{
  "data": {
    "stopOrder": {
      "rejectionReason": "REJECTION_REASON_STOP_ORDER_NOT_CLOSING_THE_POSITION"
    }
  }
}
```

**Comment by edd** [comment]
Currently every stop order with a status of `REJECTED` as a `rejectionReason` of `REJECTION_REASON_UNSPECIFIED`. Pausing this bug until, perhaps, testnet explorer has caught up.
