### ISSUE TITLE
Expand governance initiated transfer view with new info

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6388]
## The Chore

The transfer definition is now mych bigger ... containing all this info:

```
        kind{
          ...on RecurringTransfer{
            startEpoch
            endEpoch
            dispatchStrategy{
              dispatchMetric
              dispatchMetricAssetId
              marketIdsInScope
              entityScope
              individualScope
              teamScope
              nTopPerformers
              stakingRequirement
              notionalTimeWeightedAveragePositionRequirement
              windowLength
              transferInterval
              lockPeriod
              distributionStrategy
              rankTable{
                startRank
                shareRatio
              }
```

Most of this is not in the governance app view 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/cddb8664-0c66-4a28-8cb8-cb229ff5670f)

There is a core bug here which means dispatch strategy was blank on these in mainnet: https://github.com/vegaprotocol/vega/issues/10945

Its not clear to me if this made it to mainnet ... but it does look like on this proposal at least on REST they are there, but @asiaznik pasted output below indicating they're missing ... so maybe its a REST / GraphQL issue?

https://darling.network/api/v2/governance?proposalId=8e7732ad636d3c7b2a683d735da35fcaf8e01b2e4a0b974fec9d2e4795c33409

This is fixed on testnet as you can see on this proposal:

https://api.n00.testnet.vega.rocks/api/v2/governance?proposalId=04e9a7d0b20dc723d497930afdf1d776fb8249069e4c6d724d14a97c10bd1283

But on the testnet governance app it is now showing that info so we still need to do this build:

https://governance.fairground.wtf/proposals/04e9a7d0b20dc723d497930afdf1d776fb8249069e4c6d724d14a97c10bd1283

## Acceptance Criteria

- [ ] Governance initiated transfer view should contain all relevant info from dispatch strategy
- [ ] Governance transfers in a batch proposal should show this too

**Comment by asiaznik** [comment]
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/02c87f3d-7dfe-4d27-872c-a66490ae865c)

**Comment by JonRay15** [comment]
Not clear whether this missing dispatch stratregy on the API is a problem on mainnet or not .... need to establish whether it is to work out whether this fix is dependent on the next Core build.
