### ISSUE TITLE
We display an empty tooltip on hover for market selector

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#6414]
If you hover on the market name we display an empty tooltip. This tooltip is used to display details for settled market icon etc.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/245ba14d-8479-44a7-a44d-9f011eca9856)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/4d95097c-b44d-459d-a8ef-a95f7bb16032)

## Acceptance Criteria

- [ ] When there is no market status icon we should not display a tooltip at all

**Comment by MadalinaRaicu** [comment]
I fixed this already in another PR; it was a one-line fix. 
The text for the tooltip was null but we would still render a span. Fixed that.
