### ISSUE TITLE
Adjust alignment on market text in market selector and header

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#6421]
you can see that the market name isn't centered vertically here.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/f232d461-09db-4f0c-a601-b7bd22849057)

## Acceptance Criteria

- [x] Note that icons will soon increase in size (on anotehr PR)
- [x] Move the product pill and status icon to the row below the code in the market selector
- [x] Ensure the header uses the same layout and styling
- [x] Apply the same layout to the fees page

NB. No change to the "Markets" page as a result of this

**Comment by JonRay15** [comment]
This is now merged
