### ISSUE TITLE
Trading ui - withdrawal delay period for Vega

### ISSUE THREAD

**Issue by baldator** [vegaprotocol/frontend-monorepo#6436]
## Description

When withdrawing Vega the interface is showing a message stating there is a 24h delay for withdrawing Vega, but it's not true... The delay only apply to other collaterals.

**Comment by JonRay15** [comment]
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/3b19a279-3db2-4f75-8692-3078240f3f2b)

**Comment by JonRay15** [comment]
Not seeing this behaviour ... see screen shot where delay for VEGA is shown to be "None"?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/75492c04-b767-4269-bae9-8b8eb257e3ee)

**Comment by baldator** [comment]
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/5137412/608ace23-37c1-4d1f-b728-54f43e6c06a5)

**Comment by JonRay15** [comment]
See if this is covered by WAGMI changes Matt is doing ... bump into TEST

**Comment by JonRay15** [comment]
I have been testing alll the withdrawal stuff for a while and to me it all looks fine ... i'm getting the appropriate delay messages. 

I am closing this
