### ISSUE TITLE
Rank in my team section isn't correctly alligned.

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#6438]
You can see in the screenshot below that the rank text is not correctly aligned.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/74be72a2-03a3-4c02-8af0-6aa6d4e6dea8)

Think this is limited to when you are in a podium place and therefore get the prize ribbon instead of a number. 

## Acceptance criteria 

- [ ] Make sure alignment is correct even when there is a banner / picture / ribbon thing

**Comment by JonRay15** [comment]
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4f38c7f8-594b-45ea-b107-7b1bf4aaeb9c)
