### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#644]
Add a logging module to decouple Sentry from the app and to improve debugging experience generally

- [x] Add logging module
- [x] Replace Sentry.captureExceptions with equivalent
- [x] Replace Sentry.captureMessage with equivalent
- [x] Replace Sentry.addBreadcrumb with equivalent
- [x] Add "report critical" function which proxies to sentry.captureException with a critical label populated as true. This will automatically create an incident if seen so should be used sparingly.

Implementation currently used on desktop wallet app here: https://github.com/vegaprotocol/vegawallet-desktop/blob/develop/frontend/src/lib/logging.ts
We also have another implementation from console v1 here: https://github.com/vegaprotocol/slimline-console/blob/master/src/lib/logging.ts

**Comment by dexturr** [comment]
Related to #2506
