### ISSUE TITLE
Switching contract to settlement asset in deal ticket error

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6447]
## Description

For a market that uses decimal points that are more than the settlement asset there is an error when you try to switch between contracts and settlementasset notional value.
Could be something else but this market has 

postition size -1
decimalpoints 7
ticksize 100
settlement asset decimalpoints 6

## Steps to Reproduce

1. Go to a market that has more more decimal points than settlement asset (login with wallet)
2. Go to order and switch between contract and settlement asset
3. See error

## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/60a5e4c6-d137-48c1-a269-5777945c99f5

**Comment by daro-maj** [comment]
@JonRay15 I can not reproduce this issue.

**Comment by daunatv** [comment]
The issue has been resolved
