### ISSUE TITLE
CI/CD: You have attempted to create more buckets than allowed

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6449]
## The Chore

https://github.com/vegaprotocol/frontend-monorepo/actions/runs/9173247634/job/25221866965?pr=6426 failed while creating a deploy preview with the following error:

```
An error occurred (TooManyBuckets) when calling the CreateBucket operation: You have attempted to create more buckets than allowed
```

## Tasks

- [ ] Get rid of some buckets I suppose?
- [ ] Didn't we have an action that culled old buckets?

**Comment by JonRay15** [comment]
Valentin has fixed this
