### ISSUE TITLE
Console not loading, including backup links

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6471]
## Description

Console including backup links is receiving the error `"upstream timeout"`. 

## Steps to Reproduce

1. Go to [console](https://console.fairground.wtf/)
2. Click on the **main console link** (https://vegafairground.eth.limo/) or backups

## Screenshots

![Screenshot 2024-05-27 at 09 27 18](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/966fad65-f2fc-4c69-af01-9f90291c69b3)

**Comment by daunatv** [comment]
The same is true for Mainnet as well 
[https://vegaprotocol.eth.limo/](https://vegaprotocol.eth.limo/)

**Comment by edd** [comment]
This appears to have been a temporary availability issue - web gateways were timing out finding the content on IPFS.
