### ISSUE TITLE
Trading view chart doesn't update between dark and light view with console

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#6478]
Currently the trading view chart won't update to dark or light mode to follow the "main" view of console.
<img width="1503" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/94c8ea56-9edc-45b9-8a46-169ad0fd671c">

**Comment by JonRay15** [comment]
We cannot reproduce this .... what are you doing??

**Comment by JonRay15** [comment]
I have just seen this on mobile 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7f8241b3-6c83-4fbf-ae1d-a0843077e380)
