### ISSUE TITLE
Connect with an hosted (fairground) wallet

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#651]
In order to help early use of console v2 in incentives we need to allow connection with an existing hosted wallet

to display on fairground only
- [ ] UI to input custom endpoints
- [ ] ensure vega wallet API service client can switch endpoints

**Comment by campbellssource** [comment]
URL for hosted wallet service https://wallet.testnet.vega.xyz/api/v1/

**Comment by campbellssource** [comment]
This could be picked up as a requirement of the other work being done with the `connect-vega-wallet` label

**Comment by mattrussell36** [comment]
Yup. I'm closing this as its covered by #873
