### ISSUE TITLE
Mainnet - The checkmark on required average position on games is missing

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6514]
## Description

So competitions/games with a required average position size is missing the checkmark on the card, so that one knows that they are fulfilling the requirement.

## Steps to Reproduce

1. Go to https://vegaprotocol.eth.limo/#/competitions and view as 5683e36c03181dcd5c69deb11f575624c3920bdf4e10e438d5570cad09d1c689 for example
2. Check the cards and especially the one with 100 notional value of average position
3. The checkmark is missing

## Expected behaviour

Expect to see a checkmark that indicates that one fulfils the requirement. 
The example below, the user clearly fulfil the 100 average position, they even was the top of the previous reward.

## Screenshots
![Screenshot 2024-06-07 at 09 29 56](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/6837e35b-7a14-4227-a604-b14a42ea4089)
![Screenshot 2024-06-07 at 09 29 30](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/c85696a5-da16-4209-a0af-cf04c467b24e)
![Screenshot 2024-06-07 at 09 29 19](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/3c5600e7-7919-439e-9bf1-48f4f058f67b)
![Screenshot 2024-06-07 at 09 28 15](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/f3cfbb99-8532-46f7-8fc9-205918ca541a)

**Comment by JonRay15** [comment]
This will all be covered by this https://github.com/vegaprotocol/frontend-monorepo/issues/6075 soon 

So closing
