### ISSUE TITLE
Fairground - Deposit menu from trading is cut in "half"

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6519]
## Steps to Reproduce

1. Go to https://vegafairground.eth.limo/#/markets/c02cb3ede6d68479368495826562f2f67c47e339b6fbc152c69d5397a6bcb1d7
2. The deposit button on the right side of the screen
3. Change to Arbitrum Sepolia and the deposit asset to USD PEPENING 2
4. See the screen is cut in half, or 1/3 so button is cut and text is missing

## Expected behavior

Full text and button should be visible.

## Screenshots

![Screenshot 2024-06-10 at 14 10 39](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/b4aa74a4-17f2-4c76-ade5-2c15d41ff666)
![Screenshot 2024-06-10 at 14 09 16](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/50807d2d-affe-4110-8a6b-c939c0d0d402)

**Comment by JonRay15** [comment]
So much here has changed that I will assume this is fine unless it crops up again
