### ISSUE TITLE
Signposting for incomplete withdrawals needs improvement

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#6551]
View Withdrawals toast button only takes me to portfolio page and not to the withdraws table

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/67e4cbc0-4d08-4d5b-9afa-fbbdaa58fe50)

It would be good if it opened the withdraws tab/table

Also all of this is changing with the work on the new transaction list, and we need to make sure this stuff is still surfaced clearly.

**Comment by JonRay15** [comment]
This will be covered by Matt's transaction list PR
