### ISSUE TITLE
proposalsDataProvider uses deprecated graphql field

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6555]
## Description

https://github.com/vegaprotocol/frontend-monorepo/blob/develop/libs/proposals/src/lib/proposals-data-provider/Proposals.graphql#L451-L454

This query should use `proposalNode` instead of `node`. Not doing so leads to the Proposals list on Explorer not showing batch proposals. 

The missing proposals:
![Screenshot 2024-06-14 at 11 48 03](https://github.com/vegaprotocol/frontend-monorepo/assets/6678/f690bb25-1ebc-46e7-988b-a65947651c89)

## Steps to Reproduce

1. Go to https://explorer.vega.xyz/governance
2. Note the lack of batch proposals
3. Check the network response

```[tasklist]
### Tasks
- [x] Update proposalsDataProvider to use proposalNode for ProposalListQuery
```

**Comment by JonRay15** [comment]
I can see matches in proposals in mainnet .... closing
