### ISSUE TITLE
As a trader I want to place an order even when a market is suspended (in auction) due to liquidity or price monitoring

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#656]
On Vega, a Market has a Normal trading mode: e.g. continuous, where buys and sells that cross will match and trade instantly and continuously.
But a Market can also go into auction: where Buys and sells will only cross when the auction end conditions are met.

There are at least 3 reasons why a continuous market will go into auction:
- because it is new and has not yet has sufficient criteria to open
- because the market has a movement in price that hit one of the price monitoring bounds (big price moves are dangerous) 
- because the market has insufficient liquidity to trade safely. There needs to be some more volume on the book there there is open volume

The [market lifecycle spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0043-MKTL-market_lifecycle.md) explains how the `market.status` is used, and that the status `Suspended` is used to show that we are in some sort of "Exception auction". either Price or Liquidity monitoring. or an opening auction.

You can look at some of the following information to see more
```GraphQL
query{
  markets{
    name
    state
    tradingMode
    data{
      marketTradingMode
    }
  }
}
```
Returns
```GraphQL
{
      {
        "name": "All cool",
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "Continuous",
          "trigger": "unspecified"
        }
      },
      {
        "name": "Need more orders",
        "state": "Pending",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "OpeningAuction",
          "trigger": "Opening"
        }
      },
      {
        "name": "needs more liquidity",
        "state": "Suspended",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction",
          "trigger": "Liquidity"
        }
      },
      {
        "name": "Price moved to quick",
        "state": "Suspended",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction",
          "trigger": "Price"
        }
      }
}
```

note there is another type of Normal trading mode called "Batch Auction". This is out of scope for this ticket.

Generally the UX requirements for when market are in auctions are
- It should be obvious that the market is not in a normal mode, and have a way of learning more about what this is
  - Docs
  - What type of auction are we in (opening, liquidity, Price monitoring)
  - What exactly triggered it
  - What are the conditions for the auction ending
- Should still be able to place order
  - There are rules about what types of orders can and can't be placed, the deal ticket should help the user if their ticket is invalid. [Auctions spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0026-AUCT-auctions.md)
- Things that are normally possible during the normal trading mode should be highlighted as different. e.g. 
  - "Close" buttons on the positions panel may be different (they normally place market orders, but can't in auction
  - The candle chart should show where an auction has been in place
  - Order book show the crossing of bids and asks (new order book already does this)
  - Orders that have been parked should show as having done so (pegged and liquidity orders are parked during an action)

**Comment by PeteWilliams** [comment]
@campbellssource Looking at `market.tradingMode`, it looks like it would return Continuous/OpeningAuction/MonitoringAuction (and maybe others?). 
For the market header, is it worth simplifying this to just show either 'Standard' or 'Auction'?
I'm assuming that 'standard' is more intuitive to a user than 'continuous' and that they don't need the granularity of opening/monitoring auction here - though that will still be available in the market data tab.

**Comment by campbellssource** [comment]
@PeteWilliams these are the potential results in the API
<img width="365" alt="Screenshot 2022-07-01 at 11 36 57" src="https://user-images.githubusercontent.com/13255539/176878986-98074e05-627f-4288-8c80-603c760a2f44.png">
Personally I think it is worth having the granularity in the header. Seeing opening auction helps explain the lack of candles, "Price monitoring auction" with a info icon, click the icon, see what price move triggered the auction (e.g 0.5% move in 30mins, started 30 mins ago. ends in 5. Similar with "Liquidity auction" , icon... There is not enough liquidity for this market to trade continuously... this much is needed, auction end in x...
Would be nice if I didn't have to got find this info in the panel.

Here are some [designs](https://www.figma.com/file/oK8jZ9XaUOJoUPWPkiukdR/Console-V1?node-id=4532%3A103860) from V1

<img width="1372" alt="Screenshot 2022-07-01 at 11 47 09" src="https://user-images.githubusercontent.com/13255539/176880282-b01710ed-09ff-4695-94dc-3396f8fcdd66.png">

I agree that continuous isn't great, It is short for Continuous Limit Order Book (CLOB). not sure that is much better.
I think "normal" would be okay, later when there are other trading modes we can revisit (because continuous might not be as normal anymore)

**Comment by barnabee** [comment]
> I agree that continuous isn't great, It is short for Continuous Limit Order Book (CLOB)

It is short for "continuous trading" not CLOB which is the trading mode in which trading happens continuously as orders are recevied as opposed to in an auction uncrossing(s) in frequent **batch** auctions or at the end of an exceptional auction call period.

**Comment by barnabee** [comment]
I'd also asuggest that we should never make the asssumption that the market state (active/suspended/whatever) determiens the types of orders you can place or confuse the two, or invent a fuzzy pseudo-status like "normal" (which just smells like another word for active to me…). Console ought to expose (and ideally teach/inform the meaning) of both the current market lifecycle status and the current trading mode IMO.
