### ISSUE TITLE
Market list: bug: can't select the market that is already selected

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#658]
The market list that opens when when you select a market name does not allow you to select the market you are on. It should.

If it doesn't a user who isn't paying attention 🙋 doesn't know what is going on. There isn't any reason to stop them sleacting the market they are on to reload the market/close the modal.

I can only re-produce this on this select market modal, but I'm pretty sure it has happened on the one on first load as well as when you hit "trading" in the top nav. Please do a double check as part of this ticket.

**Comment by MadalinaRaicu** [comment]
This is not happening anymore in the current market selector. @campbellssource Can I close?
