### ISSUE TITLE
HTML Title of App should be the Market you are looking at or Portfolio not "Welcome to Vega trading!"

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#660]
The app currently has one `<title/>` "Welcome to Vega trading!" 🦙

Suggestions
Market pages: [market code] | Vega [Network]
Portfolio page: Portfolio | Vega [Network]

Could be further improved with: Deposit | Vega [Network]
For each page that has a dedicated action or View.

Please make other suggestions or list Routes that need names either below or in PR.

**Comment by PeteWilliams** [comment]
If you have multiple markets open in multiple tabs (which should be more discoverable once https://github.com/vegaprotocol/frontend-monorepo/issues/789 is implemented), they all show the same title - 'Welcome to Vega trading!'.

![image](https://user-images.githubusercontent.com/1325606/179495987-3a82006d-672f-4e1f-bce8-612596d988b8.png)

It would be more useful to show the name of the market, and ideally a streaming current price so you can monitor the price even when not viewing that tab.

For example: 'UNIDAI.MF21 - 7.365 - Vega'
