### ISSUE TITLE
Prices should almost always be right aligned

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#661]
Prices should almost always be right aligned. numbers generally should be too. and where they are right aligned in a table cell the table heading should be too.
for example on [AG grid](https://www.ag-grid.com/example)
![Image](https://user-images.githubusercontent.com/13255539/176211756-23e18ab2-e83f-47b7-81a7-5fb3b53767d5.png)

In console V2 in the these places they are not.

**Collateral/Balances**
![Image](https://user-images.githubusercontent.com/13255539/176206743-8dc77fae-6f4c-4072-8076-d5aef2f3ff5c.png)

**Orders/price**
![Image](https://user-images.githubusercontent.com/13255539/176207172-271b0575-22e5-48f9-9704-83acff0924c8.png)

**Trades/price & Trades/size**
![Image](https://user-images.githubusercontent.com/13255539/176211095-0bdd56bf-f551-4ca1-aee8-a15b6d7abb19.png)

Can't currently check **positions** but I expect it is the same

**Comment by MadalinaRaicu** [comment]
I would argue that any number values should be right-aligned. Sizes too. What do you think @campbellssource?
