### ISSUE TITLE
bug: Portfolio page: switch keys causes an application error

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#662]
I'm on /portfolio
I have one key armed.
I switch to another key
I get `Application error: a client-side exception has occurred (see the browser console for more information).`

![Image](https://user-images.githubusercontent.com/13255539/176214845-4981fb5b-b72b-4127-a115-4adfec9be2fe.png)

**Comment by asiaznik** [comment]
@campbellssource can you please verify if it is still valid? I can't reproduce it locally.

**Comment by campbellssource** [comment]
Nope can not reproduce this. marking as closed
