### ISSUE TITLE
Dropdowns often spontaneously close without user selecting an option

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#663]
Browser Firefox, Mac. Can't reproduce on Safari 

![Image](https://user-images.githubusercontent.com/13255539/176218665-57ff605f-7714-4271-b31f-6b61ab6b2b61.gif)

![Image](https://user-images.githubusercontent.com/13255539/176218981-70a3d218-d5f7-4e11-a55a-ff870b9dab58.gif)

Theories:
- the mouse up event is counting as a click
- Some query has fired of, refreshing the content of the list

**Comment by mattrussell36** [comment]
Closing as fixed
