### ISSUE TITLE
Console ticket information tooltip is too intrusive

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6632]
## Description

When you are trading in console the popuptext info that appears when you are hoovering over text is too intrusive, and I just need to see it once but it keeps being in the way. Would be preferable to have an (i) or something and click to see what it is.
It is probably worse since the buttons are not currently dynamic in terms of size, but should still be an active choice.

## Steps to Reproduce

1. Go to console and start trading
2. See the text that appears when hoovering and it even hides the long/short button at times

## Expected behavior

Should be an active choice to see what they mean, like clicking an (i) or something.
## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/9169fdbb-a480-436e-a73d-f064aacc5c75

![Screenshot 2024-07-03 at 10 19 00](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/f9c49356-2d2c-40c7-bf01-77ccd45e53b5)
![Screenshot 2024-07-03 at 10 18 36](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/74a70a8d-0233-46d8-9b8b-1a78b3dd399a)
![Screenshot 2024-07-03 at 10 18 30](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/38841bf4-eaf9-4a7b-b8a8-3786fe322806)
![Screenshot 2024-07-03 at 10 18 07](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/189044f6-9dfa-496e-8704-76c0efb6f452)

##  Acceptance Criteria

- [ ] Explore options to make this bette
  - [ ] Add a question mark step that initially displays 
  - [ ] Then only display the tooltip if you actually hover specifically on the question mark
  - [ ] ~Make all tolltips render to the left so they're over the order book instead of the submit button~

OPTION 1 CHOSEN

**Comment by JonRay15** [comment]
This is being covered by the work Matt is doing now ,.,.. drop to backlog and revisit to see if we're happy with what he did.

**Comment by JonRay15** [comment]
Delivered under another ticket
