### ISSUE TITLE
Capped market notional value overridden if not press enter

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6650]
## Description

Manually choosing a notional value on a capped market does not work, it uses whatever is on the slider.
## Steps to Reproduce

1. Go to a capped market and choose a notional value and long/short

## Expected behavior

See that the value of the order is the one from the slider and not what you entered.
## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/ba3ef356-882f-47cb-85e9-64d99f80a4cd

**Comment by JonRay15** [comment]
I think you're misunderstanding what is being shown. 

The notional is being set in the ticket but the values in the order book and the submit button are still the SIZE that is being submitted on the order.  We derive that size from the notional but will never match the notional ... unless of course price = 1.

There are some bugs around here still which we are working through, but if I'm interpreting this video correctly I think the above is the issue.

**Comment by JonRay15** [comment]
Dan has confirmed that this is working now
