### ISSUE TITLE
Explorer insurance pool bugs

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6670]
## Bug 1

Asset page is giving one set of values for market insurance pools. 

https://explorer.vega.xyz/assets/bf1e88d19db4b3ca0d1d5bdb73718a01686b18cf731ca26adedf3c8b83802bba

But the REST API is giving slightly different ones:

https://darling.network/api/v2/accounts?filter.assetId=bf1e88d19db4b3ca0d1d5bdb73718a01686b18cf731ca26adedf3c8b83802bba&filter.accountTypes=ACCOUNT_TYPE_INSURANCE

- [x] The decimals look wrong (and seem to be impacting diff markets differently for ... reasons).
- [x] It looks like we're filtering to only show active markets and we shouldnt because the cash actually stays in the pool for a week after the market is made inactive in case a successor market appears.  Suggest:
  - [x] Show ANY insurance pool balance, no filters
  - [ ] Any market that is inactive show a warning icon or show it in yellow, and check the enactment date of the proposal that closed it so you can show a tooltip saying "Inactive market; if no successors are proposed by `enactmentDate + market.liquidity.successorLaunchWindowLength` then balance will be released to the global insurance pool"

**Comment by edd** [comment]
#6674 split out to keep this ticket focused
