### ISSUE TITLE
Add warning in deposit flow when depositing a useless asset

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#6688]
When a user is depositing, we should try to make sure they deposit something that will be useful.

- [x] On squid router block everything other than USDT Arb
- [x] On the normal deposit flow add a warning if the selected asset is not USDT Arb; "The majority of markets on the network settle in USDT Arb, are you sure you wish to deposit?"

**Comment by barnabee** [comment]
This was raised after reports from a user who deposited USDC hoping to be able to either use it or swap it for the correct stablecoin, but this was not possible so they ended up wasting time and gas on a pointless deposit.

**Comment by JonRay15** [comment]
We should include this as part of #6686

**Comment by JonRay15** [comment]
Confirmed on mainnet
