### ISSUE TITLE
Improve fee table labels and visual hierarchy, add maker rebate column

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#6707]
The columns in this fees table are not labelled in line with industry norms, and it's not clear that three of the columns are a breakdown of another column rather than separate fees:

<img width="1434" alt="Screenshot 2024-07-18 at 11 11 46" src="https://github.com/user-attachments/assets/42fe6ef1-c59f-4124-8e58-03795ca90266">

Labels should be updated as follows:

`Total fee after discount` → `Taker fee after discount`
`Total fee before discount` → `Taker fee before discount`
 
We need to make the fee components much more clearly a breakdown of the fee before discount, perhaps we can use larger fonts for the two total fees and a more muted colour for the fee components. If there was a way to make this hierarchy/breakdown even more clear, or even to hide the breakdown initially, that'd be good.

It would also be worth adding a maker rebate column which would need to show a range from the lowest (with maxed out discounts) to the highest (the maker fee component amount) rebate that a maker woudl receive.

This table needs to be redesigned when the new fee components in https://github.com/vegaprotocol/specs/issues/2295 and the dynamic maker fee landhttps://github.com/vegaprotocol/specs/issues/2296 land, but the above should be good for now.

## Acceptance Criteria

- [x] Change `Total fee after discount` → `Taker fee after discount` and pin it to the far left
- [ ] Change `Total fee before discount` → `Taker fee before discount` and move it to be the second column
- [ ] Other columns are unchanged to the right
- [ ] Do something to emphasise those first two columns or de-emphasize the last three (brightness / size)

**Comment by JonRay15** [comment]
Personally I do not see this issue as high impact enough to justify doing it ahead of the fee mechanics changes.  Can we consider this as part of those changes and redesign the page as part of that process?
