### ISSUE TITLE
Console: Close open position uses an incorrect order size 

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6727]
## Description

When using console for closing an open position creates an order with the incorrect size, same for mainnet.

## Steps to Reproduce

1. Open a position
2. Click on the "X" in console to close the full position _(in this example 0.29 contract of XAU, which is gold around 2400 market price so rough notional value of 694)_
3. Check explorer after approving.
4. See the size is the max integer, _console and browser wallet already recognize it and show something like “Max” instead of the long number._

## Expected behavior

Should explorer show max value to correspond to browser wallet Max value?

## Screenshots
![Screenshot 2024-07-29 at 11 46 42](https://github.com/user-attachments/assets/a03d90b3-c5e9-4888-922a-46ed11f0a8f2)
![Screenshot 2024-07-29 at 11 46 34](https://github.com/user-attachments/assets/cf8c53a4-dc60-4760-9ff2-ff3534cea327)

![Screenshot 2024-07-29 at 11 48 31](https://github.com/user-attachments/assets/594267c1-c210-46c5-8c17-920fd0787339)
![Screenshot 2024-07-29 at 12 57 26](https://github.com/user-attachments/assets/0c62b3f6-1186-44d8-b045-97837f331b49)

**Comment by edd** [comment]
<img width="1199" alt="Screenshot 2024-07-31 at 12 03 15" src="https://github.com/user-attachments/assets/49f08be1-0290-4d20-a63e-d953233661ce">

Short version: no
Long version: Explorer doesn't have an API that will give it the specific price of a cancellation. The tx doesn't contain it, and there is no corresponding API that I can find that will give me a definition of the market price at that time, or the value that was submitted.
