### ISSUE TITLE
MOBILE - Clicking the price on orderbook does not transfer it to order ticket

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6743]
## Description

When using the mobile wallet, iphone-safari, clicking on a price on the orderbook does not transfer it to the order ticket.

## Steps to Reproduce

1. Go to a market using your phone
2. Click on a price on the orderbook
3. Go to trade
4. Price or size does not transfer

## Expected behavior

Price/Size should transfer to the trade ticket

## Screenshots

https://github.com/user-attachments/assets/f7de8a04-9982-4076-8c4d-8e40a6c50db6

**Comment by JonRay15** [comment]
Mobile is going to be so massively overhauled at some point soon that it is not worth worrying about this.  Will make sure we remember to test this when we do that. Closing.
