### ISSUE TITLE
We should have a link to the TX in explorer in the transaction list

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6749]
## The Chore

We have a link to the sender / receiver, but weirdly no link to the actual TX 

![image](https://github.com/user-attachments/assets/09debac9-2a68-4a4a-8542-960131d6ba00)

## Tasks

- [ ]
- [ ]

**Comment by edd** [comment]
This is probably blocked by https://github.com/vegaprotocol/vega/issues/10730 - there's no good way to get the transaction ID to link to.
