### ISSUE TITLE
Embedded wallet MVP

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6753]
## The Chore

Initial super MVP version of embedded wallet.

## Tasks

- [ ] Move the entire wallet as is into Console
- [ ] Shove it in the top right ... literally just do this 

![image](https://github.com/user-attachments/assets/2aff9c74-3c4b-4454-978c-d44f7a255bb5)

**Comment by dexturr** [comment]
Previous PR did not close the issue, this was a mistake
