### ISSUE TITLE
Games page tab in light mode does not show the text of selected tab

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6816]
## Description

If you are in light mode on the games page you will not be able to see the chosen tab due to the font colour I presue

## Steps to Reproduce

1. Go to a games page and look at the tabs when switching between dark and light mode

## Screenshots

![Screenshot 2024-08-22 at 09 04 42](https://github.com/user-attachments/assets/92696a55-ed8f-4a28-9b79-e8248247a154)
![Screenshot 2024-08-22 at 09 04 37](https://github.com/user-attachments/assets/53b844e4-262e-4e1c-9718-9f53e736f0e0)

**Comment by JonRay15** [comment]
This is probably a style sheet thing that we could fix fairly easily

**Comment by JonRay15** [comment]
Not relevant anymore
