### ISSUE TITLE
Imbedded wallet disconnects and gets stuck after page refresh

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6849]
## Description

When you are using the imbedded wallet and connect to console it works the first time, as soon as you do a refresh the connection is lost and the "GET STARTED" button just takes you to a loading screen that is waiting for you do do something with your wallet, which you cannot.

## Steps to Reproduce

1. Go to console and connect with imbedded wallet
2. Connect using get started button
3. Refresh page and see it being disconnected 
4. Try the Get started button again, will just take you to a loading screen which you can only get rid of by deleting cache and cookies and reimporting wallet

## Screenshots

https://github.com/user-attachments/assets/a61e2ca8-9ad9-4da4-bfb2-81337318f53e

**Comment by JonRay15** [comment]
This is all being wripped up for the target UX so no longer relevant
