### ISSUE TITLE
Onboarding snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6917]
### Trading page

Even when I had already connected and deposited I am still getting the GET STARTED button here and when I click it I'm asked to sign up to play, having a team is not mandatory.  Also in other cases once I've "completed onboarding" in one aseet but I'm on a market for a different asset I can try to place an order when I have none of that asset!
- [x] Button should check for balances in general account for the settlement asset of that market, regardless of onboarding status 
  - [x] If you have no balance we should show DEPOSIT instead of place order
  - [x] Ideally .... this button would know if you have "completed onboarding" or not ... maybe it coudl check for ANY balances and view that as being evidence of completing it? Then:
    - [x] If you havent completed it, because maybe you left onboarding halfway through, it could send you back into the flow at the deposit screen
    - [x] If you have completed it just trigger the normal sidebar deposit because if you just got REKT you dont want to get shoved back into onboarding, you just want to quickly deposit and start trading again.
- [ ] The banner along the top can handle whether you have a team or not:
  - [ ] If you do not, display "Sign up for games to earn rewards as you trade. Click to continue onboarding" and send you back into the onboarding flow
  - [x] If you click the X, dismiss teh banner permanently so we dont keep trying to force someone into a team if they dont want to

### Onboarding flow

- [ ] Join Vega page
  - [x] I also think we need a text strapline that explains what this is .... just something like "Sign up for games to earn rewards from on-chain games as you trade" 
  - [x] There should be a button to skip this step and just go to Trading... probably just a link to All Markets for now given we dont have a homepage.  This could be prefaced with another strapline saying "Want to just trade without games?" then a big button for "All Markets"
  - [x] I was just offered the ability to create a team even though I had one already.  I actually then clicksed back and it took me to my existing team! 
    - [x] Need to make sure we detect if someone is already in a team 
    - [ ] Need to make sure this covers the case where they are the creator of the team  .... ie teamOwner

### Trading

- [ ] I think the "CONNECT" button should probably also be "GET STARTED" if the one in the deal ticket says that?  I assume this is when we have no local state saved at all? ACTUALLY DONT DO THIS ... currently that button allows you to bypass the onboarding

### Deposit page

- [x] "To" field says "Vega key" ... needs to reflect appName
- [x] Consider defaulting this to the user's current key in this flow and not allowing them to change, they have literally just created this key ... why would they need to change it? Why would they need to enter manually?
- [ ] Consider defaulting and disabling the "to asset"
- [ ] I just managed to generate a string of 000000s!

![image](https://github.com/user-attachments/assets/aa85e8f8-cf1b-43ca-a254-1fda20c85080)

- [ ] A refresh got me the error that Jeremy was moaning about

![image](https://github.com/user-attachments/assets/adc870f4-8919-4597-a14e-5498ebb1e751)

**Comment by 0xfatman** [comment]
When creating a team, the confirmation step hangs forever, even though the transactions are confirmed on the Nebula block explorer:

![image](https://github.com/user-attachments/assets/23d22ddc-b87a-4fb9-8261-447660a4fe16)

https://explorer.neb.exchange/parties/deddc80e717b1ad77084d7693336f1b868c47eb206974985a249a323b7f4d135

**Comment by 0xfatman** [comment]
The images on the Competitions page are resized instead of being cropped.

This box:

![image](https://github.com/user-attachments/assets/45e036cd-ffc7-4f2b-b92d-bb59dc5150b5)

Is displayed incorrectly here:

![image](https://github.com/user-attachments/assets/eddd24df-309a-42eb-a2c7-e0c98fd0edf2)

**Comment by 0xfatman** [comment]
Can we improve the formatting in this popup please? These scrollbars are a bit ugly (Chrome on Linux).
![image](https://github.com/user-attachments/assets/0206a752-905b-414b-b3c9-5cdbe67c1af1)

**Comment by JonRay15** [comment]
This all looks good
