### ISSUE TITLE
Token dApp: Ethereum Key section is black with black text

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#693]
On token.fairground.wtf, which at the time of this issue is being deployed from this repo, the Ethereum wallet area is black but so is some of the text, making it unreadable. 

Tested on both Firefox & Safari
<img width="433" alt="Screenshot 2022-06-30 at 18 41 34" src="https://user-images.githubusercontent.com/62548908/176742721-297f1d5a-841b-4eee-9472-6da6e5e3bc60.png">
<img width="456" alt="Screenshot 2022-06-30 at 18 41 24" src="https://user-images.githubusercontent.com/62548908/176742732-68440a15-f610-43c2-96cd-e763cfd10792.png">

**Comment by gordsport** [comment]
This has been resolved in:
- https://github.com/vegaprotocol/frontend-monorepo/pull/650
