### ISSUE TITLE
Header has got too long

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6944]
## The Chore

On a 13in monitor on 90% zoom I am losing stuff off to the right of the header and having to scroll which is gross. 

![image](https://github.com/user-attachments/assets/0fd4d426-a92b-4726-8ddf-7b223125b281)

Need to save some space.

## Suggestions

- [ ] Change volume to be in K / M type format 
- [ ] Dont show the "contracts" volume ... just show the settlement asset version
- [ ] Can we get rid of one of status / trading mode?  Or combine them somehow?
- [ ] Should we rethink the location of the new "Share" button?  I dont love it

## Additional details / background info

Interstingly this is not a problem on Nebula

![image](https://github.com/user-attachments/assets/5e3c0388-b3b4-4f2e-9592-b7a740391201)

**Comment by dexturr** [comment]
Suggest considering moving the oracle into market data, probably not as headline information as some of the other things IMO

**Comment by JonRay15** [comment]
Not an issue ... worry aboyt it if we see it
