### ISSUE TITLE
Setup routes and basic chrome

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#7]
With nextjs setup the following routes and page chrome

- Add a basic header with button to connect to vega wallet
- Add the following routes
  - /home (just redirect to /trade for now)
  - `/trade/`
  - `/trade/<marketId>`
  - `/portfolio`

**Comment by campbellssource** [comment]
I vote /market/ rather than /trade/

Because it describes the thing not the action. Trade is something you do on a market.

**Comment by mattrussell36** [comment]
Happy for either though what would you call a page which was about a market but not for trading? I think thats something we might need
