### ISSUE TITLE
Markets page tweaks

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#7024]
## Tasks

- [x] OI should be in settlement asset units, looks like it is currently quote asset
- [x] Show the market name as the main bold text and show the code as the smaller subdued one (ie. Reverse it)

One other task split out: #7026

**Comment by edd** [comment]
@JonRay15 

> Make search box rounded

<img width="300" alt="Screenshot 2024-10-15 at 15 57 00" src="https://github.com/user-attachments/assets/af7eac5c-a749-4053-8056-31e62e23fac2">

<img width="480" alt="Screenshot 2024-10-15 at 16 23 53" src="https://github.com/user-attachments/assets/78282b67-8d7b-48f8-ae63-cc4319f791d0">

It's rounded on chrome/firefox/edge for me. Too *big* on one of them, but rounded. What's the issue?
