### ISSUE TITLE
Orders / Positions / Accounts panel takes up a large amount of the screen real estate

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#711]
Some feedback has come in via the [feedback discussions ](https://github.com/vegaprotocol/feedback/discussions/45) regarding the panel sizes not being configurable. 

This or workspace builder is due to be designed / implemented in the future most likely after trading is enabled. However it seems that there is a small bug with the amount of space the Orders / Positions / Accounts panel takes up:

<img width="1418" alt="Screenshot 2022-07-05 at 16 44 55" src="https://user-images.githubusercontent.com/83510148/177366906-b225d0fe-fe98-44bb-9d21-c75939642ff6.png">

Could this be smaller in order to see the whole deal ticket and give a bit more space for the charts

**Comment by PeteWilliams** [comment]
Think this can be closed as I've adjusted the default panel sizes and we now have resizable (though not persistent) panels.
