### ISSUE TITLE
Ethereum chain IDs to have a name: "this app only works on chain ID: 11155111" should mention "Sepolia"

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#714]
This on the deposit page on fairground Console, if your eth wallet is contact to a network other than Ropsten.

![Image](https://user-images.githubusercontent.com/13255539/177547826-6ae4702e-cf57-4dcc-a71f-9129594cff35.png)

This message should use the name of the network (perhaps the ID too), and should help the user with a clue about how to fix it.

suggested copy: 
> This app is configured to work with [network name] (id:[3]), please switch your network in your Ethereum wallet.

but I'll defer to a better suggestion in comments

**Comment by candida-d** [comment]
This has tripped up at least one user who thought Console was broken. https://github.com/vegaprotocol/feedback/discussions/80

**Comment by asiaznik** [comment]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
