### ISSUE TITLE
"Trading" tab: if you are not on the "Trading" page clicking it should take you to the market you were last on when you were in the trading tab

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#716]
From a user: https://github.com/vegaprotocol/feedback/discussions/46#discussioncomment-3086689

Suggestion:
The "trading" tab should only open this list of markets if the user has not already selected a market, Or if the user is on the trading tab.

This facilities a behaviour where a user can bounce between portfolio and a market, without having to re-select the market.

**Comment by MadalinaRaicu** [comment]
handled in https://github.com/vegaprotocol/frontend-monorepo/pull/889
