### ISSUE TITLE
Switch to another network from Block explorer

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#723]
Similar to https://github.com/vegaprotocol/frontend-monorepo/issues/722 but for block explorer.

e.g. 

![Image](https://user-images.githubusercontent.com/13255539/177795984-65044fd7-9528-45f5-ba9a-3eb3fa329c6d.png)

opens a new URL that looks at a different network

**Comment by notbot00** [comment]
code is ready to be pulled in from https://github.com/vegaprotocol/frontend-monorepo/pull/1084 for this
