### ISSUE TITLE
Switch to another network from Token site

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#724]
Similar to https://github.com/vegaprotocol/frontend-monorepo/issues/722 but for the token site.

e.g. 

![Image](https://user-images.githubusercontent.com/13255539/177796342-7473e721-0a3a-428c-9e79-fc3d9e4ebab4.png)

**Comment by notbot00** [comment]
need to pull in the code from https://github.com/vegaprotocol/frontend-monorepo/pull/1073 to make this happen
