### ISSUE TITLE
Differentiate header style to indicate network (e.g. yellow header for fairground)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#725]
## Chore 

- [ ] Create fairground  header bg to differentiate visually from mainet (Leave the logo as is for now)

![Image](https://user-images.githubusercontent.com/6803987/196741198-12b231e4-7b53-4383-a12e-702238cda827.jpg)

**Comment by PeteWilliams** [comment]
Some of David's work touches on this here: https://www.figma.com/file/deV7EBxvTF4ggdsKVVosfr/Console-V2-David?node-id=301%3A1067

**Comment by ckpringle** [comment]
Yep, and if this was prioritised, it's probably just the fairground treatment that really matters, the other networks could remain as is - this brings it in line with token front end (and will need to be rolled out to other front ends with the network switcher).

 <img width="1824" alt="Screenshot 2022-09-01 at 16 28 55" src="https://user-images.githubusercontent.com/46783148/187957426-7ed30b11-4aba-4101-a95e-4bef632b1b67.png">

**Comment by ckpringle** [comment]
@bigfandavid @joellecharlotte we'll need the asset for this
