### ISSUE TITLE
Use multi-open accordion for market info

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#744]
There's a `type` value on the accordion which you can set to `single` or `multiple`. For the market info panel, I think it would be better to allow them to open multiple sections at once.

Probably best to build this as a togglable property of the accordion component than just change it globally. 

I did try changing it to `multiple` which allowed them to open independently, but for some reason it stopped the chevron from rotating on open…

**Comment by AndyWhiteVega** [comment]
test: and looks good
