### ISSUE TITLE
Token dApp (fairground) displays incorrect network 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#751]
token.fairground.wtf shows the version as development when it should say the commit hash. It is serving the testnet environment but lists the version incorrectly.

<img width="638" alt="Screenshot 2022-07-13 at 13 48 47" src="https://user-images.githubusercontent.com/62548908/178737276-b2ca8600-ea95-4223-ae3f-6eb5e9f26fc9.png">

**Comment by sam-keen** [comment]
This has been fixed separately it seems
