### ISSUE TITLE
TFE- Add E2E tests for Vesting

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#756]
May require some set up of rewards for Capsule wallets

**Comment by jtsang586** [comment]
Linked to #477

**Comment by gordsport** [comment]
Hey @jtsang586 
Please can you let me know a little more about whats blocking here? IIRC when you run a capsule network you can create wallets and markets etc.. via the CLI, faucet tokens, and transfer via the CLI too. This way you should be able to transfer to a rewards pool/account.

**Comment by ckpringle** [comment]
Would be resolved by having a service for getting tranch balances...
