### ISSUE TITLE
Use UI toolkit components for 'jump to block'

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#76]
[apps/explorer/src/app/components/jump-to-block/index.tsx](https://github.com/vegaprotocol/frontend-monorepo/pull/58/files/9739e4b467a7ffdc478bce9ea19f6cdfd80ad5d8#diff-b542aa8e472ce143dad62b04bdc4892fe7a929319dc7bca4a9c644d684e66255)

simple solution for now: just use the input and button components from ui toolkit wrapped in a container with display flex.

At the same time, remove reliance on custom class for styling.

**Comment by dexturr** [comment]
Also jump to party
