### ISSUE TITLE
Trading - 422 returned when querying fills

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#787]
When user opens the tab for fills in the trading app a 422 is returned

`{"errors":[{"message":"Cannot query field \"totalCount\" on type \"TradeConnection\".","locations":[{"line":63,"column":7}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}`

Expected behaviour:
Total count should be removed from the query?
Fills should be displayed if there are any

**Comment by gordsport** [comment]
This has now been fixed. - closing
