### ISSUE TITLE
Candle Chart - Candles positions not updating correctly in chart 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#791]
When I have a candle chart open with the default interval of 15 mins. I see the chart update like the one in the screenshot where the candles are not correctly getting adding to the right but overlapping on top of each other. 

![Screenshot 2022-07-18 at 11 49 40](https://user-images.githubusercontent.com/30622993/179496616-dd66e6d3-7da0-48e6-9c11-14378fb6e7dd.png)

**Comment by johnwalley** [comment]
This is resolved by #1323.
