### ISSUE TITLE
GQL Subscriptions not working

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#796]
GQL subscriptions are not working on MAINNET.

We have refactored the existing functionality to poll instead of using subscriptions, so no functionality is broken as of now.

Going forward we would certainly prefer to use subscriptions. This is a ticket to track that.

@edd had a go at proxying the traffic but this was not working as we would hope.

We need to decide how we want to fix this.

Blocked - until we get HTTPS Websockets will not work: 
 - https://github.com/vegaprotocol/devops-infra/issues/1072 until we get HTTPS Websockets will not work
 
The above has been marked as closed, but I note that http://mainnet-observer.ops.vega.xyz:3008/playground still doesn't have a https:// have asked what this means.

side node: There is another potential solution to this: https://github.com/vegaprotocol/data-node/issues/295

**Comment by gordsport** [comment]
Hey @MM0819 @edd 
Do we know if datanodes will have SSL so we have https thus unblocking this ticket?

**Comment by dexturr** [comment]
This has been configured for the deployed version of production.
