### ISSUE TITLE
Verify correctness of the hash proposal prior to governance vote

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#797]
As per the spec, all frontend allowing governance vote should now verify the correctness of the linked proposal.

Related issues:
- https://github.com/vegaprotocol/protos/issues/401
- https://github.com/vegaprotocol/vega/issues/5192
- 
Related spec:
- https://github.com/vegaprotocol/specs/pull/1006

**Comment by gordsport** [comment]
Currently only freeform governance proposals require `hash` and `url`. In that case or if one is present the FE should verify that is an IPFS link and not something (IPNS?) that could be changed.

Where this is referenced in the spec:
https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md#types-of-proposals

Test:
Whatever is at the URL will be loaded by the FE and treated as markdown. Verify against the hash that the content / hash is OK. Warn users that its not verified so the users can take action on forums etc...

**Comment by gordsport** [comment]
@edd - please can you have a review / investigation into this issue and help refine it ahead of next sprint.

**Comment by edd** [comment]
Questions - Which API endpoint / gateway do we use to trust that something is on IPFS and is valid?
- How do we display what we fetch from IPFS, assuming is is markdown
- How do we verify that it is markdown
- What do we display assuming it is or is not valid?

**Comment by campbellssource** [comment]
See https://github.com/vegaprotocol/specs/issues/1184 and https://github.com/vegaprotocol/vega/issues/5752#issuecomment-1202558675

Suggest we close this issue as a won't-fix

**Comment by edd** [comment]
I think we should keep it. If it's IPFS, and we can fetch it via a gateway, we try and render it as markdown. Any other situation: just show the link.
