### ISSUE TITLE
Configure CI to publish UI toolkit package on manual trigger

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#8]
Publish UI toolkit to @vegaprotocol npm organisation

**Comment by dexturr** [comment]
@ciaran- Added you as an assignee to this as it appears that you may do this as part of lp dashboard work. If that is not the case please reassgin to me.

**Comment by ciaran-** [comment]
@dexturr Yep makes sense - happy to pick this up today! 

Did you have any preconceptions about _how_ you want this to happen that you think I should know? 

Otherwise I'll just crack on and see what I can get working (:

**Comment by ciaran-** [comment]
Noting this compatibility issue with the built artifact from `ui-toolkit` when trying to add to the website project:

```error vega@1.0.0: The engine "node" is incompatible with this module. Expected version ">=16.15.1". Got "16.14.0"```

**Comment by ciaran-** [comment]
Another one: vega.xyz is using react `17` - monorepo is using `18`. Bumping the website build to 18 doesn't seem to have caused any problems locally, so gonna suggest we try going forward with that but will check with the website team before we do.

**Comment by ciaran-** [comment]
Also - how do we feel about the volume of `peerDependencies`? There's quite a large number of them just from using `ui-toolkit` to import a single type. Do we think that's OK?

**Comment by ciaran-** [comment]
> Also - how do we feel about the volume of `peerDependencies`? There's quite a large number of them just from using `ui-toolkit` to import a single type. Do we think that's OK?

I think this was me misunderstanding how the nx output works. We can elimate these with a flag: `"buildableProjectDepsInPackageJsonType": "dependencies"` in each of the `project.json` files.
