### ISSUE TITLE
Create proposal better UX

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#800]
![Image](https://user-images.githubusercontent.com/13255539/185551878-1709590e-daa2-4938-8103-1d4316e86bd3.png)

In this improvement we seek to 
- [ ] add a page that asks your for a proposal type (see image below)
- [ ] give show the [thresholds](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-System?node-id=4156%3A83978) (e.g. max and min enactment for the selected proposal
- [ ] give you an easy way to populate the [times](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-System?node-id=1822%3A78252) (enactment etc)
- [ ] improve validation of the submit proposal (if not done already)
- [ ] UI for populating the rationale title and description
- [ ] time selector needs to be different for freeform because it doesn't have an enactment time

All terms in this ticket to be raw JSON. 
no select for market/asset/param

[See design board](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-System?node-id=4154%3A83857)

**Comment by campbellssource** [comment]
and draft ACs https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1005-PROP-propose.md

**Comment by campbellssource** [comment]
In discussion. 
Decided for this iteration that the time picker should be less complicated. here is the design for now.

![Image](https://user-images.githubusercontent.com/13255539/188439532-647faef5-96be-491e-9be5-cff614f699a5.png)
