### ISSUE TITLE
Market table filters

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#81]
Note, this is probably low priority as there won't be many markets to start with

- Add filters
- Add sorting

**Comment by campbellssource** [comment]
[designs](https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2567%3A33912)
but worth considering what AG grid gives us out of the box and filter on [column headers](https://www.ag-grid.com/javascript-data-grid/filtering/)
<img width="872" alt="Screenshot 2022-08-11 at 09 53 32" src="https://user-images.githubusercontent.com/13255539/184098200-04c13d00-b5e5-403f-bb96-5c23ed7b520f.png">

**Comment by PeteWilliams** [comment]
Proposed fields for filtering by:

- market.name (text search)
- market.tradingMode
- Expiry (multiple fields? TBC)
- Status (multiple fields? Live/Proposed/Settled)
- market.tradableInstrument.Instrument.metadata.tags.class
- market.tradableInstrument.Instrument.metadata.tags.sector
- market.tradableInstrument.Instrument.product.settlementAsset.name

One issue with using AG Grid's column header is that it restricts us to only sorting by fields that are currently displayed.

**Comment by campbellssource** [comment]
Agreed scope for this ticket:
- AG grid off shelf column filtering for market table based on the cell values

- sorting. although this is covered in this #959

**Comment by PeteWilliams** [comment]
Proposed sorting config for AG grid filtering:

These columns should use filtering, the others don't need it.
- Market
- Expiry
- Settlement asset
- Change
- Trading mode
- Taker fee
- Position (in My markets)
- Full name (in all markets)

The reset button should be added to all filtered columns:

`filterParams: {
                buttons: ['reset']
}`
