### ISSUE TITLE
Make it clear that the markets shown in Console are "Futures"

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#814]
Vega has the potential to support a number of different "products" e.g. Futures, Options, CFD, Perpetuals

At the moment it only supports "futures" (and a particular type of future), Console needs to make it clear that the products are not perpetuals etc.

Consider 
- adding headings
- adding other types of products and show coming soon
- adding "cash settled future" on market page header etc.

Could/should be done with [showing the settlement date/event](https://github.com/vegaprotocol/frontend-monorepo/issues/637)

**Comment by PeteWilliams** [comment]
As we currently only offer futures, I don't think we need to add it to the market header, just show it once at a platform-level, for instance in the market menu:

![image](https://user-images.githubusercontent.com/1325606/186182304-5c556ff4-b026-4571-9593-0474c87b9d82.png)

And when we look at an onboarding screen, we can also mention it there.
Once we offer other types of product, we can then add the product type to the market list and/or market header.

At the market-level, once https://github.com/vegaprotocol/frontend-monorepo/issues/637 is done, we will show the market's expiry in the market header which should make it evident they're not perpetuals.

![image](https://user-images.githubusercontent.com/1325606/186143410-0b9b70d0-ae78-4fdc-8958-26bbbecd8d08.png)

@campbellssource Do you think that would be sufficient?

**Comment by campbellssource** [comment]
@PeteWilliams I do!
