### ISSUE TITLE
Show auction entry and exit conditions

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#815]
Somewhere obvious in Console 2 (maybe header), Show:
- Why is this market in auction
- Why/When did it go into auction
- What are the conditions for it exiting
- explanation of auction on vega (link to docs) 

note: this was created after https://github.com/vegaprotocol/frontend-monorepo/issues/656#issuecomment-1172211912

**Comment by campbellssource** [comment]
possibly link to https://github.com/vegaprotocol/frontend-monorepo/issues/491 when there is a liquidity auction

**Comment by PeteWilliams** [comment]
Added designs here:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2634%3A33560

![image](https://user-images.githubusercontent.com/1325606/182335615-521fbfd6-5cfd-4e27-9c40-ffbe89a52c88.png)

@candida-d please review/revise the trading mode descriptions.

I was hoping we could explain Price monitoring auctions with some trigger explanation like 'the price dropped more than 5% in 1 minute', but my understanding from the [price monitoring docs](https://docs.fairground.vega.xyz/docs/trading-questions/#price-monitoring-how-vega-handles-large-price-shifts) is that the best we could say is "matching orders were found outside the price range that would be expected 95% of the time based on the last 2 hours' trading". Not sure that is clear/helpful enough to warrant showing?

**Comment by PeteWilliams** [comment]
That said… it looks like we can get the high/low from a given interval so I think we could work out the amount it's changed in that period and show that?

```
markets {
    candles(since:"2022-08-03T16:00:00.999999999Z", interval:I1M) {
     high,
     low
}
```

Then work out the percentage swing from `( (highest high - lowest low ) / lowest low ) * 100`

And show 'The price moved more than X% in Y minutes'.

I think? Perhaps one for a later iteration though…

**Comment by campbellssource** [comment]
@PeteWilliams @candida-d I wonder if "indicative" is better than "estimated" in the uncrossing price and volume?. [The spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0026-AUCT-auctions.md#new-apis) uses "indicative".
