### ISSUE TITLE
Order book controls no longer working

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#818]
The decimal place control and the 'go to mid' control are no longer clickable, the element behind them seems to be receiving the click:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/1325606/179803484-df263366-a416-4571-a1cf-1a3b50799c45.png">

**Comment by campbellssource** [comment]
@PeteWilliams can you re-produce? some changes have happened. could be fixed.

if so what browser?

**Comment by PeteWilliams** [comment]
Not seen this issue for a while.
