### ISSUE TITLE
Use rationale hash in freeform proposal title

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#824]
The rationale field was [removed from the proposals query](https://github.com/vegaprotocol/frontend-monorepo/pull/817) due to a datanode bug which prevented any proposals being shown. This means that the title of a freeform proposal uses a (not super helpful) proposal ID. Once the datanode bug is fixed lets revert back to using rationale.hash.

**Comment by campbellssource** [comment]
This may not be required as URL and Hash look like they will be removed from proposals https://github.com/vegaprotocol/specs/issues/1184

**Comment by gordsport** [comment]
closing as no longer required due to the changes to be implemented as part of:
- https://github.com/vegaprotocol/specs/issues/1184
