### ISSUE TITLE
Trading app: Exception raised when viewing trades list

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#825]
![Screenshot 2022-07-20 at 11 51 56](https://user-images.githubusercontent.com/30622993/179965338-c99c992f-f835-4fd5-80b7-e64739630406.png)
![Screenshot 2022-07-20 at 11 51 53](https://user-images.githubusercontent.com/30622993/179965345-e979ea78-07c0-4f8f-bd1b-73d2548fc25b.png)

**Comment by MadalinaRaicu** [comment]
Is this on orders list or trades list? @jtsang586
