### ISSUE TITLE
Fee display in Console V2 is incorrect

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#828]
Console (screenshot) shows liquidity fee is 0.001% but GQL shows it is 0.001 which == 0.1%. (Fees are absolute numbers / mulitpliers, never %s or basis points etc. so you need to convert to display a %.)

Same issue appears for all fees in Console V2.

**Console:**
<img width="307" alt="image" src="https://user-images.githubusercontent.com/1179257/180001601-0162012c-cc43-4683-b073-1befba2fc157.png">

**API data**
```
query {
  market(id: "234afabd27e3bce1a879039c041f9f00f915d98459935ddafd0169d38dd13850") {
    fees { factors { makerFee, infrastructureFee, liquidityFee } }
  }
}
----
{
  "data": {
    "market": {
      "fees": {
        "factors": {
          "makerFee": "0.0002",
          "infrastructureFee": "0.0005",
          "liquidityFee": "0.001"
        }
      }
    }
  }
}
```

**Comment by davidsiska-vega** [comment]
💯
