### ISSUE TITLE
Popup response for submission failed and successful is very similar

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#837]
Steps to reproduce:
- Put limit order IOC for price under the current market price so that it does not get hit
- Approved in wallet with enough assets to fulfill order
- At first glance, even though the submission failed, which is also in the text, the popup screen is very similar with colour and (including check V) with an order that is successful 
I have included two images, one that is successful and one that failed.

<img width="950" alt="Screenshot 2022-07-21 at 12 37 59" src="https://user-images.githubusercontent.com/100769129/180195296-f1488b4b-5bd3-41a4-a83a-8e9e9ebdf4e6.png">
<img width="950" alt="Screenshot 2022-07-21 at 12 30 16" src="https://user-images.githubusercontent.com/100769129/180195304-d3f64e1e-256d-464a-84ee-d416f292800f.png">

**Comment by MadalinaRaicu** [comment]
this happened because the transaction status on IOC failure was default. it is a bug and I will address this in a new PR
