### ISSUE TITLE
Portfolio: Update Positions tab

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#840]
### Current implementation:

![image](https://user-images.githubusercontent.com/1325606/180451865-14040c42-5647-498e-af27-ecf34151f3a9.png)

### Proposed design:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A25247

![image](https://user-images.githubusercontent.com/1325606/180789220-7df32dd4-e873-4cd3-a2ca-99dd78682785.png)

### Details

- Group positions by settlement asset (in alphabetical order)
- Show balance below settlement asset heading
- Show amount and notional value (in one cell if possible)
- Add liquidation price
- Add Entry Price -> Liquidation price visualisation
- Show leverage amount
- Show margin allocated
- Show unrealised profit
- Show last traded date
- Add explanation tooltips for liquidation price, realised/unrealised profit and loss (@candida-d feel free to suggest changes to these)
- Add total field for amount, realised/unrealised profit and loss

**Comment by campbellssource** [comment]
detail on decimal places from https://github.com/vegaprotocol/frontend-monorepo/issues/859
- amount aka size: `Market.positionDecimalPlaces`
- Avg entry price: `Market.decimalPlaces`
- mark price: `Market.decimalPlaces`
- liquidation price `Market.decimalPlaces`
- leverage = n/a
- margin allocated = `Asset.decimals`
- PnL = `Asset.decimals`

**Comment by gordsport** [comment]
Hey @bglownia 
Please can you update as to what parts of the position panel you have already covered in:
- https://github.com/vegaprotocol/frontend-monorepo/issues/473

**Comment by bglownia** [comment]
Things that are not covered in #473 :
 - close button
 - tooltips
 - summary row
