### ISSUE TITLE
Portfolio: Add closed positions tab

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#841]
### Proposed design
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A25672

![image](https://user-images.githubusercontent.com/1325606/180453498-dd6e1d30-22e0-4355-b5e8-802498c73e40.png)

**Comment by mattrussell36** [comment]
Closing as dupe of #469
