### ISSUE TITLE
Portfolio: Update Orders tab

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#844]
### Current implementation
![image](https://user-images.githubusercontent.com/1325606/180455052-f3833f62-036a-49fb-91ad-8be8cabb2573.png)

### Proposed design
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A26126

![image](https://user-images.githubusercontent.com/1325606/180465011-8cf47a57-3f15-4abd-9514-744ae04fafac.png)

### Details

- Separate active and inactive orders under separate headings
- Show margin used across all orders
- Show amount and notional value (in one cell if possible)
- Rearrange columns as per design

#### Active orders
- Lose Status and Updated column for active orders
- Add current price
- Add visualisation for Current price -> Entry price
- Add leverage factor
- Link fill amount to fill panel
- Changer button styles to match design

#### Inactive orders
- Add average filled price
- Add fee paid
- Add notional amount of filled amount
- Add transaction link
- Use Updated date for 'date'

**Comment by asiaznik** [comment]
We need to groom this again.
We lack of the filters for ordersConnections/

**Comment by JonRay15** [comment]
This is very old and likely will never be done. Closing.
