### ISSUE TITLE
Portfolio: Add from address to deposits table

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#848]
### Current implementation
Note, it didn't display any deposits for me, despite having made some.
![image](https://user-images.githubusercontent.com/1325606/180470122-cfe21547-4684-4cd3-bdff-2a6571e1b490.png)

### Proposed design
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2537%3A32179
![image](https://user-images.githubusercontent.com/1325606/180470283-5be07286-52f1-430f-9fb2-85d4c0a08b6f.png)

**Comment by mattrussell36** [comment]
Closing as done

**Comment by asiaznik** [comment]
I've created a data node ticket because we're missng the "from address" inn thr api: https://github.com/vegaprotocol/data-node/issues/855

**Comment by gordsport** [comment]
Hey @asiaznik @pennyandrews,
As it stands we are not capturing this data (in the datanode DB) therefore cannot expose it to be used as you require. 
The core side of this work is scheduled to be done post enable the trading release.

**Comment by pennyandrews** [comment]
Thanks @gordsport. @mattrussell36 as this isn't going to be unblocked anytime soon I've kicked this ticket to the bottom of the backlog
