### ISSUE TITLE
Add AC references to association tests

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#866]
We want to start integrating ACs with Cypress tests. 

This may require tests to be rewritten or new tests added to fit with the ACs

ACs can be found in:
https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md

For now we can reference ACs by adding comments next to tests with the AC ids

Tool for measuring coverage:
https://github.com/vegaprotocol/approbation

**Comment by radoslaw-szpiech** [comment]
There are following ACs missed that should be covered by separate flows:

- if the connected ethereum wallet has vesting tokens: must be able to select to associate from either the vesting contract or the wallet [1000-ASSO-0006](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0006) 
- must be warned if the amount being associated is greater than the amount [1000-ASSO-0010](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0010)
- If some of the tokens for the given eth key are held by the vesting contract: must select to return tokens to Vesting contract [1000-ASSO-0024](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0024)

Following ACs are missed and can be covered by putting validations into the flows, or by creating specific state in vegacapsule and then running through validations:

- must see feedback whether my association has been registered on Ethereum [1000-ASSO-0012](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0012)
- must see feedback that the association has been registered by Vega and that it can be used after the number of Ethereum block confirmations required (typically 50) [1000-ASSO-0013](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0013)
- on completion: should be prompted to go on to [nominate](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1002-STAK-staking.md) and/or participate in [Governance](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1004-GOVE-governance_list.md) [1000-ASSO-0030](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0030)

- must see a list Vega keys that the connected Ethereum wallet has associated too [1000-ASSO-0019](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0019)
  - must see an amount [1000-ASSO-0020](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0020)
  - must see the full Vega public key associated too [1000-ASSO-0021](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0021)
  - must see the the origin of the association: wallet or vesting contract [1000-ASSO-0022](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0022)
  - Should be able to select one row to populate disassociate form [1000-ASSO-0023](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0023)

- should be warned that disassociating will forfeit and rewards for the current epoch and reduce the Vote weigh on any open proposals [1000-ASSO-0026](https://github.com/vegaprotocol/specs/blob/62af5e047880327ba39998aed60b786d50030d80/user-interface/1000-ASSO-associate.md#1000-ASSO-0026)
