### ISSUE TITLE
Support v2 wallet service

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#873]
Wallet authentication is changing with the v2 api of the wallet. We need to support this.

Possible split:
- [ ] desktop wallet work to show dialogs (key to expose etc..)
- [ ] 3rd party trading app changes for authentication with the wallet

Note: review the `connect-vega-wallet` labeled issues before starting this work

**Comment by campbellssource** [comment]
https://www.figma.com/file/W8SV56AAtXpRoQJDQW9ZYt/Vega-Wallet?node-id=1640%3A93621

**Comment by gordsport** [comment]
Consider closing this issue and brining in issues with `connect-vega-wallet` labeled items as these are the same
