### ISSUE TITLE
Add link to version history in footer 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#910]
As a token site / block explorer user 
I want to access version history 
So that I can understand what's changed since last time / what I can do now that I couldn't before

Acceptance criteria
* We've added a link to version history to the footer (not just this current version)

**Comment by gordsport** [comment]
@ckpringle @pennyandrews - should this be a common issue, I can see value in all apps:
1. knowing what version you are on (especially if others host too)
2. accessing the changed history

**Comment by dexturr** [comment]
We need to start officially publishing releases, we can use github to autogenerate release logs which we can make create release logs in line with the current tags and add this to our process. @edd has made an initial one.
