### ISSUE TITLE
WalletConnect does not work. Link non-responsive on TFE

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#919]
![Image](https://user-images.githubusercontent.com/13255539/181766173-8beeb0fa-d7be-46f5-9f4a-2ff2ad87b90f.png)

The "WalletConnect" link within the connect eth wallet component is non-responsive for me. Firefox.
True on token.fariground.wtf
and
the mainnet deploy preview https://token-monorepo.netlify.app/

**Comment by campbellssource** [comment]
note: only appear to be an issue on TFE. Console is fine.

**Comment by AndyWhiteVega** [comment]
Tested: Working fine
