### ISSUE TITLE
Potential improvement to Ethereum wallet connection popup to reduce opportunity for confusion

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#922]
While walking people through staking etc. we came across the Ethereum connection popup shown below:

![image](https://user-images.githubusercontent.com/83510148/181797535-6344c4e2-4b01-4495-8800-619baa445228.png)

This had caused confusion because they didn't see any of the words they expected (MetaMask, Ledger, etc.). For example, people know they use their Ledger via MetaMask, or that FireBlocks supports WalletConnect, but they don't know which option to choose.

I think it would be useful if we clarified on this popup that:

Injected includes MetaMask and most other browser extension wallets, including users who use Ledger or other hardware wallets via MetaMask. It also includes anyone using the site via the browser built in to a wallet app.
Mobile means WalletConnect (in fact I don't know why we don't say "WalletConnect (including most mobile app based wallets)" or something rather than "Mobile" here.

Moved from 

- https://github.com/vegaprotocol/token-frontend/issues/1266

Need to decide on the language / naming for example Metamask / Brave.

**Comment by dexturr** [comment]
This has been copmpleted and has been changed.



![Image](https://user-images.githubusercontent.com/26136207/190365950-a293f932-6b1c-41d0-ba83-0b98b9f96aed.png)
