### ISSUE TITLE
Toolkit: toggle button

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#94]
- [ ] design toggle button

**Comment by PeteWilliams** [comment]
Pete's notes to Pete:
- Add screenshots/links
- Add thunking
- Light theme version
- Hover, active, focus state
- Consider visual distinction from buttons, inputs etc

**Comment by campbellssource** [comment]
I think if we are going to use the yellow more as the selected style then we should do it more and perhaps remove the accent button
