### ISSUE TITLE
React memory leak in orderbook/positions managers

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#945]
This might be sorted at the data provider level. 

![Image](https://user-images.githubusercontent.com/16125548/182814595-79126cb4-a17c-444e-bdd8-82e2a11925f6.png)

<img width="455" alt="image" src="https://user-images.githubusercontent.com/16125548/182815255-d23666af-4961-4cc7-9bae-e0f6055ca8d1.png">

**Comment by campbellssource** [comment]
held until xxxxx is updated.
