### ISSUE TITLE
Console V2 increase/decrease price with up/down buttons, decimal points is not taken into account

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#946]
When increasing/decreasing the price on a limit order but pressing the “up” or “down” arrow it does not take into account the decimals of the prices/market but rather moves it 1.

e.g.
1) Prepare a limit order by putting a price that has decimal points on a market that supports it
2) Press “up” or “down”, to increase/decrease price
- **Result**: Price moves in whole numbers
- **Expected result**: Price should take into account the market or perhaps decimal points chose in the orderbook

Example from images: 

Limit order price 8.123
If I press “up” to increase price of planned limit order
Price = 9

If I press “down” to decrease price of planned limit order
Price = 8

The “logical” thing that I was thinking is that it should take into account the current decimal points that you have chosen in the orderbook overview and increase/decrease the price accordingly or at least the decimal points of the market.

Relate issue linked to decimal points:
https://github.com/vegaprotocol/frontend-monorepo/issues/859

<img width="620" alt="Screenshot 2022-08-04 at 14 06 52" src="https://user-images.githubusercontent.com/100769129/182851497-17cc8eaf-b466-4fd4-981c-01d597b2e686.png">
<img width="620" alt="Screenshot 2022-08-04 at 14 06 43" src="https://user-images.githubusercontent.com/100769129/182851505-09c88449-c7d0-4d9b-9097-4de70f1fe6ec.png">
<img width="620" alt="Screenshot 2022-08-04 at 14 06 36" src="https://user-images.githubusercontent.com/100769129/182851508-4b620393-591c-4793-a82f-1aee707de0af.png">

**Comment by daunatv** [comment]
Adding positionDecimalPlaces to a market makes it so that both position size decimal places and price decimal places when pushing the "up"/"down" increase/decrease price of offer receives the same decimal points

The attached picture is of two nearly identical markets ATOM/USD (one in opening auction and one in liquidity auction), the only difference is that one has positionDecimalPlaces 3 which makes it so that both the increase/decrease position size buttons and price buttons receives 3 decimal places and moves the size & order 0.001. 

Michael: 
The price field should step by market.decimals
the size by market.positionDecimals.

<img width="347" alt="Screenshot 2022-08-04 at 15 41 52" src="https://user-images.githubusercontent.com/100769129/182863352-7515b643-0978-4e1c-9f44-6191ea709a73.png">
<img width="491" alt="Screenshot 2022-08-04 at 15 41 12" src="https://user-images.githubusercontent.com/100769129/182863359-82edddc8-f886-4a85-9d15-71b90206dc80.png">

**Comment by notbot00** [comment]
this got fixed in this commit: https://github.com/vegaprotocol/frontend-monorepo/pull/996/commits/6df1356b67edd40c217752ccf9754e14abd6857c
closing this as it's already merged
