### ISSUE TITLE
Actions from crit on toolkit

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#95]
- Hover: for inline button
- check all light theme colours
- remove auto capitalisation from accent button (add documentation that encourages uppercasing)
- Make buttons look different to inputs. Now: boarder radius... follow up find a brand friendly button styles
- Reset styles on buttons (`-webkit-appearance:none`)? Also fix select shading on safair
- button boarder should be white
- remove underline on hover state (use some other style to make it look more hovery)
- Add button un-styled looks like an inline link but has height of other buttons
- re: input:number. particularly for size and price input. agreed to move away from number (eventually). for now hide/disable steppers
- Don't use disabled buttons. Instead have a style for showing that a button didn't (modal or message around button) won't work until an error is fixed. Except: disabled loading button: to stop multiple submissions. There isn't a single style for disabled buttons.
- Add a Loading state for buttons

related #94

**Comment by PeteWilliams** [comment]
First up I've been playing with input affordances and making buttons and inputs different.

For the buttons, I originally went down a more skeumorphic route and tried slightly rounded corners, bevels and shadows but it looked a bit off-brand.

Ended up going back to something flatter but with a block shadow to show depth, a slight tint on hover and then on click just move the button slightly to show it go 'in'.:

Best to play with the code mockup to experience it: https://codepen.io/PeteWilliams/pen/PoEWrEK

![image](https://user-images.githubusercontent.com/1325606/160153593-3f2aa8e4-0aa3-4b98-b61f-3dad6503d55d.png)

For the inputs I don't think much change was necessary now the buttons look different, but I've added a slight bevel style with different coloured borders and a subtle shadow to make them feel a bit more inlaid.

![image](https://user-images.githubusercontent.com/1325606/160153482-963e06d9-9010-4c42-8d1b-7c7e77ff7245.png)

For the light mode versions I've tweaked things slightly, but nothing major.

**Comment by PeteWilliams** [comment]
Having just used the buttons in anger, I think I might revise the above thinking for white-theme buttons.

Originally I'd tried to keep primary buttons white across both so we're not confusing things by having different colours mean different things across the two themes, but they don't stand out enough, so I think the better compromise is to have primary buttons black on white and white on black:

![image](https://user-images.githubusercontent.com/1325606/160621754-034389d3-0571-492f-97f5-89f41a4ca84d.png)

And here's an in-context demonstration of how the white doesn't stand out as much as the black on a white background:
![image](https://user-images.githubusercontent.com/1325606/160622758-42801316-2cc0-4181-8761-b754ab5f6d18.png)

**Comment by PeteWilliams** [comment]
I've updated styles for various form controls:

- Buttons
- Inline buttons
- Text input
- Number input
- Textarea
- Dropdowns
- Toggle buttons
- Checkboxes
- Radios
- Date picker
- Tool tips
- And error styling

I've added default, active, focus, error states as necessary and added white-theme versions.

https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Vega-team-library?node-id=0%3A1

Best to review these in a crit, then we can move into dev.

**Comment by sam-keen** [comment]
Great stuff @PeteWilliams. Can you assign to me once it's good to go, cheers!

**Comment by PeteWilliams** [comment]
Updates post-crit:

Moved date-picker back to left-align:
![image](https://user-images.githubusercontent.com/1325606/166486261-46adbaaf-1858-4ab3-a29a-5cfc5eb72305.png)

Reduced datepicker size:
![image](https://user-images.githubusercontent.com/1325606/166486399-7a3f5dec-4936-4e5e-88d8-9c624dcdfd61.png)

Tweaked red/green colours for accessibility on white.
![image](https://user-images.githubusercontent.com/1325606/166486549-3062568b-ac37-4a63-95ca-0f9c5633f7f0.png)

Added error example for checkboxes:
![image](https://user-images.githubusercontent.com/1325606/166486668-cb1670c1-1279-4101-b20d-ac0d65c09783.png)

Added a full mockup of white theme, tried different selection colour and made tweaks to fit:
![image](https://user-images.githubusercontent.com/1325606/166487277-acee25e8-6718-4d5f-9b11-a21c9c5acd83.png)

Changed 'action required' intent from yellow to white:
![image](https://user-images.githubusercontent.com/1325606/166487817-a963a74c-8d7d-4c1b-9487-3e90b347679b.png)
![image](https://user-images.githubusercontent.com/1325606/166488291-91a59c11-3054-443b-b1b4-d0173f049c2a.png)

Added primary nav:
![image](https://user-images.githubusercontent.com/1325606/166487183-8602bd5f-3820-4823-ae8f-a5da811fba53.png)

To review again and then can move into dev.

**Comment by PeteWilliams** [comment]
This can now be closed as I've created a new ticket for the dev changes required: https://github.com/vegaprotocol/frontend-monorepo/issues/447

**Comment by gordsport** [comment]
Closing as in `Done`
