### ISSUE TITLE
Edit order should dialog should validate the user's input

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#950]

**Comment by MadalinaRaicu** [comment]
the user can input the price only for now. the only validation rule that we already have is that the price is required. is there any minimum or maximum price that the user can input? any upper/lower bounds?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/16125548/184687519-5b5b870c-6a21-4fbc-95e1-68d85bcd8a96.png">

**Comment by AndyWhiteVega** [comment]
Tested = Looks Good
