### ISSUE TITLE
Node switcher - Checking url sometimes gets stuck on SSL 

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#974]
This got picked up by the UI tests and should be reproducible manually.

1. Open Block explorer connected to Testnet
2. Open node switcher and enter url for devnet (as seen in the screenshot)
3. Click connect
4. Stuck on `Checking` SSL

![Screenshot 2022-08-08 at 15 15 35](https://user-images.githubusercontent.com/30622993/183445256-ca7569ec-5bbd-4a55-a27b-ef6df796cdd0.png)

**Comment by notbot00** [comment]
i believe this has been fixed in this PR: https://github.com/vegaprotocol/frontend-monorepo/pull/2357/files#diff-7034b8ddabfe4af427b5bb0d1e8279a37a7bf881d52730c93798386257d70144R75-R80
