### ISSUE TITLE
Votes should be allowed on New Asset proposals in WaitingForNodeVote

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#976]
Well, maybe. Background:
https://github.com/vegaprotocol/vega/issues/5816

This code in the core:
https://github.com/vegaprotocol/vega/blob/fc24100ccc418bb03f3ae99342eaa65c951acbc8/core/governance/engine.go#L1014-L1017
```go
func (p *proposal) IsOpenForVotes() bool {
	// It's allowed to vote during the validation of the proposal by the node.
	return p.State == types.ProposalStateOpen || p.State == types.ProposalStateWaitingForNodeVote
}
```

Does not match this code in the token frontend:
https://github.com/vegaprotocol/frontend-monorepo/blob/c375f74906f17d29d7c65a88d2b5367787e057c6/apps/token/src/routes/governance/components/vote-details/vote-buttons.tsx#L81-L83

One of these is wrong. We'll find out in https://github.com/vegaprotocol/vega/issues/5816 or https://github.com/vegaprotocol/specs/issues/1178. Either way, there's some fixing

# Tasks if WaitingForNodeVote should allow voting
- [ ] Update the above to allow voting when the proposal is in the state `WaitingForNodeVote`

# Tasks if not
- [ ] Update the error message not to say 'You voted' if I did not vote.

**Comment by dexturr** [comment]
https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1665746023968899
