### ISSUE TITLE
Cancel liquidity commitments in Console

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#984]
We already have a list of accounts, and a list of orders in Console.

Where one is a liquidity provision, we could introduce a link to cancel a liquidity provision.
this could show something like a red amber green next to each to show if it is not possible to cancel that provision, only to reduce it, or cancel it completely. then a single link (maybe dialog) to submit the transaction.

**Comment by PeteWilliams** [comment]
Would be good to discuss options here. 

As Michael said, we could add cancel actions to the orders table for orders that are liquidity commitments, but if we are building a [per-market liquidity table](https://github.com/vegaprotocol/frontend-monorepo/issues/491) which has a 'my markets' section, would it be much more effort to make a version of that that is all-markets and stick it in a tab in the Portfolio tab?
Feels like it would add a lot more value, allowing users to see/manage their liquidity provision from one place.
