### ISSUE TITLE
Revisit deal ticket warning messages before placing orders

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#997]
Revisit the warning message because persistent limit orders are accepted, including GFA, GTT, GTC as well as liquidity commitments. 
Also may be worth including the fact that as the market is suspended, any orders placed now will not trade until the auction ends.

![Image](https://user-images.githubusercontent.com/16125548/183938225-0f782c3a-87ec-4626-9ecb-2cf3c5385c21.png)

https://vegaprotocol.slack.com/archives/C8WS7M50E/p1660131156926369

**Comment by MadalinaRaicu** [comment]
Note: GFN, IOC, FOK orders during auction will be rejected.

**Comment by PeteWilliams** [comment]
Have added some suggestions as part of https://github.com/vegaprotocol/frontend-monorepo/issues/991
